[SPARK-16692] [ML] Add multi label classification evaluator, DataFrame
apache/spark pull request #14325
Opened 2016-07-23 06:38 UTC by liwzhi

Add the multi label classification evaluator to DataFrame, ML

Also add the multilabelClassifcationSuite.scala unite test. 

A multilabel classification problem involves mapping each sample in a dataset to a set of class labels. In this type of classification problem, the labels are not mutually exclusive. For example, when classifying a set of news articles into topics, a single article might be both science and politics.

2016-07-23 06:42 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2016-10-07 20:52 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-09-21 02:17 UTC, WeichenXu123 commented
You should override `override def evaluate(dataset: Dataset[_])` (without the label param).

2017-09-21 02:18 UTC, WeichenXu123 commented
ping @gatorsmile Add this to test.

2017-12-14 21:06 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-01-24 12:07 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-01-24 22:37 UTC, gatorsmile commented
ok to test

2018-01-24 22:38 UTC, gatorsmile commented
cc @WeichenXu123 @yanboliang

2018-01-24 22:42 UTC, SparkQA commented
**[Test build #86608 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/86608/testReport)** for PR 14325 at commit [`5efc2c7`](https://github.com/apache/spark/commit/5efc2c7b1e6566896f1c99b9a8e2ae3603b6abc5).

2018-01-24 22:44 UTC, SparkQA commented
**[Test build #86608 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/86608/testReport)** for PR 14325 at commit [`5efc2c7`](https://github.com/apache/spark/commit/5efc2c7b1e6566896f1c99b9a8e2ae3603b6abc5).
 * This patch **fails Scala style tests**.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `class MultilabelClassificationEvaluator @Since(\"1.5.0\") (@Since(\"1.5.0\") override val uid: String)`

2018-01-24 22:44 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2018-01-24 22:44 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/86608/
Test FAILed.

2019-02-06 00:09 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-02-06 14:49 UTC, srowen requested changes
Do we have a Python equivalent?

2019-02-06 14:49 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/ml/evaluation/MultilabelClassificationEvaluator.scala
> +@Since("1.5.0")
Nit: since 3.0.0 and remove the blank line above

2019-02-06 14:49 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/ml/evaluation/MultilabelClassificationEvaluator.scala
> +    * param for metric name in evaluation "f1Measure", "precision",
Nit: each line of scaladoc needs a `*`, and we just use javadoc style where the `*` doesn't have an extra indent

2019-02-06 14:49 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/ml/evaluation/MultilabelClassificationEvaluator.scala
> +      "(f1Measure|precision|recall|accuracy|microF1Measure|microPrecision|microRecall" +
I think you can avoid duplicating the allowed values by breaking out the list of params and referencing `list.mkString("|")` in the message string

2019-02-06 14:49 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/ml/evaluation/MultilabelClassificationEvaluator.scala
> +    metric = $( metricName ) match {
Nit: no space around parens

2019-02-06 14:49 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/ml/evaluation/MultilabelClassificationEvaluator.scala
> +    if(label!=Double.NegativeInfinity) (
Nit: need space around if and operator

2019-02-06 14:49 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/ml/evaluation/MultilabelClassificationEvaluator.scala
> +         }
Nit: indent

2019-02-06 14:49 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/ml/evaluation/MultilabelClassificationEvaluator.scala
> +    case "f1Measure" => true
Nit: list all cases with the same value together. `case "f1Measure" | "precision" | ...`

2019-02-06 14:49 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/ml/evaluation/MultilabelClassificationEvaluator.scala
> +   def copy(extra: ParamMap): MultilabelClassificationEvaluator = defaultCopy(extra)
Fix indent

2019-05-28 03:21 UTC, zhengruifeng commented
What's the progress now? @liwzhi @WeichenXu123 @srowen 
If @liwzhi are not working on this, can I take it over?

2019-06-02 00:53 UTC, closed without merging