[SPARK-17513] [STREAMING] [SQL] Make StreamExecution garbage-collect its metadata
apache/spark pull request #15067
Opened 2016-09-13 00:14 UTC by frreiss

## What changes were proposed in this pull request?

This PR modifies StreamExecution such that it discards metadata for batches that have already been fully processed. I used the `purge` method that was added as part of SPARK-17235.

## How was this patch tested?

I added a test case to verify that old metadata log files are correctly purged. 
I also ran the entire regression suite.

2016-09-13 00:17 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2016-09-17 06:54 UTC, rxin commented
Jenkins, test this please.

2016-09-17 06:55 UTC, SparkQA commented
**[Test build #3276 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3276/consoleFull)** for PR 15067 at commit [`82f5b68`](https://github.com/apache/spark/commit/82f5b681c2e8e52f8549b21c7d058c497f2fc809).

2016-09-17 06:57 UTC, SparkQA commented
**[Test build #65525 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/65525/consoleFull)** for PR 15067 at commit [`82f5b68`](https://github.com/apache/spark/commit/82f5b681c2e8e52f8549b21c7d058c497f2fc809).

2016-09-17 07:16 UTC, rxin commented
Looks pretty good to me.

2016-09-17 07:17 UTC, petermaxlee commented on sql/core/src/test/scala/org/apache/spark/sql/streaming/StreamingQuerySuite.scala
> +          toTest.size == 1 && toTest.head == "2"
actually this test case will always pass, even without the change here. I will submit a patch based on yours that fixes the issues here.

2016-09-17 07:17 UTC, petermaxlee requested changes

2016-09-17 08:43 UTC, SparkQA commented
**[Test build #65525 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/65525/consoleFull)** for PR 15067 at commit [`82f5b68`](https://github.com/apache/spark/commit/82f5b681c2e8e52f8549b21c7d058c497f2fc809).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-09-17 08:44 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-09-17 08:44 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/65525/
Test PASSed.

2016-09-17 09:16 UTC, SparkQA commented
**[Test build #3276 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3276/consoleFull)** for PR 15067 at commit [`82f5b68`](https://github.com/apache/spark/commit/82f5b681c2e8e52f8549b21c7d058c497f2fc809).
 * This patch passes all tests.
 * This patch **does not merge cleanly**.
 * This patch adds no public classes.

2016-09-20 05:19 UTC, rxin commented
@frreiss can you close this now?

2016-09-20 17:05 UTC, closed without merging

2016-09-20 17:07 UTC, frreiss commented on sql/core/src/test/scala/org/apache/spark/sql/streaming/StreamingQuerySuite.scala
> +          toTest.size == 1 && toTest.head == "2"
Oops, didn't notice I had left that "true" at the end of that block of code. @petermaxlee , let me know if you need help preparing the final version for merge.