[SPARK-17494] [SQL] changePrecision() on compact decimal should respect rounding mode
apache/spark pull request #15154
Opened 2016-09-19 21:53 UTC by davies

## What changes were proposed in this pull request?

Floor()/Ceil() of decimal is implemented using changePrecision() by passing a rounding mode, but the rounding mode is not respected when the decimal is in compact mode (could fit within a Long). 

This Update the changePrecision() to respect rounding mode, which could be ROUND_FLOOR, ROUND_CEIL, ROUND_HALF_UP, ROUND_HALF_EVEN.
 
## How was this patch tested?

Added regression tests.

2016-09-19 21:53 UTC, davies commented
cc @JoshRosen @chenghao-intel

2016-09-19 21:57 UTC, SparkQA commented
**[Test build #65617 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/65617/consoleFull)** for PR 15154 at commit [`cf0e445`](https://github.com/apache/spark/commit/cf0e445b600baad201062e77651bee3d907b42fd).

2016-09-19 23:56 UTC, SparkQA commented
**[Test build #65617 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/65617/consoleFull)** for PR 15154 at commit [`cf0e445`](https://github.com/apache/spark/commit/cf0e445b600baad201062e77651bee3d907b42fd).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-09-19 23:57 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-09-19 23:57 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/65617/
Test PASSed.

2016-09-21 17:14 UTC, srinathshankar commented on sql/catalyst/src/main/scala/org/apache/spark/sql/types/Decimal.scala
> +              longVal += (if (longVal < 0) -1L else 1L)
Is this correct if longVal is 0, after the division above
What happens if you round_half_up -0.6 ? Looks like you may get +1 ?

2016-09-21 17:14 UTC, srinathshankar commented on sql/catalyst/src/test/scala/org/apache/spark/sql/types/DecimalSuite.scala
> +      Seq("1.0", "1.1", "1.6", "2.5", "5.5", "-1.0", "-1.1", "-1.6", "-2.5", "-5.5").foreach { n =>
tests of the form 0.5, -0.5, 0.6 etc. might also be useful

2016-09-21 17:15 UTC, srinathshankar requested changes

2016-09-21 19:49 UTC, davies commented on sql/catalyst/src/test/scala/org/apache/spark/sql/types/DecimalSuite.scala
> +      Seq("1.0", "1.1", "1.6", "2.5", "5.5", "-1.0", "-1.1", "-1.6", "-2.5", "-5.5").foreach { n =>
Currently, these numbers are copied from the java doc of RoundingMode, will add more for ROUND_HALF_EVEN

2016-09-21 19:57 UTC, davies commented on sql/catalyst/src/main/scala/org/apache/spark/sql/types/Decimal.scala
> +              longVal += (if (longVal < 0) -1L else 1L)
Good catch, we should use droppedDigits here.

2016-09-21 19:57 UTC, davies reviewed
Thanks for the comment, pushed the fix

2016-09-21 20:02 UTC, SparkQA commented
**[Test build #65732 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/65732/consoleFull)** for PR 15154 at commit [`bb15eef`](https://github.com/apache/spark/commit/bb15eefed57ea32551d8b7985d9e54d4a512afe6).

2016-09-21 22:18 UTC, SparkQA commented
**[Test build #65732 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/65732/consoleFull)** for PR 15154 at commit [`bb15eef`](https://github.com/apache/spark/commit/bb15eefed57ea32551d8b7985d9e54d4a512afe6).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-09-21 22:19 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-09-21 22:19 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/65732/
Test PASSed.

2016-09-21 22:25 UTC, srinathshankar commented on sql/catalyst/src/test/scala/org/apache/spark/sql/types/DecimalSuite.scala
> +        Seq("", "-").foreach { sigh =>
I think you mean sign, not sigh, though I can understand :)

2016-09-21 22:42 UTC, SparkQA commented
**[Test build #65739 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/65739/consoleFull)** for PR 15154 at commit [`7008cd3`](https://github.com/apache/spark/commit/7008cd36f21b14817c28dbb9a4ea9547174f0f01).

2016-09-21 22:43 UTC, srinathshankar approved these changes
LGTM.

2016-09-22 01:13 UTC, SparkQA commented
**[Test build #65739 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/65739/consoleFull)** for PR 15154 at commit [`7008cd3`](https://github.com/apache/spark/commit/7008cd36f21b14817c28dbb9a4ea9547174f0f01).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-09-22 01:14 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-09-22 01:14 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/65739/
Test PASSed.

2016-09-22 04:01 UTC, rxin commented
Merging in master/2.0.

2016-09-22 04:04 UTC, closed without merging