[SPARK-17680] [SQL] [TEST] Added a Testcase for Verifying Unicode Character Support for Column Names and Comments
apache/spark pull request #15255
Opened 2016-09-27 05:09 UTC by gatorsmile

### What changes were proposed in this pull request?
When the version of the Hive metastore is higher than 0.12, Spark SQL supports Unicode characters for column names when specified within backticks(`). See the JIRA: https://issues.apache.org/jira/browse/HIVE-6013 Hive metastore supports Unicode characters for column names since 0.13 

In Spark SQL, table comments, and view comments always allow Unicode characters without backticks.

BTW, will submit a separate PR for database and table name validation because we do not support Unicode characters in these two cases. 

### How was this patch tested?
N/A

2016-09-27 05:12 UTC, SparkQA commented
**[Test build #65946 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/65946/consoleFull)** for PR 15255 at commit [`741d59c`](https://github.com/apache/spark/commit/741d59c2565f70404409cc4a8afcf002148c3d74).

2016-09-27 05:26 UTC, gatorsmile commented
Also need to add a test case for data source tables. Will do it later

2016-09-27 05:30 UTC, gatorsmile commented
... Hit a bug in the write path... Need to fix it at first...

2016-09-27 06:20 UTC, gatorsmile commented
... Hit one more bug in the write path...

2016-09-27 06:39 UTC, SparkQA commented
**[Test build #65946 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/65946/consoleFull)** for PR 15255 at commit [`741d59c`](https://github.com/apache/spark/commit/741d59c2565f70404409cc4a8afcf002148c3d74).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-09-27 06:40 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-09-27 06:40 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/65946/
Test PASSed.

2016-11-07 03:29 UTC, gatorsmile commented
retest this please

2016-11-07 03:32 UTC, SparkQA commented
**[Test build #68263 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/68263/consoleFull)** for PR 15255 at commit [`741d59c`](https://github.com/apache/spark/commit/741d59c2565f70404409cc4a8afcf002148c3d74).

2016-11-07 04:45 UTC, SparkQA commented
**[Test build #68263 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/68263/consoleFull)** for PR 15255 at commit [`741d59c`](https://github.com/apache/spark/commit/741d59c2565f70404409cc4a8afcf002148c3d74).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-11-07 04:46 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-11-07 04:46 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/68263/
Test FAILed.

2016-11-27 00:38 UTC, gatorsmile commented
retest this please

2016-11-27 00:42 UTC, SparkQA commented
**[Test build #69197 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69197/consoleFull)** for PR 15255 at commit [`741d59c`](https://github.com/apache/spark/commit/741d59c2565f70404409cc4a8afcf002148c3d74).

2016-11-27 02:13 UTC, SparkQA commented
**[Test build #69197 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69197/consoleFull)** for PR 15255 at commit [`741d59c`](https://github.com/apache/spark/commit/741d59c2565f70404409cc4a8afcf002148c3d74).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-11-27 02:13 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-11-27 02:13 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/69197/
Test PASSed.

2016-11-29 06:09 UTC, gatorsmile commented
cc @cloud-fan Could you review this PR? Thanks!

2016-11-29 06:13 UTC, cloud-fan requested changes

2016-11-29 06:13 UTC, cloud-fan commented on sql/hive/src/test/scala/org/apache/spark/sql/hive/execution/HiveDDLSuite.scala
> +      // non ascii characters are not allowed in the source code, so we disable the scalastyle.
remove this line?

2016-11-29 10:53 UTC, cloud-fan commented
LGTM

2016-11-29 22:42 UTC, SparkQA commented
**[Test build #69357 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69357/consoleFull)** for PR 15255 at commit [`57817a1`](https://github.com/apache/spark/commit/57817a1c96c9577725ee8766834b20b06adfe521).

2016-11-30 00:14 UTC, SparkQA commented
**[Test build #69357 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69357/consoleFull)** for PR 15255 at commit [`57817a1`](https://github.com/apache/spark/commit/57817a1c96c9577725ee8766834b20b06adfe521).
 * This patch **fails PySpark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-11-30 00:15 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-11-30 00:15 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/69357/
Test FAILed.

2016-11-30 04:00 UTC, gatorsmile commented
retest this please

2016-11-30 04:02 UTC, SparkQA commented
**[Test build #69379 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69379/consoleFull)** for PR 15255 at commit [`57817a1`](https://github.com/apache/spark/commit/57817a1c96c9577725ee8766834b20b06adfe521).

2016-11-30 06:01 UTC, SparkQA commented
**[Test build #69379 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69379/consoleFull)** for PR 15255 at commit [`57817a1`](https://github.com/apache/spark/commit/57817a1c96c9577725ee8766834b20b06adfe521).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-11-30 06:02 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-11-30 06:02 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/69379/
Test PASSed.

2016-11-30 07:19 UTC, cloud-fan commented
thanks, merging to master/2.1!

2016-11-30 07:19 UTC, closed without merging