[SPARK-17733][SQL] InferFiltersFromConstraints rule never terminates for query
apache/spark pull request #15319
Opened 2016-10-01 05:03 UTC by jiangxb1987

## What changes were proposed in this pull request?

The function `QueryPlan.inferAdditionalConstraints` and `UnaryNode.getAliasedConstraints` can produce a non-converging set of constraints for recursive functions. For instance, if we have two constraints of the form(where a is an alias):
`a = b, a = f(b, c)`
Applying both these rules in the next iteration would infer:
`f(b, c) = f(f(b, c), c)`
This process repeated, the iteration won't converge and the set of constraints will grow larger and larger until OOM.

To fix this problem, we collect alias from expressions and skip infer constraints if we are to transform an `Expression` to another which contains it.

## How was this patch tested?

Add new testcase in `SQLQuerySuite`.

2016-10-01 05:04 UTC, rxin commented on sql/core/src/test/scala/org/apache/spark/sql/SQLQuerySuite.scala
> +  test("SPARK-17733 InferFiltersFromConstraints rule never terminates for query") {
can we construct a unit test rather than an end-to-end test here?

2016-10-01 05:07 UTC, SparkQA commented
**[Test build #66205 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66205/consoleFull)** for PR 15319 at commit [`ebba446`](https://github.com/apache/spark/commit/ebba4468c6707e35656d122f99ec074f2785195e).

2016-10-01 05:10 UTC, jiangxb1987 commented on sql/core/src/test/scala/org/apache/spark/sql/SQLQuerySuite.scala
> +  test("SPARK-17733 InferFiltersFromConstraints rule never terminates for query") {
Yes - Perhaps we could add new testcases in `InferFiltersFromConstraintsSuite`.

2016-10-01 05:11 UTC, rxin commented on sql/core/src/test/scala/org/apache/spark/sql/SQLQuerySuite.scala
> +  test("SPARK-17733 InferFiltersFromConstraints rule never terminates for query") {
+1

2016-10-01 05:21 UTC, SparkQA commented
**[Test build #66205 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66205/consoleFull)** for PR 15319 at commit [`ebba446`](https://github.com/apache/spark/commit/ebba4468c6707e35656d122f99ec074f2785195e).
 * This patch **fails MiMa tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-01 05:21 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-01 05:21 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66205/
Test FAILed.

2016-10-01 05:31 UTC, hvanhovell commented
retest this please

2016-10-01 05:32 UTC, SparkQA commented
**[Test build #66206 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66206/consoleFull)** for PR 15319 at commit [`ebba446`](https://github.com/apache/spark/commit/ebba4468c6707e35656d122f99ec074f2785195e).

2016-10-01 07:40 UTC, SparkQA commented
**[Test build #66206 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66206/consoleFull)** for PR 15319 at commit [`ebba446`](https://github.com/apache/spark/commit/ebba4468c6707e35656d122f99ec074f2785195e).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-01 07:41 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-01 07:41 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66206/
Test PASSed.

2016-10-01 08:32 UTC, SparkQA commented
**[Test build #66212 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66212/consoleFull)** for PR 15319 at commit [`7d9e2b0`](https://github.com/apache/spark/commit/7d9e2b0580f274df68d3de4c867e1527924d1b24).

2016-10-01 08:33 UTC, jiangxb1987 commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/optimizer/InferFiltersFromConstraintsSuite.scala
> +      && IsNotNull(Coalesce(Seq('a, 'b))) && 'a === 'b)
These predicates are infered from `t.a = t2.a, t.d = t2.a, t.int_col = t2.a`, which in line with our expectation.

2016-10-01 08:37 UTC, SparkQA commented
**[Test build #66213 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66213/consoleFull)** for PR 15319 at commit [`3b93209`](https://github.com/apache/spark/commit/3b93209b7192461a1390e205f88d51bbee780ff0).

2016-10-01 10:28 UTC, SparkQA commented
**[Test build #66212 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66212/consoleFull)** for PR 15319 at commit [`7d9e2b0`](https://github.com/apache/spark/commit/7d9e2b0580f274df68d3de4c867e1527924d1b24).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-01 10:30 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-01 10:30 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66212/
Test PASSed.

2016-10-01 10:39 UTC, SparkQA commented
**[Test build #66213 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66213/consoleFull)** for PR 15319 at commit [`3b93209`](https://github.com/apache/spark/commit/3b93209b7192461a1390e205f88d51bbee780ff0).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-01 10:40 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-01 10:40 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66213/
Test PASSed.

2016-10-01 16:52 UTC, SparkQA commented
**[Test build #66223 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66223/consoleFull)** for PR 15319 at commit [`5b25fce`](https://github.com/apache/spark/commit/5b25fce87bb1c33bee4437936ed49e008db6a427).

2016-10-01 17:12 UTC, jiangxb1987 commented
After more thoughts, I discovered various ways to create non-converge constraint set(in the following cases, a represents `Alias(f(b, c), "a")`):
Condition 1. `a = b` will infer `f(b, c) = f(f(b, c), c)`;
Condition 2. `a = d, b = d` will infer `a = b` and therefore deducts `f(b, c) = f(f(b, c), c)`;
Condition 3. `a = d, d = e, e = f, ..., x = b` will deduct `f(b, c) = f(f(b, c), c)` too after certain iterations;
Condition 4. `a = d, b = d` will also infer `f(d, c) = f(f(d, c), c)` and so on.

For the Cond. 1/2/3, we can avoid to create non-converge constraint set by checking whether constraint contains `a.child`(e.g. f(b, c)), but for the Cond. 4, I haven't figure out a work around.

A new approach will be avoid replace an `Alias` into constraint, it will ensure that `QueryPlan.inferAdditionalConstraints` and `UnaryNode.getAliasedConstraints` won't both apply and therefore no non-converge constraint set will be created. For this approach, we may miss some constraints that could have been infered, but I think it won't be super harmful because these constraints are commonly complex that rarely filters more data.

2016-10-01 17:15 UTC, jiangxb1987 commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/optimizer/InferFiltersFromConstraintsSuite.scala
> +    val batches =
Previous `batches` will not apply `InferFiltersFromConstraints` after  `PushPredicateThroughJoin`.

2016-10-01 17:32 UTC, SparkQA commented
**[Test build #66224 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66224/consoleFull)** for PR 15319 at commit [`e5912f8`](https://github.com/apache/spark/commit/e5912f86c94ff4d6303c9d0a9b80a30d30b99e3d).

2016-10-01 18:51 UTC, SparkQA commented
**[Test build #66223 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66223/consoleFull)** for PR 15319 at commit [`5b25fce`](https://github.com/apache/spark/commit/5b25fce87bb1c33bee4437936ed49e008db6a427).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-01 18:52 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-01 18:52 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66223/
Test PASSed.

2016-10-01 19:11 UTC, SparkQA commented
**[Test build #66224 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66224/consoleFull)** for PR 15319 at commit [`e5912f8`](https://github.com/apache/spark/commit/e5912f86c94ff4d6303c9d0a9b80a30d30b99e3d).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-01 19:12 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-01 19:12 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66224/
Test FAILed.

2016-10-02 01:52 UTC, SparkQA commented
**[Test build #66234 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66234/consoleFull)** for PR 15319 at commit [`9639c71`](https://github.com/apache/spark/commit/9639c71862d1e7783bc3ca4d750d68e7aa35be92).

2016-10-02 03:51 UTC, SparkQA commented
**[Test build #66234 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66234/consoleFull)** for PR 15319 at commit [`9639c71`](https://github.com/apache/spark/commit/9639c71862d1e7783bc3ca4d750d68e7aa35be92).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-02 03:52 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-02 03:52 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66234/
Test PASSed.

2016-10-05 02:01 UTC, hvanhovell commented
cc @sameeragarwal

2016-10-08 11:12 UTC, jiangxb1987 commented
@sameeragarwal Could you review this PR please?

2016-10-08 15:06 UTC, lins05 commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/QueryPlan.scala
> +    // For more details, infer https://issues.apache.org/jira/browse/SPARK-17733
typo "infer" -> "refer" (to)?

2016-10-08 15:06 UTC, lins05 commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/QueryPlan.scala
> +    val aliasMap = AttributeMap((expressions ++ children.flatMap(_.expressions)).collect {
Why not using `AttributeSet`?

2016-10-09 06:22 UTC, SparkQA commented
**[Test build #66597 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66597/consoleFull)** for PR 15319 at commit [`1558d4c`](https://github.com/apache/spark/commit/1558d4c2f9190691239e9b27e9517714c2af2bcc).

2016-10-09 08:23 UTC, SparkQA commented
**[Test build #66597 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66597/consoleFull)** for PR 15319 at commit [`1558d4c`](https://github.com/apache/spark/commit/1558d4c2f9190691239e9b27e9517714c2af2bcc).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-09 08:23 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-09 08:23 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66597/
Test FAILed.

2016-10-10 06:30 UTC, jiangxb1987 commented
retest this please.

2016-10-10 06:32 UTC, SparkQA commented
**[Test build #66631 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66631/consoleFull)** for PR 15319 at commit [`1558d4c`](https://github.com/apache/spark/commit/1558d4c2f9190691239e9b27e9517714c2af2bcc).

2016-10-10 08:33 UTC, SparkQA commented
**[Test build #66631 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66631/consoleFull)** for PR 15319 at commit [`1558d4c`](https://github.com/apache/spark/commit/1558d4c2f9190691239e9b27e9517714c2af2bcc).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-10 08:34 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-10 08:34 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66631/
Test FAILed.

2016-10-10 10:34 UTC, jiangxb1987 commented
Not sure why these testcases are failing, they passed in my local envirement.

2016-10-10 12:52 UTC, SparkQA commented
**[Test build #3308 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3308/consoleFull)** for PR 15319 at commit [`1558d4c`](https://github.com/apache/spark/commit/1558d4c2f9190691239e9b27e9517714c2af2bcc).

2016-10-10 13:00 UTC, SparkQA commented
**[Test build #3308 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3308/consoleFull)** for PR 15319 at commit [`1558d4c`](https://github.com/apache/spark/commit/1558d4c2f9190691239e9b27e9517714c2af2bcc).
 * This patch **fails to build**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-10 15:44 UTC, jiangxb1987 commented
retest this please.

2016-10-10 15:47 UTC, SparkQA commented
**[Test build #66658 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66658/consoleFull)** for PR 15319 at commit [`1558d4c`](https://github.com/apache/spark/commit/1558d4c2f9190691239e9b27e9517714c2af2bcc).

2016-10-10 18:07 UTC, SparkQA commented
**[Test build #66658 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66658/consoleFull)** for PR 15319 at commit [`1558d4c`](https://github.com/apache/spark/commit/1558d4c2f9190691239e9b27e9517714c2af2bcc).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-10 18:08 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-10 18:08 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66658/
Test FAILed.

2016-10-10 18:18 UTC, SparkQA commented
**[Test build #3319 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3319/consoleFull)** for PR 15319 at commit [`1558d4c`](https://github.com/apache/spark/commit/1558d4c2f9190691239e9b27e9517714c2af2bcc).

2016-10-10 20:48 UTC, SparkQA commented
**[Test build #3319 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3319/consoleFull)** for PR 15319 at commit [`1558d4c`](https://github.com/apache/spark/commit/1558d4c2f9190691239e9b27e9517714c2af2bcc).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-15 05:38 UTC, jiangxb1987 commented
retest this please.

2016-10-15 05:42 UTC, SparkQA commented
**[Test build #67007 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67007/consoleFull)** for PR 15319 at commit [`1558d4c`](https://github.com/apache/spark/commit/1558d4c2f9190691239e9b27e9517714c2af2bcc).

2016-10-15 07:54 UTC, SparkQA commented
**[Test build #67007 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67007/consoleFull)** for PR 15319 at commit [`1558d4c`](https://github.com/apache/spark/commit/1558d4c2f9190691239e9b27e9517714c2af2bcc).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-15 07:55 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-15 07:55 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67007/
Test FAILed.

2016-10-15 16:57 UTC, SparkQA commented
**[Test build #67020 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67020/consoleFull)** for PR 15319 at commit [`388443d`](https://github.com/apache/spark/commit/388443d2886d09fec6a25b8400c6eb9631373135).

2016-10-15 19:05 UTC, SparkQA commented
**[Test build #67020 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67020/consoleFull)** for PR 15319 at commit [`388443d`](https://github.com/apache/spark/commit/388443d2886d09fec6a25b8400c6eb9631373135).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-15 19:06 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-15 19:06 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67020/
Test PASSed.

2016-10-17 01:57 UTC, jiangxb1987 commented
ping @sameeragarwal

2016-10-18 03:12 UTC, jiangxb1987 commented
This PR is ready for review, would anyone look at it?

2016-10-18 06:57 UTC, sameeragarwal requested changes

2016-10-18 06:57 UTC, sameeragarwal commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/QueryPlan.scala
> +          case a: Attribute if a.semanticEquals(l) && !aliasSet.contains(r) => r
@jiangxb1987 isn't this a fairly restrictive way to solve this problem? You are essentially not inferring any additional constraints from those that contain aliases. For e.g., if we have have a query `SELECT a AS a1, b AS b1 WHERE a1 = 1 AND a1 = b1`, this change would never allow us to infer a filter/constraint on `b = 1`. Can we identify and just disallow recursive constraints?

2016-10-19 12:27 UTC, SparkQA commented
**[Test build #67195 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67195/consoleFull)** for PR 15319 at commit [`909d2cd`](https://github.com/apache/spark/commit/909d2cde961bc61ff5d6a20b135803fb7eee3eb9).

2016-10-19 14:30 UTC, SparkQA commented
**[Test build #67195 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67195/consoleFull)** for PR 15319 at commit [`909d2cd`](https://github.com/apache/spark/commit/909d2cde961bc61ff5d6a20b135803fb7eee3eb9).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-19 14:31 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-19 14:31 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67195/
Test PASSed.

2016-10-19 15:17 UTC, jiangxb1987 commented
@sameeragarwal I've updated the rule, please review when you have time! Thank you!

2016-10-21 05:39 UTC, sameeragarwal commented
Thanks @jiangxb1987, this equivalence class approach looks pretty solid. I'll take a closer look tomorrow!

2016-10-24 09:31 UTC, sameeragarwal requested changes
Thanks again @jiangxb1987, I just left some comments around structure and styling but overall this approach looks good to me.

2016-10-24 09:31 UTC, sameeragarwal commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/QueryPlan.scala
> +    val equalExprSets = generateEqualExpressionSets(constraints, aliasMap)
nit: How about calling them `val constraintClasses`?

2016-10-24 09:31 UTC, sameeragarwal commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/QueryPlan.scala
> +  private def generateEqualExpressionSets(
How about `generateEquivalentConstraintClasses` or `generateEquivalentConstraintSet`?

2016-10-24 09:31 UTC, sameeragarwal commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/QueryPlan.scala
> +        if (!leftEqualSet.isEmpty && !rightEqualSet.isEmpty) {
nit: can use `leftEqualSet.nonEmpty` and `rightEqualSet.nonEmpty` here and at other places

2016-10-24 09:31 UTC, sameeragarwal commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/QueryPlan.scala
> +        val leftEqualSet = getEqualExprSet(left, equalExprSets).getOrElse(Set.empty[Expression])
nit: similarly, I think calling these `leftConstraintSet` and `rightConstraintSet` might be more readable (things like `Equal` and `ExprSet` are already implied from semantics and method definition and needn't be in the method name)

2016-10-24 09:31 UTC, sameeragarwal commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/QueryPlan.scala
> +  private def getEqualExprSet(
nit: `getConstraintSet` or `getConstraintClass`?

2016-10-24 09:31 UTC, sameeragarwal commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/QueryPlan.scala
> +    equalExprSets.filter(_.contains(expr)).headOption
can just have `equalExprSets.find(_.contains(expr))`

2016-10-24 09:31 UTC, sameeragarwal commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/QueryPlan.scala
> +      equalExprSets: Seq[Set[Expression]]): Option[Set[Expression]] =
we can just have this return `Set[Expression]` and fold the `.getOrElse(Set.empty[Expression])` logic inside

2016-10-24 09:31 UTC, sameeragarwal commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/QueryPlan.scala
> +   *  Check whether replace by an [[Attribute]] will cause an recursive deduction. Generally it
nit: typo s/an/a

2016-10-24 09:31 UTC, sameeragarwal commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/QueryPlan.scala
> +   *  has an form like: `a -> f(a, b)`, where `a` and `b` are expressions and `f` is an function.
nit: typo s/an/a

2016-10-24 09:31 UTC, sameeragarwal commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/QueryPlan.scala
> +   *  is child of the referenced expression.
nit: `is a child`.

2016-10-24 09:31 UTC, sameeragarwal commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/QueryPlan.scala
> +   *  is child of the referenced expression.
This is a great comment btw!

2016-10-24 09:31 UTC, sameeragarwal commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/optimizer/InferFiltersFromConstraintsSuite.scala
> +    val currectAnswer = t1.where(IsNotNull('a) && IsNotNull(Coalesce(Seq('a, 'b)))
nit: typo `correctAnswer`

2016-10-24 09:31 UTC, sameeragarwal commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/optimizer/InferFiltersFromConstraintsSuite.scala
> +    val currectAnswer = t1.where(IsNotNull('a) && IsNotNull('b)
nit: typo

2016-10-24 09:31 UTC, sameeragarwal commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/optimizer/InferFiltersFromConstraintsSuite.scala
> +        && 'a <=> 'a && 'b <=> 'b &&'a === 'b)
nit: 2 spaces

2016-10-24 09:31 UTC, sameeragarwal commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/optimizer/InferFiltersFromConstraintsSuite.scala
> +        &&'a === Coalesce(Seq('a, 'b)))
nit: 2 spaces

2016-10-24 09:31 UTC, sameeragarwal commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/optimizer/InferFiltersFromConstraintsSuite.scala
> +      && 'a === Coalesce(Seq('a, 'a)) && 'a <=> Coalesce(Seq('a, 'a)) && 'a <=> 'a
nit: 2 spaces

2016-10-24 09:31 UTC, sameeragarwal commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/optimizer/InferFiltersFromConstraintsSuite.scala
> +      && Coalesce(Seq('a, 'a)) <=> Coalesce(Seq('a, 'a))), Inner,
nit: 2 spaces

2016-10-24 09:31 UTC, sameeragarwal commented on sql/core/src/test/scala/org/apache/spark/sql/SQLQuerySuite.scala
> +  test("SPARK-17733 InferFiltersFromConstraints rule never terminates for query") {
Given that you already have a unit test for cases like these, how about we remove this now? This test was randomly generated to catch issues like this and in its current form, it isn't very obvious how this query has anything to do with `InferFiltersFromConstraints`.

2016-10-25 07:12 UTC, jiangxb1987 commented
Thank you @sameeragarwal ! I've updated these codes following your advice, please have a look at them when you have time.

2016-10-25 07:12 UTC, SparkQA commented
**[Test build #67495 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67495/consoleFull)** for PR 15319 at commit [`905eaa1`](https://github.com/apache/spark/commit/905eaa12925fe8638df01a738b977e2f32a5fc9c).

2016-10-25 07:17 UTC, SparkQA commented
**[Test build #67497 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67497/consoleFull)** for PR 15319 at commit [`45308d5`](https://github.com/apache/spark/commit/45308d50de27fb4b6c2c9ee88e55ba808ef5ef6f).

2016-10-25 09:27 UTC, SparkQA commented
**[Test build #67495 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67495/consoleFull)** for PR 15319 at commit [`905eaa1`](https://github.com/apache/spark/commit/905eaa12925fe8638df01a738b977e2f32a5fc9c).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-25 09:28 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-25 09:28 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67495/
Test PASSed.

2016-10-25 09:30 UTC, SparkQA commented
**[Test build #67497 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67497/consoleFull)** for PR 15319 at commit [`45308d5`](https://github.com/apache/spark/commit/45308d50de27fb4b6c2c9ee88e55ba808ef5ef6f).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-25 09:31 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-25 09:31 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67497/
Test PASSed.

2016-10-26 12:02 UTC, sameeragarwal commented
LGTM, Thanks!

2016-10-26 15:09 UTC, hvanhovell commented
Merging to master! Thanks!

2016-10-26 15:12 UTC, closed without merging