[SPARK-17157][SPARKR]: Add multiclass logistic regression SparkR Wrapper
apache/spark pull request #15365
Opened 2016-10-05 23:41 UTC by wangmiao1981

## What changes were proposed in this pull request?

As we discussed in #14818, I added a separate R wrapper spark.logit for logistic regression. 

This single interface supports both binary and multinomial logistic regression. It also has "predict" and "summary" for binary logistic regression. 

## How was this patch tested?

New unit tests are added.

2016-10-05 23:42 UTC, SparkQA commented
**[Test build #66405 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66405/consoleFull)** for PR 15365 at commit [`5bfd132`](https://github.com/apache/spark/commit/5bfd1320000791bed933b10dc3af8f0857d6be99).

2016-10-05 23:46 UTC, SparkQA commented
**[Test build #66405 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66405/consoleFull)** for PR 15365 at commit [`5bfd132`](https://github.com/apache/spark/commit/5bfd1320000791bed933b10dc3af8f0857d6be99).
 * This patch **fails R style tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-05 23:46 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-05 23:46 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66405/
Test FAILed.

2016-10-05 23:57 UTC, SparkQA commented
**[Test build #66407 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66407/consoleFull)** for PR 15365 at commit [`0f4f551`](https://github.com/apache/spark/commit/0f4f5510e595459b7eb399f5d32d8a9a9304ba84).

2016-10-06 00:02 UTC, SparkQA commented
**[Test build #66407 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66407/consoleFull)** for PR 15365 at commit [`0f4f551`](https://github.com/apache/spark/commit/0f4f5510e595459b7eb399f5d32d8a9a9304ba84).
 * This patch **fails R style tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-06 00:02 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-06 00:02 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66407/
Test FAILed.

2016-10-06 04:12 UTC, SparkQA commented
**[Test build #66428 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66428/consoleFull)** for PR 15365 at commit [`a172bb4`](https://github.com/apache/spark/commit/a172bb4a5ff1ce0f6c5d1bd79c74dc8abc7a14a8).

2016-10-06 05:10 UTC, SparkQA commented
**[Test build #66428 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66428/consoleFull)** for PR 15365 at commit [`a172bb4`](https://github.com/apache/spark/commit/a172bb4a5ff1ce0f6c5d1bd79c74dc8abc7a14a8).
 * This patch **fails SparkR unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-06 05:10 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-06 05:10 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66428/
Test FAILed.

2016-10-06 18:07 UTC, wangmiao1981 commented
@felixcheung  When run check-cran, there are errors:
 Error : requireNamespace("e1071", quietly = TRUE) is not TRUE
Error : requireNamespace("e1071", quietly = TRUE) is not TRUE
Error : requireNamespace("e1071", quietly = TRUE) is not TRUE
Error : requireNamespace("e1071", quietly = TRUE) is not TRUE
Error : requireNamespace("e1071", quietly = TRUE) is not TRUE

I am trying to figure out what is the problem. Any hints?

Thanks!

2016-10-06 18:18 UTC, wangmiao1981 commented
From Jekins, I saw the error:
WARNING: There was 1 warning.
NOTE: There were 3 notes.
See
  '/home/jenkins/workspace/SparkPullRequestBuilder/R/SparkR.Rcheck/00check.log'
for details.

Had CRAN check errors; see logs.

How can I access the above file?

2016-10-06 18:40 UTC, wangmiao1981 commented
I see the error message on local test:

LaTeX errors when creating PDF version.
This typically indicates Rd problems.
* checking PDF version of manual without hyperrefs or index ... ERROR
Re-running with no redirection of stdout/stderr.
Hmm ... looks like a package
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  pdflatex is not available
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  pdflatex is not available
Error in running tools::texi2pdf()
You may want to clean up by 'rm -rf /var/folders/s_/83b0sgvj2kl2kwq4stvft_pm0000gn/T//RtmpXHJrOk/Rd2pdfac8961d3ab54'
* DONE

2016-10-06 19:29 UTC, vectorijk commented
@wangmiao1981 I saw the similar error on Jekin. Same with question with you.
Regarding to `e1071`, I think we only need to install that package locally.

2016-10-06 20:58 UTC, wangmiao1981 commented
@vectorijk  Thanks for your information! I installed e1071 and installed tex package. I just want to find what causes the error.

2016-10-06 21:36 UTC, wangmiao1981 commented
My local tests passed.

Jenkins, retest this please.

2016-10-06 22:04 UTC, wangmiao1981 commented
re-test please

2016-10-06 22:42 UTC, SparkQA commented
**[Test build #66468 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66468/consoleFull)** for PR 15365 at commit [`0811fc3`](https://github.com/apache/spark/commit/0811fc3c71b665b99aec1e794d3782c98563e84c).

2016-10-06 23:46 UTC, SparkQA commented
**[Test build #66468 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66468/consoleFull)** for PR 15365 at commit [`0811fc3`](https://github.com/apache/spark/commit/0811fc3c71b665b99aec1e794d3782c98563e84c).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-06 23:47 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-06 23:47 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66468/
Test PASSed.

2016-10-07 02:07 UTC, wangmiao1981 commented
@felixcheung I fixed the cran errors. It is ready to review now. Thanks!

2016-10-07 17:26 UTC, wangmiao1981 commented
cc @sethah @yanboliang

2016-10-07 18:49 UTC, felixcheung commented
It would be great to get some feedback on the name `spark.logit`
What do folks think about it?

2016-10-07 22:38 UTC, wangmiao1981 commented on R/pkg/R/mllib.R
> +#' binary_df <- suppressWarnings(createDataFrame(binary_data))
I followed other test examples. If it is not necessary, I can remove all of them as a followup JIRA.

2016-10-07 22:40 UTC, wangmiao1981 commented
For the name, as we previously discussed, we can't use glm as interface changes and glm only support binominal logistic regression. We don't use glmnet because current spark.logit only provides logistic regressions which are subset of glmnet.

2016-10-07 23:26 UTC, felixcheung commented on R/pkg/R/mllib.R
> +#' binary_df <- suppressWarnings(createDataFrame(binary_data))
Not for all data frame - it is only necessary for data frame with column names containing `.`, eg. `iris`. So not for this case.

2016-10-07 23:27 UTC, felixcheung commented
Sure-  I recall that discussion.

2016-10-08 02:41 UTC, wangmiao1981 commented
I just pick the name for simplicity. Hope to receive feedback from the community and I can make changes accordingly. Thanks!

2016-10-08 02:41 UTC, wangmiao1981 commented on R/pkg/R/mllib.R
> +#' binary_df <- suppressWarnings(createDataFrame(binary_data))
I see. Thanks for your explanation!

2016-10-08 04:02 UTC, SparkQA commented
**[Test build #66563 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66563/consoleFull)** for PR 15365 at commit [`1921221`](https://github.com/apache/spark/commit/1921221964131b9cf8ba500b2dcf2f2219d3b20c).

2016-10-08 05:01 UTC, SparkQA commented
**[Test build #66563 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66563/consoleFull)** for PR 15365 at commit [`1921221`](https://github.com/apache/spark/commit/1921221964131b9cf8ba500b2dcf2f2219d3b20c).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-08 05:01 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-08 05:01 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66563/
Test PASSed.

2016-10-08 06:40 UTC, vectorijk commented on R/pkg/R/mllib.R
> +#' @seealso \link{spark.logit}, \link{read.ml}
this group of links could be sorted

2016-10-08 06:40 UTC, vectorijk commented on R/pkg/R/mllib.R
> +#' @seealso \link{spark.mlp}, \link{spark.naiveBayes}, \link{spark.survreg}, \link{spark.logit}
same here.

2016-10-09 18:41 UTC, felixcheung commented on R/pkg/R/mllib.R
> +#'               Supported options:
roxygen2 is going to trim all the whitespaces, you will need to add formatting with \item and so on

2016-10-09 18:46 UTC, felixcheung commented on R/pkg/R/mllib.R
> +#' @param thresholds in multiclass (or binary) classification to adjust the probability of predicting each class.
this might be confusing, in particular with parameter matching in R, should this be `thresholds` when length == 1 for binary and > 1 for multiclass?

2016-10-09 18:58 UTC, felixcheung commented on R/pkg/R/mllib.R
> +#'                  threshold p is equivalent to setting thresholds (Array(1-p, p)). When threshold is set, any user-set
do you have a more R-like representation for `(Array(1-p, p))`?

2016-10-09 18:59 UTC, felixcheung commented on R/pkg/R/mllib.R
> +#'                   Array must have length equal to the number of classes, with values > 0, excepting that at most one
Array is not often used in R, could we handle vector?

2016-10-09 19:01 UTC, felixcheung commented on R/pkg/R/mllib.R
> +#' binary_df <- suppressWarnings(createDataFrame(binary_data))
so let's remove this suppressWarnings here.

2016-10-09 19:02 UTC, felixcheung commented on R/pkg/R/mllib.R
> +#' df <- suppressWarnings(createDataFrame(data))
same here for `suppressWarnings`

2016-10-09 19:05 UTC, felixcheung commented on R/pkg/R/mllib.R
> +#' @rdname spark.logit
add `@aliases`

2016-10-09 19:07 UTC, felixcheung commented on R/pkg/R/mllib.R
> +              NULL
instead of return NULL, perhaps we should `stop()` with a message?

2016-10-09 19:19 UTC, felixcheung requested changes
How is this related to `spark.glm(family = "binomial")`?

2016-10-09 19:31 UTC, felixcheung commented on R/pkg/R/mllib.R
> +                   threshold = 0.5, thresholds = NULL, weightCol = NULL, aggregationDepth = 2) {
should it support `probabilityCol`

2016-10-10 06:53 UTC, wangmiao1981 commented on R/pkg/R/mllib.R
> +#' @seealso \link{spark.logit}, \link{read.ml}
I will make changes when we agree on the name. Thanks!

2016-10-12 23:42 UTC, SparkQA commented
**[Test build #66857 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66857/consoleFull)** for PR 15365 at commit [`08babe5`](https://github.com/apache/spark/commit/08babe50df42bc4247a65f24cc95241891b555a8).

2016-10-12 23:44 UTC, wangmiao1981 commented on R/pkg/R/mllib.R
> +              NULL
Refactored the code. Stop() if it is loaded and remove `if` statements in other places.

2016-10-12 23:44 UTC, wangmiao1981 commented on R/pkg/R/mllib.R
> +#' @rdname spark.logit
Done.

2016-10-12 23:44 UTC, wangmiao1981 commented on R/pkg/R/mllib.R
> +#' df <- suppressWarnings(createDataFrame(data))
Done.

2016-10-12 23:47 UTC, wangmiao1981 commented on R/pkg/R/mllib.R
> +#' @param thresholds in multiclass (or binary) classification to adjust the probability of predicting each class.
I don't quite understand this comment. There is a JIRA SPARK-11543 discussing the expected relationship, but it is not implemented yet. So, we keep both threshold and thresholds on Scala side.

2016-10-12 23:47 UTC, wangmiao1981 commented on R/pkg/R/mllib.R
> +#'               Supported options:
Done.

2016-10-12 23:56 UTC, felixcheung commented on R/pkg/R/mllib.R
> +                   threshold = 0.5, thresholds = NULL, weightCol = NULL, aggregationDepth = 2) {
perhaps turning that into a list/array on the Scala side so it becomes list on the R side?

2016-10-13 00:43 UTC, SparkQA commented
**[Test build #66857 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66857/consoleFull)** for PR 15365 at commit [`08babe5`](https://github.com/apache/spark/commit/08babe50df42bc4247a65f24cc95241891b555a8).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-13 00:43 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-13 00:43 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66857/
Test PASSed.

2016-10-13 04:37 UTC, wangmiao1981 commented on R/pkg/R/mllib.R
> +                   threshold = 0.5, thresholds = NULL, weightCol = NULL, aggregationDepth = 2) {
Let me check whether it is feasible to do that, because the trait is shared by other algorithms.

2016-10-20 21:42 UTC, SparkQA commented
**[Test build #67293 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67293/consoleFull)** for PR 15365 at commit [`a222de7`](https://github.com/apache/spark/commit/a222de7efe93aea51f9de755f4fd29eb4ff8554a).

2016-10-20 21:55 UTC, wangmiao1981 commented on R/pkg/R/mllib.R
> +#' @param thresholds in multiclass (or binary) classification to adjust the probability of predicting each class.
Done.

2016-10-20 22:18 UTC, wangmiao1981 commented on R/pkg/R/mllib.R
> +                   threshold = 0.5, thresholds = NULL, weightCol = NULL, aggregationDepth = 2) {
@felixcheung  I don't find a native method to convert the `Vector` to `Array` when using select on R side.
Optionally, I can add a method `getProbability` in scala wrapper, which converts the Rows of Vectors to a dataframe. Then, on R side, we can call that method in `summary` method. At the same time, we remove the `probabilityCol` from the function definition.
What do you think?

2016-10-20 22:45 UTC, SparkQA commented
**[Test build #67293 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67293/consoleFull)** for PR 15365 at commit [`a222de7`](https://github.com/apache/spark/commit/a222de7efe93aea51f9de755f4fd29eb4ff8554a).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-20 22:46 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-20 22:46 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67293/
Test PASSed.

2016-10-24 18:34 UTC, wangmiao1981 commented
ping @felixcheung

2016-10-24 22:16 UTC, felixcheung commented
re: https://github.com/apache/spark/pull/15365#discussion_r84387432
This is definitely an issue as Vector/SparseVector/DenseVector is mapped to environment in R, and within the DataFrame, environment is hard to operate with.

It might likely be how serde/type mapping is handling this but from my digging so far I haven't pinpointed where and how we fix this. It could be separated into another JIRA though.

I'll look at the rest of this PR today.

2016-10-24 22:29 UTC, wangmiao1981 commented
Thanks for your response! I will do some research on how to bring Vectors back at spare time.

2016-10-25 05:35 UTC, felixcheung requested changes

2016-10-25 05:35 UTC, felixcheung commented on R/pkg/R/mllib.R
> +#'                        of L1 and L2. Default is 0.0 which is an L2 penalty.
if this is supposed to be numeric, could you change it to 0.0 or 1.0 consistently throughout this comment?

2016-10-25 05:35 UTC, felixcheung commented on R/pkg/R/mllib.R
> +#' binary_df <- suppressWarnings(createDataFrame(binary_data))
suppressWarnings still here?

2016-10-25 05:35 UTC, felixcheung commented on R/pkg/R/mllib.R
> +#' @aliases spark.logit,SparkDataFrame,formula-method
This is not the right alias..

2016-10-25 05:35 UTC, felixcheung commented on R/pkg/R/mllib.R
> +              dataFrame(callJMethod(jobj, "fMeasureByThreshold"))
are there reasons these are all in 2 lines?

2016-10-25 05:35 UTC, felixcheung commented on R/pkg/inst/tests/testthat/test_mllib.R
> +  blr_model <- spark.logit(binary_df, label ~ feature, threshold = 1.0)
I would update the example to use `thresholds` instead

2016-10-25 05:35 UTC, felixcheung commented on R/pkg/inst/tests/testthat/test_mllib.R
> +  blr_model1 <- spark.logit(binary_df, label ~ feature, threshold = 0.0)
ditto thresholds

2016-10-25 05:35 UTC, felixcheung commented on R/pkg/R/mllib.R
> +#'                           If numClasses == 1 || numClasses == 2, set to "binomial".
is there supposed to be a `numClasses` parameter?

2016-10-25 05:35 UTC, felixcheung commented on mllib/src/main/scala/org/apache/spark/ml/r/LogisticRegressionWrapper.scala
> +    logisticRegressionModel.summary.asInstanceOf[BinaryLogisticRegressionSummary].roc
consider another `val` for `logisticRegressionModel.summary.asInstanceOf[BinaryLogisticRegressionSummary]` to avoid duplication

2016-10-25 20:02 UTC, wangmiao1981 commented on R/pkg/R/mllib.R
> +#'                        of L1 and L2. Default is 0.0 which is an L2 penalty.
Changed to 0.0 and 1.0 in the comments.

2016-10-25 20:03 UTC, wangmiao1981 commented on R/pkg/R/mllib.R
> +#'                           If numClasses == 1 || numClasses == 2, set to "binomial".
There is no `numClasses` parameter. The algorithm infers the number of classes. I changed to `number of classes` to avoid confusion.

2016-10-25 20:05 UTC, wangmiao1981 commented on R/pkg/R/mllib.R
> +#' @aliases spark.logit,SparkDataFrame,formula-method
`suppressWarnings` is removed. For the aliases, I followed `spark.kmeans`. Are there any specific rules?

2016-10-25 20:06 UTC, wangmiao1981 commented on R/pkg/R/mllib.R
> +              dataFrame(callJMethod(jobj, "fMeasureByThreshold"))
I thought it could exceed the the line limit. Now, I changed it back to 1 line.

2016-10-25 20:06 UTC, wangmiao1981 commented on R/pkg/inst/tests/testthat/test_mllib.R
> +  blr_model <- spark.logit(binary_df, label ~ feature, threshold = 1.0)
Updated tests and example.

2016-10-25 20:06 UTC, wangmiao1981 commented on R/pkg/inst/tests/testthat/test_mllib.R
> +  blr_model1 <- spark.logit(binary_df, label ~ feature, threshold = 0.0)
Done.

2016-10-25 20:06 UTC, wangmiao1981 commented on mllib/src/main/scala/org/apache/spark/ml/r/LogisticRegressionWrapper.scala
> +    logisticRegressionModel.summary.asInstanceOf[BinaryLogisticRegressionSummary].roc
Add a new `val blrSummary`

2016-10-25 20:12 UTC, SparkQA commented
**[Test build #67526 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67526/consoleFull)** for PR 15365 at commit [`d0452ae`](https://github.com/apache/spark/commit/d0452ae1f92b9d72a620942be269f965c5810392).

2016-10-25 21:00 UTC, felixcheung commented on R/pkg/R/mllib.R
> +#' @aliases spark.logit,SparkDataFrame,formula-method
this is the `summary` method, not `spark.logit` method?

2016-10-25 21:08 UTC, wangmiao1981 commented on R/pkg/R/mllib.R
> +#' @aliases spark.logit,SparkDataFrame,formula-method
Oh. I see. I looked the wrong line number.

2016-10-25 21:11 UTC, wangmiao1981 commented on R/pkg/R/mllib.R
> +#' @aliases spark.logit,SparkDataFrame,formula-method
fixed. Thanks!

2016-10-25 21:12 UTC, SparkQA commented
**[Test build #67531 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67531/consoleFull)** for PR 15365 at commit [`031cf9b`](https://github.com/apache/spark/commit/031cf9b8efa104de0bc288b5833ffc03b2fe7097).

2016-10-25 21:15 UTC, SparkQA commented
**[Test build #67526 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67526/consoleFull)** for PR 15365 at commit [`d0452ae`](https://github.com/apache/spark/commit/d0452ae1f92b9d72a620942be269f965c5810392).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-25 21:16 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-25 21:16 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67526/
Test PASSed.

2016-10-25 22:10 UTC, SparkQA commented
**[Test build #67531 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67531/consoleFull)** for PR 15365 at commit [`031cf9b`](https://github.com/apache/spark/commit/031cf9b8efa104de0bc288b5833ffc03b2fe7097).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-25 22:10 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-25 22:11 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67531/
Test PASSed.

2016-10-26 04:38 UTC, felixcheung commented
LGTM.

Let's see if anyone has any other comments.

Could you open a JIRA on Vector/SparseVector/DenseVector?

2016-10-26 05:39 UTC, wangmiao1981 commented
Sure. I will do it. Thanks!

2016-10-26 23:15 UTC, closed without merging

2016-10-26 23:16 UTC, felixcheung commented
merged to master.