[SPARK-17876] Write StructuredStreaming WAL to a stream instead of materializing all at once
apache/spark pull request #15437
Opened 2016-10-11 18:27 UTC by brkyvz

## What changes were proposed in this pull request?

The CompactibleFileStreamLog materializes the whole metadata log in memory as a String. This can cause issues when there are lots of files that are being committed, especially during a compaction batch.
You may come across stacktraces that look like:
```
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
at java.lang.StringCoding.encode(StringCoding.java:350)
at java.lang.String.getBytes(String.java:941)
at org.apache.spark.sql.execution.streaming.FileStreamSinkLog.serialize(FileStreamSinkLog.scala:127)
 
```
The safer way is to write to an output stream so that we don't have to materialize a huge string.

## How was this patch tested?

Existing unit tests

2016-10-11 18:32 UTC, SparkQA commented
**[Test build #66754 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66754/consoleFull)** for PR 15437 at commit [`4d50be5`](https://github.com/apache/spark/commit/4d50be565841bdb6d647c75e36168151e1e8a621).

2016-10-11 20:40 UTC, SparkQA commented
**[Test build #66754 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66754/consoleFull)** for PR 15437 at commit [`4d50be5`](https://github.com/apache/spark/commit/4d50be565841bdb6d647c75e36168151e1e8a621).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-11 20:41 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-11 20:41 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66754/
Test PASSed.

2016-10-11 20:58 UTC, brkyvz commented
cc @tdas @zsxwing Would one of you want to look at this?

2016-10-12 20:54 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/HDFSMetadataLog.scala
> +import org.apache.hadoop.io.IOUtils
nit: use org.apache.commons.io.IOUtils instead. Hadoop's IOUtils is `@InterfaceStability.Evolving` which can break compatibility at minor release

2016-10-12 20:56 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/CompactibleFileStreamLog.scala
> +    val lines = IOUtils.lineIterator(in, UTF_8).asScala
nit: why not use `Source.getLines` since this is Scala.

2016-10-12 20:57 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/CompactibleFileStreamLog.scala
> +    out.flush()
nit: no need to flush since it will be closed at once.

2016-10-12 20:58 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/FileStreamSourceLog.scala
> +import java.io.OutputStream
nit: unused import

2016-10-12 21:00 UTC, zsxwing requested changes
Looks pretty good. Just some nits

2016-10-12 23:27 UTC, brkyvz commented
Thanks @zsxwing addressed your comments

2016-10-12 23:27 UTC, SparkQA commented
**[Test build #66855 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66855/consoleFull)** for PR 15437 at commit [`cece672`](https://github.com/apache/spark/commit/cece6723de82607c12681e97f16ef5a86c2d90d2).

2016-10-12 23:33 UTC, SparkQA commented
**[Test build #66855 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66855/consoleFull)** for PR 15437 at commit [`cece672`](https://github.com/apache/spark/commit/cece6723de82607c12681e97f16ef5a86c2d90d2).
 * This patch **fails to build**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-12 23:33 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-12 23:33 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66855/
Test FAILed.

2016-10-12 23:37 UTC, SparkQA commented
**[Test build #66856 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66856/consoleFull)** for PR 15437 at commit [`9c4fe72`](https://github.com/apache/spark/commit/9c4fe723ce7ae09ac0b559e62468f13769baed6b).

2016-10-13 01:40 UTC, SparkQA commented
**[Test build #66856 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66856/consoleFull)** for PR 15437 at commit [`9c4fe72`](https://github.com/apache/spark/commit/9c4fe723ce7ae09ac0b559e62468f13769baed6b).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-13 01:41 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-13 01:41 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66856/
Test PASSed.

2016-10-13 04:40 UTC, zsxwing commented
LGTM. Thanks! Merging to master and 2.0.

2016-10-13 04:42 UTC, closed without merging