[SPARK-17822] Use weak reference in JVMObjectTracker.objMap because it may leak JVM objects
apache/spark pull request #15433
Opened 2016-10-11 13:12 UTC by techaddict

## What changes were proposed in this pull request?
Use weak reference in JVMObjectTracker.objMap because it may leak JVM objects

## How was this patch tested?
existing tests

2016-10-11 13:17 UTC, SparkQA commented
**[Test build #66742 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66742/consoleFull)** for PR 15433 at commit [`995611d`](https://github.com/apache/spark/commit/995611d75351d24907ce2b22e7d33752cc803da3).

2016-10-11 15:20 UTC, SparkQA commented
**[Test build #66742 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66742/consoleFull)** for PR 15433 at commit [`995611d`](https://github.com/apache/spark/commit/995611d75351d24907ce2b22e7d33752cc803da3).
 * This patch **fails SparkR unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-11 15:21 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-11 15:21 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66742/
Test FAILed.

2016-10-11 15:47 UTC, shivaram commented
@techaddict Thanks for the PR. The test failures seem related to this patch -- Could you check why they are failing ?

2016-10-12 06:37 UTC, SparkQA commented
**[Test build #66797 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66797/consoleFull)** for PR 15433 at commit [`7d50d84`](https://github.com/apache/spark/commit/7d50d84f90fcda9e5dec79c9be834870c83443c4).

2016-10-12 08:11 UTC, SparkQA commented
**[Test build #66797 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66797/consoleFull)** for PR 15433 at commit [`7d50d84`](https://github.com/apache/spark/commit/7d50d84f90fcda9e5dec79c9be834870c83443c4).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-12 08:11 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-12 08:11 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66797/
Test FAILed.

2016-10-12 08:50 UTC, srowen requested changes

2016-10-12 08:50 UTC, srowen commented on core/src/main/scala/org/apache/spark/api/r/RBackendHandler.scala
> +  def remove(id: String) {
Although it's normal to return the object that was removed from map methods, if this isn't desired, I'd declare this as `: Unit` to be clear

2016-10-12 08:50 UTC, srowen commented on core/src/main/scala/org/apache/spark/api/r/RBackendHandler.scala
> +  private[this] val objMap: ConcurrentMap[String, Object] =
Not that it matters a lot, but do you need the reference type?

2016-10-12 08:50 UTC, srowen commented on core/src/main/scala/org/apache/spark/api/r/RBackendHandler.scala
>    def put(obj: Object): String = {
It kind of seems like this class is meant to be thread-safe, but this isn't. You could use `AtomicLong` and `getAndIncrement`?

2016-10-13 09:21 UTC, srowen commented on core/src/main/scala/org/apache/spark/api/r/RBackendHandler.scala
>    def put(obj: Object): String = {
Agree, this can just be changed a little more to also handle that issue. They end up being interrelated here.

2016-10-13 12:17 UTC, SparkQA commented
**[Test build #66888 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66888/consoleFull)** for PR 15433 at commit [`69e6f7d`](https://github.com/apache/spark/commit/69e6f7d27f53b501c5ab7194ac868462c5bf6153).

2016-10-13 12:22 UTC, SparkQA commented
**[Test build #66890 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66890/consoleFull)** for PR 15433 at commit [`2fc9cbd`](https://github.com/apache/spark/commit/2fc9cbdc2f10045762a77e753b4216f3b518b0e1).

2016-10-13 14:21 UTC, SparkQA commented
**[Test build #66888 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66888/consoleFull)** for PR 15433 at commit [`69e6f7d`](https://github.com/apache/spark/commit/69e6f7d27f53b501c5ab7194ac868462c5bf6153).
 * This patch **fails SparkR unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-13 14:22 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-13 14:22 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66888/
Test FAILed.

2016-10-13 14:30 UTC, SparkQA commented
**[Test build #66890 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/66890/consoleFull)** for PR 15433 at commit [`2fc9cbd`](https://github.com/apache/spark/commit/2fc9cbdc2f10045762a77e753b4216f3b518b0e1).
 * This patch **fails SparkR unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-13 14:30 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-13 14:30 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/66890/
Test FAILed.

2016-10-13 15:57 UTC, techaddict commented
@shivaram @srowen not sure why its failing, will try to fix this ASAP.

2016-10-20 11:32 UTC, SparkQA commented
**[Test build #67263 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67263/consoleFull)** for PR 15433 at commit [`2e9298a`](https://github.com/apache/spark/commit/2e9298a382946969493ca28f1804046c88073105).

2016-10-20 13:16 UTC, SparkQA commented
**[Test build #67263 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67263/consoleFull)** for PR 15433 at commit [`2e9298a`](https://github.com/apache/spark/commit/2e9298a382946969493ca28f1804046c88073105).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-20 13:17 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-20 13:17 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67263/
Test FAILed.

2016-10-20 13:42 UTC, SparkQA commented
**[Test build #67267 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67267/consoleFull)** for PR 15433 at commit [`a2b0358`](https://github.com/apache/spark/commit/a2b0358f8a5a2fcf74fe6bf68a191b92209e9d05).

2016-10-20 15:32 UTC, SparkQA commented
**[Test build #67267 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67267/consoleFull)** for PR 15433 at commit [`a2b0358`](https://github.com/apache/spark/commit/a2b0358f8a5a2fcf74fe6bf68a191b92209e9d05).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-20 15:33 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-20 15:33 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67267/
Test FAILed.

2016-10-20 16:53 UTC, yhuai commented
test this please

2016-10-20 16:57 UTC, SparkQA commented
**[Test build #67272 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67272/consoleFull)** for PR 15433 at commit [`a2b0358`](https://github.com/apache/spark/commit/a2b0358f8a5a2fcf74fe6bf68a191b92209e9d05).

2016-10-20 18:45 UTC, SparkQA commented
**[Test build #67272 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67272/consoleFull)** for PR 15433 at commit [`a2b0358`](https://github.com/apache/spark/commit/a2b0358f8a5a2fcf74fe6bf68a191b92209e9d05).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-20 18:46 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-20 18:46 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67272/
Test FAILed.

2016-10-20 18:47 UTC, yhuai commented
test this please

2016-10-20 18:52 UTC, SparkQA commented
**[Test build #67280 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67280/consoleFull)** for PR 15433 at commit [`a2b0358`](https://github.com/apache/spark/commit/a2b0358f8a5a2fcf74fe6bf68a191b92209e9d05).

2016-10-20 20:58 UTC, SparkQA commented
**[Test build #67280 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67280/consoleFull)** for PR 15433 at commit [`a2b0358`](https://github.com/apache/spark/commit/a2b0358f8a5a2fcf74fe6bf68a191b92209e9d05).
 * This patch **fails SparkR unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-20 20:59 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-20 20:59 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67280/
Test FAILed.

2016-10-23 13:22 UTC, techaddict commented
closing this since, its maybe not the right way to do this

2016-10-23 13:22 UTC, closed without merging