[SPARK-18063][SQL] Failed to infer constraints over multiple aliases
apache/spark pull request #15597
Opened 2016-10-22 06:39 UTC by jiangxb1987

## What changes were proposed in this pull request?

The `UnaryNode.getAliasedConstraints` function fails to replace all expressions by their alias where constraints contains more than one expression to be replaced. 
For example:
```
val tr = LocalRelation('a.int, 'b.string, 'c.int)
val multiAlias = tr.where('a === 'c + 10).select('a.as('x), 'c.as('y))
multiAlias.analyze.constraints
```
currently outputs:
```
ExpressionSet(Seq(
    IsNotNull(resolveColumn(multiAlias.analyze, "x")),
    IsNotNull(resolveColumn(multiAlias.analyze, "y"))
)
```
The constraint `resolveColumn(multiAlias.analyze, "x") === resolveColumn(multiAlias.analyze, "y") + 10)` is missing.

## How was this patch tested?

Add new test cases in `ConstraintPropagationSuite`.

2016-10-22 06:42 UTC, SparkQA commented
**[Test build #67379 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67379/consoleFull)** for PR 15597 at commit [`2fe728f`](https://github.com/apache/spark/commit/2fe728fe155c0e70d31ef03675a331ac9337c2f0).

2016-10-22 08:41 UTC, SparkQA commented
**[Test build #67379 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67379/consoleFull)** for PR 15597 at commit [`2fe728f`](https://github.com/apache/spark/commit/2fe728fe155c0e70d31ef03675a331ac9337c2f0).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-22 08:42 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-22 08:42 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67379/
Test FAILed.

2016-10-23 07:31 UTC, rxin commented
cc @sameeragarwal

2016-10-24 04:47 UTC, SparkQA commented
**[Test build #67433 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67433/consoleFull)** for PR 15597 at commit [`32e0b36`](https://github.com/apache/spark/commit/32e0b36eb3c2441ecf6418fed1c0944d1841c13c).

2016-10-24 06:54 UTC, SparkQA commented
**[Test build #67433 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67433/consoleFull)** for PR 15597 at commit [`32e0b36`](https://github.com/apache/spark/commit/32e0b36eb3c2441ecf6418fed1c0944d1841c13c).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-24 06:55 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-24 06:55 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67433/
Test PASSed.

2016-10-24 10:03 UTC, sameeragarwal requested changes
Looks good modulo a couple of comments. Thanks!

2016-10-24 10:03 UTC, sameeragarwal commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlan.scala
> +    var aliasedConstraints = child.constraints.toSet
Remove `toSet` (`ExpressionSet` should support all these operations)

2016-10-24 10:03 UTC, sameeragarwal commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlan.scala
> +    aliasedConstraints
This should really return `aliasedConstraints -- child.constraints`. Perhaps rename `aliasedConstraints` to `allConstraints` and then return `allConstraints -- child.constraints`?

2016-10-25 09:02 UTC, jiangxb1987 commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlan.scala
> +    var aliasedConstraints = child.constraints.toSet
I transformed `child.constraints` to `Set[Expression]` as we need to apply `++=` operator on it.

2016-10-25 09:04 UTC, jiangxb1987 commented
@sameeragarwal I've addressed your comments! Thank you!

2016-10-25 09:07 UTC, SparkQA commented
**[Test build #67504 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67504/consoleFull)** for PR 15597 at commit [`3f07493`](https://github.com/apache/spark/commit/3f0749338c917301c24330d95a839ab1e7151a1d).

2016-10-25 11:24 UTC, SparkQA commented
**[Test build #67504 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67504/consoleFull)** for PR 15597 at commit [`3f07493`](https://github.com/apache/spark/commit/3f0749338c917301c24330d95a839ab1e7151a1d).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-25 11:25 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-25 11:25 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67504/
Test PASSed.

2016-10-26 11:57 UTC, sameeragarwal commented
LGTM, thanks!

2016-10-26 12:05 UTC, sameeragarwal commented
Just to be extra safe, it'd be great to re-run the test suite on this once  https://github.com/apache/spark/pull/15319 is merged.

2016-10-26 15:10 UTC, hvanhovell commented
retest this please

2016-10-26 15:12 UTC, SparkQA commented
**[Test build #67583 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67583/consoleFull)** for PR 15597 at commit [`3f07493`](https://github.com/apache/spark/commit/3f0749338c917301c24330d95a839ab1e7151a1d).

2016-10-26 17:28 UTC, SparkQA commented
**[Test build #67583 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67583/consoleFull)** for PR 15597 at commit [`3f07493`](https://github.com/apache/spark/commit/3f0749338c917301c24330d95a839ab1e7151a1d).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-26 17:30 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-26 17:30 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67583/
Test PASSed.

2016-10-26 18:11 UTC, rxin commented
Merging this in master/branch-2.0.

2016-10-26 18:14 UTC, closed without merging