[SPARK-18144][SQL] logging StreamingQueryListener$QueryStartedEvent
apache/spark pull request #15675
Opened 2016-10-28 20:42 UTC by CodingCat

## What changes were proposed in this pull request?

The PR fixes the bug that the QueryStartedEvent is not logged

The reason of the bug is that listeners in `ListenerBus` is typed as CopyOnWriteArray so that the thread calling postToAll to post QueryStartedEvent will see an empty `listeners` (stale version). In fact, we should never call postToAll() directly but call `LiveListenerBus.post()` to broadcast events

@zsxwing 

## How was this patch tested?

![image](https://cloud.githubusercontent.com/assets/678008/19821553/007a7d28-9d2d-11e6-9f13-49851559cdaa.png)

2016-10-28 20:46 UTC, CodingCat commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/StreamingQueryListenerBus.scala
> -    event match {
actually I didn't see any reason to distinguish these two types of event when posting

2016-10-28 20:47 UTC, SparkQA commented
**[Test build #67722 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67722/consoleFull)** for PR 15675 at commit [`766c67d`](https://github.com/apache/spark/commit/766c67d4d1609782bf7558a2b7c742df72bff620).

2016-10-28 22:21 UTC, SparkQA commented
**[Test build #67722 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67722/consoleFull)** for PR 15675 at commit [`766c67d`](https://github.com/apache/spark/commit/766c67d4d1609782bf7558a2b7c742df72bff620).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-28 22:21 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-10-28 22:21 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67722/
Test FAILed.

2016-10-28 22:35 UTC, zsxwing commented
It's intentional. Just to provide a synchronous callback for the `start` event... It's documented in `StreamingQueryListener`. This issue now is not really a big issue since no place use it now.

2016-10-28 22:36 UTC, zsxwing commented
Ideally, it should not use the listener api for a synchronous callback. But right now I don't have any good API design for this one.

2016-10-29 01:51 UTC, CodingCat commented
Sorry, I misunderstood the real reason of the bug

The real reason is actually very simple...the original postToAll() is actually calling `StreamingQueryListenerBus.postToAll()` which has no listener at all....we shall post by `sparkListenerBus.postToAll(s)` and `this.postToAll()` to trigger local listeners as well as the listeners registered in LiveListenerBus

2016-10-29 01:52 UTC, SparkQA commented
**[Test build #67737 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67737/consoleFull)** for PR 15675 at commit [`24bcd7b`](https://github.com/apache/spark/commit/24bcd7b700627dff961ac6e405922babf5d1851f).

2016-10-29 04:04 UTC, SparkQA commented
**[Test build #67737 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67737/consoleFull)** for PR 15675 at commit [`24bcd7b`](https://github.com/apache/spark/commit/24bcd7b700627dff961ac6e405922babf5d1851f).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-29 04:05 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-29 04:05 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67737/
Test PASSed.

2016-10-31 00:28 UTC, CodingCat commented
@zsxwing mind looking at it again?

2016-10-31 20:39 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/StreamingQueryListenerBus.scala
> +        sparkListenerBus.postToAll(s)
This may break the existing spark listeners because they are not thread-safe.

2016-10-31 20:48 UTC, SparkQA commented
**[Test build #67833 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67833/consoleFull)** for PR 15675 at commit [`8d2b3a6`](https://github.com/apache/spark/commit/8d2b3a63f8d14acb8bd33ce15a9b7a593b703f97).

2016-10-31 20:51 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/StreamingQueryListenerBus.scala
> +        sparkListenerBus.post(s)
`QueryStartedEvent` will be sent twice to `StreamingQueryListener`. There is a thread local variable in `LiveListenerBus`. You can use it to ignore duplicated  `QueryStartedEvent` if it's posted in the listener thread.

2016-10-31 20:53 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/StreamingQueryListenerBus.scala
> +        sparkListenerBus.post(s)
Since this is hacky, it's better to have some tests to make sure we won't break things in future when removing the hacky codes.

2016-10-31 23:03 UTC, SparkQA commented
**[Test build #67833 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67833/consoleFull)** for PR 15675 at commit [`8d2b3a6`](https://github.com/apache/spark/commit/8d2b3a63f8d14acb8bd33ce15a9b7a593b703f97).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-10-31 23:04 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-10-31 23:04 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67833/
Test PASSed.

2016-11-01 00:33 UTC, SparkQA commented
**[Test build #67851 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67851/consoleFull)** for PR 15675 at commit [`4b29d8f`](https://github.com/apache/spark/commit/4b29d8f7be52f230f3e5dc726f11599e86ee4e07).

2016-11-01 03:03 UTC, SparkQA commented
**[Test build #67851 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67851/consoleFull)** for PR 15675 at commit [`4b29d8f`](https://github.com/apache/spark/commit/4b29d8f7be52f230f3e5dc726f11599e86ee4e07).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-11-01 03:05 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-11-01 03:05 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67851/
Test PASSed.

2016-11-01 21:36 UTC, zsxwing requested changes
Looks good. Just some nits

2016-11-01 21:36 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/StreamingQueryListenerBus.scala
> +        if (Thread.currentThread().getName != "SparkListenerBus" ||
nit: please use `!LiveListenerBus.withinListenerThread.value` instead.

2016-11-01 21:36 UTC, zsxwing commented on sql/core/src/test/scala/org/apache/spark/sql/streaming/StreamingQuerySuite.scala
> -      override def onQueryStarted(queryStarted: QueryStartedEvent): Unit = { }
nit: please add `@volatile`

2016-11-02 01:07 UTC, SparkQA commented
**[Test build #67942 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67942/consoleFull)** for PR 15675 at commit [`00dd3ce`](https://github.com/apache/spark/commit/00dd3ceadf24c17b2d16283a86644a22e4102a88).

2016-11-02 03:12 UTC, SparkQA commented
**[Test build #67942 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67942/consoleFull)** for PR 15675 at commit [`00dd3ce`](https://github.com/apache/spark/commit/00dd3ceadf24c17b2d16283a86644a22e4102a88).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-11-02 03:13 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-11-02 03:13 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/67942/
Test PASSed.

2016-11-02 06:39 UTC, zsxwing commented
LGTM. Thanks! Merging to master, 2.1 and 2.0.

2016-11-02 06:42 UTC, closed without merging

2016-11-02 12:14 UTC, CodingCat commented
thanks