[SPARK-18429] [SQL] implement a new Aggregate for CountMinSketch
apache/spark pull request #15877
Opened 2016-11-14 06:20 UTC by wzhfy

## What changes were proposed in this pull request?

This PR implements a new Aggregate to generate count min sketch, which is a wrapper of CountMinSketch.

## How was this patch tested?

add test cases

2016-11-14 06:22 UTC, SparkQA commented
**[Test build #68604 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/68604/consoleFull)** for PR 15877 at commit [`a4753e4`](https://github.com/apache/spark/commit/a4753e4fa2c8272576fbd44c4b4670947b332289).

2016-11-14 06:22 UTC, wzhfy commented
cc @rxin

2016-11-14 06:23 UTC, rxin commented
cc @liancheng

2016-11-14 08:32 UTC, SparkQA commented
**[Test build #68604 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/68604/consoleFull)** for PR 15877 at commit [`a4753e4`](https://github.com/apache/spark/commit/a4753e4fa2c8272576fbd44c4b4670947b332289).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `case class CountMinSketchAgg(`

2016-11-14 08:32 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-11-14 08:32 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/68604/
Test FAILed.

2016-11-14 08:50 UTC, wzhfy commented
retest this please

2016-11-14 08:52 UTC, SparkQA commented
**[Test build #68610 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/68610/consoleFull)** for PR 15877 at commit [`a4753e4`](https://github.com/apache/spark/commit/a4753e4fa2c8272576fbd44c4b4670947b332289).

2016-11-14 11:17 UTC, SparkQA commented
**[Test build #68610 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/68610/consoleFull)** for PR 15877 at commit [`a4753e4`](https://github.com/apache/spark/commit/a4753e4fa2c8272576fbd44c4b4670947b332289).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `case class CountMinSketchAgg(`

2016-11-14 11:18 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-11-14 11:18 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/68610/
Test PASSed.

2016-11-14 11:51 UTC, hvanhovell commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +  override def eval(buffer: CountMinSketch): Any = new GenericArrayData(serialize(buffer))
Is this an array of bytes?

2016-11-14 12:50 UTC, wzhfy commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +  override def eval(buffer: CountMinSketch): Any = new GenericArrayData(serialize(buffer))
yes

2016-11-14 13:07 UTC, hvanhovell commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +  override def eval(buffer: CountMinSketch): Any = new GenericArrayData(serialize(buffer))
It is better just to return the byte array and to change the datatype into a BinaryType

2016-11-14 13:09 UTC, hvanhovell commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +    val defaultCheck = super.checkInputDataTypes()
I don't think we need to check this (the super class does not implement this).

2016-11-14 13:11 UTC, hvanhovell commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +    val eps: Double = epsExpression.eval().asInstanceOf[Double]
Should we cache this in lazy vals? I am not sure about the performance implications.

2016-11-14 13:12 UTC, hvanhovell commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +      buffer.add(if (value.isInstanceOf[UTF8String]) value.toString else value)
How bad would it be to add support for UTF8 string to CMS? Or to pass the UTF8 byte array to CMS?

2016-11-14 13:13 UTC, hvanhovell commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> + * sub-linear space, which is useful for equality predicates and join size estimation.
Maybe something on the return type? A developer should know how to work with these bytes.

2016-11-14 13:13 UTC, hvanhovell commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +    // currently `CountMinSketch` supports integral and string types
Should we expand this?

2016-11-14 13:26 UTC, hvanhovell commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAggSuite.scala
> +    }
This might also be a good place to test merging in a different order, and the merging of an empty partition.

2016-11-14 13:28 UTC, hvanhovell commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAggSuite.scala
> +      case arrayData: ArrayData =>
Add `case _ => fail("unexpected return type")` to have a nicer error when something goed wrong there

2016-11-14 13:30 UTC, hvanhovell commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +    } else if (epsExpression.eval() == null || confidenceExpression.eval() == null ||
Should we also check for negative eps and confidence values?

2016-11-14 13:31 UTC, hvanhovell commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAggSuite.scala
> +        invalidAgg.createAggregationBuffer()
See my comment in the CMS agg. This is too late to throw such an error. I'd rather have driver side errors then executor side errors.

2016-11-14 13:32 UTC, hvanhovell requested changes
This looks pretty good! I have left a few minor comments. Also consider to register this aggregate in the FunctionRegistry and to add it to functions.scala.

2016-11-15 00:57 UTC, wzhfy commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +  override def eval(buffer: CountMinSketch): Any = new GenericArrayData(serialize(buffer))
Yes, that's better, thanks!

2016-11-15 01:05 UTC, wzhfy commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +    val defaultCheck = super.checkInputDataTypes()
ExpectsInputTypes.checkInputDataTypes() checks validity of input types, right?

2016-11-15 01:06 UTC, wzhfy commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +    val eps: Double = epsExpression.eval().asInstanceOf[Double]
Ok, i'll change them to lazy vals

2016-11-15 01:07 UTC, hvanhovell commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +    val defaultCheck = super.checkInputDataTypes()
That is fair.

2016-11-15 01:37 UTC, wzhfy commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> + * sub-linear space, which is useful for equality predicates and join size estimation.
ok, I wrote this in usage, but I'll add it here too, thanks.

2016-11-15 01:51 UTC, wzhfy commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAggSuite.scala
> +        invalidAgg.createAggregationBuffer()
Yes, we should have driver side errors, thanks.

2016-11-15 01:55 UTC, wzhfy commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +    // currently `CountMinSketch` supports integral and string types
@rxin suggested that for unsupported types, we hash it before count min sketch, i.e. CountMinSketchAgg(hash(col)).

2016-11-15 02:12 UTC, wzhfy commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +      buffer.add(if (value.isInstanceOf[UTF8String]) value.toString else value)
Yes, we should pass the byte array to CMS.

2016-11-15 02:15 UTC, wzhfy commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAggSuite.scala
> +    }
Ok, I'll also test these.

2016-11-15 08:18 UTC, rxin commented
yes please register a count_min_sketch and alias cmsketch in FunctionRegistry.

2016-11-15 13:07 UTC, SparkQA commented
**[Test build #68664 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/68664/consoleFull)** for PR 15877 at commit [`0cca205`](https://github.com/apache/spark/commit/0cca20510ac8ce8e4639660820843427cd36ceac).

2016-11-15 13:24 UTC, hvanhovell commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +        case IntegerType => buffer.addLong(value.asInstanceOf[Int])
Add DateType?

2016-11-15 13:47 UTC, SparkQA commented
**[Test build #68666 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/68666/consoleFull)** for PR 15877 at commit [`2064846`](https://github.com/apache/spark/commit/20648461905bd6b573acf957463b97f1c3142bd1).

2016-11-15 15:35 UTC, SparkQA commented
**[Test build #68664 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/68664/consoleFull)** for PR 15877 at commit [`0cca205`](https://github.com/apache/spark/commit/0cca20510ac8ce8e4639660820843427cd36ceac).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-11-15 15:36 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-11-15 15:36 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/68664/
Test PASSed.

2016-11-15 15:48 UTC, SparkQA commented
**[Test build #68666 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/68666/consoleFull)** for PR 15877 at commit [`2064846`](https://github.com/apache/spark/commit/20648461905bd6b573acf957463b97f1c3142bd1).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-11-15 15:48 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-11-15 15:48 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/68666/
Test FAILed.

2016-11-16 02:18 UTC, rxin commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +      child.dataType match {
although i don't know if it matters much here given we are going to run it through many hash functions.

2016-11-16 02:19 UTC, rxin commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala
> +    expression[CountMinSketchAgg]("cmsketch"),
actually i take my word back. let's add only count_min_sketch. I don't think it's worth having an alias given this is sketch is difficult to consume (returning some binary)

2016-11-16 02:19 UTC, rxin commented on sql/core/src/main/scala/org/apache/spark/sql/functions.scala
> +  def count_min_sketch(e: Column, eps: Double, confidence: Double, seed: Int): Column = {
let's not add these for now.

2016-11-16 06:27 UTC, SparkQA commented
**[Test build #68699 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/68699/consoleFull)** for PR 15877 at commit [`7bfdd40`](https://github.com/apache/spark/commit/7bfdd40839c30cd1d66c37aa7c6d3e6ab397c8eb).

2016-11-16 06:52 UTC, SparkQA commented
**[Test build #68703 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/68703/consoleFull)** for PR 15877 at commit [`6143997`](https://github.com/apache/spark/commit/61439978a9e21d1aaf78f2cac120fe38dc0f5e5b).

2016-11-16 08:50 UTC, SparkQA commented
**[Test build #68699 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/68699/consoleFull)** for PR 15877 at commit [`7bfdd40`](https://github.com/apache/spark/commit/7bfdd40839c30cd1d66c37aa7c6d3e6ab397c8eb).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-11-16 08:51 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-11-16 08:51 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/68699/
Test PASSed.

2016-11-16 09:27 UTC, SparkQA commented
**[Test build #68703 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/68703/consoleFull)** for PR 15877 at commit [`6143997`](https://github.com/apache/spark/commit/61439978a9e21d1aaf78f2cac120fe38dc0f5e5b).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-11-16 09:29 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-11-16 09:29 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/68703/
Test PASSed.

2016-11-17 09:24 UTC, wzhfy commented
Hi @hvanhovell @rxin, I've updated this pr, does it look good to you now?

2016-11-18 19:58 UTC, hvanhovell commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +      DoubleType, DoubleType, IntegerType)
Also add `FloatType` (use Float.floatToIntBits), `DoubleType` (use Double.doubleToLongBits), `BooleanType` and `BinaryType`? We could also add support for Decimal, but that would be a bit harder to get right.

2016-11-19 02:53 UTC, wzhfy commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +      DoubleType, DoubleType, IntegerType)
@rxin @hvanhovell If we really want to support all these types, is it better to move this conversion and pattern match logics into `CountMinSketch`? That is, make cms support these types itself. Then, when users do queries e.g. on float type, they don't need to do conversions like `cms.estimateCount(Float.floatToIntBits(value))`.

2016-11-20 05:42 UTC, rxin commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAgg.scala
> +      DoubleType, DoubleType, IntegerType)
Yes if we want to add support for those I think it'd make sense to do it in count-min sketch itself too.

2016-11-22 08:22 UTC, SparkQA commented
**[Test build #68985 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/68985/consoleFull)** for PR 15877 at commit [`ca4a13f`](https://github.com/apache/spark/commit/ca4a13f70e95522105d670e60a908c2e7b4e6cab).

2016-11-22 11:07 UTC, SparkQA commented
**[Test build #68994 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/68994/consoleFull)** for PR 15877 at commit [`b009ff8`](https://github.com/apache/spark/commit/b009ff858dd53a73bdc4e64ba7a090c0118ba235).

2016-11-22 11:13 UTC, SparkQA commented
**[Test build #68985 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/68985/consoleFull)** for PR 15877 at commit [`ca4a13f`](https://github.com/apache/spark/commit/ca4a13f70e95522105d670e60a908c2e7b4e6cab).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-11-22 11:14 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-11-22 11:14 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/68985/
Test PASSed.

2016-11-22 13:42 UTC, SparkQA commented
**[Test build #68994 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/68994/consoleFull)** for PR 15877 at commit [`b009ff8`](https://github.com/apache/spark/commit/b009ff858dd53a73bdc4e64ba7a090c0118ba235).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-11-22 13:43 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-11-22 13:43 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/68994/
Test PASSed.

2016-11-23 03:32 UTC, SparkQA commented
**[Test build #69047 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69047/consoleFull)** for PR 15877 at commit [`a6bbefc`](https://github.com/apache/spark/commit/a6bbefcb8c0b8c4b14c47a3ff031be064f576ab2).

2016-11-23 03:36 UTC, wzhfy commented
cc @rxin @hvanhovell

2016-11-23 03:37 UTC, SparkQA commented
**[Test build #69049 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69049/consoleFull)** for PR 15877 at commit [`1bfb6fd`](https://github.com/apache/spark/commit/1bfb6fd7810c7db9218bcdb65aed80102406b211).

2016-11-23 05:41 UTC, SparkQA commented
**[Test build #69049 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69049/consoleFull)** for PR 15877 at commit [`1bfb6fd`](https://github.com/apache/spark/commit/1bfb6fd7810c7db9218bcdb65aed80102406b211).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-11-23 05:42 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-11-23 05:42 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/69049/
Test FAILed.

2016-11-23 06:12 UTC, SparkQA commented
**[Test build #69047 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69047/consoleFull)** for PR 15877 at commit [`a6bbefc`](https://github.com/apache/spark/commit/a6bbefcb8c0b8c4b14c47a3ff031be064f576ab2).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-11-23 06:13 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-11-23 06:13 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/69047/
Test PASSed.

2016-11-29 06:07 UTC, rxin commented on common/sketch/src/main/java/org/apache/spark/util/sketch/CountMinSketchImpl.java
> +      addString(((BigDecimal) item).toString(), count);
Is this true? 

"1.0" and "1.00" is the same value but not the same string representation.

2016-11-29 21:16 UTC, rxin commented
Thanks - I'm going to merge this in master. I will submit a follow-up PR to simplify this a little bit, and remove the handling of float/double/decimal types and require explicit user action on how to turn that into long.

2016-11-29 21:19 UTC, closed without merging

2016-11-29 21:46 UTC, rxin commented
Hey guys - after looking at the pr more, I'm afraid we have gone overboard with testing here. Most of the test cases written are just repeating each other and doing exactly the same thing. For testing something like this I'd probably just have some simple end-to-end test and then be done with it, because most of the complicated logics are isolated in the actual CountMinSketch implementation itself and already has good test coverage.

2016-11-29 21:49 UTC, rxin commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CountMinSketchAggSuite.scala
> +  def testHighLevelInterface[T: ClassTag](
@wzhfy can you comment on why we need to test both the high level interface and the low level interface?