[SPARK-18356] [ML] Improve MLKmeans Performance
apache/spark pull request #15965
Opened 2016-11-21 14:28 UTC by ZakariaHili

## What changes were proposed in this pull request?

Spark Kmeans fit() doesn't cache the RDD which generates a lot of warnings : 
 WARN KMeans: The input data is not directly cached, which may hurt performance if its parent RDDs are also uncached.
So, Kmeans should cache the internal rdd before calling the Mllib.Kmeans algo, this helped to improve spark kmeans performance by 14%

https://github.com/ZakariaHili/spark/commit/a9cf905cf7dbd50eeb9a8b4f891f2f41ea672472

@hhbyyh 
## How was this patch tested?
Pass Kmeans tests and existing tests

2016-11-21 14:32 UTC, srowen requested changes

2016-11-21 14:32 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/ml/clustering/KMeans.scala
> +      val versionRegex = "([0-9]+)\\.(.+)".r
Your change is reverting some other changes like this one. Can you clean this up to only reflect the changes you intend?

2016-11-21 14:32 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2016-11-21 17:55 UTC, hhbyyh commented
@ZakariaHili Great to see your PR. @srowen is right, please try to merge with the latest code.

2016-11-21 17:55 UTC, hhbyyh commented on mllib/src/main/scala/org/apache/spark/ml/clustering/KMeans.scala
> + */
remove the extra space, please use [Spark root]/dev/lint-scala to verify your code style.

2016-11-21 17:55 UTC, hhbyyh commented on mllib/src/main/scala/org/apache/spark/ml/clustering/KMeans.scala
> +    */
The comment may not be necessary, as it's used elsewhere and clear by the code itself

2016-11-21 19:45 UTC, ZakariaHili reviewed
sorry for my late reply, i was a little bit busy.
I cleaned the code and I tested the code style using ./dev/lint-scala.

2016-11-21 19:45 UTC, ZakariaHili commented on mllib/src/main/scala/org/apache/spark/ml/clustering/KMeans.scala
> + */
I cleaned the code, then I run /dev/lint-scala and I received : 
Scalastyle checks passed.

2016-11-21 19:45 UTC, ZakariaHili commented on mllib/src/main/scala/org/apache/spark/ml/clustering/KMeans.scala
> +      val versionRegex = "([0-9]+)\\.(.+)".r
sorry for my late, I was busy,
now , I think the code is ready

2016-11-22 01:57 UTC, hhbyyh commented
Hi @ZakariaHili is it finished? https://github.com/apache/spark/pull/15965/files still contains a lot of unrelated code change.

2016-11-22 09:17 UTC, ZakariaHili commented
Hi Yuhao , are you sure ?
I think that you still compare previous commits with

2016-11-22 09:22 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2016-11-22 09:57 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2016-11-22 09:58 UTC, ZakariaHili commented
Sorry, I didn't know that you already accepted some changes from other people, so I had to force the synchronization, then re-test everything.
Now, the code is clean

2016-11-22 09:59 UTC, srowen requested changes

2016-11-22 09:59 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/ml/clustering/KMeans.scala
> +  @Since("2.0.0")
This still has several problems. This can't be since 2.0.0 and there is no space before this line.

2016-11-22 09:59 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/ml/clustering/KMeans.scala
> +     instances.unpersist()
fix spacing here

2016-11-22 10:22 UTC, ZakariaHili reviewed
@srowen,  I added the space and I removed @ Since("2.0.0")

2016-11-22 10:22 UTC, ZakariaHili commented on mllib/src/main/scala/org/apache/spark/ml/clustering/KMeans.scala
> +  @Since("2.0.0")
Ok it's removed

2016-11-22 10:22 UTC, ZakariaHili commented on mllib/src/main/scala/org/apache/spark/ml/clustering/KMeans.scala
> +     instances.unpersist()
the space is fixed

2016-11-22 11:06 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/ml/clustering/KMeans.scala
> +  protected def fit(dataset: Dataset[_], handlePersistence: Boolean): KMeansModel = {
Still wrong -- no space, and now no `@Since` at all. This is `@Since("2.2.0")` if it goes in.

2016-11-22 14:04 UTC, ZakariaHili reviewed
@srowen I hope that i understood you right, this time

2016-11-22 14:04 UTC, ZakariaHili commented on mllib/src/main/scala/org/apache/spark/ml/clustering/KMeans.scala
> +  @Since("2.2.0")
@srowen ,now I think I understand what do you mean by no space here.

2016-11-22 14:46 UTC, srowen requested changes

2016-11-22 14:46 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/ml/clustering/KMeans.scala
> +  @Since("2.2.0")
Why did you change this? this is wrong.

2016-11-22 14:46 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/ml/clustering/KMeans.scala
> +  @Since("2.2.0")
There is still no blank line above this line -- not sure how else to express this?
The indentation of the line above is off too.

Look, you should match the style you see around this code, and you can see how it isn't the same? just make it match.

2016-11-22 15:12 UTC, ZakariaHili commented
@srowen, Ok I found it
I fixed

2016-11-23 09:05 UTC, ZakariaHili commented
@srowen, I think it's ready to merge

2016-11-23 11:16 UTC, srowen commented
I think that's OK. @hhbyyh ?

2016-11-23 20:47 UTC, hhbyyh commented
LGTM.

2016-11-24 11:00 UTC, SparkQA commented
**[Test build #3436 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3436/consoleFull)** for PR 15965 at commit [`fd4543d`](https://github.com/apache/spark/commit/fd4543d918b26b451000fe92fbe1cdb259a6687b).

2016-11-24 11:01 UTC, SparkQA commented
**[Test build #3436 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3436/consoleFull)** for PR 15965 at commit [`fd4543d`](https://github.com/apache/spark/commit/fd4543d918b26b451000fe92fbe1cdb259a6687b).
 * This patch **fails Scala style tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-11-24 12:04 UTC, ZakariaHili commented on mllib/src/main/scala/org/apache/spark/ml/clustering/KMeans.scala
> +
I didn't see that with vim editor

2016-11-25 09:45 UTC, SparkQA commented
**[Test build #3438 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3438/consoleFull)** for PR 15965 at commit [`f17a54c`](https://github.com/apache/spark/commit/f17a54c34e9aa007f36426c2b8459ab0bf784863).

2016-11-25 12:31 UTC, SparkQA commented
**[Test build #3438 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3438/consoleFull)** for PR 15965 at commit [`f17a54c`](https://github.com/apache/spark/commit/f17a54c34e9aa007f36426c2b8459ab0bf784863).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-11-25 13:21 UTC, closed without merging

2016-12-14 06:18 UTC, jkbradley commented on mllib/src/main/scala/org/apache/spark/ml/clustering/KMeans.scala
> +  protected def fit(dataset: Dataset[_], handlePersistence: Boolean): KMeansModel = {
Hi, sorry for not seeing this earlier.  We should not make a new public method for this.  @ZakariaHili would you mind sending a follow-up PR (under the same JIRA issue) which eliminates this new fit() method?  You should be able to delete lines 311 - 315 here and keep everything else the same.  Thank you!

2016-12-14 14:17 UTC, ZakariaHili commented
Hi @jkbradley, 
In actually, I thought of the same thing, but Mr. yuhao yang advised me to do the same style of LogisticRegression.scala
anywhere I changed the file as you want, and I changed the code a little (e.g : no need to generate the rdd two time
the first one to check storage level and the second one for Kmeans
)

2016-12-14 14:25 UTC, ZakariaHili commented on mllib/src/main/scala/org/apache/spark/ml/clustering/KMeans.scala
> +  protected def fit(dataset: Dataset[_], handlePersistence: Boolean): KMeansModel = {
Hi @jkbradley, 
In actually, I thought of the same thing, but Mr. yuhao yang advised me to do the same style of LogisticRegression.scala
anywhere I changed the file as you want, and I changed the code a little (e.g : no need to generate the rdd two times
the first one to check storage level and the second one for Kmeans
)
here the change
https://github.com/ZakariaHili/spark/commit/58de5499d0930e4019c94718a2a9ed3dd715acb2

do you still want from me to send a PR ?

2016-12-15 01:22 UTC, jkbradley commented on mllib/src/main/scala/org/apache/spark/ml/clustering/KMeans.scala
> +  protected def fit(dataset: Dataset[_], handlePersistence: Boolean): KMeansModel = {
I like the change in terms of eliminating the extra fit() method (which is not done anywhere else in spark.ml), but I think you'll need to keep the original test for storage level ```val handlePersistence = dataset.rdd.getStorageLevel == StorageLevel.NONE```.  In the current change, the RDD being tested is different from ```dataset.rdd```, so handlePersistence would always be true regardless of the original storage level.  Could you please send a little PR which merges the 2 fit() methods?  Thanks!