[SPARK-17251][SQL] Support `OuterReference` in projection list of a correlated subquery
apache/spark pull request #16012
Opened 2016-11-25 11:30 UTC by dongjoon-hyun

## What changes were proposed in this pull request?

Currently, correlated subqueries does not allow `OuterReference` columns in projection lists. This PR aims to support that by making `OuterReference` as `NamedExpression` and extending `pullOutCorrelatedPredicates` into `pullOutCorrelatedProjectionAndPredicates`.

```scala
scala> sql("CREATE TEMPORARY VIEW t1 AS SELECT * FROM VALUES 1, 2 AS t1(a)")
scala> sql("CREATE TEMPORARY VIEW t2 AS SELECT * FROM VALUES 1 AS t2(b)")
scala> sql("SELECT a FROM t1 WHERE a IN (SELECT a FROM t2)").show
java.lang.ClassCastException: org.apache.spark.sql.catalyst.expressions.OuterReference cannot be cast to org.apache.spark.sql.catalyst.expressions.NamedExpression
```

## How was this patch tested?

Pass the Jenkins test with new test cases.

2016-11-25 11:32 UTC, SparkQA commented
**[Test build #69163 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69163/consoleFull)** for PR 16012 at commit [`58449b3`](https://github.com/apache/spark/commit/58449b317f9a04e5cba2f106afede19dbfde953e).

2016-11-25 13:06 UTC, hvanhovell commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/namedExpressions.scala
> +  override def name: String = throw new UnsupportedOperationException
Implement as much of these as possible (delegate to the NamedExpression). It is a resolved expression after all.

2016-11-25 13:09 UTC, hvanhovell commented on sql/core/src/test/resources/sql-tests/inputs/correlated.sql
> +CREATE TEMPORARY VIEW t1 AS SELECT * FROM VALUES 1, 2 AS t1(a);
Naming: lets call this `subqueries.sql`. Correlation has a different meaning in different contexts

2016-11-25 14:07 UTC, SparkQA commented
**[Test build #69163 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69163/consoleFull)** for PR 16012 at commit [`58449b3`](https://github.com/apache/spark/commit/58449b317f9a04e5cba2f106afede19dbfde953e).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `case class OuterReference(e: NamedExpression)`

2016-11-25 14:09 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-11-25 14:09 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/69163/
Test PASSed.

2016-11-25 18:14 UTC, dongjoon-hyun commented
Thank you, @hvanhovell ! I'll fix like that!

2016-11-25 19:42 UTC, SparkQA commented
**[Test build #69173 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69173/consoleFull)** for PR 16012 at commit [`3de9419`](https://github.com/apache/spark/commit/3de9419a30790020fb4d562625941dbc5e1772d2).

2016-11-25 20:43 UTC, hvanhovell requested changes

2016-11-25 20:43 UTC, hvanhovell commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/namedExpressions.scala
> +  val exprId: ExprId = NamedExpression.newExprId)
Use the `exprId` of the `NamedExpression`.

2016-11-25 20:43 UTC, hvanhovell commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/namedExpressions.scala
> +  override def newInstance(): NamedExpression = OuterReference(e)()
`OuterReference(e.newInstance())()`?

2016-11-25 20:43 UTC, hvanhovell commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/Analyzer.scala
> +                    case Some(outerAttr) => OuterReference(outerAttr)()
I am not sure the analyzer change has the desired effect. This just remove the outer reference from the tree, and this won't work if we use the attribute anywhere in the tree. For example:
```sql
select *
from   tbl_a
where id in (select x
             from (select tbl_b.id,
                          tbl_a.id + 1 as x,
                          tbl_a.id + tbl_b.id as y
                   from   tbl_b)
              where y > 0)
```

I think we need to break this down into two steps:
1. Do not support this for now and just fix the named expression. That would be my goal for 2.1.
2. Try to see if we can rewrite the tree in such a way that we can extract the value. That would be my goal for 2.2. I am not sure how well we can make this work. In the end I think we need a dedicated subquery operator.

cc @nsyca what do you think.

2016-11-25 20:56 UTC, dongjoon-hyun commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/namedExpressions.scala
> +  override def newInstance(): NamedExpression = OuterReference(e)()
Sure.

2016-11-25 22:13 UTC, SparkQA commented
**[Test build #69173 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69173/consoleFull)** for PR 16012 at commit [`3de9419`](https://github.com/apache/spark/commit/3de9419a30790020fb4d562625941dbc5e1772d2).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `case class OuterReference(e: NamedExpression)(`

2016-11-25 22:14 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-11-25 22:14 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/69173/
Test PASSed.

2016-11-26 02:26 UTC, nsyca commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/Analyzer.scala
> +                    case Some(outerAttr) => OuterReference(outerAttr)()
Another interesting case to consider:
````sql
select ...
from   t1
where  t1.c1 in (select sum(t1.c2) from t2)
````

If we support correlated columns in SELECT clause, do we build the Aggregate on T2 or T1?

2016-11-26 03:35 UTC, dongjoon-hyun commented
Thank you for review, @hvanhovell and @nsyca .
I agree with you. We need enough time for this.
So, the option one for 2.1 is spun off into #16015.

2016-11-27 20:48 UTC, hvanhovell commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/Analyzer.scala
> +                    case Some(outerAttr) => OuterReference(outerAttr)()
The `LEFT ANTI` join should produce the correct result. Unfortunately we push down the `tbl_a.c1 = tbl_a.c2` expression into the `tbl_a` side of the plan. So we need to fix this. I have created https://issues.apache.org/jira/browse/SPARK-18597 to track this.

2016-11-27 20:51 UTC, dongjoon-hyun commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/Analyzer.scala
> +                    case Some(outerAttr) => OuterReference(outerAttr)()
Thank you @hvanhovell .
BTW, may I rebase this PR and try to the second plan for 2.2 here?
> 2. Try to see if we can rewrite the tree in such a way that we can extract the value. That would be my goal for 2.2. I am not sure how well we can make this work. In the end I think we need a dedicated subquery operator.

2016-11-28 00:16 UTC, dongjoon-hyun commented
Hi, @hvanhovell and @nsyca .

I created a JIRA issue for Option 2 with simple and complex example (@hvanhovell 's).

* https://issues.apache.org/jira/browse/SPARK-18603

Now, I'm closing this PR. Thank you for reviews, @hvanhovell and @nsyca .

2016-11-28 00:16 UTC, closed without merging