[MINOR][DOCS] Updates to the Accumulator example in the programming guide. Fixed typos, AccumulatorV2 in Java
apache/spark pull request #16024
Opened 2016-11-27 22:00 UTC by aokolnychyi

## What changes were proposed in this pull request?

This pull request contains updates to Scala and Java Accumulator code snippets in the programming guide. 

- For Scala, the pull request fixes the signature of the 'add()' method in the custom Accumulator, which contained two params (as the old AccumulatorParam) instead of one (as in AccumulatorV2). 

- The Java example was updated to use the AccumulatorV2 class since AccumulatorParam is marked as deprecated.  

- Scala and Java examples are more consistent now.

## How was this patch tested?

This patch was tested manually by building the docs locally.

![image](https://cloud.githubusercontent.com/assets/6235869/20652099/77d98d18-b4f3-11e6-8565-a995fe8cf8e5.png)

2016-11-27 22:02 UTC, SparkQA commented
**[Test build #69209 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69209/consoleFull)** for PR 16024 at commit [`f4388a8`](https://github.com/apache/spark/commit/f4388a84181e7c40003db0b1574602350160721a).

2016-11-27 22:21 UTC, SparkQA commented
**[Test build #69209 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69209/consoleFull)** for PR 16024 at commit [`f4388a8`](https://github.com/apache/spark/commit/f4388a84181e7c40003db0b1574602350160721a).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `class MathVectorAccumulatorV2 extends AccumulatorV2[MathVector, MathVector] `
  * `class MathVectorAccumulatorV2 implements AccumulatorV2<MathVector, MathVector> `

2016-11-27 22:22 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-11-27 22:22 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/69209/
Test PASSed.

2016-11-28 02:28 UTC, HyukjinKwon commented on docs/programming-guide.md
> +Note that, when programmers define their own type of AccumulatorV2,the resulting type can be different
I was reading this for my fun but I just found a possible super minor `AccumulatorV2,the` to `AccumulatorV2, the`

2016-11-28 12:32 UTC, srowen requested changes

2016-11-28 12:32 UTC, srowen commented on docs/programming-guide.md
> +For example, supposing we had a `MathVector` class representing mathematical vectors, we could write:
Why MyVector -> MathVector? to limit the scope and make it clearer, probably best to not change elements of the example that were OK.

2016-11-28 14:18 UTC, aokolnychyi commented on docs/programming-guide.md
> +Note that, when programmers define their own type of AccumulatorV2,the resulting type can be different
Sure, I'll update that. Thanks

2016-11-28 14:36 UTC, aokolnychyi commented on docs/programming-guide.md
> +For example, supposing we had a `MathVector` class representing mathematical vectors, we could write:
Your point makes sense to me. 

The renaming was to done to improve the consistency between Java/Scala examples. For instance, the Scala example used MyVector, while the Java one - Vector. 

Will it be a better idea to keep MyVector in the Scala example and reuse this name in Java?

2016-11-28 14:56 UTC, srowen commented on docs/programming-guide.md
> +For example, supposing we had a `MathVector` class representing mathematical vectors, we could write:
Yes let's use MyVector call consistently then.

2016-11-28 19:22 UTC, SparkQA commented
**[Test build #69256 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69256/consoleFull)** for PR 16024 at commit [`0366a3c`](https://github.com/apache/spark/commit/0366a3c77957ae9a6f7d9a92581ed3b9af430c62).

2016-11-28 19:48 UTC, SparkQA commented
**[Test build #69256 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69256/consoleFull)** for PR 16024 at commit [`0366a3c`](https://github.com/apache/spark/commit/0366a3c77957ae9a6f7d9a92581ed3b9af430c62).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `class VectorAccumulatorV2 extends AccumulatorV2[MyVector, MyVector] `
  * `class VectorAccumulatorV2 implements AccumulatorV2<MyVector, MyVector> `

2016-11-28 19:48 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-11-28 19:48 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/69256/
Test PASSed.

2016-11-29 10:01 UTC, srowen approved these changes

2016-11-29 13:50 UTC, srowen commented
Merged to master/2.1

2016-11-29 13:52 UTC, closed without merging