[SPARK-18685][TESTS] Fix URI and release resources after opening in tests at ExecutorClassLoaderSuite
apache/spark pull request #16116
Opened 2016-12-02 07:46 UTC by HyukjinKwon

## What changes were proposed in this pull request?

This PR fixes two problems as below:

- Close `BufferedSource` after `Source.fromInputStream(...)` to release resource and make the tests pass on Windows in `ExecutorClassLoaderSuite`

  ```
  [info] Exception encountered when attempting to run a suite with class name: org.apache.spark.repl.ExecutorClassLoaderSuite *** ABORTED *** (7 seconds, 333 milliseconds)
  [info]   java.io.IOException: Failed to delete: C:\projects\spark\target\tmp\spark-77b2f37b-6405-47c4-af1c-4a6a206511f2
  [info]   at org.apache.spark.util.Utils$.deleteRecursively(Utils.scala:1010)
  [info]   at org.apache.spark.repl.ExecutorClassLoaderSuite.afterAll(ExecutorClassLoaderSuite.scala:76)
  [info]   at org.scalatest.BeforeAndAfterAll$class.afterAll(BeforeAndAfterAll.scala:213)
  ...
  ```

- Fix URI correctly so that related tests can be passed on Windows.

  ```
  [info] - child first *** FAILED *** (78 milliseconds)
  [info]   java.net.URISyntaxException: Illegal character in authority at index 7: file://C:\projects\spark\target\tmp\spark-00b66070-0548-463c-b6f3-8965d173da9b
  [info]   at java.net.URI$Parser.fail(URI.java:2848)
  [info]   at java.net.URI$Parser.parseAuthority(URI.java:3186)
  ...
  [info] - parent first *** FAILED *** (15 milliseconds)
  [info]   java.net.URISyntaxException: Illegal character in authority at index 7: file://C:\projects\spark\target\tmp\spark-00b66070-0548-463c-b6f3-8965d173da9b
  [info]   at java.net.URI$Parser.fail(URI.java:2848)
  [info]   at java.net.URI$Parser.parseAuthority(URI.java:3186)
  ...
  [info] - child first can fall back *** FAILED *** (0 milliseconds)
  [info]   java.net.URISyntaxException: Illegal character in authority at index 7: file://C:\projects\spark\target\tmp\spark-00b66070-0548-463c-b6f3-8965d173da9b
  [info]   at java.net.URI$Parser.fail(URI.java:2848)
  [info]   at java.net.URI$Parser.parseAuthority(URI.java:3186)
  ...
  [info] - child first can fail *** FAILED *** (0 milliseconds)
  [info]   java.net.URISyntaxException: Illegal character in authority at index 7: file://C:\projects\spark\target\tmp\spark-00b66070-0548-463c-b6f3-8965d173da9b
  [info]   at java.net.URI$Parser.fail(URI.java:2848)
  [info]   at java.net.URI$Parser.parseAuthority(URI.java:3186)
  ...
  [info] - resource from parent *** FAILED *** (0 milliseconds)
  [info]   java.net.URISyntaxException: Illegal character in authority at index 7: file://C:\projects\spark\target\tmp\spark-00b66070-0548-463c-b6f3-8965d173da9b
  [info]   at java.net.URI$Parser.fail(URI.java:2848)
  [info]   at java.net.URI$Parser.parseAuthority(URI.java:3186)
  ...
  [info] - resources from parent *** FAILED *** (0 milliseconds)
  [info]   java.net.URISyntaxException: Illegal character in authority at index 7: file://C:\projects\spark\target\tmp\spark-00b66070-0548-463c-b6f3-8965d173da9b
  [info]   at java.net.URI$Parser.fail(URI.java:2848)
  [info]   at java.net.URI$Parser.parseAuthority(URI.java:3186)
  ```

## How was this patch tested?

Manually tested via AppVeyor.

**Before**
https://ci.appveyor.com/project/spark-test/spark/build/102-rpel-ExecutorClassLoaderSuite

**After**
https://ci.appveyor.com/project/spark-test/spark/build/108-rpel-ExecutorClassLoaderSuite

2016-12-02 07:47 UTC, SparkQA commented
**[Test build #69552 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69552/consoleFull)** for PR 16116 at commit [`8d40848`](https://github.com/apache/spark/commit/8d40848fd5559a46561fd9bd3aefac4151d6321d).

2016-12-02 07:56 UTC, HyukjinKwon commented
Build started: [Tests] `org.apache.spark.repl.ExecutorClassLoaderSuite` [![PR-16116](https://ci.appveyor.com/api/projects/status/github/spark-test/spark?branch=D9720E89-7333-4FBE-8F62-F387A249B5D8&svg=true)](https://ci.appveyor.com/project/spark-test/spark/branch/D9720E89-7333-4FBE-8F62-F387A249B5D8)
Diff: https://github.com/apache/spark/compare/master...spark-test:D9720E89-7333-4FBE-8F62-F387A249B5D8

2016-12-02 08:02 UTC, HyukjinKwon commented
cc @srowen and @mridulm, Could I please ask to take a look?

2016-12-02 08:05 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-12-02 08:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/69552/
Test FAILed.

2016-12-02 08:17 UTC, HyukjinKwon commented
retest this please

2016-12-02 08:22 UTC, SparkQA commented
**[Test build #69557 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69557/consoleFull)** for PR 16116 at commit [`8d40848`](https://github.com/apache/spark/commit/8d40848fd5559a46561fd9bd3aefac4151d6321d).

2016-12-02 08:46 UTC, srowen requested changes

2016-12-02 08:46 UTC, srowen commented on repl/src/test/scala/org/apache/spark/repl/ExecutorClassLoaderSuite.scala
> +      bufferedSource = Source.fromInputStream(is, "UTF-8")
Can this line be outside the try block? if it fails, there's nothing to clean up. Then you don't need a var

2016-12-02 08:48 UTC, SparkQA commented
**[Test build #69557 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69557/consoleFull)** for PR 16116 at commit [`8d40848`](https://github.com/apache/spark/commit/8d40848fd5559a46561fd9bd3aefac4151d6321d).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-12-02 08:49 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-12-02 08:49 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/69557/
Test FAILed.

2016-12-02 09:05 UTC, srowen commented on repl/src/test/scala/org/apache/spark/repl/ExecutorClassLoaderSuite.scala
> +    url1 = "file://" + tempDir1.toURI.getPath
Is it simpler to use tempDir1.toUri or something like that rather than rebuild a URI by hand?

2016-12-02 09:20 UTC, HyukjinKwon commented on repl/src/test/scala/org/apache/spark/repl/ExecutorClassLoaderSuite.scala
> +      bufferedSource = Source.fromInputStream(is, "UTF-8")
Ah, sure. I will address the comment below too. Thank you.

2016-12-02 09:32 UTC, SparkQA commented
**[Test build #69561 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69561/consoleFull)** for PR 16116 at commit [`0886730`](https://github.com/apache/spark/commit/0886730b603c9bd0a7ecac432e1d853d49098117).

2016-12-02 09:32 UTC, HyukjinKwon commented
Build started: [Tests] `org.apache.spark.repl.ExecutorClassLoaderSuite` [![PR-16116](https://ci.appveyor.com/api/projects/status/github/spark-test/spark?branch=59176151-3EB5-4D9C-8E8D-398EFF22DE64&svg=true)](https://ci.appveyor.com/project/spark-test/spark/branch/59176151-3EB5-4D9C-8E8D-398EFF22DE64)
Diff: https://github.com/apache/spark/compare/master...spark-test:59176151-3EB5-4D9C-8E8D-398EFF22DE64

2016-12-02 11:49 UTC, HyukjinKwon commented
Build started: [Tests] `org.apache.spark.repl.ExecutorClassLoaderSuite` [![PR-16116](https://ci.appveyor.com/api/projects/status/github/spark-test/spark?branch=BFC9C65B-256B-4A41-B8F8-F224F3093018&svg=true)](https://ci.appveyor.com/project/spark-test/spark/branch/BFC9C65B-256B-4A41-B8F8-F224F3093018)
Diff: https://github.com/apache/spark/compare/master...spark-test:BFC9C65B-256B-4A41-B8F8-F224F3093018

2016-12-02 11:52 UTC, SparkQA commented
**[Test build #69566 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69566/consoleFull)** for PR 16116 at commit [`d588207`](https://github.com/apache/spark/commit/d588207b7ff0ec775f3a54ade45ebd6bd4ca2759).

2016-12-02 11:55 UTC, SparkQA commented
**[Test build #69561 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69561/consoleFull)** for PR 16116 at commit [`0886730`](https://github.com/apache/spark/commit/0886730b603c9bd0a7ecac432e1d853d49098117).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-12-02 11:56 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-12-02 11:56 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/69561/
Test PASSed.

2016-12-02 12:03 UTC, srowen approved these changes

2016-12-02 14:26 UTC, SparkQA commented
**[Test build #69566 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69566/consoleFull)** for PR 16116 at commit [`d588207`](https://github.com/apache/spark/commit/d588207b7ff0ec775f3a54ade45ebd6bd4ca2759).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-12-02 14:28 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-12-02 14:28 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/69566/
Test PASSed.

2016-12-03 10:13 UTC, srowen commented
Merged to master/2.1/2.0

2016-12-03 10:16 UTC, closed without merging

2016-12-03 10:17 UTC, HyukjinKwon commented
Thank you !!