[DO_NOT_MERGE]Try to fix kafka
apache/spark pull request #16282
Opened 2016-12-14 21:20 UTC by zsxwing

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

Please review http://spark.apache.org/contributing.html before opening a pull request.

2016-12-14 21:22 UTC, SparkQA commented
**[Test build #70146 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70146/testReport)** for PR 16282 at commit [`4a690b6`](https://github.com/apache/spark/commit/4a690b65c76940d88b29f9d6d1cf582fdbba1de4).

2016-12-14 21:22 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-12-14 21:22 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70146/
Test FAILed.

2016-12-14 21:32 UTC, SparkQA commented
**[Test build #70148 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70148/testReport)** for PR 16282 at commit [`c4e6962`](https://github.com/apache/spark/commit/c4e6962dbf22c2ec7658f95fd1be069628860855).

2016-12-14 23:23 UTC, SparkQA commented
**[Test build #70148 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70148/testReport)** for PR 16282 at commit [`c4e6962`](https://github.com/apache/spark/commit/c4e6962dbf22c2ec7658f95fd1be069628860855).
 * This patch **fails executing the `dev/run-tests` script**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-12-14 23:23 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-12-14 23:23 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70148/
Test FAILed.

2016-12-14 23:24 UTC, zsxwing commented
retest this please

2016-12-14 23:27 UTC, SparkQA commented
**[Test build #70153 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70153/testReport)** for PR 16282 at commit [`c4e6962`](https://github.com/apache/spark/commit/c4e6962dbf22c2ec7658f95fd1be069628860855).

2016-12-15 03:37 UTC, SparkQA commented
**[Test build #70153 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70153/testReport)** for PR 16282 at commit [`c4e6962`](https://github.com/apache/spark/commit/c4e6962dbf22c2ec7658f95fd1be069628860855).
 * This patch **fails from timeout after a configured wait of \`250m\`**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-12-15 03:37 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-12-15 03:37 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70153/
Test FAILed.

2016-12-15 16:35 UTC, SparkQA commented
**[Test build #3501 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3501/testReport)** for PR 16282 at commit [`c4e6962`](https://github.com/apache/spark/commit/c4e6962dbf22c2ec7658f95fd1be069628860855).

2016-12-15 21:16 UTC, zsxwing commented
retest this please

2016-12-15 21:17 UTC, SparkQA commented
**[Test build #70210 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70210/testReport)** for PR 16282 at commit [`c4e6962`](https://github.com/apache/spark/commit/c4e6962dbf22c2ec7658f95fd1be069628860855).

2016-12-15 23:47 UTC, SparkQA commented
**[Test build #70219 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70219/testReport)** for PR 16282 at commit [`2143462`](https://github.com/apache/spark/commit/21434625f609b89eff30a2dd88b2886f31fa9521).

2016-12-16 01:27 UTC, SparkQA commented
**[Test build #70210 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70210/testReport)** for PR 16282 at commit [`c4e6962`](https://github.com/apache/spark/commit/c4e6962dbf22c2ec7658f95fd1be069628860855).
 * This patch **fails from timeout after a configured wait of \`250m\`**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-12-16 01:27 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-12-16 01:27 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70210/
Test FAILed.

2016-12-16 01:32 UTC, SparkQA commented
**[Test build #70229 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70229/testReport)** for PR 16282 at commit [`5afb13d`](https://github.com/apache/spark/commit/5afb13d5fa4461bd57a748deb157aaa290d6155f).

2016-12-16 03:57 UTC, SparkQA commented
**[Test build #70219 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70219/testReport)** for PR 16282 at commit [`2143462`](https://github.com/apache/spark/commit/21434625f609b89eff30a2dd88b2886f31fa9521).
 * This patch **fails from timeout after a configured wait of \`250m\`**.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `  case class AssignStrategy(partitions: Array[TopicPartition]) extends ConsumerStrategy `
  * `  case class SubscribeStrategy(topics: Seq[String]) extends ConsumerStrategy `
  * `  case class SubscribePatternStrategy(topicPattern: String)`
  * `class KafkaConsumerGroupIdGenerator(groupIdPrefix: String) `

2016-12-16 03:57 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-12-16 03:57 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70219/
Test FAILed.

2016-12-16 05:42 UTC, SparkQA commented
**[Test build #70229 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70229/testReport)** for PR 16282 at commit [`5afb13d`](https://github.com/apache/spark/commit/5afb13d5fa4461bd57a748deb157aaa290d6155f).
 * This patch **fails from timeout after a configured wait of \`250m\`**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-12-16 05:42 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-12-16 05:42 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70229/
Test FAILed.

2016-12-16 07:17 UTC, SparkQA commented
**[Test build #70240 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70240/testReport)** for PR 16282 at commit [`7b75dd6`](https://github.com/apache/spark/commit/7b75dd6a6213441a51d6c58b230d4e52097595ea).

2016-12-16 08:05 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-12-16 08:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70240/
Test FAILed.

2016-12-16 18:37 UTC, zsxwing commented
retest this please

2016-12-16 18:42 UTC, SparkQA commented
**[Test build #70262 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70262/testReport)** for PR 16282 at commit [`7b75dd6`](https://github.com/apache/spark/commit/7b75dd6a6213441a51d6c58b230d4e52097595ea).

2016-12-16 19:17 UTC, SparkQA commented
**[Test build #70264 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70264/testReport)** for PR 16282 at commit [`f10ee87`](https://github.com/apache/spark/commit/f10ee87f5b40721d26bc350ed0a87b575b2c9cdd).

2016-12-16 19:22 UTC, zsxwing commented on external/kafka-0-10-sql/src/main/scala/org/apache/spark/sql/kafka010/KafkaSource.scala
> +private[kafka010] class KafkaSource(
Remove `case` to make `equals` faster since this class has implemented its `toString`.

2016-12-16 19:24 UTC, zsxwing commented on external/kafka-0-10-sql/src/main/scala/org/apache/spark/sql/kafka010/KafkaSource.scala
> -                case x: OffsetOutOfRangeException =>
`OffsetOutOfRangeException` only happens when we call `seek` than `poll`. So it won't happen here. It's pretty confusing as it doesn't update `attempt`, so I just removed it.

2016-12-16 19:26 UTC, zsxwing commented on external/kafka-0-10-sql/src/main/scala/org/apache/spark/sql/kafka010/KafkaSource.scala
> -private[kafka010] case class KafkaSource(
Remove `case` to make `equals` faster since this class has implemented its `toString`.

2016-12-16 19:26 UTC, zsxwing commented on external/kafka-0-10-sql/src/main/scala/org/apache/spark/sql/kafka010/KafkaSource.scala
> -                case x: OffsetOutOfRangeException =>
`OffsetOutOfRangeException` only happens when we call `seek` than `poll`. So it won't happen here. It's pretty confusing as it doesn't update attempt, so I just removed it.

2016-12-16 19:27 UTC, SparkQA commented
**[Test build #70266 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70266/testReport)** for PR 16282 at commit [`0f3a7f9`](https://github.com/apache/spark/commit/0f3a7f9fa1b23bd3901ccbc4fd443bfafa03e71c).

2016-12-16 19:57 UTC, SparkQA commented
**[Test build #70268 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70268/testReport)** for PR 16282 at commit [`fd53ee1`](https://github.com/apache/spark/commit/fd53ee12ed0fd09e788518fe7df8eda2d389dc42).

2016-12-16 20:32 UTC, SparkQA commented
**[Test build #70264 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70264/testReport)** for PR 16282 at commit [`f10ee87`](https://github.com/apache/spark/commit/f10ee87f5b40721d26bc350ed0a87b575b2c9cdd).
 * This patch **fails executing the `dev/run-tests` script**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-12-16 20:32 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-12-16 20:32 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70264/
Test FAILed.

2016-12-16 21:09 UTC, SparkQA commented
**[Test build #70268 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70268/testReport)** for PR 16282 at commit [`fd53ee1`](https://github.com/apache/spark/commit/fd53ee12ed0fd09e788518fe7df8eda2d389dc42).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-12-16 21:09 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-12-16 21:09 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70268/
Test FAILed.

2016-12-16 22:52 UTC, SparkQA commented
**[Test build #70281 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70281/testReport)** for PR 16282 at commit [`fd63513`](https://github.com/apache/spark/commit/fd63513d9e1ac3978f7ffe29382aff46ad86027b).

2016-12-16 22:52 UTC, SparkQA commented
**[Test build #70262 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70262/testReport)** for PR 16282 at commit [`7b75dd6`](https://github.com/apache/spark/commit/7b75dd6a6213441a51d6c58b230d4e52097595ea).
 * This patch **fails from timeout after a configured wait of \`250m\`**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-12-16 22:52 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-12-16 22:52 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70262/
Test FAILed.

2016-12-16 23:36 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-12-16 23:36 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70266/
Test FAILed.

2016-12-17 01:39 UTC, SparkQA commented
**[Test build #70281 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70281/testReport)** for PR 16282 at commit [`fd63513`](https://github.com/apache/spark/commit/fd63513d9e1ac3978f7ffe29382aff46ad86027b).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-12-17 01:40 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-12-17 01:40 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70281/
Test PASSed.

2016-12-17 06:19 UTC, zsxwing commented
retest this please

2016-12-17 06:22 UTC, SparkQA commented
**[Test build #70297 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70297/testReport)** for PR 16282 at commit [`fd63513`](https://github.com/apache/spark/commit/fd63513d9e1ac3978f7ffe29382aff46ad86027b).

2016-12-17 08:05 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-12-17 08:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70297/
Test FAILed.

2016-12-17 20:28 UTC, zsxwing commented
retest this please

2016-12-19 07:02 UTC, zsxwing commented
SPARK-18907

2016-12-19 07:02 UTC, zsxwing commented
retest this please

2016-12-19 07:07 UTC, SparkQA commented
**[Test build #70343 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70343/testReport)** for PR 16282 at commit [`fd63513`](https://github.com/apache/spark/commit/fd63513d9e1ac3978f7ffe29382aff46ad86027b).

2016-12-19 08:05 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-12-19 18:38 UTC, zsxwing commented
retest this please

2016-12-19 18:42 UTC, SparkQA commented
**[Test build #70370 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70370/testReport)** for PR 16282 at commit [`fd63513`](https://github.com/apache/spark/commit/fd63513d9e1ac3978f7ffe29382aff46ad86027b).

2016-12-19 21:25 UTC, SparkQA commented
**[Test build #70370 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70370/testReport)** for PR 16282 at commit [`fd63513`](https://github.com/apache/spark/commit/fd63513d9e1ac3978f7ffe29382aff46ad86027b).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-12-19 21:26 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-12-19 21:26 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70370/
Test PASSed.

2016-12-19 22:57 UTC, zsxwing commented
cc @tdas

2016-12-19 22:57 UTC, SparkQA commented
**[Test build #70386 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70386/testReport)** for PR 16282 at commit [`410c223`](https://github.com/apache/spark/commit/410c223cc89a669f86bc73693174a5c10c62b056).

2016-12-19 23:33 UTC, SparkQA commented
**[Test build #70386 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70386/testReport)** for PR 16282 at commit [`410c223`](https://github.com/apache/spark/commit/410c223cc89a669f86bc73693174a5c10c62b056).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `class KafkaSourceStressForDontFailOnDataLossSuite extends StreamTest with SharedSQLContext `

2016-12-19 23:34 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-12-19 23:34 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70386/
Test PASSed.

2016-12-20 21:41 UTC, brkyvz commented on external/kafka-0-10-sql/src/main/scala/org/apache/spark/sql/kafka010/KafkaSource.scala
> +        new KafkaConsumer[Array[Byte], Array[Byte]](kafkaParams)
nit: move to line above

2016-12-20 23:52 UTC, SparkQA commented
**[Test build #70439 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70439/testReport)** for PR 16282 at commit [`7c789e8`](https://github.com/apache/spark/commit/7c789e80255fbcb400eb2f62c959fed7ccb93455).

2016-12-21 01:00 UTC, tdas requested changes
Overall approach looks good. Few questions though.

2016-12-21 01:00 UTC, tdas commented on external/kafka-0-10-sql/src/main/scala/org/apache/spark/sql/kafka010/KafkaSource.scala
> +      val newKafkaParams = new ju.HashMap[String, Object](kafkaParams)
Nit: please dont reuse the name of the function as a variable. its confusing while reading code.

2016-12-21 01:00 UTC, tdas commented on external/kafka-0-10-sql/src/main/scala/org/apache/spark/sql/kafka010/KafkaSource.scala
> +    def newKafkaParams(
What is the need of this new method in ConsumerStrategy. Does not seem to be overridden or used any where?

2016-12-21 01:00 UTC, tdas commented on external/kafka-0-10-sql/src/main/scala/org/apache/spark/sql/kafka010/KafkaSource.scala
> -private[kafka010] case class KafkaSource(
But does hashcode use the toString to generate unique hashcode?

2016-12-21 01:00 UTC, tdas commented on external/kafka-0-10-sql/src/main/scala/org/apache/spark/sql/kafka010/KafkaSource.scala
> -private[kafka010] case class KafkaSource(
This is needed in StreamExecution for distinctSources, etc.

2016-12-21 01:00 UTC, tdas commented on external/kafka-0-10-sql/src/main/scala/org/apache/spark/sql/kafka010/KafkaSource.scala
> -private[kafka010] case class KafkaSource(
What is the performance concern here?

2016-12-21 01:22 UTC, zsxwing commented on external/kafka-0-10-sql/src/main/scala/org/apache/spark/sql/kafka010/KafkaSource.scala
> -private[kafka010] case class KafkaSource(
Shouldn't the default hashCode is enough?

2016-12-21 01:27 UTC, SparkQA commented
**[Test build #70443 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70443/testReport)** for PR 16282 at commit [`13b7d43`](https://github.com/apache/spark/commit/13b7d43422a60a1403153e95e4b1eb0106851594).

2016-12-21 01:35 UTC, zsxwing commented on dev/sparktestsupport/modules.py
> +        "external/kafka-0-10/",
Fixed this to avoid triggering dstream kafka tests

2016-12-21 01:37 UTC, SparkQA commented
**[Test build #70444 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70444/testReport)** for PR 16282 at commit [`9080acd`](https://github.com/apache/spark/commit/9080acd43f7568ba1b084ee892144a92f4cfa376).

2016-12-21 02:05 UTC, SparkQA commented
**[Test build #70443 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70443/testReport)** for PR 16282 at commit [`13b7d43`](https://github.com/apache/spark/commit/13b7d43422a60a1403153e95e4b1eb0106851594).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-12-21 02:05 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-12-21 02:05 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70443/
Test PASSed.

2016-12-21 02:21 UTC, tdas commented on dev/sparktestsupport/modules.py
> +        "external/kafka-0-10/",
Great!

2016-12-21 02:24 UTC, tdas commented on external/kafka-0-10-sql/src/main/scala/org/apache/spark/sql/kafka010/KafkaSource.scala
> -private[kafka010] case class KafkaSource(
the unique id of the object? maybe. I am not sure. if the same kafkaDF is used twice in a query (say, union two duplicate the data), will it actually create two distinct source objects, or reuse the same one. And in that case do we want them to match or not?

2016-12-21 04:02 UTC, SparkQA commented
**[Test build #70439 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70439/testReport)** for PR 16282 at commit [`7c789e8`](https://github.com/apache/spark/commit/7c789e80255fbcb400eb2f62c959fed7ccb93455).
 * This patch **fails from timeout after a configured wait of \`250m\`**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-12-21 04:03 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-12-21 04:03 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70439/
Test FAILed.

2016-12-21 05:47 UTC, SparkQA commented
**[Test build #70444 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70444/testReport)** for PR 16282 at commit [`9080acd`](https://github.com/apache/spark/commit/9080acd43f7568ba1b084ee892144a92f4cfa376).
 * This patch **fails from timeout after a configured wait of \`250m\`**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-12-21 05:48 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2016-12-21 05:48 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70444/
Test FAILed.

2016-12-21 18:54 UTC, zsxwing commented
> Test build #70439 has finished for PR 16282 at commit 7c789e8.

This is DStream failure: DirectKafkaStreamSuite

> Test build #70444 has finished for PR 16282 at commit 9080acd.

Looks like Python tests were hung. But that's not related to this PR.

2016-12-21 18:54 UTC, zsxwing commented
retest this please

2016-12-21 18:57 UTC, SparkQA commented
**[Test build #70486 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70486/testReport)** for PR 16282 at commit [`9080acd`](https://github.com/apache/spark/commit/9080acd43f7568ba1b084ee892144a92f4cfa376).

2016-12-21 21:44 UTC, SparkQA commented
**[Test build #70486 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/70486/testReport)** for PR 16282 at commit [`9080acd`](https://github.com/apache/spark/commit/9080acd43f7568ba1b084ee892144a92f4cfa376).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-12-21 21:46 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2016-12-21 21:46 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/70486/
Test PASSed.

2016-12-21 23:39 UTC, tdas commented
Merging to master and 2.1

2016-12-21 23:42 UTC, closed without merging