[SPARK-19003][DOCS] Add Java example in Spark Streaming Guide, section Design Patterns for using foreachRDD
apache/spark pull request #16408
Opened 2016-12-26 17:26 UTC by adesharatushar

## What changes were proposed in this pull request?

Added missing Java example under section "Design Patterns for using foreachRDD". Now this section has examples in all 3 languages, improving consistency of documentation.

## How was this patch tested?

Manual.
Generated docs using command "SKIP_API=1 jekyll build" and verified generated HTML page manually.

The syntax of example has been tested for correctness using sample code on Java1.7 and Spark 2.2.0-SNAPSHOT.

2016-12-26 17:27 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2016-12-27 20:46 UTC, srowen requested changes

2016-12-27 20:46 UTC, srowen commented on docs/streaming-programming-guide.md
> +  @Override public void call(JavaRDD<String> rdd) throws Exception {
Nits:

```
@Override
public ...
```

Don't `throws Exception`; remove or make more specific.

Extra space before new on next line.

2016-12-27 20:46 UTC, srowen commented on docs/streaming-programming-guide.md
> +        Connection connection = new Connection(connectionString);
Why is this different from the Scala example?

2016-12-27 20:46 UTC, srowen commented on docs/streaming-programming-guide.md
> +    final Connection connection =  new Connection(connectionString); // executed at the driver
Why make this different from Scala?

2016-12-28 09:54 UTC, adesharatushar commented
Thanks @srowen  for review and comments, made changes and committed on branch.

2016-12-28 10:03 UTC, srowen approved these changes

2016-12-28 10:04 UTC, SparkQA commented
**[Test build #3518 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3518/testReport)** for PR 16408 at commit [`ebb5e5d`](https://github.com/apache/spark/commit/ebb5e5d0c9df3c7415fe9739d82093a1105a40af).

2016-12-28 10:21 UTC, SparkQA commented
**[Test build #3518 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3518/testReport)** for PR 16408 at commit [`ebb5e5d`](https://github.com/apache/spark/commit/ebb5e5d0c9df3c7415fe9739d82093a1105a40af).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2016-12-29 22:04 UTC, srowen commented
Merged to master/2.1

2016-12-29 22:06 UTC, closed without merging