[SPARK-19162][PYTHON][SQL][WIP] UserDefinedFunction should validate that func is callable
apache/spark pull request #16535
Opened 2017-01-10 21:45 UTC by zero323

## What changes were proposed in this pull request?

UDF constructor checks if `func` argument is callable and if it is not, fails fast instead of waiting for an action.

## How was this patch tested?

Unit tests.

2017-01-10 21:47 UTC, SparkQA commented
**[Test build #71162 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71162/testReport)** for PR 16535 at commit [`5271bda`](https://github.com/apache/spark/commit/5271bda7b60db15f06c07f1f48c14a4eb6eb0d2e).

2017-01-10 22:24 UTC, SparkQA commented
**[Test build #71162 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71162/testReport)** for PR 16535 at commit [`5271bda`](https://github.com/apache/spark/commit/5271bda7b60db15f06c07f1f48c14a4eb6eb0d2e).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `                \"(a function or an instance of a class with __call__). \"`

2017-01-10 22:24 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-01-10 22:24 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/71162/
Test PASSed.

2017-01-11 00:16 UTC, rdblue requested changes

2017-01-11 00:16 UTC, rdblue commented on python/pyspark/sql/tests.py
> +        self.assertRaises(TypeError, udf)
I think this should have positive tests for a function and a class that defines `__call__`.

2017-01-11 00:16 UTC, rdblue commented on python/pyspark/sql/functions.py
> +                "func should be a callable object "
I think the error message could be more clear: "Not a function or callable (__call__ is not defined): {}"

I don't think it's necessary to use the name of the argument, but it isn't a problem if you think it is better.

2017-01-11 00:16 UTC, rdblue commented on python/pyspark/sql/tests.py
> +        self.assertRaises(TypeError, udf)
Why doesn't this test call udf?

2017-01-11 13:23 UTC, zero323 commented on python/pyspark/sql/tests.py
> +        self.assertRaises(TypeError, udf)
Different positive scenarios are quite well covered by the [existing tests](https://github.com/apache/spark/blob/master/python/pyspark/sql/tests.py#L271-L310).

`self.assertRaises` actually calls its argument when it is executed. But we should really test `UserDefinedFunction` directly here, not `udf`. Let me correct that.

2017-01-11 13:23 UTC, zero323 commented on python/pyspark/sql/functions.py
> +                "func should be a callable object "
Sounds good.

2017-01-11 13:33 UTC, SparkQA commented
**[Test build #71205 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71205/testReport)** for PR 16535 at commit [`d447f85`](https://github.com/apache/spark/commit/d447f85158b2c8055710ee6e4edcd1fe4164a11f).

2017-01-11 13:56 UTC, SparkQA commented
**[Test build #71205 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71205/testReport)** for PR 16535 at commit [`d447f85`](https://github.com/apache/spark/commit/d447f85158b2c8055710ee6e4edcd1fe4164a11f).
 * This patch **fails PySpark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-01-11 13:56 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-01-11 13:56 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/71205/
Test FAILed.

2017-01-11 14:13 UTC, SparkQA commented
**[Test build #71209 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71209/testReport)** for PR 16535 at commit [`e24cd90`](https://github.com/apache/spark/commit/e24cd90c4d86867e5920ef137b72469dafda5c5a).

2017-01-11 14:42 UTC, SparkQA commented
**[Test build #71209 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71209/testReport)** for PR 16535 at commit [`e24cd90`](https://github.com/apache/spark/commit/e24cd90c4d86867e5920ef137b72469dafda5c5a).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-01-11 14:42 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-01-11 14:42 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/71209/
Test PASSed.

2017-01-11 17:22 UTC, rdblue commented on python/pyspark/sql/tests.py
> +        self.assertRaises(TypeError, udf)
Sorry if my wording was confusing. My point was that it called `udf` as a test method without arguments, which isn't the call you wanted to test. The update that passes `non_callable` is what I was looking for.

2017-01-11 17:26 UTC, rdblue commented
+1. Thanks for working on this @zero323!

2017-01-11 19:52 UTC, zero323 commented
@rdblue Thank you for taking your time to review this.

2017-01-19 23:12 UTC, SparkQA commented
**[Test build #71677 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71677/testReport)** for PR 16535 at commit [`f7ec316`](https://github.com/apache/spark/commit/f7ec3167829fdfac0b8f0804917411030dc6f796).

2017-01-19 23:48 UTC, SparkQA commented
**[Test build #71677 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71677/testReport)** for PR 16535 at commit [`f7ec316`](https://github.com/apache/spark/commit/f7ec3167829fdfac0b8f0804917411030dc6f796).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-01-19 23:49 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-01-19 23:49 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/71677/
Test PASSed.

2017-01-20 00:48 UTC, SparkQA commented
**[Test build #71684 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71684/testReport)** for PR 16535 at commit [`23d9c9d`](https://github.com/apache/spark/commit/23d9c9da3663ea7ce30971ff3feaaff4800e9894).

2017-01-20 01:19 UTC, SparkQA commented
**[Test build #71684 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71684/testReport)** for PR 16535 at commit [`23d9c9d`](https://github.com/apache/spark/commit/23d9c9da3663ea7ce30971ff3feaaff4800e9894).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-01-20 01:20 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-01-20 01:20 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/71684/
Test PASSed.

2017-01-26 19:46 UTC, holdenk commented
So I generally agree improved error messages are a good thing - but is this something which people have run into often? Trying to create a UDF with something that ins't callable seems like an not a super common error?

If this is something we want to do - the follow up question is would we want to instead move the check inside of the prepare function so the improved error message would surface for people which try and do RDD transformations without calleable objects as well.

2017-01-26 20:55 UTC, zero323 commented
@holdenk I admit this is probably not the most common issue :) but taken together, all cases when we could fail fast, and instead we let it happen on JVM or worker interpreter, significantly degrade user experience. Both Py4J tracebacks and stuff we get from the workers, interleaved with many pages of JVM junk, seem to be completely unreadable for many users.

So my opinion is that if we can fail fast (without triggering Spark job), fail cheap (without significant runtime overhead or unnecessary limitations) and provide meaningful feedback (if exactly know what type is expected) then we should. I wouldn't bother with this alone, but if are already messing with UDF it is just a good opportunity to make things  a little bit better.

2017-02-01 11:43 UTC, SparkQA commented
**[Test build #72243 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72243/testReport)** for PR 16535 at commit [`b3a83f0`](https://github.com/apache/spark/commit/b3a83f0cbf36e86ad333f2dd0e5ba1e855189465).

2017-02-01 12:12 UTC, SparkQA commented
**[Test build #72243 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72243/testReport)** for PR 16535 at commit [`b3a83f0`](https://github.com/apache/spark/commit/b3a83f0cbf36e86ad333f2dd0e5ba1e855189465).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-02-01 12:13 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-02-01 12:13 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/72243/
Test PASSed.

2017-02-12 19:53 UTC, nchammas approved these changes
This seems like a solid improvement, though I agree with @holdenk that it seems like an unlikely scenario. Still, piecing through Java stack traces is never fun.

2017-02-13 21:28 UTC, SparkQA commented
**[Test build #72831 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72831/testReport)** for PR 16535 at commit [`7d350bf`](https://github.com/apache/spark/commit/7d350bfe8f871f1b2557d7dc3c5e8e4017636b37).

2017-02-13 22:02 UTC, SparkQA commented
**[Test build #72831 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72831/testReport)** for PR 16535 at commit [`7d350bf`](https://github.com/apache/spark/commit/7d350bfe8f871f1b2557d7dc3c5e8e4017636b37).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-02-13 22:02 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-02-13 22:02 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/72831/
Test PASSed.

2017-02-14 17:45 UTC, holdenk commented
looks good to me. I'll merge this to master since it helps with fast fail but in the future I'd appreciate it if you gave some thought as to how to do these in bigger chunks so we don't have a large number one-off PRs for the same type of issue (as discussed on the other thread).

2017-02-14 17:48 UTC, closed without merging

2017-02-14 17:49 UTC, holdenk commented
Merged to master.