[SPARK-19267][SS]Fix a race condition when stopping StateStore
apache/spark pull request #16627
Opened 2017-01-18 00:35 UTC by zsxwing

## What changes were proposed in this pull request?

There is a race condition when stopping StateStore which makes `StateStoreSuite.maintenance` flaky. `StateStore.stop` doesn't wait for the running task to finish, and an out-of-date task may fail `doMaintenance` and cancel the new task. Here is a reproducer: https://github.com/zsxwing/spark/commit/dde1b5b106ba034861cf19e16883cfe181faa6f3

This PR changes `stop` to `stop(blocking: Boolean = true)` to allow the caller waiting until the background thread exits.

## How was this patch tested?

Jenkins

2017-01-18 00:37 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/StateStore.scala
>      if (SparkEnv.get == null) {
There is another potential issue here: if a SparkContext is created after checking `SparkEnv.get == null`, the following `stop` may cancel a new valid task. However, I think that won't happen in practice, so don't fix it.

2017-01-18 00:37 UTC, SparkQA commented
**[Test build #71545 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71545/testReport)** for PR 16627 at commit [`5fa096c`](https://github.com/apache/spark/commit/5fa096c3e11285429100155cdfeb8cc50ef653a8).

2017-01-18 03:01 UTC, SparkQA commented
**[Test build #71545 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71545/testReport)** for PR 16627 at commit [`5fa096c`](https://github.com/apache/spark/commit/5fa096c3e11285429100155cdfeb8cc50ef653a8).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-01-18 03:02 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-01-18 03:02 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/71545/
Test PASSed.

2017-01-19 00:28 UTC, SparkQA commented
**[Test build #71624 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71624/testReport)** for PR 16627 at commit [`4e6b89b`](https://github.com/apache/spark/commit/4e6b89bae8c927fcdea3c324a0aa95d3b479b2bd).

2017-01-19 02:40 UTC, SparkQA commented
**[Test build #71624 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71624/testReport)** for PR 16627 at commit [`4e6b89b`](https://github.com/apache/spark/commit/4e6b89bae8c927fcdea3c324a0aa95d3b479b2bd).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-01-19 02:41 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-01-19 02:41 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/71624/
Test PASSed.

2017-01-19 03:17 UTC, tdas requested changes
I had a more surgical fix in mind when I said that put multiple volatile objects into a class so that we can replace the class completely. Here is what I had in mind. 

https://github.com/apache/spark/compare/master...tdas:state-store-fix?expand=1

What do you think?

2017-01-20 19:58 UTC, SparkQA commented
**[Test build #71739 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71739/testReport)** for PR 16627 at commit [`cbcd6e8`](https://github.com/apache/spark/commit/cbcd6e8ef715cd09389284020f6c49587318869a).

2017-01-20 19:58 UTC, zsxwing commented
@tdas could you take another look? I fixed some minor issues in your patch.

2017-01-20 21:55 UTC, tdas reviewed
Mostly LGTM.

2017-01-20 21:55 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/StateStore.scala
> +  class MaintenanceTask(periodMs: Long, task: => Unit, onError: => Unit) {
Can you add docs.

2017-01-20 21:55 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/StateStore.scala
> +  class MaintenanceTask(periodMs: Long, task: => Unit, onError: => Unit) {
you should mention the properties of this class. that it automatically cancels the periodic task if there is an exception. and what is onError for.

2017-01-20 21:55 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/StateStore.scala
> +    if (env != null && (maintenanceTask == null || !maintenanceTask.isRunning)) {
Can you replace this with the method isMaintenanceRunning?

2017-01-20 22:16 UTC, SparkQA commented
**[Test build #71739 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71739/testReport)** for PR 16627 at commit [`cbcd6e8`](https://github.com/apache/spark/commit/cbcd6e8ef715cd09389284020f6c49587318869a).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-01-20 22:18 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-01-20 22:18 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/71739/
Test PASSed.

2017-01-20 22:49 UTC, SparkQA commented
**[Test build #71744 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71744/testReport)** for PR 16627 at commit [`d66f8d7`](https://github.com/apache/spark/commit/d66f8d74ac675796254105de7397bb7b6b3c960e).

2017-01-21 00:27 UTC, tdas commented
LGTM, pending tests.

2017-01-21 01:18 UTC, SparkQA commented
**[Test build #71744 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71744/testReport)** for PR 16627 at commit [`d66f8d7`](https://github.com/apache/spark/commit/d66f8d74ac675796254105de7397bb7b6b3c960e).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-01-21 01:20 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-01-21 01:20 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/71744/
Test PASSed.

2017-01-21 01:50 UTC, closed without merging