[SPARK-19234][MLLib] AFTSurvivalRegression should fail fast when any labels are zero
apache/spark pull request #16652
Opened 2017-01-20 04:55 UTC by admackin

## What changes were proposed in this pull request?

If any labels of 0.0 (which are invalid) are supplied, AFTSurvivalRegression gives an error straight away rather than hard-to-interpret warnings and zero-valued coefficients in the output.

## How was this patch tested?

Verified against current test suite. (One test needed to be updated as it was providing values of zero for labels so was failing after this patch)

Please review http://spark.apache.org/contributing.html before opening a pull request.

2017-01-20 04:58 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-01-20 11:40 UTC, srowen requested changes

2017-01-20 11:40 UTC, srowen commented on mllib/src/test/scala/org/apache/spark/ml/regression/AFTSurvivalRegressionSuite.scala
> -
(Leave the blank)

2017-01-20 11:40 UTC, srowen commented on mllib/src/test/scala/org/apache/spark/ml/regression/AFTSurvivalRegressionSuite.scala
> +  private[AFTSurvivalRegressionSuite] def checkNumericTypes[M <: Model[M], T <: Estimator[M]](
This is being copied in from MLUtils? why is it necessary?

2017-01-21 07:35 UTC, admackin commented
Yes, the version in MLUtils had labels of zero in the test cases, so was causing test cases to fail after my patch. It didn't look like there was a way to fix this, so I thought it better to make a patch that didn't affect potentially dozens of other packages. Any other thoughts on how to achieve this? I could add a 'minLabel' param to the MLUtils methods but that seems overly specific for this one package.

2017-01-21 14:06 UTC, srowen commented
I imagine there's a better way to do this without copying code. Do you mean the common test code assumes 0 labels are permitted? then maybe it should just not do that, because it's just using any old value to test.

If it doesn't actually assume 0 labels are permitted, then its logic should still work. It's just that this test would need some additional logic to verify that 0 labels cause an exception.

2017-01-21 23:36 UTC, admackin commented
Yes that’s right, in MLUtils it supplies zero-labels as test cases (ie assumes they’re allowed, which for other regression algorithms would be true). More than happy to patch that instead though if you think that’s OK – it’ll just affect presumably a lot of other test cases.

Verifying the 0-labels cause exceptions isn’t yet covered, but probably should be (separately to MLUtils). (I’ll just need to find out how to assert thrown errors in the Spark testing)

On 22 Jan 2017, 01:07 +1100, Sean Owen <notifications@github.com>, wrote:
> I imagine there's a better way to do this without copying code. Do you mean the common test code assumes 0 labels are permitted? then maybe it should just not do that, because it's just using any old value to test.
> If it doesn't actually assume 0 labels are permitted, then its logic should still work. It's just that this test would need some additional logic to verify that 0 labels cause an exception.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.((

2017-01-22 11:01 UTC, srowen commented
It looks like there is no particular reason that `("0", Vectors.dense(0, 2, 3), 0.0)` really needs to set a 0 value as the label. You could make it 1 and see that it still passes all tests.

2017-01-22 11:07 UTC, SparkQA commented
**[Test build #3544 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3544/testReport)** for PR 16652 at commit [`b07c281`](https://github.com/apache/spark/commit/b07c281c378d68d86b81498ca247c7346719973e).

2017-01-22 11:08 UTC, SparkQA commented
**[Test build #3544 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3544/testReport)** for PR 16652 at commit [`b07c281`](https://github.com/apache/spark/commit/b07c281c378d68d86b81498ca247c7346719973e).
 * This patch **fails Scala style tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-01-23 06:51 UTC, admackin commented
I've addressed all the problems I think – code style now fixed, MLTestingUtils patched (and verified all MLLib test cases still pass), and added a test case for zero-valued labels

2017-01-24 11:37 UTC, srowen commented
This is looking OK to me, but it needs a (squash, optionally, and) rebase now before it can test again.

2017-01-26 10:19 UTC, SparkQA commented
**[Test build #3551 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3551/testReport)** for PR 16652 at commit [`cfdd286`](https://github.com/apache/spark/commit/cfdd28649b1d83bfcb63cfc7b5389470125d2cad).

2017-01-26 10:22 UTC, SparkQA commented
**[Test build #3551 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3551/testReport)** for PR 16652 at commit [`cfdd286`](https://github.com/apache/spark/commit/cfdd28649b1d83bfcb63cfc7b5389470125d2cad).
 * This patch **fails Scala style tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-01-30 12:59 UTC, srowen commented on mllib/src/test/scala/org/apache/spark/ml/regression/AFTSurvivalRegressionSuite.scala
> -
This is still causing a style check failure @admackin

2017-01-30 19:10 UTC, imatiach-msft commented on mllib/src/test/scala/org/apache/spark/ml/regression/AFTSurvivalRegressionSuite.scala
> +    intercept[SparkException] {
it's recommended to verify the error message using withClue, eg:
withClue("label of AFTPoint must be positive") {
     intercept[SparkException] { 
        aft.fit(dataset)
     }
}

2017-01-30 19:11 UTC, imatiach-msft commented
looks good to me too.  I just added a small suggestion.  Thanks!

2017-02-02 12:31 UTC, SparkQA commented
**[Test build #3552 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3552/testReport)** for PR 16652 at commit [`c855976`](https://github.com/apache/spark/commit/c855976dd2806cd7e8fd13f46d120f229f7ff6cd).

2017-02-02 13:19 UTC, SparkQA commented
**[Test build #3552 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3552/testReport)** for PR 16652 at commit [`c855976`](https://github.com/apache/spark/commit/c855976dd2806cd7e8fd13f46d120f229f7ff6cd).
 * This patch **fails PySpark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-02-04 11:18 UTC, SparkQA commented
**[Test build #3554 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3554/testReport)** for PR 16652 at commit [`c855976`](https://github.com/apache/spark/commit/c855976dd2806cd7e8fd13f46d120f229f7ff6cd).

2017-02-04 13:48 UTC, SparkQA commented
**[Test build #3554 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3554/testReport)** for PR 16652 at commit [`c855976`](https://github.com/apache/spark/commit/c855976dd2806cd7e8fd13f46d120f229f7ff6cd).
 * This patch **fails PySpark unit tests**.
 * This patch **does not merge cleanly**.
 * This patch adds no public classes.

2017-02-07 11:51 UTC, srowen commented
The core change is looking OK @admackin but seems like it fails Python tests? if you have a moment to look at that, could be all that's needed to get this over the line.

2017-05-11 14:15 UTC, HyukjinKwon commented
gentle ping @admackin

2017-05-18 08:02 UTC, closed without merging