[SPARK-19347] ReceiverSupervisorImpl can add block to ReceiverTracker multiple times because of askWithRetry.
apache/spark pull request #16690
Opened 2017-01-24 09:45 UTC by jinxing64

## What changes were proposed in this pull request?

`ReceiverSupervisorImpl` on executor side reports block's meta back to `ReceiverTracker` on driver side. In current code, `askWithRetry` is used. However, for `AddBlock`, `ReceiverTracker` is not idempotent, which may result in messages are processed multiple times.

*To reproduce*:
1. Check if it is the first time receiving `AddBlock` in `ReceiverTracker`, if so sleep long enough(say 200 seconds), thus the first RPC call will be timeout in `askWithRetry`, then `AddBlock` will be resent.
2. Rebuild Spark and run following job:
```
  def streamProcessing(): Unit = {
    val conf = new SparkConf()
      .setAppName("StreamingTest")
      .setMaster(masterUrl)
    val ssc = new StreamingContext(conf, Seconds(200))
    val stream = ssc.socketTextStream("localhost", 1234)
    stream.print()
    ssc.start()
    ssc.awaitTermination()
  }
```
To fix:
It makes sense to provide a blocking version `ask` in RpcEndpointRef, as mentioned in SPARK-18113 (https://github.com/apache/spark/pull/16503#event-927953218). Because Netty RPC layer will not drop messages. `askWithRetry` is a leftover from akka days. It imposes restrictions on the caller(e.g. idempotency) and other things that people generally don't pay that much attention to when using it.

## How was this patch tested?
Test manually. The scenario described above doesn't happen with this patch.
Please review http://spark.apache.org/contributing.html before opening a pull request.

2017-01-24 09:47 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-01-24 16:26 UTC, squito commented
Jenkins, ok to test

2017-01-24 16:27 UTC, SparkQA commented
**[Test build #71938 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71938/testReport)** for PR 16690 at commit [`ce5216e`](https://github.com/apache/spark/commit/ce5216eb09b58f95c2f9c045c47b33ef5138e963).

2017-01-24 16:31 UTC, squito commented
cc @vanzin @zsxwing 

(I was going to make a longer comment about removing `askWithRetry` and whether we need another method, but then saw the comments on the referenced PR -- I'll defer to the experts here)

2017-01-24 18:24 UTC, SparkQA commented
**[Test build #71938 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/71938/testReport)** for PR 16690 at commit [`ce5216e`](https://github.com/apache/spark/commit/ce5216eb09b58f95c2f9c045c47b33ef5138e963).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-01-24 18:25 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-01-24 18:25 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/71938/
Test FAILed.

2017-01-26 16:12 UTC, SparkQA commented
**[Test build #72027 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72027/testReport)** for PR 16690 at commit [`fe86511`](https://github.com/apache/spark/commit/fe8651199a60bb579108247b68e56b3a44e6136b).

2017-01-26 20:22 UTC, SparkQA commented
**[Test build #72027 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72027/testReport)** for PR 16690 at commit [`fe86511`](https://github.com/apache/spark/commit/fe8651199a60bb579108247b68e56b3a44e6136b).
 * This patch **fails from timeout after a configured wait of \`250m\`**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-01-26 20:23 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-01-26 20:23 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/72027/
Test FAILed.

2017-01-27 00:18 UTC, SparkQA commented
**[Test build #72057 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72057/testReport)** for PR 16690 at commit [`3b7e17b`](https://github.com/apache/spark/commit/3b7e17ba3a2db650b83b0f8d161754bfe53ca31a).

2017-01-27 02:47 UTC, SparkQA commented
**[Test build #72057 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72057/testReport)** for PR 16690 at commit [`3b7e17b`](https://github.com/apache/spark/commit/3b7e17ba3a2db650b83b0f8d161754bfe53ca31a).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-01-27 02:48 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-01-27 02:48 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/72057/
Test PASSed.

2017-01-27 03:33 UTC, jinxing64 commented
@vanzin @zsxwing 
ping for review~

2017-01-27 21:52 UTC, vanzin requested changes
Also, since you're adding the blocking API, please add a deprecation annotation to `askWithRetry`.

2017-01-27 21:52 UTC, vanzin commented on core/src/main/scala/org/apache/spark/rpc/RpcEndpointRef.scala
> +
nit: don't add.

2017-01-27 21:52 UTC, vanzin commented on core/src/main/scala/org/apache/spark/rpc/RpcEndpointRef.scala
> +  def askWithBlocking[T: ClassTag](message: Any): T = askWithBlocking(message, defaultAskTimeout)
`askWithBlocking` is a weird name. I'd use `blockingAsk`, or `askSync`.

2017-01-27 21:52 UTC, vanzin commented on core/src/main/scala/org/apache/spark/rpc/RpcEndpointRef.scala
> +      if (result == null) {
This is not an error. It's perfectly legitimate to return null.

2017-01-27 21:52 UTC, vanzin commented on core/src/main/scala/org/apache/spark/rpc/RpcEndpointRef.scala
> +        throw new SparkException(
Isn't it better to just propagate the original exception? You can get the context from the stack trace.

2017-01-28 15:58 UTC, SparkQA commented
**[Test build #72107 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72107/testReport)** for PR 16690 at commit [`e7002c1`](https://github.com/apache/spark/commit/e7002c13d0f9f19bcbec3de75560abf53f903bb2).

2017-01-28 18:29 UTC, SparkQA commented
**[Test build #72107 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72107/testReport)** for PR 16690 at commit [`e7002c1`](https://github.com/apache/spark/commit/e7002c13d0f9f19bcbec3de75560abf53f903bb2).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-01-28 18:31 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-01-28 18:31 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/72107/
Test PASSed.

2017-01-30 11:14 UTC, jinxing64 commented
@vanzin 
ping for review

2017-01-30 18:02 UTC, vanzin commented
> ping for review

Please be a little more patient, especially during weekends.

2017-01-30 23:46 UTC, jinxing64 commented
I feel very sorry if this is disturbing : )
@vanzin Thanks a lot for continuing reviewing this and I'll be more patient : )
Sorry again~~

2017-01-31 19:20 UTC, vanzin approved these changes
Looks good, just need to fix the versions.

2017-01-31 19:20 UTC, vanzin commented on core/src/main/scala/org/apache/spark/rpc/RpcEndpointRef.scala
> +  @deprecated("use 'askSync' instead.", "2.1.0")
2.2.0

2017-01-31 19:20 UTC, vanzin commented on core/src/main/scala/org/apache/spark/rpc/RpcEndpointRef.scala
> +  @deprecated("use 'askSync' instead.", "2.1.0")
2.2.0

2017-01-31 19:20 UTC, vanzin commented on core/src/main/scala/org/apache/spark/rpc/RpcEndpointRef.scala
> +import scala.util.control.NonFatal
not used

2017-02-01 03:47 UTC, SparkQA commented
**[Test build #72228 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72228/testReport)** for PR 16690 at commit [`42eb540`](https://github.com/apache/spark/commit/42eb540f8617ee3dc22c81014452896eedec97a3).

2017-02-01 06:25 UTC, SparkQA commented
**[Test build #72228 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72228/testReport)** for PR 16690 at commit [`42eb540`](https://github.com/apache/spark/commit/42eb540f8617ee3dc22c81014452896eedec97a3).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-02-01 06:26 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-02-01 06:26 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/72228/
Test PASSed.

2017-02-01 10:04 UTC, jinxing64 commented
@vanzin 
Thanks a lot for helping this PR~ I've already refined~
Please take another look~

2017-02-01 21:53 UTC, vanzin commented
LGTM, merging to master.

2017-02-01 21:57 UTC, closed without merging

2017-02-02 02:29 UTC, jinxing64 commented
Thanks a lot for reviewing this PR~

2017-02-16 20:18 UTC, srowen commented on core/src/main/scala/org/apache/spark/rpc/RpcEndpointRef.scala
> +  @deprecated("use 'askSync' instead.", "2.2.0")
It seems like this has caused the build to produce a lot of deprecation warnings. @jinxing64 could the callers of this method be changed, in Spark, to use the new alternative?

2017-02-17 02:18 UTC, jinxing64 commented
@srowen 
How do you think about https://github.com/apache/spark/pull/16790?