[SPARK-19378][SS] Ensure continuity of stateOperator and eventTime metrics even if there is no new data in trigger
apache/spark pull request #16716
Opened 2017-01-27 00:43 UTC by brkyvz

## What changes were proposed in this pull request?

In StructuredStreaming, if a new trigger was skipped because no new data arrived, we suddenly report nothing for the metrics `stateOperator` and `eventTime`. We could however easily report the metrics from `lastExecution` to ensure continuity of metrics.

## How was this patch tested?

Regression test in `StreamingQueryStatusAndProgressSuite`

2017-01-27 00:48 UTC, SparkQA commented
**[Test build #72059 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72059/testReport)** for PR 16716 at commit [`884a789`](https://github.com/apache/spark/commit/884a7893f5ae0c388ee79b04f92f62757b8aaea0).

2017-01-27 00:56 UTC, tdas commented on sql/core/src/test/scala/org/apache/spark/sql/streaming/StreamingQueryStatusAndProgressSuite.scala
> +          assert(nextProgress.timestamp !== progress.timestamp)
can you explicitly verify that this progress has no data?

2017-01-27 00:57 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/ProgressReporter.scala
> +   * SPARK-19378: Still report stateOperator metrics even though no data was processed while
Does not make sense to have jira numbers in a methods scala docs.

2017-01-27 01:01 UTC, tdas requested changes
Approach looks good, but need some cleanup and better test.

2017-01-27 01:01 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/ProgressReporter.scala
> +   * SPARK-19378: Still report eventTime metrics even though no data was processed while
Same here.

2017-01-27 01:01 UTC, tdas commented on sql/core/src/test/scala/org/apache/spark/sql/streaming/StreamingQueryStatusAndProgressSuite.scala
> +          assert(progress.stateOperators.length > 0)
you are not verifying that that the metric values are as expected.

2017-01-27 01:01 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/ProgressReporter.scala
> +  private def extractEventTimeStats(watermarkTs: Map[String, String]): Map[String, String] = {
it does not make sense for this method to take this watermarkTs as a param. its not extracting event time states from watermark ts, its just appending it. Then why not just return empty map, and do the appending outside? Or do the extraction of watermark inside the function as well.

2017-01-27 01:22 UTC, SparkQA commented
**[Test build #72061 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72061/testReport)** for PR 16716 at commit [`55e3d36`](https://github.com/apache/spark/commit/55e3d3643c856ddf4f43a12c0b74953d4baec80d).

2017-01-27 01:30 UTC, brkyvz commented
@tdas Addressed

2017-01-27 03:04 UTC, SparkQA commented
**[Test build #72061 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72061/testReport)** for PR 16716 at commit [`55e3d36`](https://github.com/apache/spark/commit/55e3d3643c856ddf4f43a12c0b74953d4baec80d).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-01-27 03:05 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-01-27 03:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/72061/
Test FAILed.

2017-01-27 03:12 UTC, SparkQA commented
**[Test build #72059 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72059/testReport)** for PR 16716 at commit [`884a789`](https://github.com/apache/spark/commit/884a7893f5ae0c388ee79b04f92f62757b8aaea0).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-01-27 03:13 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-01-27 03:13 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/72059/
Test PASSed.

2017-01-27 03:28 UTC, tdas commented on sql/core/src/test/scala/org/apache/spark/sql/streaming/StreamingQueryStatusAndProgressSuite.scala
> +          assert(nextProgress.eventTime.get("min") === "2017-01-26 01:00:00")
This does not make sense. if there is no data in the last trigger, the min, max, avg timestamps cannot be different. 
and what about the watermark?

2017-01-27 04:00 UTC, brkyvz commented on sql/core/src/test/scala/org/apache/spark/sql/streaming/StreamingQueryStatusAndProgressSuite.scala
> +          assert(nextProgress.eventTime.get("min") === "2017-01-26 01:00:00")
Oh shoot. I should definitely leave those out because they are trigger specific right?
I should only keep the stateOperator part

2017-01-27 04:02 UTC, SparkQA commented
**[Test build #72064 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72064/testReport)** for PR 16716 at commit [`e23de4a`](https://github.com/apache/spark/commit/e23de4ad5adae6a79a0b081344ba2bf575ec6d8c).

2017-01-27 06:16 UTC, SparkQA commented
**[Test build #72064 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72064/testReport)** for PR 16716 at commit [`e23de4a`](https://github.com/apache/spark/commit/e23de4ad5adae6a79a0b081344ba2bf575ec6d8c).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-01-27 06:17 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-01-27 06:17 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/72064/
Test PASSed.

2017-01-28 02:06 UTC, tdas commented on sql/core/src/test/scala/org/apache/spark/sql/streaming/StreamingQueryStatusAndProgressSuite.scala
> +          assert(nextProgress.stateOperators.head.numRowsTotal === 2)
why is this line twice?

2017-01-30 20:29 UTC, brkyvz commented
@tdas addressed

2017-01-30 20:33 UTC, SparkQA commented
**[Test build #72168 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72168/testReport)** for PR 16716 at commit [`0b9fcfc`](https://github.com/apache/spark/commit/0b9fcfc6babc3bce0238be0716437275bb9e3a72).

2017-01-30 23:00 UTC, SparkQA commented
**[Test build #72168 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72168/testReport)** for PR 16716 at commit [`0b9fcfc`](https://github.com/apache/spark/commit/0b9fcfc6babc3bce0238be0716437275bb9e3a72).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-01-30 23:01 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-01-30 23:01 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/72168/
Test PASSed.

2017-02-01 00:55 UTC, closed without merging