[SPARK-19527][Core] Approximate Size of Intersection of Bloom Filters
apache/spark pull request #16864
Opened 2017-02-09 02:14 UTC by Bcpoole

**What changes were proposed in this pull request?**

Added functions to get the Swamidass & Baldi (2007) approximation for number of items in a Bloom filter and the intersections of two filters. Added an exception type IncompatibleUnionException mimicing IncompatibleMergeException. As needed for the intersection approximation, there is a function that create the union of two Bloom filters (no mutations).

**How was this patch tested?**

Manual Tests

2017-02-09 02:18 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-02-09 09:25 UTC, rxin commented on common/sketch/src/main/java/org/apache/spark/util/sketch/IncompatibleUnionException.java
> +public class IncompatibleUnionException extends Exception {
we need some javadoc ere.

2017-02-09 09:26 UTC, rxin commented on common/sketch/src/main/java/org/apache/spark/util/sketch/BloomFilter.java
> +  public abstract BloomFilterImpl createUnionBloomFilter(BloomFilter other) throws IncompatibleUnionException;
how about just calling this union?

2017-02-09 09:26 UTC, rxin commented on common/sketch/src/main/java/org/apache/spark/util/sketch/BloomFilter.java
> +  public abstract double approxItems();
shouldn't this return a long rather than a double?

2017-02-09 09:26 UTC, rxin commented
cc @mengxr / @tjhunter / @jkbradley  is this good to have?

2017-02-09 18:44 UTC, rxin commented
I meant just union, but createUnion ...

2017-02-09 18:50 UTC, Bcpoole commented on common/sketch/src/main/java/org/apache/spark/util/sketch/IncompatibleUnionException.java
> +public class IncompatibleUnionException extends Exception {
In that case IncompatibleMergeException needs it too :)

2017-02-09 19:06 UTC, Bcpoole commented on common/sketch/src/main/java/org/apache/spark/util/sketch/BloomFilter.java
> +  public abstract double approxItems();
I was debating this due to possible rounding errors.

2017-02-10 10:00 UTC, rxin commented on common/sketch/src/main/java/org/apache/spark/util/sketch/BloomFilter.java
> +  public abstract double approxItems();
yea but that would only be off by 1. I wouldn't worry about that since it is approximate anyway.

2017-02-10 16:34 UTC, mengxr requested changes

2017-02-10 16:34 UTC, mengxr commented on common/sketch/src/main/java/org/apache/spark/util/sketch/BloomFilter.java
> +   * Swamidass & Baldi (2007) approximation for number of items in a Bloom filter
Please describe the method first and its properties (approximation error).  Then put the reference in `@seealso` with a permanent link to the paper: https://dx.doi.org/10.1021%2Fci600526a

2017-02-10 16:34 UTC, mengxr commented on common/sketch/src/main/java/org/apache/spark/util/sketch/BloomFilter.java
> +  public abstract double approxItems();
It might be easier to keep it as double because the estimate could be out of bound if the bits are full.

2017-02-10 16:34 UTC, mengxr commented on common/sketch/src/main/java/org/apache/spark/util/sketch/BloomFilter.java
> +   * Swamidass & Baldi (2007) approximation for number of items in the intersection of two Bloom filters
* Same here. Document the method first and then mention the reference.
* How is it different from intersecting two bloom filters and then estimate the number of items? Union might lead to larger approximation error.

2017-02-10 16:34 UTC, mengxr commented on common/sketch/src/main/java/org/apache/spark/util/sketch/BloomFilterImpl.java
> +    return (-m / numHashFunctions) * Math.log(1 - (bits.cardinality() / m));
* `Math` is deprecated. Use `math`.
* Please add a test when `bits` is full. This should return `Double.Infinity`.

2017-02-10 21:11 UTC, Bcpoole commented on common/sketch/src/main/java/org/apache/spark/util/sketch/BloomFilterImpl.java
> +    return (-m / numHashFunctions) * Math.log(1 - (bits.cardinality() / m));
> Math is deprecated. Use math.

Assume you were thinking of Scala?

2017-02-14 00:17 UTC, Bcpoole reviewed
Believe requested changes were all handled

2017-06-19 15:01 UTC, jiangxb1987 commented
ping @mengxr Should we move forward with this PR?

2017-06-19 15:02 UTC, jiangxb1987 commented
retest this please

2017-06-23 21:36 UTC, Bcpoole commented
Looks good

2017-09-02 03:08 UTC, WeichenXu123 commented
@Bcpoole Thanks for this PR. But I want to ask which place in spark can this extension apply to ? e.g. can this algo used in join cost estimating or somewhere else ? But if there is no apparent uses for now, I will decrease priority of reviewing this because there're many PRs accumulated waiting review.

2017-10-03 14:32 UTC, jiangxb1987 commented
Should we close this PR since it goes stale? WDYT @WeichenXu123 ?

2017-11-06 11:15 UTC, WeichenXu123 commented
@jiangxb1987 yes I agree to close it.

2017-11-07 09:00 UTC, closed without merging