[SPARK-19582][SPARKR] Allow to disable hive in sparkR shell
apache/spark pull request #16907
Opened 2017-02-13 05:54 UTC by zjffdu

## What changes were proposed in this pull request?
SPARK-15236 do this for scala shell, this ticket is for sparkR shell. This is not only for sparkR itself, but can also benefit downstream project like livy which use shell.R for its interactive session. For now, livy has no control of whether enable hive or not.

## How was this patch tested?

Tested it manually, run `bin/sparkR --master local --conf spark.sql.catalogImplementation=in-memory` and verify hive is not enabled.

2017-02-13 05:58 UTC, SparkQA commented
**[Test build #72801 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72801/testReport)** for PR 16907 at commit [`8329be6`](https://github.com/apache/spark/commit/8329be6dce176022d08bb3109dc994434bf7c84a).

2017-02-13 08:05 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-02-13 08:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/72801/
Test FAILed.

2017-02-13 08:22 UTC, SparkQA commented
**[Test build #72810 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72810/testReport)** for PR 16907 at commit [`9a3aea6`](https://github.com/apache/spark/commit/9a3aea61caf8030659de1e81b59030b8ae3bfa1b).

2017-02-13 10:46 UTC, SparkQA commented
**[Test build #72810 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72810/testReport)** for PR 16907 at commit [`9a3aea6`](https://github.com/apache/spark/commit/9a3aea61caf8030659de1e81b59030b8ae3bfa1b).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-02-13 10:47 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-02-13 10:47 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/72810/
Test PASSed.

2017-02-13 11:24 UTC, zjffdu commented
@felixcheung  Please help review.

2017-02-13 18:03 UTC, felixcheung commented on sql/core/src/main/scala/org/apache/spark/sql/api/r/SQLUtils.scala
> +        && jsc.sc.conf.get(CATALOG_IMPLEMENTATION.key, "hive") == "hive") {
I don't think we should check for this for this message

2017-02-13 18:05 UTC, felixcheung commented
We should discuss other uses outside of sparkR shell - shell.R is not intended to be an API for reuse outside of the sparkR shell - we have other assumptions in the code that could be easily broken that way.

2017-02-13 18:09 UTC, felixcheung requested changes

2017-02-13 18:09 UTC, felixcheung commented on sql/core/src/main/scala/org/apache/spark/sql/api/r/SQLUtils.scala
> +        && jsc.sc.conf.get(CATALOG_IMPLEMENTATION.key, "hive") == "hive") {
you need to `toLowerCase` like here https://github.com/apache/spark/blob/master/repl/scala-2.11/src/main/scala/org/apache/spark/repl/Main.scala#L91

2017-02-14 02:03 UTC, zjffdu commented
Address the comments. @felixcheung, correct, `shell.R` is not supposed to be used outside. This ticket is mainly for disabling hive in sparkR shell, sparkR batch mode already support this feature.

2017-02-14 02:08 UTC, SparkQA commented
**[Test build #72842 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72842/testReport)** for PR 16907 at commit [`6839c02`](https://github.com/apache/spark/commit/6839c027743b12ec24e804d24b2ae756c7dc66b6).

2017-02-14 03:26 UTC, felixcheung requested changes

2017-02-14 03:26 UTC, felixcheung commented on sql/core/src/main/scala/org/apache/spark/sql/api/r/SQLUtils.scala
> +          s"Spark is not built with Hive or Hive is disabled via ${CATALOG_IMPLEMENTATION.key} " +
I'd be specific to say instead of `Hive is disabled via ${CATALOG_IMPLEMENTATION.key} `
say `${CATALOG_IMPLEMENTATION.key} is not set to "hive"; `

2017-02-14 04:30 UTC, SparkQA commented
**[Test build #72842 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72842/testReport)** for PR 16907 at commit [`6839c02`](https://github.com/apache/spark/commit/6839c027743b12ec24e804d24b2ae756c7dc66b6).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-02-14 04:31 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-02-14 04:31 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/72842/
Test PASSed.

2017-02-15 02:33 UTC, SparkQA commented
**[Test build #72915 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72915/testReport)** for PR 16907 at commit [`ee20be3`](https://github.com/apache/spark/commit/ee20be3d13e5b35c9e90ee5cabdd770c797224ae).

2017-02-15 04:19 UTC, SparkQA commented
**[Test build #72915 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/72915/testReport)** for PR 16907 at commit [`ee20be3`](https://github.com/apache/spark/commit/ee20be3d13e5b35c9e90ee5cabdd770c797224ae).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-02-15 04:20 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-02-15 04:20 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/72915/
Test FAILed.

2017-02-24 02:06 UTC, zjffdu commented on sql/core/src/main/scala/org/apache/spark/sql/api/r/SQLUtils.scala
> +          s"Spark is not built with Hive or Hive is disabled via ${CATALOG_IMPLEMENTATION.key} " +
Ping @felixcheung, message is updated.

2017-02-24 08:20 UTC, felixcheung commented on sql/core/src/main/scala/org/apache/spark/sql/api/r/SQLUtils.scala
> +          s"Spark is not built with Hive or Hive is disabled via ${CATALOG_IMPLEMENTATION.key} " +
test failed? https://github.com/apache/spark/pull/16907#issuecomment-279913201

2017-02-24 08:33 UTC, zjffdu commented
Seems a flaky test, let me trigger the build

2017-02-24 08:37 UTC, SparkQA commented
**[Test build #73416 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/73416/testReport)** for PR 16907 at commit [`68b5823`](https://github.com/apache/spark/commit/68b5823cf070dc09512723ef3a671589d0f42275).

2017-02-24 10:35 UTC, SparkQA commented
**[Test build #73416 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/73416/testReport)** for PR 16907 at commit [`68b5823`](https://github.com/apache/spark/commit/68b5823cf070dc09512723ef3a671589d0f42275).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-02-24 10:36 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-02-24 10:36 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/73416/
Test PASSed.

2017-02-24 19:07 UTC, felixcheung approved these changes
LGTM.
You want this in branch-2.1 and master, yes?

2017-02-25 00:57 UTC, zjffdu commented
Yeah, it would be nice to be merged into 2.1 as well. Thanks

2017-02-28 18:15 UTC, felixcheung requested changes

2017-02-28 18:15 UTC, felixcheung commented on sql/core/src/main/scala/org/apache/spark/sql/api/r/SQLUtils.scala
> +          s"Spark is not built with Hive or ${CATALOG_IMPLEMENTATION.key} is not set to 'hive', " +
actually, I notice this when reviewing before merge, I think this check is not matching with the message - in this case we already know CATALOG_IMPLEMENTATION == "hive"

2017-03-01 02:32 UTC, zjffdu commented on sql/core/src/main/scala/org/apache/spark/sql/api/r/SQLUtils.scala
> +          s"Spark is not built with Hive or ${CATALOG_IMPLEMENTATION.key} is not set to 'hive', " +
Good catch, I updated the if condition to match the message.

2017-03-01 02:32 UTC, SparkQA commented
**[Test build #73642 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/73642/testReport)** for PR 16907 at commit [`89a8752`](https://github.com/apache/spark/commit/89a8752deac4bfeb7a8a224b06127bec8654a61d).

2017-03-01 04:19 UTC, SparkQA commented
**[Test build #73642 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/73642/testReport)** for PR 16907 at commit [`89a8752`](https://github.com/apache/spark/commit/89a8752deac4bfeb7a8a224b06127bec8654a61d).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-01 04:20 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-01 04:20 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/73642/
Test PASSed.

2017-03-01 06:22 UTC, felixcheung commented
merged to master and branch-2.1

2017-03-01 06:24 UTC, closed without merging