[SPARK-19626]update cred using spark.yarn.credentials.updateTime
apache/spark pull request #16955
Opened 2017-02-16 09:53 UTC by yaooqinn

## What changes were proposed in this pull request?

update cred using spark.yarn.credentials.updateTime

## How was this patch tested?

existing test

cc @jerryshao @vanzin

2017-02-16 09:58 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-02-16 10:03 UTC, jerryshao requested changes
Thanks for the fix, only one comment about the changes.

2017-02-16 10:03 UTC, jerryshao commented on resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/security/CredentialUpdater.scala
> +    val remainingTime = Math.max(1, startTime - System.currentTimeMillis())
The logic looks different compared to the above code, also `1` is minute nor millisecond.

2017-02-16 10:53 UTC, yaooqinn commented on resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/security/CredentialUpdater.scala
> +    val remainingTime = Math.max(1, startTime - System.currentTimeMillis())
OK, let me change it back

2017-02-16 11:00 UTC, yaooqinn commented
cc again @jerryshao

2017-02-16 12:30 UTC, srowen commented
There's no detail in the JIRA or PR. I can't tell whether you are solving the problem you set out to solve. Are you saying this is the entire problem, that the wrong config is being queried?

2017-02-16 12:49 UTC, jerryshao commented
Agreed with @srowen , please describe the problem and fix both here in PR and in JIRA, also changing the title to be more meaningful. It would be better for others without the context to understand the issue fast.

2017-02-16 14:31 UTC, yaooqinn commented
@srowen @jerryshao  Thanks for your comments. I have added some descriptions both in the JIRA and here, please check whether OK or not.

2017-02-17 09:26 UTC, yaooqinn commented
ping @srowen, would you plz verify this patch again? thanks.

2017-02-17 09:28 UTC, srowen commented
(I don't know enough about this to review)

2017-02-17 19:40 UTC, vanzin commented
ok to test

2017-02-17 19:42 UTC, SparkQA commented
**[Test build #73068 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/73068/testReport)** for PR 16955 at commit [`211bbd3`](https://github.com/apache/spark/commit/211bbd3234a3641b02b38eae7bc0020ffb5b46d3).

2017-02-17 20:00 UTC, SparkQA commented
**[Test build #73068 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/73068/testReport)** for PR 16955 at commit [`211bbd3`](https://github.com/apache/spark/commit/211bbd3234a3641b02b38eae7bc0020ffb5b46d3).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-02-17 20:01 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-02-17 20:01 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/73068/
Test PASSed.

2017-02-20 09:22 UTC, yaooqinn commented
@vanzin Thanks, all tests passed

2017-02-20 09:55 UTC, jerryshao approved these changes

2017-02-21 17:57 UTC, vanzin commented
Merging to master / 2.1.

2017-02-21 18:00 UTC, closed without merging