[SPARK-19682][SparkR] Issue warning (or error) when subset method "[[" takes vector index
apache/spark pull request #17017
Opened 2017-02-21 19:08 UTC by actuaryzhang

## What changes were proposed in this pull request?
The `[[` method is supposed to take a single index and return a column. This is different from base R which takes a vector index.  We should check for this and issue warning or error when vector index is supplied (which is very likely given the behavior in base R). 

Currently I'm issuing a warning message and just take the first element of the vector index. We could change this to an error it that's better. 

## How was this patch tested?
new tests

2017-02-21 19:11 UTC, actuaryzhang commented
@felixcheung 
Simple example to illustrate this
```
df <- suppressWarnings(createDataFrame(iris))
df[[1:2]]
```
Instead of issuing warning and taking the first element, we can throw a more meaningful error message. Minor issue, but many R users may be accustomed to use vector index with `[[`.

2017-02-21 19:12 UTC, SparkQA commented
**[Test build #73227 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/73227/testReport)** for PR 17017 at commit [`66888b6`](https://github.com/apache/spark/commit/66888b6ca30fdc76565fcaf60fdf98366a5b49c9).

2017-02-21 19:16 UTC, SparkQA commented
**[Test build #73227 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/73227/testReport)** for PR 17017 at commit [`66888b6`](https://github.com/apache/spark/commit/66888b6ca30fdc76565fcaf60fdf98366a5b49c9).
 * This patch **fails R style tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-02-21 19:16 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-02-21 19:16 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/73227/
Test FAILed.

2017-02-21 19:27 UTC, SparkQA commented
**[Test build #73228 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/73228/testReport)** for PR 17017 at commit [`f614d00`](https://github.com/apache/spark/commit/f614d007f7e611c476ea9f119e1ece65b179f6eb).

2017-02-21 19:31 UTC, SparkQA commented
**[Test build #73228 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/73228/testReport)** for PR 17017 at commit [`f614d00`](https://github.com/apache/spark/commit/f614d007f7e611c476ea9f119e1ece65b179f6eb).
 * This patch **fails R style tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-02-21 19:31 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-02-21 19:31 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/73228/
Test FAILed.

2017-02-21 19:57 UTC, SparkQA commented
**[Test build #73231 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/73231/testReport)** for PR 17017 at commit [`91204aa`](https://github.com/apache/spark/commit/91204aa36b7b9456a9b7f27d5eb97c1c92a61699).

2017-02-21 20:26 UTC, SparkQA commented
**[Test build #73231 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/73231/testReport)** for PR 17017 at commit [`91204aa`](https://github.com/apache/spark/commit/91204aa36b7b9456a9b7f27d5eb97c1c92a61699).
 * This patch **fails SparkR unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-02-21 20:26 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-02-21 20:26 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/73231/
Test FAILed.

2017-02-22 06:42 UTC, felixcheung commented
Jenkins, retest this please

2017-02-22 06:43 UTC, felixcheung commented
That's one weird test failure.
Looks good

2017-02-22 07:17 UTC, SparkQA commented
**[Test build #73264 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/73264/testReport)** for PR 17017 at commit [`91204aa`](https://github.com/apache/spark/commit/91204aa36b7b9456a9b7f27d5eb97c1c92a61699).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-02-22 07:17 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-02-22 07:17 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/73264/
Test PASSed.

2017-02-22 19:28 UTC, felixcheung requested changes

2017-02-22 19:28 UTC, felixcheung commented on R/pkg/R/DataFrame.R
> +            }
actually, sorry I missed this - could you add a test for this?

2017-02-23 06:45 UTC, actuaryzhang commented on R/pkg/R/DataFrame.R
> +            }
@felixcheung Test added. Thanks for catching this.

2017-02-23 06:47 UTC, SparkQA commented
**[Test build #73329 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/73329/testReport)** for PR 17017 at commit [`46f6ca8`](https://github.com/apache/spark/commit/46f6ca8f0a6c36917f4b634262f5657bcde36f2b).

2017-02-23 07:19 UTC, SparkQA commented
**[Test build #73329 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/73329/testReport)** for PR 17017 at commit [`46f6ca8`](https://github.com/apache/spark/commit/46f6ca8f0a6c36917f4b634262f5657bcde36f2b).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-02-23 07:19 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-02-23 07:19 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/73329/
Test PASSed.

2017-02-23 19:13 UTC, felixcheung commented
thanks - merged to master and branch-2.1

2017-02-23 19:14 UTC, closed without merging