[SPARK-19831][CORE] Use a separate thread to clean up the finished application to avoid the block
apache/spark pull request #17189
Opened 2017-03-07 12:02 UTC by hustfxj

Cleaning the application may cost much time at worker, then it will block that the worker send heartbeats master because the worker is extend ThreadSafeRpcEndpoint. If the heartbeat from a worker is blocked by the message ApplicationFinished, master will think the worker is dead. If the worker has a driver, the driver will be scheduled by master again. 
It had better use a separate thread to clean up the finished application to avoid the block

2017-03-07 12:07 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-03-08 12:55 UTC, jerryshao commented
I think you need to call `cleanupApplicationThreadExecutor.shutdownNow()` when `worker` is stopped.

2017-03-08 19:16 UTC, zsxwing requested changes

2017-03-08 19:16 UTC, zsxwing commented on core/src/main/scala/org/apache/spark/deploy/worker/Worker.scala
> +      cleanupApplicationThreadExecutor.submit(new Runnable {
I prefer to just reuse the existing `cleanupThreadExecutor` like this:
```Scala
      appDirectories.remove(id).foreach { dirList =>
        concurrent.Future {
          logInfo(s"Cleaning up local directories for application $id")
          dirList.foreach { dir =>
            Utils.deleteRecursively(new File(dir))
          }
        }(cleanupThreadExecutor).onFailure {
          case e: Throwable =>
            logError(s"cleanup app dir $dirList failed: ${e.getMessage}", e)
        }(cleanupThreadExecutor)
      }
      shuffleService.applicationRemoved(id)
```

2017-03-08 19:16 UTC, zsxwing commented
ok to test

2017-03-08 19:17 UTC, SparkQA commented
**[Test build #74220 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/74220/testReport)** for PR 17189 at commit [`a353262`](https://github.com/apache/spark/commit/a353262f3089c2c06fe07fc858450f771b3f54a8).

2017-03-08 21:57 UTC, SparkQA commented
**[Test build #74220 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/74220/testReport)** for PR 17189 at commit [`a353262`](https://github.com/apache/spark/commit/a353262f3089c2c06fe07fc858450f771b3f54a8).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-08 21:58 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-08 21:58 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/74220/
Test PASSed.

2017-03-09 02:45 UTC, hustfxj commented on core/src/main/scala/org/apache/spark/deploy/worker/Worker.scala
> +      cleanupApplicationThreadExecutor.submit(new Runnable {
I agree with you, but I am worried that cleaning up the workDir and application all cost mush time.

2017-03-09 03:48 UTC, zsxwing commented on core/src/main/scala/org/apache/spark/deploy/worker/Worker.scala
> +      cleanupApplicationThreadExecutor.submit(new Runnable {
That won't become an issue. The worst case is there will be some pending tasks in the queue of `cleanupThreadExecutor`. Considering the number of applications is not huge, it won't be an issue.

2017-03-09 12:02 UTC, SparkQA commented
**[Test build #74266 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/74266/testReport)** for PR 17189 at commit [`cbf14b2`](https://github.com/apache/spark/commit/cbf14b2a92a9fd07dcb86ed18e4ea8f88e3b01ce).

2017-03-09 14:41 UTC, SparkQA commented
**[Test build #74266 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/74266/testReport)** for PR 17189 at commit [`cbf14b2`](https://github.com/apache/spark/commit/cbf14b2a92a9fd07dcb86ed18e4ea8f88e3b01ce).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-09 14:42 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-09 14:42 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/74266/
Test PASSed.

2017-03-09 18:31 UTC, zsxwing commented on core/src/main/scala/org/apache/spark/deploy/worker/Worker.scala
> +  // A separated thread to clean up the workDir and the finished application.
nit: the directories of finished applications.

2017-03-09 18:32 UTC, zsxwing commented
@hustfxj Looks pretty good. Could you update the PR title and description to reflect the latest changes?

2017-03-12 08:02 UTC, SparkQA commented
**[Test build #74397 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/74397/testReport)** for PR 17189 at commit [`8e44aab`](https://github.com/apache/spark/commit/8e44aabe3697b77353b7ffdc310c688e0cc2e0a1).

2017-03-12 08:02 UTC, hustfxj commented
@zsxwing Of course, Thank you for your reminding

2017-03-12 10:39 UTC, SparkQA commented
**[Test build #74397 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/74397/testReport)** for PR 17189 at commit [`8e44aab`](https://github.com/apache/spark/commit/8e44aabe3697b77353b7ffdc310c688e0cc2e0a1).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-12 10:40 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-12 10:40 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/74397/
Test PASSed.

2017-03-12 17:28 UTC, zsxwing commented
LGTM. Merging to master. Thanks!

2017-03-12 17:31 UTC, closed without merging