[SPARK-19892][MLlib] Implement findAnalogies method for Word2VecModel
apache/spark pull request #17234
Opened 2017-03-10 05:29 UTC by benradford

## What changes were proposed in this pull request?

Added findAnalogies method to Word2VecModel for performing vector-algebra-based queries (e.g. King + Woman - Man).

## How was this patch tested?

Followed the contributor's guide for Spark and ran the run-tests. Compiled and tested functionality in spark-shell.

This is an original work that I license to the project under the project's open source license.

2017-03-10 05:32 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-03-10 05:32 UTC, benradford commented
ok to test
Jenkins, add to whitelist

2017-03-10 06:08 UTC, felixcheung requested changes

2017-03-10 06:08 UTC, felixcheung commented on R/pkg/DESCRIPTION
> +RoxygenNote: 6.0.1
please revert this.

2017-03-10 08:38 UTC, srowen commented on R/pkg/DESCRIPTION
> +RoxygenNote: 6.0.1
This happens automatically. Ideally the build doesn't modify source files -- do you know any way to make it not do this?

2017-03-10 08:41 UTC, srowen reviewed
I'm not sure if this adds enough value to be in the core implementation. Any caller can do this. Is it common enough that it needs to be a convenience method in Spark?

2017-03-10 08:41 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/mllib/feature/Word2Vec.scala
> +                            negative: Array[String] = Array(),
Nit: indentation.

2017-03-10 08:41 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/mllib/feature/Word2Vec.scala
> +      positiveVectors.map(x => {
There is a fair bit of duplicated code that could be factored into methods.

2017-03-10 08:41 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/mllib/feature/Word2Vec.scala
> +        x.map(y => y / math.pow(sumsqr, .5))
You just mean sqrt right? pow 0.5 is less readable

2017-03-10 16:36 UTC, benradford commented
@srowen I find this functionality useful and thought others might as well. It is a common use-case for word2vec and is suggested as a method for validating good model fit by Mikolov et al. I understand if you prefer not to include it in the core implementation, too. I did my best to address your suggestions in my latest commit.

2017-03-12 18:04 UTC, felixcheung commented on R/pkg/DESCRIPTION
> +RoxygenNote: 6.0.1
It does it automatically when someone having a newer roxygen2 installed is running the R build.
From looking at that code, there isn't an option to disable the behavior of updating this string automatically. And, I don't think there is a way to fix the version either, other than mucking with R packages that are installed.

2017-07-23 03:04 UTC, benradford reviewed
Corrected roxygen

2017-07-23 03:12 UTC, benradford commented
@srowen @felixcheung: I believe all concerns have been addressed. Please let me know if there are any remaining issues.

2017-09-08 16:14 UTC, benradford reviewed
fixed.

2017-12-14 21:04 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-01-18 17:33 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-01-24 00:32 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-03-16 07:21 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-09-16 18:26 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-01-18 00:08 UTC, closed without merging