[SPARK-20048][SQL] Cloning SessionState does not clone query execution listeners
apache/spark pull request #17379
Opened 2017-03-21 21:19 UTC by kunalkhamar

## What changes were proposed in this pull request?

Bugfix from SPARK-19540.
Cloning SessionState does not clone query execution listeners, so cloned session is unable to listen to events on queries.

## How was this patch tested?

- Unit test

2017-03-21 21:22 UTC, SparkQA commented
**[Test build #75002 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75002/testReport)** for PR 17379 at commit [`ad77fe9`](https://github.com/apache/spark/commit/ad77fe9ad258eac224f069bbc89294818ee6b549).

2017-03-21 22:52 UTC, SparkQA commented
**[Test build #75002 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75002/testReport)** for PR 17379 at commit [`ad77fe9`](https://github.com/apache/spark/commit/ad77fe9ad258eac224f069bbc89294818ee6b549).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-21 22:52 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-03-21 22:52 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/75002/
Test FAILed.

2017-03-21 23:59 UTC, kunalkhamar commented
retest this please

2017-03-22 00:02 UTC, SparkQA commented
**[Test build #75015 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75015/testReport)** for PR 17379 at commit [`ad77fe9`](https://github.com/apache/spark/commit/ad77fe9ad258eac224f069bbc89294818ee6b549).

2017-03-22 02:14 UTC, SparkQA commented
**[Test build #75015 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75015/testReport)** for PR 17379 at commit [`ad77fe9`](https://github.com/apache/spark/commit/ad77fe9ad258eac224f069bbc89294818ee6b549).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-22 02:15 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-22 02:15 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/75015/
Test PASSed.

2017-03-22 22:32 UTC, SparkQA commented
**[Test build #75066 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75066/testReport)** for PR 17379 at commit [`f63e81d`](https://github.com/apache/spark/commit/f63e81de5c0119e736ad0ddea7977da1060893a9).

2017-03-23 00:37 UTC, SparkQA commented
**[Test build #75066 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75066/testReport)** for PR 17379 at commit [`f63e81d`](https://github.com/apache/spark/commit/f63e81de5c0119e736ad0ddea7977da1060893a9).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-23 00:38 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-23 00:38 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/75066/
Test PASSed.

2017-03-23 21:17 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/internal/SessionState.scala
>   * @param functionRegistry Internal catalog for managing functions registered by the user.
why have you removed these?

2017-03-23 21:51 UTC, tdas requested changes
overall, i am confused as to why listener is not being passed as a constructor param, rather as a complicated override.

And why are docs being removed?

2017-03-23 21:51 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/internal/SessionState.scala
> - * @param experimentalMethods The experimental methods.
why have you removed these?

2017-03-23 21:51 UTC, tdas commented on sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveSessionState.scala
> - * @param queryExecutionCreator Lambda to create a [[QueryExecution]] from a [[LogicalPlan]]
why have these been removed?

2017-03-23 21:51 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/internal/SessionState.scala
> +      override val listenerManager: ExecutionListenerManager = self.listenerManager.clone()
Why do it this way? Why not pass it as a constructor param?

2017-03-23 21:51 UTC, tdas commented on sql/core/src/test/scala/org/apache/spark/sql/SessionStateSuite.scala
> +    def createTestListener: (ArrayBuffer[String], QueryExecutionListener) = {
Add a comment on what it creates? what the two things returned.

2017-03-23 21:51 UTC, tdas commented on sql/core/src/test/scala/org/apache/spark/sql/SessionStateSuite.scala
> +    def createTestListener: (ArrayBuffer[String], QueryExecutionListener) = {
super nit: cleaner to do 
```
class CommandCollector extends QueryExecutionListener {
  val commands = ...
  ...
} 
```

2017-03-24 01:51 UTC, kunalkhamar commented on sql/core/src/main/scala/org/apache/spark/sql/internal/SessionState.scala
> - * @param experimentalMethods The experimental methods.
These comments are adding little or no value. We should remove or make them more detailed, which would you prefer? If the latter, what's a good doc for shared state and experimental methods?

2017-03-24 01:51 UTC, kunalkhamar commented on sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveSessionState.scala
> - * @param queryExecutionCreator Lambda to create a [[QueryExecution]] from a [[LogicalPlan]]
Each of these is identical to their `SessionState` counterpart and should be inherited by Scaladoc comment inheritance, do we still need them?

2017-03-24 01:51 UTC, kunalkhamar commented on sql/core/src/test/scala/org/apache/spark/sql/SessionStateSuite.scala
> +    def createTestListener: (ArrayBuffer[String], QueryExecutionListener) = {
neat, changed.

2017-03-24 01:51 UTC, kunalkhamar commented on sql/core/src/main/scala/org/apache/spark/sql/internal/SessionState.scala
> +      override val listenerManager: ExecutionListenerManager = self.listenerManager.clone()
I think the general rule we followed in the cloneSession PR is that `val`s that directly depend on `SparkSession` to be initialized, are to be constructor params. We leave the other `val`s in the body of class. 
The advantage here is less duplicated code between `SessionState`, `HiveSessionState` and `TestHiveSparkSession`.
This is consistent with that, what would be the advantage of changing it to be a param?

2017-03-24 01:52 UTC, SparkQA commented
**[Test build #75135 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75135/testReport)** for PR 17379 at commit [`eb5581a`](https://github.com/apache/spark/commit/eb5581a8b685407c33a3ff76885dd6b9cb6f5fd8).

2017-03-24 03:59 UTC, SparkQA commented
**[Test build #75135 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75135/testReport)** for PR 17379 at commit [`eb5581a`](https://github.com/apache/spark/commit/eb5581a8b685407c33a3ff76885dd6b9cb6f5fd8).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-24 03:59 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-24 03:59 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/75135/
Test PASSed.

2017-03-28 20:37 UTC, SparkQA commented
**[Test build #75328 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75328/testReport)** for PR 17379 at commit [`16f5bea`](https://github.com/apache/spark/commit/16f5beae3d08627606c13ccb301d624836cb1233).

2017-03-28 20:41 UTC, kunalkhamar commented on sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveSessionState.scala
> - * @param queryExecutionCreator Lambda to create a [[QueryExecution]] from a [[LogicalPlan]]
`HiveSessionState` is gone, so this is not relevant anymore.

2017-03-28 20:43 UTC, kunalkhamar commented on sql/core/src/main/scala/org/apache/spark/sql/internal/SessionState.scala
> +      override val listenerManager: ExecutionListenerManager = self.listenerManager.clone()
Builders were added in [https://github.com/apache/spark/pull/17433](url). Changed initialization to use that pattern, so it is a constructor param now.

2017-03-28 20:45 UTC, kunalkhamar commented on sql/core/src/main/scala/org/apache/spark/sql/internal/SessionState.scala
> - * @param experimentalMethods The experimental methods.
Added it back, hopefully more descriptive.

2017-03-28 22:41 UTC, SparkQA commented
**[Test build #75328 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75328/testReport)** for PR 17379 at commit [`16f5bea`](https://github.com/apache/spark/commit/16f5beae3d08627606c13ccb301d624836cb1233).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-28 22:42 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-28 22:42 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/75328/
Test PASSed.

2017-03-28 23:32 UTC, SparkQA commented
**[Test build #75331 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75331/testReport)** for PR 17379 at commit [`cad1b63`](https://github.com/apache/spark/commit/cad1b6314c64fc5308d3b5ad0a86285356abbac0).

2017-03-29 01:48 UTC, SparkQA commented
**[Test build #75331 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75331/testReport)** for PR 17379 at commit [`cad1b63`](https://github.com/apache/spark/commit/cad1b6314c64fc5308d3b5ad0a86285356abbac0).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-29 01:50 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-29 01:50 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/75331/
Test PASSed.

2017-03-29 01:58 UTC, tdas reviewed
Few minor comments.
@hvanhovell should take a look too.

2017-03-29 01:58 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/internal/sessionStateBuilders.scala
> +  protected def udf: UDFRegistration = new UDFRegistration(functionRegistry)
This file only contains effectively one builder. So it should be named after the class.

2017-03-29 01:58 UTC, tdas commented on sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveSessionState.scala
>  @InterfaceStability.Unstable
This file should not be named HiveSessionState anymore. It doesnt even have the class HiveSessionState. It does have an object HiveSession, but do we need that object any more? 
@hvanhovell

2017-03-29 03:46 UTC, kunalkhamar commented on sql/core/src/main/scala/org/apache/spark/sql/internal/SessionState.scala
> +    val udf: UDFRegistration,
changed.

2017-03-29 03:46 UTC, kunalkhamar commented on sql/core/src/main/scala/org/apache/spark/sql/internal/sessionStateBuilders.scala
> +  protected def udf: UDFRegistration = new UDFRegistration(functionRegistry)
changed.

2017-03-29 03:47 UTC, kunalkhamar commented on sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveSessionState.scala
>  @InterfaceStability.Unstable
Renamed, removed `object HiveSessionState`.

2017-03-29 03:47 UTC, SparkQA commented
**[Test build #75337 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75337/testReport)** for PR 17379 at commit [`be191c6`](https://github.com/apache/spark/commit/be191c62f7d549931debbc08f21e025edf418faa).

2017-03-29 03:52 UTC, SparkQA commented
**[Test build #75338 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75338/testReport)** for PR 17379 at commit [`119dae9`](https://github.com/apache/spark/commit/119dae974554bc7a1755b8532c373464618ad56d).

2017-03-29 06:00 UTC, SparkQA commented
**[Test build #75337 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75337/testReport)** for PR 17379 at commit [`be191c6`](https://github.com/apache/spark/commit/be191c62f7d549931debbc08f21e025edf418faa).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-29 06:01 UTC, SparkQA commented
**[Test build #75338 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75338/testReport)** for PR 17379 at commit [`119dae9`](https://github.com/apache/spark/commit/119dae974554bc7a1755b8532c373464618ad56d).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-29 06:01 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-29 06:01 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/75337/
Test PASSed.

2017-03-29 06:02 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-29 06:02 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/75338/
Test PASSed.

2017-03-29 06:18 UTC, kunalkhamar commented
cc @hvanhovell

2017-03-29 12:27 UTC, hvanhovell commented on sql/core/src/main/scala/org/apache/spark/sql/internal/BaseSessionStateBuilder.scala
> +  protected def udfRegistration: UDFRegistration = new UDFRegistration(functionRegistry)
Minor: I was wondering why you moved this into the builder?

2017-03-29 12:31 UTC, hvanhovell commented on sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveSessionState.scala
>  @InterfaceStability.Unstable
Yeah, lets rename the file to `HiveSessionBuilder.scala`

2017-03-29 12:32 UTC, hvanhovell commented on sql/core/src/main/scala/org/apache/spark/sql/internal/sessionStateBuilders.scala
> +  protected def udf: UDFRegistration = new UDFRegistration(functionRegistry)
It also contains a mix-in `WithTestConf`. But renaming is fine.

2017-03-29 12:35 UTC, hvanhovell approved these changes
@kunalkhamar could you rename HiveSessionState into HiveSessionStateBuilder? Other than that, LGTM.

2017-03-29 18:12 UTC, kunalkhamar commented on sql/core/src/main/scala/org/apache/spark/sql/internal/BaseSessionStateBuilder.scala
> +  protected def udfRegistration: UDFRegistration = new UDFRegistration(functionRegistry)
It was the only thing not initialized in the builder, thought it would be more consistent to have all initialization in the builder. Is this okay?

2017-03-29 18:12 UTC, kunalkhamar commented
@hvanhovell it should be HiveSessionStateBuilder now

2017-03-29 19:34 UTC, hvanhovell commented
Merging to master. Thanks!

2017-03-29 19:37 UTC, closed without merging