[SQL][DOC] Use recommended values for row boundaries in Window's scal…
apache/spark pull request #17417
Opened 2017-03-24 21:46 UTC by jaceklaskowski

…adoc

## What changes were proposed in this pull request?

Use recommended values for row boundaries in Window's scaladoc, i.e. `Window.unboundedPreceding`, `Window.unboundedFollowing`, and `Window.currentRow` (that were introduced in 2.1.0).

## How was this patch tested?

Local build

2017-03-24 21:47 UTC, SparkQA commented
**[Test build #75180 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75180/testReport)** for PR 17417 at commit [`efc420b`](https://github.com/apache/spark/commit/efc420bfc0cb19bed5adec919587cc20182293fe).

2017-03-24 22:02 UTC, SparkQA commented
**[Test build #75183 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75183/testReport)** for PR 17417 at commit [`07a36f8`](https://github.com/apache/spark/commit/07a36f88473599d5bc5003bd0ed6539c2835213f).

2017-03-24 23:49 UTC, SparkQA commented
**[Test build #75180 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75180/testReport)** for PR 17417 at commit [`efc420b`](https://github.com/apache/spark/commit/efc420bfc0cb19bed5adec919587cc20182293fe).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-24 23:50 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-24 23:50 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/75180/
Test PASSed.

2017-03-25 00:03 UTC, SparkQA commented
**[Test build #75183 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75183/testReport)** for PR 17417 at commit [`07a36f8`](https://github.com/apache/spark/commit/07a36f88473599d5bc5003bd0ed6539c2835213f).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-25 00:04 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-25 00:04 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/75183/
Test PASSed.

2017-03-25 08:58 UTC, srowen reviewed
I'm not sure any of these changes are necessary?

2017-03-25 08:58 UTC, srowen commented on sql/core/src/main/scala/org/apache/spark/sql/expressions/Window.scala
> + * Utility functions for defining window in Datasets.
These are used with DataFrames, right? At least that's what I have used Window for, am I missing something?

2017-03-25 08:58 UTC, srowen commented on sql/core/src/main/scala/org/apache/spark/sql/expressions/Window.scala
> +   * Both `start` and `end` are relative positions to the current row. For example, "0" means
I think the right phrasing is: "are positions relative to the current row". The current text is OK IMHO

2017-03-25 08:58 UTC, srowen commented on sql/core/src/main/scala/org/apache/spark/sql/expressions/Window.scala
> +   * We recommend users to use [[Window.unboundedPreceding]], [[Window.unboundedFollowing]],
"We recommend that users use" is correct, but 'that' can be omitted and it's still correct.
I think the backticks are on purpose as many scaladoc refs like this also cause doc failures. At least you need to verify this before changing.

2017-03-25 08:58 UTC, srowen commented on sql/core/src/main/scala/org/apache/spark/sql/expressions/Window.scala
> +   *     Window.partitionBy('category).orderBy('id).rowsBetween(Window.currentRow, 1)
Why this change? 0 should mean current row.

2017-03-25 12:43 UTC, jaceklaskowski commented on sql/core/src/main/scala/org/apache/spark/sql/expressions/Window.scala
> + * Utility functions for defining window in Datasets.
Sure. I'm going to revert the changes. There's a little value in them. I'd rather see the changes approved in general than fight for DataFrame vs Dataset.

p.s. There's no `DataFrame` in Spark SQL which is just a type alias of `Dataset[Row]` -- see https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/package.scala#L46.

2017-03-25 12:44 UTC, jaceklaskowski commented on sql/core/src/main/scala/org/apache/spark/sql/expressions/Window.scala
> +   * Both `start` and `end` are relative positions to the current row. For example, "0" means
I'll fix it to be more accurate (that's the purpose of this particular change so the more accurate the merrier). Thanks!

2017-03-25 12:46 UTC, jaceklaskowski commented on sql/core/src/main/scala/org/apache/spark/sql/expressions/Window.scala
> +   *     Window.partitionBy('category).orderBy('id).rowsBetween(Window.currentRow, 1)
See the above change where Spark devs "recommend that users use" the values by their aliases not their numeric values.

2017-03-25 12:49 UTC, jaceklaskowski commented on sql/core/src/main/scala/org/apache/spark/sql/expressions/Window.scala
> +   * We recommend users to use [[Window.unboundedPreceding]], [[Window.unboundedFollowing]],
Leaving 'that' aside is incorrect -- see http://dictionary.cambridge.org/dictionary/english/recommend where *to* is even highlighted to make the point.

2017-03-25 12:49 UTC, srowen commented on sql/core/src/main/scala/org/apache/spark/sql/expressions/Window.scala
> + * Utility functions for defining window in Datasets.
It's an alias, yes, but it certainly exists as a user-facing type.

2017-03-25 13:02 UTC, SparkQA commented
**[Test build #75217 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75217/testReport)** for PR 17417 at commit [`07001a9`](https://github.com/apache/spark/commit/07001a99b5f902e18b2974de1b77dc7f4f4e37a3).

2017-03-25 15:03 UTC, SparkQA commented
**[Test build #75217 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75217/testReport)** for PR 17417 at commit [`07001a9`](https://github.com/apache/spark/commit/07001a99b5f902e18b2974de1b77dc7f4f4e37a3).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-25 15:04 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-25 15:04 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/75217/
Test PASSed.

2017-03-26 09:40 UTC, srowen commented on sql/core/src/main/scala/org/apache/spark/sql/expressions/Window.scala
> +   * We recommend that users use `Window.unboundedPreceding`, `Window.unboundedFollowing`,
Either way is correct, it wasn't wrong

2017-03-26 09:40 UTC, srowen commented on sql/core/src/main/scala/org/apache/spark/sql/expressions/Window.scala
> +   *              the minimum long value, i.e. `Window.unboundedPreceding`.
Likewise this is effectively identical. I wouldn't make changes like this

2017-03-26 15:47 UTC, SparkQA commented
**[Test build #75240 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75240/testReport)** for PR 17417 at commit [`bf82dc6`](https://github.com/apache/spark/commit/bf82dc61b5c93c35008d0a37556760c6ca095635).

2017-03-26 17:47 UTC, SparkQA commented
**[Test build #75240 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75240/testReport)** for PR 17417 at commit [`bf82dc6`](https://github.com/apache/spark/commit/bf82dc61b5c93c35008d0a37556760c6ca095635).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-26 17:48 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-26 17:48 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/75240/
Test PASSed.

2017-03-26 18:59 UTC, srowen commented on sql/core/src/main/scala/org/apache/spark/sql/expressions/Window.scala
> +   *     Window.partitionBy('category).orderBy('id).rowsBetween(Window.currentRow, 1)
Got it, and I think there are also doc examples like this in `Column.scala` and `WindowSpec.scala` that could be similarly improved

2017-03-27 16:23 UTC, jaceklaskowski commented
Hey @srowen Would appreciate your looking at the changes again and comments (or merge). Thanks!

2017-03-27 17:32 UTC, srowen commented
How about the other files I mentioned? I think they can take similar changes. I think you can roll your other PR into this. They're both kinda misc doc improvements.

2017-03-28 14:06 UTC, jaceklaskowski commented
I'm going to merge the two PRs with your comments applied (i.e. excluding changes that are not necessarily doc-only). Thanks a lot for your time, Sean. Appreciate a lot.

2017-03-29 09:57 UTC, SparkQA commented
**[Test build #75352 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75352/testReport)** for PR 17417 at commit [`0c4a77e`](https://github.com/apache/spark/commit/0c4a77eea4f5bd16e8445120ed8ee7758fcbb35b).

2017-03-29 10:02 UTC, SparkQA commented
**[Test build #75353 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75353/testReport)** for PR 17417 at commit [`8dc1f04`](https://github.com/apache/spark/commit/8dc1f046ee5b6eafbea436eb35190e403179c0e5).

2017-03-29 10:27 UTC, SparkQA commented
**[Test build #75354 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75354/testReport)** for PR 17417 at commit [`e09802d`](https://github.com/apache/spark/commit/e09802df77cf7a7c0bbdd444293d6e3a7db202aa).

2017-03-29 11:52 UTC, SparkQA commented
**[Test build #75355 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75355/testReport)** for PR 17417 at commit [`db426e3`](https://github.com/apache/spark/commit/db426e35729b5948a5391c3d16ddc0d5b2a3ccdb).

2017-03-29 12:42 UTC, SparkQA commented
**[Test build #75352 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75352/testReport)** for PR 17417 at commit [`0c4a77e`](https://github.com/apache/spark/commit/0c4a77eea4f5bd16e8445120ed8ee7758fcbb35b).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `trait Source `

2017-03-29 12:43 UTC, SparkQA commented
**[Test build #75353 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75353/testReport)** for PR 17417 at commit [`8dc1f04`](https://github.com/apache/spark/commit/8dc1f046ee5b6eafbea436eb35190e403179c0e5).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-29 12:43 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-29 12:43 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/75352/
Test PASSed.

2017-03-29 12:44 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-29 12:44 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/75353/
Test PASSed.

2017-03-29 12:45 UTC, jaceklaskowski commented
Executed `cd docs && SKIP_PYTHONDOC=1 SKIP_RDOC=1 jekyll serve`  to check the changes and they've seemed fine. I had to fix some extra javadoc-related places to please jekyll.

@srowen Ready to review the changes once more? Thanks.

2017-03-29 13:13 UTC, SparkQA commented
**[Test build #75354 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75354/testReport)** for PR 17417 at commit [`e09802d`](https://github.com/apache/spark/commit/e09802df77cf7a7c0bbdd444293d6e3a7db202aa).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-29 13:14 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-29 13:14 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/75354/
Test PASSed.

2017-03-29 14:50 UTC, SparkQA commented
**[Test build #75355 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75355/testReport)** for PR 17417 at commit [`db426e3`](https://github.com/apache/spark/commit/db426e35729b5948a5391c3d16ddc0d5b2a3ccdb).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-29 14:51 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-29 14:51 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/75355/
Test PASSed.

2017-03-29 20:11 UTC, srowen requested changes
Most of this looks fine to me, but I have a few questions still about the changes.

2017-03-29 20:11 UTC, srowen commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/windowExpressions.scala
> -  override def foldable: Boolean = false
I get that this is redundant, or happens to be right now, but I don't think I'd remove it in a docs-only change

2017-03-29 20:11 UTC, srowen commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/parser/ExpressionParserSuite.scala
> + * If the type of an expression is supported it should be tested here.
This is a no-op change, I'd avoid this.

2017-03-29 20:11 UTC, srowen commented on sql/core/src/main/scala/org/apache/spark/sql/SparkSession.scala
> + *   SparkSession.builder
Is this for consistency? it also seems not worth changing otherwise

2017-03-29 20:20 UTC, jaceklaskowski commented on core/src/main/java/org/apache/spark/shuffle/sort/BypassMergeSortShuffleWriter.java
> + * Records are not buffered in memory. It writes output in a format
`HashShuffleWriter` is long gone.

2017-03-29 20:21 UTC, jaceklaskowski commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/windowExpressions.scala
> -  override def foldable: Boolean = false
Correct. Reverting...

2017-03-29 20:23 UTC, jaceklaskowski commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/parser/ExpressionParserSuite.scala
> + * If the type of an expression is supported it should be tested here.
Almost. I replaced `a` with `the` and added `an` before `expression`.

2017-03-29 20:24 UTC, jaceklaskowski commented on sql/core/src/main/scala/org/apache/spark/sql/SparkSession.scala
> + *   SparkSession.builder
Consistency (and one of the recommended coding styles of mine).

2017-03-29 20:27 UTC, SparkQA commented
**[Test build #75368 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75368/testReport)** for PR 17417 at commit [`913dbb8`](https://github.com/apache/spark/commit/913dbb81c6680e6063875a3fd7ddd0214bf7a7c4).

2017-03-29 23:28 UTC, SparkQA commented
**[Test build #75368 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75368/testReport)** for PR 17417 at commit [`913dbb8`](https://github.com/apache/spark/commit/913dbb81c6680e6063875a3fd7ddd0214bf7a7c4).
 * This patch passes all tests.
 * This patch **does not merge cleanly**.
 * This patch adds no public classes.

2017-03-29 23:29 UTC, AmplabJenkins commented
Build finished. Test PASSed.

2017-03-29 23:29 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/75368/
Test PASSed.

2017-03-30 09:52 UTC, srowen approved these changes

2017-03-30 09:52 UTC, srowen commented
Looks good, just needs a rebase now

2017-03-30 11:27 UTC, SparkQA commented
**[Test build #75388 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75388/testReport)** for PR 17417 at commit [`ae57b33`](https://github.com/apache/spark/commit/ae57b33a12e26c2b2c512d35c33ff8663f4f3373).

2017-03-30 14:21 UTC, SparkQA commented
**[Test build #75388 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/75388/testReport)** for PR 17417 at commit [`ae57b33`](https://github.com/apache/spark/commit/ae57b33a12e26c2b2c512d35c33ff8663f4f3373).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-03-30 14:22 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-30 14:22 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/75388/
Test PASSed.

2017-03-30 15:07 UTC, srowen commented
Merged to master

2017-03-30 15:10 UTC, closed without merging