[SPARK-20403][SQL][Documentation]Modify the instructions of some functions, and add  instructions of  'cast'  function
apache/spark pull request #17698
Opened 2017-04-20 07:23 UTC by 10110346

## What changes were proposed in this pull request?
1.	‘’hashSet‘ and ‘hashMap‘ are mutable,so,using 'val' will be better;
2.    	modify annotation:HALF_UP -> HALF_EVEN 
3.    add  instructions of  'cast'  function When using 'show functions'  and 'desc function cast'
       command in spark-sql
4.    Modify the  instructions of functions，such as
     boolean，tinyint，smallint，int，bigint，float，double，decimal，date，timestamp，binary，string

## How was this patch tested?
Before modification：
spark-sql>desc function boolean;
Function: boolean
Class: org.apache.spark.sql.catalyst.expressions.Cast
Usage: boolean(expr AS type) - Casts the value `expr` to the target data type `type`.

After modification：
spark-sql> desc function boolean;
Function: boolean
Class: org.apache.spark.sql.catalyst.expressions.CastAlias
Usage: boolean(expr) - Casts the value `expr` to the target data type `boolean`.

spark-sql> desc function cast
Function: cast
Class: org.apache.spark.sql.catalyst.expressions.Cast
Usage: cast(expr AS type) - Casts the value `expr` to the target data type `type`.

2017-04-20 07:27 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-04-20 07:27 UTC, rxin commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/Cast.scala
> +class CastAlias(child: Expression, dataType: DataType, timeZoneId: Option[String] = None)
will this work with our pattern matches in the query optimizer?

2017-04-20 07:28 UTC, srowen requested changes

2017-04-20 07:28 UTC, srowen commented on core/src/main/scala/org/apache/spark/ui/jobs/UIData.scala
> +    val accumulables = new HashMap[Long, AccumulableInfo]
Revert these unrelated changes

2017-04-20 07:28 UTC, srowen commented on examples/src/main/scala/org/apache/spark/examples/LocalKMeans.scala
> +    val points = new HashSet[Vector[Double]]
Revert these unrelated changes

2017-04-20 08:16 UTC, 10110346 commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/Cast.scala
> +class CastAlias(child: Expression, dataType: DataType, timeZoneId: Option[String] = None)
No,it will not

2017-04-20 08:19 UTC, 10110346 commented on core/src/main/scala/org/apache/spark/ui/jobs/UIData.scala
> +    val accumulables = new HashMap[Long, AccumulableInfo]
has reverted

2017-04-20 08:20 UTC, 10110346 commented on examples/src/main/scala/org/apache/spark/examples/LocalKMeans.scala
> +    val points = new HashSet[Vector[Double]]
has reverted

2017-04-21 08:09 UTC, 10110346 commented
Jenkins, test this please.

2017-04-25 01:47 UTC, 10110346 commented
can Jenkins to test?

2017-04-25 02:57 UTC, 10110346 commented
@srowen  test is not started, could you help trigger it ?

2017-05-01 04:10 UTC, 10110346 commented
@srowen, can you review it again?

2017-05-03 02:46 UTC, 10110346 commented
@rxin, would you help me review it again?thanks

2017-05-06 06:07 UTC, 10110346 commented
I  have tested all of them(boolean，tinyint，smallint，int，bigint，float，double，decimal，date，timestamp，binary，string),  they can work properly. @srowen @rxin

2017-05-10 13:35 UTC, HyukjinKwon commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala
> +    expression[Cast]("cast"),
Do we need this? I think we cover this in the parser.

2017-05-10 13:47 UTC, HyukjinKwon reviewed
For me, I don't think this is a proper approach (adding classes to fix a documentation).

2017-05-10 14:48 UTC, HyukjinKwon commented
Would there be other better ways, for example, fixing it in `DescribeFunctionCommand` or just hijacking the usage within `castAlias`?

2017-05-11 00:57 UTC, 10110346 commented
@ HyukjinKwon  I agree with you,i will try ,thanks.

2017-05-11 02:51 UTC, 10110346 commented
I have updated it , and test passed
please review it again,thanks @srowen @rxin @HyukjinKwon

2017-05-18 18:45 UTC, gatorsmile commented
LGTM except one comment:

Please add the test cases to the end of file `cast.sql`
```
DESC FUNCTION boolean;
DESC FUNCTION EXTENDED boolean;
```

You can generate the result file by 
```
SPARK_GENERATE_GOLDEN_FILES=1 build/sbt "sql/test-only *SQLQueryTestSuite"
```

2017-05-19 09:03 UTC, 10110346 commented
@gatorsmile   I have added test cases to the file `cast.sql` , thanks.

2017-05-19 12:47 UTC, kiszk commented
Jenkins, test this please

2017-05-22 07:08 UTC, 10110346 commented
@kiszk @gatorsmile  Test is not started, could you help trigger it again?

2017-05-22 20:46 UTC, gatorsmile commented
ok to test

2017-05-22 20:57 UTC, SparkQA commented
**[Test build #77201 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77201/testReport)** for PR 17698 at commit [`e09dc2a`](https://github.com/apache/spark/commit/e09dc2a884b122ffd5b3369bbe97bddb060e1f8e).

2017-05-22 22:26 UTC, SparkQA commented
**[Test build #77201 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77201/testReport)** for PR 17698 at commit [`e09dc2a`](https://github.com/apache/spark/commit/e09dc2a884b122ffd5b3369bbe97bddb060e1f8e).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-05-22 22:27 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-05-22 22:27 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/77201/
Test FAILed.

2017-05-23 01:02 UTC, SparkQA commented
**[Test build #77213 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77213/testReport)** for PR 17698 at commit [`6ce4220`](https://github.com/apache/spark/commit/6ce4220bf861f4a64f3126f1f14043dcb666a056).

2017-05-23 01:42 UTC, SparkQA commented
**[Test build #77214 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77214/testReport)** for PR 17698 at commit [`7edfed5`](https://github.com/apache/spark/commit/7edfed5577e8610b4ba42f64979c4168fce829d5).

2017-05-23 02:27 UTC, SparkQA commented
**[Test build #77213 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77213/testReport)** for PR 17698 at commit [`6ce4220`](https://github.com/apache/spark/commit/6ce4220bf861f4a64f3126f1f14043dcb666a056).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-05-23 02:27 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-05-23 02:27 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/77213/
Test FAILed.

2017-05-23 03:07 UTC, SparkQA commented
**[Test build #77214 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77214/testReport)** for PR 17698 at commit [`7edfed5`](https://github.com/apache/spark/commit/7edfed5577e8610b4ba42f64979c4168fce829d5).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-05-23 03:08 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-05-23 03:08 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/77214/
Test FAILed.

2017-05-23 03:17 UTC, SparkQA commented
**[Test build #77217 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77217/testReport)** for PR 17698 at commit [`10be7eb`](https://github.com/apache/spark/commit/10be7eb586dcf992af2982ba94aa446408ad1e25).

2017-05-23 04:45 UTC, SparkQA commented
**[Test build #77217 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77217/testReport)** for PR 17698 at commit [`10be7eb`](https://github.com/apache/spark/commit/10be7eb586dcf992af2982ba94aa446408ad1e25).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-05-23 04:46 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-05-23 04:46 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/77217/
Test FAILed.

2017-05-23 05:25 UTC, ueshin commented
@10110346 Hi, you can use the command @gatorsmile mentioned above to generate the result file.

2017-05-23 08:07 UTC, SparkQA commented
**[Test build #77241 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77241/testReport)** for PR 17698 at commit [`51949d7`](https://github.com/apache/spark/commit/51949d74c196cd7c2452e76e6fa8ecb71e0c768f).

2017-05-23 10:23 UTC, SparkQA commented
**[Test build #77241 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77241/testReport)** for PR 17698 at commit [`51949d7`](https://github.com/apache/spark/commit/51949d74c196cd7c2452e76e6fa8ecb71e0c768f).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-05-23 10:24 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-05-23 10:24 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/77241/
Test PASSed.

2017-05-23 22:05 UTC, 10110346 commented
Test passed, thanks. @ueshin @gatorsmile

2017-05-25 00:31 UTC, gatorsmile commented
LGTM

2017-05-25 00:32 UTC, gatorsmile commented
Thanks! Merging to master/2.2

2017-05-25 00:34 UTC, closed without merging