enable configurable reducer count in topByKey()
apache/spark pull request #17697
Opened 2017-04-20 06:57 UTC by yangyangyyy

## What changes were proposed in this pull request?

in the topByKey() call, provide a configurable partition count. without this, currently topByKey() results in only 16 reducers even if you have a 100GB input size

## How was this patch tested?
use existing unit tests

Please review http://spark.apache.org/contributing.html before opening a pull request.

2017-04-20 07:02 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-04-20 07:06 UTC, HyukjinKwon commented
It looks like a non-trivial change that needs a JIRA. Could you check ttp://spark.apache.org/contributing.html out and make a JIRA?

2017-04-20 07:09 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctions.scala
> +  def topByKey(num: Int, bucketsCount: Int = 200)(implicit ord: Ordering[V]): RDD[(K, Array[V])] = {
This might be problematic because it changes the binary API. It is a developer API though.

2017-04-20 07:22 UTC, HyukjinKwon commented on mllib/src/main/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctions.scala
> +  def topByKey(num: Int, bucketsCount: Int = 200)(implicit ord: Ordering[V]): RDD[(K, Array[V])] = {
Yes, I think this breaks binary compatibility (not source compatibility) up to my knowledge.

I tested this as described in https://github.com/databricks/scala-style-guide/issues/46 but with 

```
object A {
  def toString(v: Int, extra: String = ""): String = v.toString
}
```

2017-04-20 07:24 UTC, SparkQA commented
**[Test build #3667 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3667/testReport)** for PR 17697 at commit [`09d6643`](https://github.com/apache/spark/commit/09d66432787488b3672f22e03c492e558bf45019).

2017-04-20 07:34 UTC, SparkQA commented
**[Test build #3667 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3667/testReport)** for PR 17697 at commit [`09d6643`](https://github.com/apache/spark/commit/09d66432787488b3672f22e03c492e558bf45019).
 * This patch **fails MiMa tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-04-20 15:34 UTC, yangyangyyy commented
Jira created: https://issues.apache.org/jira/browse/SPARK-20414

2017-04-20 15:36 UTC, srowen commented
@yangyangyyy update the title please. There's no detail in the JIRA either?

2017-04-20 15:46 UTC, yangyangyyy commented
@srowen sorry typed 'ENTER' too early. added details in JIRA. 

which title do you mean? this PR title? (I did put down title in the jira)

2017-04-20 15:48 UTC, srowen commented
Put the JIRA number in this title. See the contributing guide or any other PR

2017-04-21 18:53 UTC, tejasapatil commented on mllib/src/main/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctions.scala
> +  def topByKey(num: Int, bucketsCount: Int = 200)(implicit ord: Ordering[V]): RDD[(K, Array[V])] = {
Not having this param means users are stuck with less reducers so I definitely see value in this PR.

Is there a recommendation about how to add a param to existing API ?

2017-04-21 19:12 UTC, HyukjinKwon commented on mllib/src/main/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctions.scala
> +  def topByKey(num: Int, bucketsCount: Int = 200)(implicit ord: Ordering[V]): RDD[(K, Array[V])] = {
Can we just add another overloaded method rather than fixing existing one? I guess probably this case is fine.

2017-04-21 21:50 UTC, yangyangyyy commented on mllib/src/main/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctions.scala
> +  def topByKey(num: Int, bucketsCount: Int = 200)(implicit ord: Ordering[V]): RDD[(K, Array[V])] = {
@HyukjinKwon   yes , updated that way

2017-04-22 07:16 UTC, HyukjinKwon reviewed
I just left some comment only about https://github.com/apache/spark/pull/17697#discussion_r112382018

I tested identically again but with

```
object A {
  def toString(v: Int): String = v.toString
  def toString(v: Int, a: String): String = v.toString
}
```

this time.

2017-04-22 07:16 UTC, HyukjinKwon commented on mllib/src/test/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctionsSuite.scala
> +      1), (3, 5)), 2)
little nit: the indentation looks not nice. probably ...

```scala
val data = Array((1, 7), (1, 3), (1, 6), (1, 1), (1, 2), (3, 2), (3, 7), (5, 1), (3, 5))
val topMap = sc.parallelize(data, 2)
```

2017-04-22 07:16 UTC, HyukjinKwon commented on mllib/src/main/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctions.scala
> +  def topByKeyUsingBuckets(num: Int, bucketsCount: Int = 200)(implicit ord: Ordering[V]): RDD[(K, Array[V])] = {
I actually meant ... 

```scala
def topByKey(num: Int, bucketsCount: Int)(implicit ord: Ordering[V]): RDD[(K, Array[V])] = {
  ...
}
```

2017-04-22 07:37 UTC, HyukjinKwon commented on mllib/src/test/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctionsSuite.scala
> +  test("topByKeyUsingBuckets") {
BTW, does this test the number of reducers? It looks the input/output is the same with the test above.

2017-04-22 08:18 UTC, yangyangyyy commented on mllib/src/main/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctions.scala
> +  def topByKeyUsingBuckets(num: Int, bucketsCount: Int = 200)(implicit ord: Ordering[V]): RDD[(K, Array[V])] = {
does this exist  in scala ? I thought scala does not allow overloading and default argument values are supposed to replace that. let me check ...

2017-04-22 08:20 UTC, yangyangyyy commented on mllib/src/test/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctionsSuite.scala
> +  test("topByKeyUsingBuckets") {
yes it's supposed to be the same. unfortunately I can't see a way to verify the number of reducers being actually used. it's not a correctness issue though, so I think verifying manually should be enough ---- I did verify on spark UI that it's invoking the intended reducer count

2017-04-24 21:57 UTC, yangyangyyy commented on mllib/src/main/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctions.scala
> +  def topByKey(num: Int, bucketsCount: Int = 200)(implicit ord: Ordering[V]): RDD[(K, Array[V])] = {
@HyukjinKwon @srowen I just updated the PR to make the overloaded function name to be the same as old

2017-04-25 19:27 UTC, yangyangyyy commented
btw @srowen  when I run either the current version or the patched version of the topByKey(), I get the mappers running almost 99% of the time in kyro serialization, do you have any ideas why ? the tasks run for 10minutes for only a 50MB input, due to the kyro cost

2017-05-01 18:20 UTC, yangyangyyy commented
@HyukjinKwon
@srowen 

team: anything I need to update, or does this look good to go now? thanks a lot

2017-05-01 19:26 UTC, srowen requested changes

2017-05-01 19:26 UTC, srowen commented on mllib/src/test/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctionsSuite.scala
> +    val topMap = sc.parallelize(Array(
Can the array just be a 'constant' rather than repeating it?

2017-05-01 19:26 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctions.scala
> +  def topByKey(num: Int, bucketsCount: Int = 200)(implicit ord: Ordering[V]): RDD[(K, Array[V])] = {
Doesn't this make a call to `topByKey(n)` ambiguous? maybe not, but seems like it should. I don't think you want a default value here. The 'default' case is the existing method.

2017-05-02 17:42 UTC, yangyangyyy commented on mllib/src/main/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctions.scala
> +  def topByKey(num: Int, bucketsCount: Int = 200)(implicit ord: Ordering[V]): RDD[(K, Array[V])] = {
thanks @srowen , I just updated them accordingly

2017-05-05 21:34 UTC, yangyangyyy commented
friendly ping .....

2017-05-07 02:21 UTC, yangyangyyy commented
@HyukjinKwon  @srowen

2017-05-07 03:02 UTC, HyukjinKwon commented on mllib/src/main/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctions.scala
> +      topByKey(num, 16)
To be clear, was this 16 by default before this PR? Adding a parameter would be fine but this should not change the original behaviour without this parameter before this PR.

2017-05-07 03:02 UTC, HyukjinKwon commented on mllib/src/main/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctions.scala
> +
It looks this newline can be removed if more commits should be pushed.

2017-05-07 03:02 UTC, HyukjinKwon commented on mllib/src/main/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctions.scala
> +      topByKey(num, 16)
Also, I believe the indentation here should be double spaced.

2017-05-07 03:02 UTC, HyukjinKwon commented on mllib/src/test/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctionsSuite.scala
> +                     )
Indentation should be double-spaced here too

2017-05-07 03:04 UTC, HyukjinKwon commented
I left some comments here though, I think I am not confident enough for a sign-off. Please let me defer to @srowen and @tejasapatil

2017-05-07 03:16 UTC, HyukjinKwon commented on mllib/src/test/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctionsSuite.scala
> +  val source_array = Array(
Also, I think we use naming convention, `sourceArray`. Probably, just `data` is enough?

2017-05-08 07:15 UTC, yangyangyyy commented
@HyukjinKwon  thanks, updated accordingly

2017-12-14 21:03 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-01-18 17:25 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-05-18 14:12 UTC, SparkQA commented
**[Test build #4184 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/4184/testReport)** for PR 17697 at commit [`29f9fbd`](https://github.com/apache/spark/commit/29f9fbda9a9deaaa9ae3afc9ff5ea34b75e92c8e).

2018-05-18 17:09 UTC, SparkQA commented
**[Test build #4184 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/4184/testReport)** for PR 17697 at commit [`29f9fbd`](https://github.com/apache/spark/commit/29f9fbda9a9deaaa9ae3afc9ff5ea34b75e92c8e).
 * This patch **fails PySpark unit tests**.
 * This patch **does not merge cleanly**.
 * This patch adds no public classes.

2018-05-22 13:21 UTC, SparkQA commented
**[Test build #4186 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/4186/testReport)** for PR 17697 at commit [`29f9fbd`](https://github.com/apache/spark/commit/29f9fbda9a9deaaa9ae3afc9ff5ea34b75e92c8e).

2018-05-22 16:28 UTC, SparkQA commented
**[Test build #4186 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/4186/testReport)** for PR 17697 at commit [`29f9fbd`](https://github.com/apache/spark/commit/29f9fbda9a9deaaa9ae3afc9ff5ea34b75e92c8e).
 * This patch **fails PySpark unit tests**.
 * This patch **does not merge cleanly**.
 * This patch adds no public classes.

2019-04-16 14:22 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-06-05 13:40 UTC, srowen requested changes

2019-06-05 13:40 UTC, srowen commented on mllib/src/main/scala/org/apache/spark/mllib/rdd/MLPairRDDFunctions.scala
> +  def topByKey(num: Int, bucketsCount: Int)(implicit ord: Ordering[V]): RDD[(K, Array[V])] = {
You can just keep one method with a new optional Int argument. Its default can be `Partitioner.defaultPartitioner(self)` This new method isn't used though?

2019-09-16 18:33 UTC, closed without merging