[SPARK-20519][SQL][CORE]Modify to prevent some possible runtime exceptions
apache/spark pull request #17796
Opened 2017-04-28 03:14 UTC by 10110346

Signed-off-by: liuxian <liu.xian3@zte.com.cn>

## What changes were proposed in this pull request?

For some functions,when the input parameter is null, may be a runtime exception occurs

## How was this patch tested?
Existing unit tests or add unit tests

2017-04-28 03:17 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-04-28 07:39 UTC, srowen reviewed
Don't make JIRAs for these; these are borderline not worth proposing, please.

2017-04-28 07:39 UTC, srowen commented on core/src/main/scala/org/apache/spark/util/Utils.scala
> +    customHostname = Option(hostname)
This should be OK, but, it's already being checked for null in the line above.

2017-04-28 08:54 UTC, 10110346 commented
ok, thanks for review it@srowen

2017-04-30 08:18 UTC, srowen commented on sql/core/src/main/scala/org/apache/spark/sql/SQLContext.scala
> +    Dataset.ofRows(sparkSession, ShowTablesCommand(Option(databaseName), None))
CC maybe @yhuai - OK to let `tables(null)` act like `tables()`? seems reasonable

2017-05-04 10:06 UTC, srowen commented
@10110346  to be conservative, maybe remove the change to SQLContext. It's not clear to me that you are supposed to be able to call {{tables(null)}} because in this case you should call {{tables()}}. A NullPointerException seems like reasonable behavior.

However I think you could also expand the improvement for `Utils.checkHost` and `checkHostPort`. They all take this "message" argument which is pretty pointless. The message is a little different in many places and doesn't include the actual value most of the time. Just setting a complete valid message once in the method rather than taking it as an argument would further help.

2017-05-04 10:41 UTC, 10110346 commented
I quite agree with you.
I will do it,thanks @srowen

2017-05-04 13:59 UTC, SparkQA commented
**[Test build #3689 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3689/testReport)** for PR 17796 at commit [`88b9e8c`](https://github.com/apache/spark/commit/88b9e8cbb4d50d944165a463da9da74a2858bdd8).

2017-05-04 14:08 UTC, SparkQA commented
**[Test build #3689 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3689/testReport)** for PR 17796 at commit [`88b9e8c`](https://github.com/apache/spark/commit/88b9e8cbb4d50d944165a463da9da74a2858bdd8).
 * This patch **fails to build**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-05-05 06:31 UTC, gatorsmile commented
ok to test

2017-05-05 06:32 UTC, SparkQA commented
**[Test build #76482 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/76482/testReport)** for PR 17796 at commit [`0b7aac2`](https://github.com/apache/spark/commit/0b7aac2982a7d6e33798fd2e674b28082bc0c5d7).

2017-05-05 07:05 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-05-05 07:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/76482/
Test FAILed.

2017-05-05 07:39 UTC, 10110346 commented
Test FAILed. I don't know why. 
Environment problem? Could you help me? @gatorsmile

2017-05-05 11:24 UTC, srowen requested changes
Other than the message change, yes, looks good

2017-05-05 11:24 UTC, srowen commented on core/src/main/scala/org/apache/spark/util/Utils.scala
> +    assert(host != null && host.indexOf(':') == -1, "Expected hostname")
The message should be `s"Expected hostname (not IP) but got $host"`

2017-05-05 11:24 UTC, srowen commented on core/src/main/scala/org/apache/spark/util/Utils.scala
> +    assert(hostPort != null && hostPort.indexOf(':') != -1, "Expected hostport")
Likewise here

2017-05-06 01:37 UTC, SparkQA commented
**[Test build #76507 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/76507/testReport)** for PR 17796 at commit [`494928d`](https://github.com/apache/spark/commit/494928d1349f35a224121810eb5db7b32e386bba).

2017-05-06 04:24 UTC, SparkQA commented
**[Test build #76507 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/76507/testReport)** for PR 17796 at commit [`494928d`](https://github.com/apache/spark/commit/494928d1349f35a224121810eb5db7b32e386bba).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-05-06 04:25 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-05-06 04:25 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/76507/
Test PASSed.

2017-05-06 08:25 UTC, 10110346 commented
@srowen  done, thank you very much.

2017-05-06 09:37 UTC, srowen commented on core/src/main/scala/org/apache/spark/util/Utils.scala
> +    assert(hostPort != null && hostPort.indexOf(':') != -1, s"Expected hostport but got $hostPort")
Change "hostport" to "host and port"

2017-05-08 00:52 UTC, SparkQA commented
**[Test build #76557 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/76557/testReport)** for PR 17796 at commit [`0e879c8`](https://github.com/apache/spark/commit/0e879c8d920ef53624d3c13f3176e2408d6563ac).

2017-05-08 03:42 UTC, SparkQA commented
**[Test build #76557 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/76557/testReport)** for PR 17796 at commit [`0e879c8`](https://github.com/apache/spark/commit/0e879c8d920ef53624d3c13f3176e2408d6563ac).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-05-08 03:43 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-05-08 03:43 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/76557/
Test PASSed.

2017-05-08 09:01 UTC, srowen commented
Merged to master

2017-05-08 09:03 UTC, closed without merging