[SPARK-20726][SPARKR] wrapper for SQL broadcast
apache/spark pull request #17965
Opened 2017-05-12 16:39 UTC by zero323

## What changes were proposed in this pull request?

Adds R wrapper for `o.a.s.sql.functions.broadcast`.

## How was this patch tested?

Unit tests, check `check-cran.sh`.

2017-05-12 16:42 UTC, SparkQA commented
**[Test build #76874 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/76874/testReport)** for PR 17965 at commit [`f190d62`](https://github.com/apache/spark/commit/f190d62460829dcfb84ff1a8e6dd6fe9cbd25719).

2017-05-12 16:45 UTC, zero323 commented
Points to discuss:

- Do we really need this. It gives us full API parity but is not strictly necessary. `hint(df, "broadcast")` should be equivalent.
- Is this the best implementation? Some alternatives:

    - Use generics for both and `signature(x = "SparkDataFrame", "missing")` for `DataFrame` version and `signature(x = "jobj", object = "Any")` for general version. This would keep internal API intact, but is hard to document without leaking internal details.

    - Use different name for `DataFrame` version, for example `broadcast_table`.  This is a bit verbose, and slightly harder to port for users.

- Is `dataframe.R` the best location? It is generic on `SparkDataFrame` so `functions.R` don't feel like a right choice.

2017-05-12 16:45 UTC, SparkQA commented
**[Test build #76874 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/76874/testReport)** for PR 17965 at commit [`f190d62`](https://github.com/apache/spark/commit/f190d62460829dcfb84ff1a8e6dd6fe9cbd25719).
 * This patch **fails R style tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-05-12 16:45 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-05-12 16:45 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/76874/
Test FAILed.

2017-05-12 17:42 UTC, SparkQA commented
**[Test build #76875 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/76875/testReport)** for PR 17965 at commit [`397ab1f`](https://github.com/apache/spark/commit/397ab1f7b4b4e2b9e51b697c92e3be197fed4554).

2017-05-12 18:18 UTC, SparkQA commented
**[Test build #76875 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/76875/testReport)** for PR 17965 at commit [`397ab1f`](https://github.com/apache/spark/commit/397ab1f7b4b4e2b9e51b697c92e3be197fed4554).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-05-12 18:18 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-05-12 18:18 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/76875/
Test PASSed.

2017-05-13 04:15 UTC, felixcheung requested changes

2017-05-13 04:15 UTC, felixcheung commented on R/pkg/R/DataFrame.R
> +
nit:  one empty line instead of two

2017-05-13 04:15 UTC, felixcheung commented on R/pkg/R/DataFrame.R
> +#' Equivalent to hint(x, "broadcast).
`"broadcast"`

2017-05-13 04:15 UTC, felixcheung commented on R/pkg/R/DataFrame.R
> +#' Equivalent to hint(x, "broadcast).
`\code{hint(x, "broadcast")}`

2017-05-13 04:15 UTC, felixcheung commented on R/pkg/R/context.R
> +broadcast_ <- function(sc, object) {
please change this to `broadcastRDD` like other functions

2017-05-13 04:15 UTC, felixcheung commented on R/pkg/R/generics.R
> +setGeneric("broadcast", function(x) { standardGeneric("broadcast") })
this list is sorted alphabetically within this section

2017-05-13 04:15 UTC, felixcheung commented on R/pkg/R/generics.R
> +setGeneric("broadcast", function(x) { standardGeneric("broadcast") })
there is a rd for `broadcast` already though https://github.com/zero323/spark/blob/397ab1f7b4b4e2b9e51b697c92e3be197fed4554/R/pkg/R/generics.R#L376
we probably need to remove that one

2017-05-13 04:17 UTC, felixcheung commented on R/pkg/R/context.R
> +broadcast_ <- function(sc, object) {
right, generally this is how we have handled name conflict with an existing RDD method.
we should be removing the internal only RDD methods at some point

2017-05-13 09:56 UTC, zero323 commented on R/pkg/R/DataFrame.R
> +#' Equivalent to hint(x, "broadcast).
I double check this but for some reason `\code` here made `roxygen` unhappy when I tried it last time.

2017-05-13 10:42 UTC, SparkQA commented
**[Test build #76898 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/76898/testReport)** for PR 17965 at commit [`1530785`](https://github.com/apache/spark/commit/1530785f7469830446cd95717d524eb42d88e4ab).

2017-05-13 10:42 UTC, zero323 commented on R/pkg/R/generics.R
> +setGeneric("broadcast", function(x) { standardGeneric("broadcast") })
It doesn't seem to affect the docs so I don't think we have to touch this for now:

![image](https://cloud.githubusercontent.com/assets/1554276/26024791/88a39940-37d9-11e7-9f11-ac1510b59215.png)

2017-05-13 10:43 UTC, zero323 commented on R/pkg/R/DataFrame.R
> +
Done.

2017-05-13 11:16 UTC, SparkQA commented
**[Test build #76898 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/76898/testReport)** for PR 17965 at commit [`1530785`](https://github.com/apache/spark/commit/1530785f7469830446cd95717d524eb42d88e4ab).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-05-13 11:16 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-05-13 11:16 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/76898/
Test PASSed.

2017-05-13 19:51 UTC, zero323 commented on R/pkg/R/generics.R
> +setGeneric("broadcast", function(x) { standardGeneric("broadcast") })
> this list is sorted alphabetically within this section

Looks like it used to be at some point, but these days are long gone. I can reorder it right now, but this means rearranging a whole section.

2017-05-14 18:02 UTC, felixcheung commented on R/pkg/R/generics.R
> +setGeneric("broadcast", function(x) { standardGeneric("broadcast") })
ouch it is `#` and not `#'`

let's leave the sorting for now. we really need to stick with one method

2017-05-14 18:49 UTC, felixcheung requested changes
I think we need to add broadcast to NAMESPACE
https://github.com/apache/spark/blob/master/R/pkg/NAMESPACE

(testthat is running inside the SparkR namespace)

2017-05-14 18:51 UTC, felixcheung commented on R/pkg/R/generics.R
> +setGeneric("broadcast", function(x) { standardGeneric("broadcast") })
let's fix up the sorting when 2.2.0 is released - it would help to minimize major changes for now to make it easier to merge fixes.

2017-05-14 19:12 UTC, SparkQA commented
**[Test build #76912 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/76912/testReport)** for PR 17965 at commit [`d6c3435`](https://github.com/apache/spark/commit/d6c343538a731a45353bec5a7c290a201756039b).

2017-05-14 19:45 UTC, SparkQA commented
**[Test build #76912 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/76912/testReport)** for PR 17965 at commit [`d6c3435`](https://github.com/apache/spark/commit/d6c343538a731a45353bec5a7c290a201756039b).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-05-14 19:45 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-05-14 19:45 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/76912/
Test PASSed.

2017-05-14 20:22 UTC, felixcheung approved these changes
LGTM, Jenkins passed, AppVeyor passed before

2017-05-14 20:23 UTC, felixcheung commented
merged to master

2017-05-14 20:26 UTC, closed without merging