[SPARK-20759] SCALA_VERSION in _config.yml should be consistent with  pom.xml
apache/spark pull request #17992
Opened 2017-05-16 03:17 UTC by liu-zhaokun

[https://issues.apache.org/jira/browse/SPARK-20759](https://issues.apache.org/jira/browse/SPARK-20759)
SCALA_VERSION in _config.yml is 2.11.7, but 2.11.8 in pom.xml. So I think SCALA_VERSION in _config.yml should be consistent with pom.xml.

2017-05-16 08:59 UTC, srowen commented
@liu-zhaokun there are more changes to be made. Please make all the changes in https://github.com/apache/spark/pull/17982/files but don't update to 2.11.11; stay on 2.11.8.

2017-05-16 09:35 UTC, liu-zhaokun commented
@srowen 
Hello, I have made some changes according to your advice.Please review the new PR?

2017-05-16 10:53 UTC, srowen requested changes

2017-05-16 10:53 UTC, srowen commented on repl/scala-2.11/src/main/scala/org/apache/spark/repl/SparkILoop.scala
> +   * We override `createInterpreter` because we need to initialize Spark *before* the REPL
Sorry, I meant you should follow the version changes. You can't take this change; it depends on 2.11.11

2017-05-16 10:53 UTC, srowen commented on build/mvn
> +  local zinc_path="zinc-0.3.15/bin/zinc"
Don't change the zinc version here

2017-05-16 11:41 UTC, liu-zhaokun commented
@srowen 
Thanks for your reply.I modified the files again.Please review it.

2017-05-16 11:43 UTC, srowen approved these changes

2017-05-16 15:18 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-05-17 06:58 UTC, liu-zhaokun commented
@srowen 
Hi,could you help me merge this PR?

2017-05-17 08:10 UTC, srowen commented
It isn't tested yet, no. Jenkins isn't working right now

2017-05-17 09:35 UTC, SparkQA commented
**[Test build #3718 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3718/testReport)** for PR 17992 at commit [`7f0c75a`](https://github.com/apache/spark/commit/7f0c75a6d39632a65f112f06832cc7ad430d9b10).

2017-05-17 20:23 UTC, SparkQA commented
**[Test build #3719 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3719/testReport)** for PR 17992 at commit [`7f0c75a`](https://github.com/apache/spark/commit/7f0c75a6d39632a65f112f06832cc7ad430d9b10).

2017-05-18 05:59 UTC, liu-zhaokun commented
@srowen 
The test doesn't finish,need I do anything?

2017-05-19 01:06 UTC, liu-zhaokun commented
@srowen  
Hello,do you know how to finish the test?

2017-05-19 06:41 UTC, SparkQA commented
**[Test build #3723 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3723/testReport)** for PR 17992 at commit [`7f0c75a`](https://github.com/apache/spark/commit/7f0c75a6d39632a65f112f06832cc7ad430d9b10).

2017-05-19 08:27 UTC, liu-zhaokun commented
@srowen 
Hi,do you know why this PR can't pass the test? I don't think it's my problem.

2017-05-19 11:32 UTC, SparkQA commented
**[Test build #3732 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3732/testReport)** for PR 17992 at commit [`7f0c75a`](https://github.com/apache/spark/commit/7f0c75a6d39632a65f112f06832cc7ad430d9b10).

2017-05-19 14:25 UTC, SparkQA commented
**[Test build #3732 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3732/testReport)** for PR 17992 at commit [`7f0c75a`](https://github.com/apache/spark/commit/7f0c75a6d39632a65f112f06832cc7ad430d9b10).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-05-19 14:28 UTC, srowen commented
Merged to master/2.2/2.1

2017-05-19 14:29 UTC, closed without merging