[SPARK-20883][SPARK-20376][SS] Refactored StateStore APIs and added conf to choose implementation
apache/spark pull request #18107
Opened 2017-05-25 11:11 UTC by tdas

## What changes were proposed in this pull request?

A bunch of changes to the StateStore APIs and implementation.
Current state store API has a bunch of problems that causes too many transient objects causing memory pressure.
- `StateStore.get(): Option` forces creation of Some/None objects for every get. Changed this to return the row or null.
- `StateStore.iterator(): (UnsafeRow, UnsafeRow)` forces creation of new tuple for each record returned. Changed this to return a UnsafeRowTuple which can be reused across records.
- `StateStore.updates()` requires the implementation to keep track of updates, while this is used minimally (only by Append mode in streaming aggregations). Removed this.

Additionally,
- Added a configuration that allows the user to specify which implementation to use. 
- Added new metrics to understand the time taken to update keys, remove keys and commit all changes to the state store. These metrics will be visible on the plan diagram in the SQL tab of the UI.
- Refactored unit tests such that they can be reused to test any implementation of StateStore.

## How was this patch tested?
Old and new unit tests

2017-05-25 11:11 UTC, tdas commented on sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala
> +        "Minimum number of state store delta files that needs to be generated before they " +
update this description

2017-05-25 11:12 UTC, SparkQA commented
**[Test build #77362 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77362/testReport)** for PR 18107 at commit [`03f5bf3`](https://github.com/apache/spark/commit/03f5bf3f1fc4e6d60b43d7c05a3cdc6dddcbd1af).

2017-05-25 11:15 UTC, SparkQA commented
**[Test build #77362 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77362/testReport)** for PR 18107 at commit [`03f5bf3`](https://github.com/apache/spark/commit/03f5bf3f1fc4e6d60b43d7c05a3cdc6dddcbd1af).
 * This patch **fails build dependency tests**.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `case class StateStoreId(`
  * `case class StateStoreStats()`
  * `case class UnsafeRowTuple(var key: UnsafeRow = null, var value: UnsafeRow = null) `
  * `trait StateStoreWriter extends StatefulOperator `

2017-05-25 11:15 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-05-25 11:15 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/77362/
Test FAILed.

2017-05-25 11:18 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/StateStore.scala
> +case class StateStoreStats()
remove this

2017-05-25 11:18 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/StateStore.scala
> +  def getRange(start: Option[UnsafeRow], end: Option[UnsafeRow]): Iterator[UnsafeRowTuple]
add docs

2017-05-25 11:19 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/StateStore.scala
> +  def instantiate(
add docs.

2017-05-25 11:20 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/statefulOperators.scala
> +            allUpdatesTimeMs += timeTakenMs {
this update is to accommodate for removal of StateStore.updates()

2017-05-25 11:22 UTC, SparkQA commented
**[Test build #77363 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77363/testReport)** for PR 18107 at commit [`d645b41`](https://github.com/apache/spark/commit/d645b416ddd79b56c00bb443569de4c7af5de4fb).

2017-05-25 11:23 UTC, SparkQA commented
**[Test build #3755 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3755/testReport)** for PR 18107 at commit [`d645b41`](https://github.com/apache/spark/commit/d645b416ddd79b56c00bb443569de4c7af5de4fb).

2017-05-25 12:49 UTC, SparkQA commented
**[Test build #3755 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3755/testReport)** for PR 18107 at commit [`d645b41`](https://github.com/apache/spark/commit/d645b416ddd79b56c00bb443569de4c7af5de4fb).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `case class StateStoreId(`
  * `case class StateStoreStats()`
  * `case class UnsafeRowTuple(var key: UnsafeRow = null, var value: UnsafeRow = null) `
  * `trait StateStoreWriter extends StatefulOperator `

2017-05-25 12:50 UTC, SparkQA commented
**[Test build #77363 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77363/testReport)** for PR 18107 at commit [`d645b41`](https://github.com/apache/spark/commit/d645b416ddd79b56c00bb443569de4c7af5de4fb).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `case class StateStoreId(`
  * `case class StateStoreStats()`
  * `case class UnsafeRowTuple(var key: UnsafeRow = null, var value: UnsafeRow = null) `
  * `trait StateStoreWriter extends StatefulOperator `

2017-05-25 12:50 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-05-25 12:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/77363/
Test FAILed.

2017-05-25 20:07 UTC, SparkQA commented
**[Test build #77386 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77386/testReport)** for PR 18107 at commit [`324fc24`](https://github.com/apache/spark/commit/324fc24f4b9e6c6aa31df45955afa7ca5471ab63).

2017-05-25 22:05 UTC, tdas commented on sql/core/src/test/scala/org/apache/spark/sql/streaming/FlatMapGroupsWithStateSuite.scala
> -  test("StateStoreUpdater - rows are cloned before writing to StateStore") {
This is not needed any more as the operator is not responsible for cloning the rows when writing to the store.

2017-05-25 22:21 UTC, SparkQA commented
**[Test build #77386 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77386/testReport)** for PR 18107 at commit [`324fc24`](https://github.com/apache/spark/commit/324fc24f4b9e6c6aa31df45955afa7ca5471ab63).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-05-25 22:22 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-05-25 22:22 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/77386/
Test PASSed.

2017-05-26 03:37 UTC, SparkQA commented
**[Test build #77402 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77402/testReport)** for PR 18107 at commit [`3e49621`](https://github.com/apache/spark/commit/3e496217811755f756a9acaabb686200d0be15f1).

2017-05-26 05:56 UTC, SparkQA commented
**[Test build #77402 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77402/testReport)** for PR 18107 at commit [`3e49621`](https://github.com/apache/spark/commit/3e496217811755f756a9acaabb686200d0be15f1).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `case class StateStoreId(`
  * `case class UnsafeRowPair(var key: UnsafeRow = null, var value: UnsafeRow = null) `

2017-05-26 05:57 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-05-26 05:57 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/77402/
Test PASSed.

2017-05-30 05:51 UTC, zsxwing requested changes
Looks pretty good. My major comment is [Prefer nanoTime over currentTimeMillis](https://github.com/databricks/scala-style-guide#misc_currentTimeMillis_vs_nanoTime)

2017-05-30 05:51 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/StateStore.scala
> +    val provider = Utils.getContextOrSparkClassLoader
nit: Use `Utils.classForName(providerClass)`.

2017-05-30 05:51 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/StateStore.scala
> +   * Get the current value of a non-null key.
nit: please mention that `null` means key doesn't exist.

2017-05-30 05:51 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/StateStore.scala
> +   * @note put cannot be done once
Could you clarify it?

2017-05-30 05:51 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/statefulOperators.scala
> +                allRemovalsTimeMs += System.currentTimeMillis - removalStartTime
nit: please use `nanoTime`

2017-05-30 05:51 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/statefulOperators.scala
> +            val updatesStartTimeMs = System.currentTimeMillis
nit: please use `nanoTime`

2017-05-30 05:51 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/statefulOperators.scala
> +
nit: extra empty lines

2017-05-30 05:51 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/statefulOperators.scala
> +      val updatesStartTimeMs = System.currentTimeMillis
nit: please use `nanoTime`

2017-05-30 05:51 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/statefulOperators.scala
> +        allUpdatesTimeMs += System.currentTimeMillis - updatesStartTimeMs
nit: please use `nanoTime`

2017-05-30 05:51 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/statefulOperators.scala
> +                  val UnsafeRowPair(keyRow, valueRow) = rangeIter.next()
Case class's `unapply` will create a `Tuple`. You should not use this Scala syntactic sugar :)

2017-05-30 18:00 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/statefulOperators.scala
> +                  val UnsafeRowPair(keyRow, valueRow) = rangeIter.next()
That is true! I had assumed unapply will get desugared into something simple, but its probably best to not to rely on the Scala compiler so much.

2017-05-30 18:01 UTC, tdas commented on sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala
> +  def stateStoreProviderClass: Option[String] = getConf(STATE_STORE_PROVIDER_CLASS)
Good idea.

2017-05-30 18:01 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/StateStore.scala
> +   * Get the current value of a non-null key.
Good point.

2017-05-30 19:32 UTC, SparkQA commented
**[Test build #77546 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77546/testReport)** for PR 18107 at commit [`baba63d`](https://github.com/apache/spark/commit/baba63d68adff67b99d651225083a89353ecb154).

2017-05-30 19:42 UTC, SparkQA commented
**[Test build #77547 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77547/testReport)** for PR 18107 at commit [`5c0961c`](https://github.com/apache/spark/commit/5c0961cf302ae7a02bfa603a8ddd0ccfa54a062c).

2017-05-30 19:47 UTC, SparkQA commented
**[Test build #77549 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77549/testReport)** for PR 18107 at commit [`fdfdcab`](https://github.com/apache/spark/commit/fdfdcabacbec7cd1c1040dcd0c86d74e417c2f5e).

2017-05-30 20:01 UTC, zsxwing commented
LGTM pending tests.

2017-05-30 21:49 UTC, SparkQA commented
**[Test build #77546 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77546/testReport)** for PR 18107 at commit [`baba63d`](https://github.com/apache/spark/commit/baba63d68adff67b99d651225083a89353ecb154).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `class UnsafeRowPair(var key: UnsafeRow = null, var value: UnsafeRow = null) `

2017-05-30 21:50 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-05-30 21:50 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/77546/
Test PASSed.

2017-05-30 21:59 UTC, SparkQA commented
**[Test build #77547 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77547/testReport)** for PR 18107 at commit [`5c0961c`](https://github.com/apache/spark/commit/5c0961cf302ae7a02bfa603a8ddd0ccfa54a062c).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-05-30 22:00 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-05-30 22:00 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/77547/
Test PASSed.

2017-05-30 22:01 UTC, SparkQA commented
**[Test build #77549 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77549/testReport)** for PR 18107 at commit [`fdfdcab`](https://github.com/apache/spark/commit/fdfdcabacbec7cd1c1040dcd0c86d74e417c2f5e).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-05-30 22:02 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-05-30 22:02 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/77549/
Test PASSed.

2017-05-30 22:32 UTC, zsxwing commented
Thanks! Merging to master.

2017-05-30 22:36 UTC, closed without merging