[SPARK-21006][TESTS][FOLLOW-UP]Some Worker's RpcEnv is leaked in WorkerSuite
apache/spark pull request #18259
Opened 2017-06-10 09:13 UTC by 10110346

## What changes were proposed in this pull request?

Create rpcEnv and run later needs shutdown. as #18226

## How was this patch tested?
unit test

2017-06-10 09:19 UTC, SparkQA commented
**[Test build #77873 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77873/testReport)** for PR 18259 at commit [`77653f4`](https://github.com/apache/spark/commit/77653f4308d11ea6fa49a709cd0f3f74bb112187).

2017-06-10 09:40 UTC, srowen commented
@10110346 do you know of other related changes? we should make them all at once.

2017-06-10 12:21 UTC, SparkQA commented
**[Test build #77873 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77873/testReport)** for PR 18259 at commit [`77653f4`](https://github.com/apache/spark/commit/77653f4308d11ea6fa49a709cd0f3f74bb112187).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `class WorkerSuite extends SparkFunSuite with Matchers with BeforeAndAfter `

2017-06-10 12:22 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-06-10 12:22 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/77873/
Test PASSed.

2017-06-11 09:04 UTC, srowen commented on core/src/test/scala/org/apache/spark/deploy/worker/WorkerSuite.scala
> +  after {
Shouldn't this be `override def after(): Unit = {`?

2017-06-12 00:49 UTC, 10110346 commented on core/src/test/scala/org/apache/spark/deploy/worker/WorkerSuite.scala
> +  after {
@srowen Because `BeforeAndAfter` is a `trait`,so we can simplify.
  I referenced the 'MasterSuite.scala'

2017-06-12 01:02 UTC, 10110346 commented
@srowen Thanks. I have checked  in the whole project,there are no more  related changes

2017-06-12 09:13 UTC, srowen requested changes

2017-06-12 09:13 UTC, srowen commented on core/src/test/scala/org/apache/spark/deploy/worker/WorkerSuite.scala
> +  after {
That's bad practice, and why `override` exists. For example if you wrote `afer {` you'd maybe never notice that your cleanup code was silently not being triggered.

The code doesn't do this consistently, but more often does write the full declaration, which is probably a good idea. I'd recommend changing this one.

2017-06-12 09:13 UTC, srowen commented on core/src/test/scala/org/apache/spark/deploy/worker/WorkerSuite.scala
> +  private def makeWorker(conf: SparkConf): Worker = {
Space before

2017-06-12 09:13 UTC, srowen commented on core/src/test/scala/org/apache/spark/deploy/worker/WorkerSuite.scala
> +  after {
Space before for readability

2017-06-12 09:21 UTC, 10110346 commented on core/src/test/scala/org/apache/spark/deploy/worker/WorkerSuite.scala
> +  after {
@srowen I agree with you, i will change this one,thanks

2017-06-12 09:38 UTC, SparkQA commented
**[Test build #77929 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77929/testReport)** for PR 18259 at commit [`d4ee0ce`](https://github.com/apache/spark/commit/d4ee0ceac3c1175fc6e3469a0c49619ce80aa1ef).

2017-06-12 09:38 UTC, 10110346 commented on core/src/test/scala/org/apache/spark/deploy/worker/WorkerSuite.scala
> +  after {
@srowen I have tried to change it, But `after()` must write like this

2017-06-12 12:12 UTC, SparkQA commented
**[Test build #77929 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77929/testReport)** for PR 18259 at commit [`d4ee0ce`](https://github.com/apache/spark/commit/d4ee0ceac3c1175fc6e3469a0c49619ce80aa1ef).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `class WorkerSuite extends SparkFunSuite with Matchers with BeforeAndAfter `

2017-06-12 12:13 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-06-12 12:13 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/77929/
Test FAILed.

2017-06-13 00:42 UTC, SparkQA commented
**[Test build #77955 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77955/testReport)** for PR 18259 at commit [`67913fd`](https://github.com/apache/spark/commit/67913fdd33d88cc2ffedd8a4cd6886421aa8684d).

2017-06-13 02:47 UTC, SparkQA commented
**[Test build #77955 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77955/testReport)** for PR 18259 at commit [`67913fd`](https://github.com/apache/spark/commit/67913fdd33d88cc2ffedd8a4cd6886421aa8684d).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `class WorkerSuite extends SparkFunSuite with Matchers with BeforeAndAfter `

2017-06-13 02:48 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-06-13 02:48 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/77955/
Test FAILed.

2017-06-13 05:37 UTC, SparkQA commented
**[Test build #77964 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77964/testReport)** for PR 18259 at commit [`4787b9b`](https://github.com/apache/spark/commit/4787b9ba12177ba9bf89ae8c5711264425e34514).

2017-06-13 07:05 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-06-13 07:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/77964/
Test FAILed.

2017-06-13 07:44 UTC, 10110346 commented
Jenkins, retest this please

2017-06-13 07:48 UTC, SparkQA commented
**[Test build #77980 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77980/testReport)** for PR 18259 at commit [`4787b9b`](https://github.com/apache/spark/commit/4787b9ba12177ba9bf89ae8c5711264425e34514).

2017-06-13 11:22 UTC, SparkQA commented
**[Test build #77980 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/77980/testReport)** for PR 18259 at commit [`4787b9b`](https://github.com/apache/spark/commit/4787b9ba12177ba9bf89ae8c5711264425e34514).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `class WorkerSuite extends SparkFunSuite with Matchers with BeforeAndAfter `

2017-06-13 11:23 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-06-13 11:23 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/77980/
Test PASSed.

2017-06-13 11:29 UTC, srowen commented
Merged to master

2017-06-13 11:33 UTC, closed without merging