[SPARK-21263][SQL] Do not allow partially parsing double and floats via NumberFormat in CSV
apache/spark pull request #18532
Opened 2017-07-04 23:45 UTC by HyukjinKwon

## What changes were proposed in this pull request?

This PR proposes to remove `NumberFormat.parse` use to disallow a case of partially parsed data. For example,

```
scala> spark.read.schema("a DOUBLE").option("mode", "FAILFAST").csv(Seq("10u12").toDS).show()
+----+
|   a|
+----+
|10.0|
+----+
```

## How was this patch tested?

Unit tests added in `UnivocityParserSuite` and `CSVSuite`.

2017-07-04 23:45 UTC, HyukjinKwon commented
cc @srowen and @falaki, could you take a look and see if I understood correctly?

2017-07-04 23:47 UTC, HyukjinKwon commented on sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/csv/UnivocityParser.scala
> -        case datum =>
BTW, it looks we are not using `NumberFormat.parse` in schema inference - https://github.com/apache/spark/blob/7e5359be5ca038fdb579712b18e7f226d705c276/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/csv/CSVInferSchema.scala#L141

2017-07-04 23:47 UTC, SparkQA commented
**[Test build #79167 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79167/testReport)** for PR 18532 at commit [`024dfcc`](https://github.com/apache/spark/commit/024dfccaf8969edb8f1bc719063d3bc97ebff64b).

2017-07-04 23:54 UTC, falaki requested changes

2017-07-04 23:54 UTC, falaki commented on sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/csv/CSVSuite.scala
> +  test("Do not partially lose data when parsing float and double") {
I suggest a better description for this test and please include the JIRA number. E.g., 
```SPARK-21263: Invalid float and double are handled correctly in different modes```

2017-07-05 00:04 UTC, HyukjinKwon commented on sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/csv/CSVSuite.scala
> +  test("Do not partially lose data when parsing float and double") {
Sure, thanks.

2017-07-05 00:07 UTC, SparkQA commented
**[Test build #79168 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79168/testReport)** for PR 18532 at commit [`32233dd`](https://github.com/apache/spark/commit/32233dd1d5772b5df57919fabc467a197574fa72).

2017-07-05 00:22 UTC, SparkQA commented
**[Test build #79169 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79169/testReport)** for PR 18532 at commit [`a41c028`](https://github.com/apache/spark/commit/a41c028392acf70600f2e882cafdf59ad50def14).

2017-07-05 01:44 UTC, SparkQA commented
**[Test build #79168 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79168/testReport)** for PR 18532 at commit [`32233dd`](https://github.com/apache/spark/commit/32233dd1d5772b5df57919fabc467a197574fa72).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-07-05 01:45 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-07-05 01:45 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/79168/
Test FAILed.

2017-07-05 02:01 UTC, SparkQA commented
**[Test build #79167 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79167/testReport)** for PR 18532 at commit [`024dfcc`](https://github.com/apache/spark/commit/024dfccaf8969edb8f1bc719063d3bc97ebff64b).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-07-05 02:02 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-07-05 02:02 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/79167/
Test PASSed.

2017-07-05 02:36 UTC, SparkQA commented
**[Test build #79169 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79169/testReport)** for PR 18532 at commit [`a41c028`](https://github.com/apache/spark/commit/a41c028392acf70600f2e882cafdf59ad50def14).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-07-05 02:37 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-07-05 02:37 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/79169/
Test PASSed.

2017-07-05 21:39 UTC, falaki reviewed
Minor suggestions. Otherwise LGTM

2017-07-05 21:39 UTC, falaki commented on sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/csv/UnivocityParserSuite.scala
> +    assert(message.contains("10u000"))
Is there some more specific error we could check for?

2017-07-05 21:39 UTC, falaki commented on sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/csv/UnivocityParserSuite.scala
> +    assert(message.contains("10u000"))
dito

2017-07-05 21:39 UTC, falaki commented on sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/csv/CSVSuite.scala
> +    assert(exception.getMessage.contains("10u12"))
Can we check for more specific error message?

2017-07-06 02:38 UTC, HyukjinKwon commented
Thank you @falaki. I just updated.

2017-07-06 02:42 UTC, SparkQA commented
**[Test build #79256 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79256/testReport)** for PR 18532 at commit [`c1967f8`](https://github.com/apache/spark/commit/c1967f80e340b374e2d6b0e7b9759d0d61a9df13).

2017-07-06 04:55 UTC, SparkQA commented
**[Test build #79256 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79256/testReport)** for PR 18532 at commit [`c1967f8`](https://github.com/apache/spark/commit/c1967f80e340b374e2d6b0e7b9759d0d61a9df13).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-07-06 04:56 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-07-06 04:56 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/79256/
Test PASSed.

2017-07-08 07:36 UTC, srowen approved these changes

2017-07-11 10:11 UTC, srowen commented
Merged to master

2017-07-11 10:13 UTC, closed without merging