[SPARK-21315][SQL]Skip some spill files when generateIterator(startIndex) in ExternalAppendOnlyUnsafeRowArray.
apache/spark pull request #18541
Opened 2017-07-05 10:25 UTC by jinxing64

## What changes were proposed in this pull request?

In current code, it is expensive to use `UnboundedFollowingWindowFunctionFrame`, because it is iterating from the start to lower bound every time calling `write` method. When traverse the iterator, it's possible to skip some spilled files thus to save some time.

## How was this patch tested?

Added unit test

2017-07-05 10:27 UTC, SparkQA commented
**[Test build #79213 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79213/testReport)** for PR 18541 at commit [`442abb3`](https://github.com/apache/spark/commit/442abb32cc08a3311ce6540e7e40c4b62e51a0c1).

2017-07-05 12:37 UTC, SparkQA commented
**[Test build #79213 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79213/testReport)** for PR 18541 at commit [`442abb3`](https://github.com/apache/spark/commit/442abb32cc08a3311ce6540e7e40c4b62e51a0c1).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-07-05 12:37 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-07-05 12:37 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/79213/
Test FAILed.

2017-07-05 12:46 UTC, hvanhovell requested changes
This looks promising. I left a few minor comments. Can you also post some benchmarks?

2017-07-05 12:46 UTC, hvanhovell commented on core/src/main/java/org/apache/spark/util/collection/unsafe/sort/UnsafeExternalSorter.java
> +        UnsafeSorterIterator iter = inMemSorter.getSortedIterator();
This is almost similar to the code in the first if clause. Let's try to get rid of this duplication, and move this logic into a separate function.

2017-07-05 12:46 UTC, hvanhovell commented on core/src/main/java/org/apache/spark/util/collection/unsafe/sort/UnsafeExternalSorter.java
> +          continue;
Nit: remove continue. It is useless and confusing.

2017-07-05 12:46 UTC, hvanhovell commented on core/src/main/java/org/apache/spark/util/collection/unsafe/sort/UnsafeExternalSorter.java
> +  public UnsafeSorterIterator getIterator() throws IOException {
Shall we remove this method?

2017-07-05 12:46 UTC, hvanhovell commented on core/src/main/java/org/apache/spark/util/collection/unsafe/sort/UnsafeExternalSorter.java
> +  public UnsafeSorterIterator getIterator(int startIndex) throws IOException {
Can you update the documentation and add the parameter?

2017-07-05 12:47 UTC, hvanhovell commented
retest this please

2017-07-05 12:52 UTC, SparkQA commented
**[Test build #79216 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79216/testReport)** for PR 18541 at commit [`442abb3`](https://github.com/apache/spark/commit/442abb32cc08a3311ce6540e7e40c4b62e51a0c1).

2017-07-05 15:37 UTC, SparkQA commented
**[Test build #79216 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79216/testReport)** for PR 18541 at commit [`442abb3`](https://github.com/apache/spark/commit/442abb32cc08a3311ce6540e7e40c4b62e51a0c1).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-07-05 15:38 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-07-05 15:38 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/79216/
Test PASSed.

2017-07-06 12:17 UTC, SparkQA commented
**[Test build #79282 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79282/testReport)** for PR 18541 at commit [`8425aae`](https://github.com/apache/spark/commit/8425aaec77cd6611e88930034bdd285e7e3cac17).

2017-07-06 12:33 UTC, jinxing64 commented
Did a small test:
2000200 rows in the `UnsafeExternalSorter`: 2 spill files(each contains 1000000 rows) and `inMemSorter` contains 200 rows.
I want to target the iterator to index=2000001.

With this change: `getIterator(2000001)`, it will cost almost 0ms~1ms;
Without this change:
`for(int i=0; i<2000001; i++)geIterator().loadNext()`, it will cost 300ms;

2017-07-06 12:34 UTC, jinxing64 commented
@hvanhovell 
I refined according to your comments. Please take another look when you have time :)

2017-07-06 15:06 UTC, SparkQA commented
**[Test build #79282 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79282/testReport)** for PR 18541 at commit [`8425aae`](https://github.com/apache/spark/commit/8425aaec77cd6611e88930034bdd285e7e3cac17).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-07-06 15:07 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-07-06 15:07 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/79282/
Test PASSed.

2017-07-09 07:15 UTC, dongjoon-hyun commented on core/src/main/java/org/apache/spark/util/collection/unsafe/sort/UnsafeExternalSorter.java
> +   * Returns a iterator starts from startIndex, which will return the rows in the order as inserted.
nit: `a iterator` -> `an iterator`.

2017-07-09 08:39 UTC, jinxing64 commented on core/src/main/java/org/apache/spark/util/collection/unsafe/sort/UnsafeExternalSorter.java
> +   * Returns a iterator starts from startIndex, which will return the rows in the order as inserted.
Sure thing.

2017-07-09 08:41 UTC, jinxing64 commented
@cloud-fan 
Would you mind take a look when  you have time :)

2017-07-09 08:42 UTC, SparkQA commented
**[Test build #79411 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79411/testReport)** for PR 18541 at commit [`a0d90c9`](https://github.com/apache/spark/commit/a0d90c9953798808295ea5fb1f0b69be6247b79f).

2017-07-09 11:31 UTC, SparkQA commented
**[Test build #79411 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79411/testReport)** for PR 18541 at commit [`a0d90c9`](https://github.com/apache/spark/commit/a0d90c9953798808295ea5fb1f0b69be6247b79f).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-07-09 11:32 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-07-09 11:32 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/79411/
Test PASSed.

2017-07-10 03:49 UTC, cloud-fan commented on core/src/main/java/org/apache/spark/util/collection/unsafe/sort/UnsafeExternalSorter.java
> +  private void moveOver(UnsafeSorterIterator iter, int currentIndex, int targetIndex)
instead of having 2 parameters, I think we have just have one `int steps`.

2017-07-10 03:51 UTC, cloud-fan commented on core/src/main/java/org/apache/spark/util/collection/unsafe/sort/UnsafeExternalSorter.java
> +          i += spillWriter.recordsSpilled();
shall we break the loop here?

2017-07-10 03:55 UTC, cloud-fan commented
LGTM except some minor comments, good catch!

2017-07-10 04:57 UTC, SparkQA commented
**[Test build #79437 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79437/testReport)** for PR 18541 at commit [`473483d`](https://github.com/apache/spark/commit/473483d541bfe6b18106f9b7f1fd571ff23fad48).

2017-07-10 06:07 UTC, kiszk commented on core/src/main/java/org/apache/spark/util/collection/unsafe/sort/UnsafeExternalSorter.java
> +          i += spillWriter.recordsSpilled();
nit: Can we move lines 611 and 617 after line 618 since they are the same? If we could do this, we can update line 610, too.

2017-07-10 06:31 UTC, jinxing64 commented on core/src/main/java/org/apache/spark/util/collection/unsafe/sort/UnsafeExternalSorter.java
> +          i += spillWriter.recordsSpilled();
Sure

2017-07-10 06:37 UTC, SparkQA commented
**[Test build #79444 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79444/testReport)** for PR 18541 at commit [`3ab157d`](https://github.com/apache/spark/commit/3ab157d89f240ac014bc48ef67fdde859e040ab6).

2017-07-10 06:55 UTC, cloud-fan commented on core/src/main/java/org/apache/spark/util/collection/unsafe/sort/UnsafeExternalSorter.java
> +      for (int i = 0; i < steps && iter.hasNext(); i++) {
nit: we should move `iter.hasNext` to the loop body with an assert, to match the original behavior: https://github.com/apache/spark/pull/18541/files#diff-a17b7c6b3521a3e93f958a634501b7f6L219

2017-07-10 07:04 UTC, SparkQA commented
**[Test build #79444 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79444/testReport)** for PR 18541 at commit [`3ab157d`](https://github.com/apache/spark/commit/3ab157d89f240ac014bc48ef67fdde859e040ab6).
 * This patch **fails due to an unknown error code, -9**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-07-10 07:04 UTC, SparkQA commented
**[Test build #79437 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79437/testReport)** for PR 18541 at commit [`473483d`](https://github.com/apache/spark/commit/473483d541bfe6b18106f9b7f1fd571ff23fad48).
 * This patch **fails due to an unknown error code, -9**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-07-10 07:05 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-07-10 07:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/79444/
Test FAILed.

2017-07-10 07:05 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-07-10 07:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/79437/
Test FAILed.

2017-07-10 07:32 UTC, SparkQA commented
**[Test build #79453 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79453/testReport)** for PR 18541 at commit [`c319dc9`](https://github.com/apache/spark/commit/c319dc98db6cbb7a25b7fed4d8528c8a9c5d1e59).

2017-07-10 10:25 UTC, SparkQA commented
**[Test build #79453 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79453/testReport)** for PR 18541 at commit [`c319dc9`](https://github.com/apache/spark/commit/c319dc98db6cbb7a25b7fed4d8528c8a9c5d1e59).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-07-10 10:26 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-07-10 10:26 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/79453/
Test PASSed.

2017-07-10 12:05 UTC, jiangxb1987 approved these changes
LGTM, could you also update the result of the benchmark to the PR description? Thanks for your effort!

2017-07-10 15:03 UTC, jinxing64 commented
@jiangxb1987 
Thanks for approving !
Already updated to PR description.

2017-07-10 16:18 UTC, dongjoon-hyun approved these changes
+1, LGTM, too.

2017-07-11 03:48 UTC, cloud-fan commented
thanks, merging to master!

2017-07-11 03:50 UTC, closed without merging