[SPARK-22238] Fix plan resolution bug caused by EnsureStatefulOpPartitioning
apache/spark pull request #19467
Opened 2017-10-10 22:07 UTC by brkyvz

## What changes were proposed in this pull request?

In EnsureStatefulOpPartitioning, we check that the inputRDD to a SparkPlan has the expected partitioning for Streaming Stateful Operators. The problem is that we are not allowed to access this information during planning.
The reason we added that check was because CoalesceExec could actually create RDDs with 0 partitions. We should fix it such that when CoalesceExec says that there is a SinglePartition, there is in fact an inputRDD of 1 partition instead of 0 partitions.

## How was this patch tested?

Regression test in StreamingQuerySuite

2017-10-10 22:08 UTC, SparkQA commented
**[Test build #82607 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/82607/testReport)** for PR 19467 at commit [`961ade1`](https://github.com/apache/spark/commit/961ade120f7a179751e5ec45b24e159259de0bae).

2017-10-10 23:13 UTC, SparkQA commented
**[Test build #82609 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/82609/testReport)** for PR 19467 at commit [`549b882`](https://github.com/apache/spark/commit/549b88237e727bbf9f00a0bd59d19ca072478dc5).

2017-10-11 00:42 UTC, SparkQA commented
**[Test build #82607 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/82607/testReport)** for PR 19467 at commit [`961ade1`](https://github.com/apache/spark/commit/961ade120f7a179751e5ec45b24e159259de0bae).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `  class EmptyRDDWithPartitions(`
  * `  case class SimplePartition(index: Int) extends Partition`
  * `case class EnsureStatefulOpPartitioning(conf: SQLConf) extends Rule[SparkPlan] `

2017-10-11 00:43 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-10-11 00:43 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/82607/
Test PASSed.

2017-10-11 01:43 UTC, SparkQA commented
**[Test build #82609 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/82609/testReport)** for PR 19467 at commit [`549b882`](https://github.com/apache/spark/commit/549b88237e727bbf9f00a0bd59d19ca072478dc5).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-10-11 01:44 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-10-11 01:44 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/82609/
Test PASSed.

2017-10-11 17:36 UTC, brkyvz commented
cc @tdas

2017-10-11 22:25 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/execution/basicPhysicalOperators.scala
> +  case class SimplePartition(index: Int) extends Partition
nit: EmptyPartition?  isnt that more descriptive than "simple"

2017-10-11 22:29 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/IncrementalExecution.scala
> +      val numPartitions = conf.numShufflePartitions
why this change?

2017-10-12 01:51 UTC, tdas requested changes
Added a few minor points. 
Major point (offline discussion) that the right way to do this is the codify the requirement for fixed number of partitions as a require child distribution, and let EnsureRequirement take care of ti.

2017-10-12 16:02 UTC, brkyvz commented on sql/core/src/main/scala/org/apache/spark/sql/execution/basicPhysicalOperators.scala
> +    if (numPartitions == 1 && child.execute().getNumPartitions < 1) {
the existing tests for the original problem should catch it

2017-10-12 16:03 UTC, SparkQA commented
**[Test build #82689 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/82689/testReport)** for PR 19467 at commit [`70211ca`](https://github.com/apache/spark/commit/70211ca3d3bb83a831634dfd9a9f5534eafdcdad).

2017-10-12 16:08 UTC, SparkQA commented
**[Test build #82690 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/82690/testReport)** for PR 19467 at commit [`48d1f25`](https://github.com/apache/spark/commit/48d1f25ccae8c8456a9a5d9c373208e573da1027).

2017-10-12 17:56 UTC, SparkQA commented
**[Test build #82689 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/82689/testReport)** for PR 19467 at commit [`70211ca`](https://github.com/apache/spark/commit/70211ca3d3bb83a831634dfd9a9f5534eafdcdad).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `case class ClusteredDistribution(`

2017-10-12 17:56 UTC, SparkQA commented
**[Test build #82690 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/82690/testReport)** for PR 19467 at commit [`48d1f25`](https://github.com/apache/spark/commit/48d1f25ccae8c8456a9a5d9c373208e573da1027).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `  case class EmptyPartition(index: Int) extends Partition`

2017-10-12 17:57 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-10-12 17:57 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/82689/
Test FAILed.

2017-10-12 17:57 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-10-12 17:57 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/82690/
Test FAILed.

2017-10-12 18:23 UTC, SparkQA commented
**[Test build #82699 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/82699/testReport)** for PR 19467 at commit [`3f51c5c`](https://github.com/apache/spark/commit/3f51c5ce7592e50d922864eb4d9643b984f73cba).

2017-10-12 20:12 UTC, SparkQA commented
**[Test build #82699 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/82699/testReport)** for PR 19467 at commit [`3f51c5c`](https://github.com/apache/spark/commit/3f51c5ce7592e50d922864eb4d9643b984f73cba).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-10-12 20:12 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-10-12 20:12 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/82699/
Test FAILed.

2017-10-12 20:28 UTC, SparkQA commented
**[Test build #82704 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/82704/testReport)** for PR 19467 at commit [`407d76c`](https://github.com/apache/spark/commit/407d76c57aea09232c2ca92df2eab4fc0d2d8838).

2017-10-12 21:43 UTC, SparkQA commented
**[Test build #82705 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/82705/testReport)** for PR 19467 at commit [`5122117`](https://github.com/apache/spark/commit/51221175458f28788352a0c315fa14577b5f0c87).

2017-10-12 23:14 UTC, SparkQA commented
**[Test build #82704 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/82704/testReport)** for PR 19467 at commit [`407d76c`](https://github.com/apache/spark/commit/407d76c57aea09232c2ca92df2eab4fc0d2d8838).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-10-12 23:15 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-10-12 23:15 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/82704/
Test PASSed.

2017-10-12 23:24 UTC, SparkQA commented
**[Test build #82705 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/82705/testReport)** for PR 19467 at commit [`5122117`](https://github.com/apache/spark/commit/51221175458f28788352a0c315fa14577b5f0c87).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `trait StatefulOperatorTest `

2017-10-12 23:24 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-10-12 23:24 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/82705/
Test FAILed.

2017-10-12 23:26 UTC, tdas approved these changes
Almost LGTM assuming tests pass. Just a few nits.

2017-10-12 23:26 UTC, tdas commented on sql/core/src/test/scala/org/apache/spark/sql/execution/streaming/state/StateStoreRDDSuite.scala
> -    StatefulOperatorStateInfo(path, queryRunId, operatorId = 0, version)
super nit: numPartitions = 5

2017-10-12 23:26 UTC, tdas commented on sql/core/src/test/scala/org/apache/spark/sql/streaming/StatefulOperatorTest.scala
> +      numPartitions: Option[Int] = None): Boolean = {
numPartitions is never used.

2017-10-12 23:26 UTC, tdas commented on sql/core/src/test/scala/org/apache/spark/sql/streaming/StatefulOperatorTest.scala
> +  protected def checkChildOutputPartitioning[T <: StatefulOperator](
since this is only for HashPartitioning, how about checkChildOutputHashPartitioning

2017-10-12 23:29 UTC, tdas commented
Whoops, i missed one comment. Not LGTM. Need tests in PlannerSuite that tests whether EnsureRequirements respects numPartitions in ClusteredDistribution.

2017-10-13 21:03 UTC, SparkQA commented
**[Test build #82747 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/82747/testReport)** for PR 19467 at commit [`84ac2d8`](https://github.com/apache/spark/commit/84ac2d84fff94a54a01d92f0ecf00c1f9ace4203).

2017-10-13 21:39 UTC, tdas commented
LGTM, assuming tests pass.

2017-10-13 22:56 UTC, SparkQA commented
**[Test build #82747 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/82747/testReport)** for PR 19467 at commit [`84ac2d8`](https://github.com/apache/spark/commit/84ac2d84fff94a54a01d92f0ecf00c1f9ace4203).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-10-13 22:56 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-10-13 22:56 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/82747/
Test FAILed.

2017-10-13 23:43 UTC, SparkQA commented
**[Test build #82749 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/82749/testReport)** for PR 19467 at commit [`971f579`](https://github.com/apache/spark/commit/971f57963a3f8f7f5b0481441fef387c80920048).

2017-10-14 02:30 UTC, SparkQA commented
**[Test build #82749 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/82749/testReport)** for PR 19467 at commit [`971f579`](https://github.com/apache/spark/commit/971f57963a3f8f7f5b0481441fef387c80920048).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-10-14 02:30 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-10-14 02:30 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/82749/
Test PASSed.

2017-10-15 00:24 UTC, tdas commented
Merging to master

2017-10-15 00:42 UTC, closed without merging