[SPARK-22305] Write HDFSBackedStateStoreProvider.loadMap non-recursively
apache/spark pull request #19611
Opened 2017-10-30 16:36 UTC by joseph-torres

## What changes were proposed in this pull request?
Write HDFSBackedStateStoreProvider.loadMap non-recursively. This prevents stack overflow if too many deltas stack up in a low memory environment.

## How was this patch tested?

existing unit tests for functional equivalence, new unit test to check for stack overflow

2017-10-30 16:37 UTC, SparkQA commented
**[Test build #83217 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/83217/testReport)** for PR 19611 at commit [`33ea2fb`](https://github.com/apache/spark/commit/33ea2fb59f5ad47ed4713ca73945a9630486677c).

2017-10-30 16:41 UTC, srowen requested changes
Just a few initial style comments

2017-10-30 16:41 UTC, srowen commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/HDFSBackedStateStoreProvider.scala
> +      lastAvailableVersion = lastAvailableVersion - 1
Nit: -= 1?

2017-10-30 16:41 UTC, srowen commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/HDFSBackedStateStoreProvider.scala
> +    if (currentVersionMap.isDefined) return currentVersionMap.get
I'd unroll this onto two lines with braces for consistency

2017-10-30 16:41 UTC, srowen commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/HDFSBackedStateStoreProvider.scala
> +    var resultMap = lastAvailableMap.get
val?

2017-10-30 16:41 UTC, srowen commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/HDFSBackedStateStoreProvider.scala
> +    return resultMap
Don't need return

2017-10-30 16:52 UTC, SparkQA commented
**[Test build #83220 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/83220/testReport)** for PR 19611 at commit [`70df407`](https://github.com/apache/spark/commit/70df4075c14cb4d5f1ecc76858c6071ef562205d).

2017-10-30 16:54 UTC, joseph-torres commented
One issue I want to explicitly bring up: this new unit test takes very long, almost 2 minutes on my computer. Creating 10k files isn't going to be super fast no matter what we do, but is there something that can mitigate the problem? Maybe it'd be better in a different suite or something; I don't know what the typical practice is.

2017-10-30 17:47 UTC, zsxwing commented
I think we can remove the unit test. It's obviously that `loadMap` is not recursive and will not cause StackOverflowError.

2017-10-30 18:57 UTC, SparkQA commented
**[Test build #83225 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/83225/testReport)** for PR 19611 at commit [`e81d142`](https://github.com/apache/spark/commit/e81d142eb9829eabcf5f106c4eda6acfc5265005).

2017-10-30 19:29 UTC, SparkQA commented
**[Test build #83217 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/83217/testReport)** for PR 19611 at commit [`33ea2fb`](https://github.com/apache/spark/commit/33ea2fb59f5ad47ed4713ca73945a9630486677c).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-10-30 19:30 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-10-30 19:30 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/83217/
Test PASSed.

2017-10-30 20:14 UTC, SparkQA commented
**[Test build #83220 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/83220/testReport)** for PR 19611 at commit [`70df407`](https://github.com/apache/spark/commit/70df4075c14cb4d5f1ecc76858c6071ef562205d).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-10-30 20:15 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-10-30 20:15 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/83220/
Test PASSed.

2017-10-30 20:57 UTC, zsxwing reviewed
Overall looks good. Left some comments

2017-10-30 20:57 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/HDFSBackedStateStoreProvider.scala
> +    val resultMap = lastAvailableMap.get
We should create a new map here to not change the previous map in case the maintenance task is using it.

2017-10-30 20:57 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/HDFSBackedStateStoreProvider.scala
> +      synchronized { loadedMaps.get(version) }.orElse(readSnapshotFile(version))
we should put the map read from snapshot file into `loadedMaps`.

2017-10-30 20:57 UTC, zsxwing commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/HDFSBackedStateStoreProvider.scala
> +    loadedMaps.put(version, resultMap)
`loadedMaps.put(version, resultMap)` -> `synchronized { loadedMaps.put(version, resultMap) }`

This is a different issue but since you are touching this, it's better to fix it as well.

2017-10-30 21:33 UTC, SparkQA commented
**[Test build #83229 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/83229/testReport)** for PR 19611 at commit [`d98ce9e`](https://github.com/apache/spark/commit/d98ce9e34050d0ef08a6e8802952a3c3bb6fc896).

2017-10-30 21:49 UTC, zsxwing commented
LGTM pending tests

2017-10-31 00:20 UTC, SparkQA commented
**[Test build #83229 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/83229/testReport)** for PR 19611 at commit [`d98ce9e`](https://github.com/apache/spark/commit/d98ce9e34050d0ef08a6e8802952a3c3bb6fc896).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2017-10-31 00:21 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-10-31 00:21 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/83229/
Test PASSed.

2017-10-31 18:53 UTC, zsxwing commented
Thanks! Merging to master.

2017-10-31 18:56 UTC, closed without merging

2017-11-06 12:26 UTC, briggsw commented
Is there any chance of this change getting merged into 2.2.1?

2017-11-06 19:42 UTC, zsxwing commented
@briggsw This is pretty hard to hit. I could not make it happen in a real query. So I think it's not worth to backport it.