[SPARK-23085][ML] API parity for mllib.linalg.Vectors.sparse
apache/spark pull request #20275
Opened 2018-01-16 06:12 UTC by zhengruifeng

## What changes were proposed in this pull request?
`ML.Vectors#sparse(size: Int, elements: Seq[(Int, Double)])` support zero-length

## How was this patch tested?
existing tests

2018-01-16 06:17 UTC, SparkQA commented
**[Test build #86158 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/86158/testReport)** for PR 20275 at commit [`1a3cd3a`](https://github.com/apache/spark/commit/1a3cd3aab355a00a73993979896624a8684a9aad).

2018-01-16 07:19 UTC, SparkQA commented
**[Test build #86158 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/86158/testReport)** for PR 20275 at commit [`1a3cd3a`](https://github.com/apache/spark/commit/1a3cd3aab355a00a73993979896624a8684a9aad).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-01-16 07:20 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-01-16 07:20 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/86158/
Test PASSed.

2018-01-16 13:36 UTC, mgaido91 commented
as far as I know mllib is not maintained anymore, thus I am not sure this fix is useful

2018-01-16 13:58 UTC, srowen commented
That's true, although, there's no conceptual reason not to support a 0-size vector, and the existing checks even checked for >= 0 in one case. This is arguably just fixing internal consistency. How about a unit test?

2018-01-17 02:32 UTC, SparkQA commented
**[Test build #86225 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/86225/testReport)** for PR 20275 at commit [`ac067e7`](https://github.com/apache/spark/commit/ac067e71164e0977ebc1098e3306751f680270ca).

2018-01-17 03:35 UTC, SparkQA commented
**[Test build #86225 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/86225/testReport)** for PR 20275 at commit [`ac067e7`](https://github.com/apache/spark/commit/ac067e71164e0977ebc1098e3306751f680270ca).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-01-17 03:36 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-01-17 03:36 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/86225/
Test PASSed.

2018-01-17 14:31 UTC, srowen approved these changes

2018-01-17 23:22 UTC, srowen commented
Unless someone like @jkbradley or @MLnick objects, I think this doesn't hurt and actually makes things a little more consistent.

2018-01-18 09:52 UTC, MLnick requested changes
Seems fine to add for consistency, even though `mllib` is no longer actively developed.

But we should round out the tests - I left a couple comments on that.

2018-01-18 09:52 UTC, MLnick commented on mllib/src/test/scala/org/apache/spark/mllib/linalg/VectorsSuite.scala
> +  test("zero-length sparse vector") {
We may as well add the same test to `ml.linalg`

2018-01-18 09:52 UTC, MLnick commented on mllib/src/test/scala/org/apache/spark/mllib/linalg/VectorsSuite.scala
> +  test("zero-length sparse vector") {
While we're doing this we may as well also add a test to `intercept` the exception for negative size (as per the other sparse vector construction tests), for both `ml` and `mllib`

2018-01-19 03:16 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-01-19 03:16 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution/25/
Test PASSed.

2018-01-19 03:17 UTC, SparkQA commented
**[Test build #86373 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/86373/testReport)** for PR 20275 at commit [`f3a4329`](https://github.com/apache/spark/commit/f3a4329d1ec0358de485ea0955f1dbb590342caf).

2018-01-19 04:22 UTC, SparkQA commented
**[Test build #86373 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/86373/testReport)** for PR 20275 at commit [`f3a4329`](https://github.com/apache/spark/commit/f3a4329d1ec0358de485ea0955f1dbb590342caf).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-01-19 04:22 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-01-19 04:22 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/86373/
Test PASSed.

2018-01-19 10:47 UTC, MLnick approved these changes
LGTM

2018-01-19 15:28 UTC, srowen commented
Merged to master

2018-01-19 15:31 UTC, closed without merging