[SPARK-23099][SS] Migrate foreach sink to DataSourceV2
apache/spark pull request #20552
Opened 2018-02-08 20:29 UTC by jose-torres

## What changes were proposed in this pull request?

Migrate the foreach sink to the DataSourceV2 API.

## How was this patch tested?

existing unit tests, and new test to verify edge case

2018-02-08 20:29 UTC, jose-torres commented
/cc @tdas

2018-02-08 20:31 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-02-08 20:32 UTC, SparkQA commented
**[Test build #87230 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/87230/testReport)** for PR 20552 at commit [`44de1ea`](https://github.com/apache/spark/commit/44de1ea878fb65e4e04ac6cd594f2e7c72ea2d5e).

2018-02-08 20:38 UTC, SparkQA commented
**[Test build #87230 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/87230/testReport)** for PR 20552 at commit [`44de1ea`](https://github.com/apache/spark/commit/44de1ea878fb65e4e04ac6cd594f2e7c72ea2d5e).
 * This patch **fails to build**.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `case class ForeachWriterProvider[T: Encoder](writer: ForeachWriter[T]) extends StreamWriteSupport `
  * `case class ForeachInternalWriter[T: Encoder](`
  * `case class ForeachWriterFactory[T: Encoder](writer: ForeachWriter[T], encoder: ExpressionEncoder[T])`
  * `class ForeachDataWriter[T : Encoder](`

2018-02-08 20:38 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2018-02-08 20:38 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/87230/
Test FAILed.

2018-02-08 20:52 UTC, SparkQA commented
**[Test build #87231 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/87231/testReport)** for PR 20552 at commit [`87d0bc8`](https://github.com/apache/spark/commit/87d0bc8ce23ab5a95ba0b5432d6b58042b32bdac).

2018-02-08 23:08 UTC, tdas requested changes
This is fine, just a few comments. But one major concern I have is the way we are indirectly exposing the batchId to the DataWriter (using job properties). If we are not exposing it directly, then essentially we are saying is that other data source build by general developers are not supposed to use batch ids in the executors for any purpose. In a way that is very odd: there is some transactional logic that you can write with ForeachWriter (which exposes the id), but you cannot write the same logic with DataSource V2 APIs. 

I know that the alternative is also not great; we will have to again split the StreamWriter to separate APIs for MicroBatch and Continuous.

2018-02-08 23:10 UTC, SparkQA commented
**[Test build #87231 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/87231/testReport)** for PR 20552 at commit [`87d0bc8`](https://github.com/apache/spark/commit/87d0bc8ce23ab5a95ba0b5432d6b58042b32bdac).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-02-08 23:10 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2018-02-08 23:10 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/87231/
Test FAILed.

2018-02-09 01:41 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/ForeachSink.scala
> +case class ForeachInternalWriter[T: Encoder](
actually.. probably should not inline this. its outer closure may not be serializable in that case.

2018-02-09 01:42 UTC, tdas commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/ForeachSink.scala
> +case class ForeachWriterFactory[T: Encoder](writer: ForeachWriter[T], encoder: ExpressionEncoder[T])
actually.. probably should not inline this. its outer closure may not be serializable in that case.

2018-02-09 02:35 UTC, jose-torres commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/ForeachSink.scala
> +    val byteStream = new ByteArrayOutputStream()
You're right; this suggestion is what we really want.

2018-02-09 02:35 UTC, jose-torres commented on sql/core/src/test/scala/org/apache/spark/sql/execution/streaming/ForeachSinkSuite.scala
> +
Good instinct, it didn't quite work. Added the test.

2018-02-09 02:37 UTC, SparkQA commented
**[Test build #87241 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/87241/testReport)** for PR 20552 at commit [`a33a35c`](https://github.com/apache/spark/commit/a33a35ccbae7350519a3faf8d5d3d6f35692feb3).

2018-02-09 02:40 UTC, jose-torres commented
It's my intent to say that other data sources built by general developers aren't supposed to use batch ids in the executors for any purpose. In addition to the issue you mentioned, I don't think there's a compelling reason to do so in the DataSourceV2 model, and I worry it's easy to write implementations that seem correct but aren't that way.

Since this interface is still evolving, I think it makes sense to revisit the question if we notice a scenario where it's infeasible to rewrite a piece of transactional logic to not use the batch ID in the executor.

2018-02-09 05:06 UTC, SparkQA commented
**[Test build #87241 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/87241/testReport)** for PR 20552 at commit [`a33a35c`](https://github.com/apache/spark/commit/a33a35ccbae7350519a3faf8d5d3d6f35692feb3).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-02-09 05:07 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2018-02-09 05:07 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/87241/
Test FAILed.

2018-02-13 19:31 UTC, jose-torres commented
Filed SPARK-23416 for the unrelated failure in build 87241.

2018-02-13 22:07 UTC, SparkQA commented
**[Test build #87417 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/87417/testReport)** for PR 20552 at commit [`66270c5`](https://github.com/apache/spark/commit/66270c530ff7d7a82f9661b42d158d0b4544b8b7).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-02-13 22:08 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2018-02-13 22:08 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/87417/
Test FAILed.

2018-03-07 18:00 UTC, jose-torres commented
This is obsolete - we're changing the lifecycle of DataWriter.

2018-03-07 18:00 UTC, closed without merging