[SPARK-24954][Core] Fail fast on job submit if run a barrier stage with dynamic resource allocation enabled
apache/spark pull request #21915
Opened 2018-07-30 14:40 UTC by jiangxb1987

## What changes were proposed in this pull request?

We don't support run a barrier stage with dynamic resource allocation enabled, it shall lead to some confusing behaviors (eg. with dynamic resource allocation enabled, it may happen that we acquire some executors (but not enough to launch all the tasks in a barrier stage) and later release them due to executor idle time expire, and then acquire again).

We perform the check on job submit and fail fast if running a barrier stage with dynamic resource allocation enabled.

## How was this patch tested?

Added new test suite `BarrierStageOnSubmittedSuite` to cover all the fail fast cases that submitted a job containing one or more barrier stages.

2018-07-30 14:40 UTC, holdensmagicalunicorn commented
@jiangxb1987, thanks! I am a bot who has found some folks who might be able to help with the review:@mateiz, @rxin and @kayousterhout

2018-07-30 14:42 UTC, jiangxb1987 commented
cc @squito

2018-07-30 14:42 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-07-30 14:42 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/1491/
Test PASSed.

2018-07-30 14:43 UTC, SparkQA commented
**[Test build #93791 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/93791/testReport)** for PR 21915 at commit [`2ffa2b7`](https://github.com/apache/spark/commit/2ffa2b700eaf9913efd8de77e8194fa093d03581).

2018-07-30 19:11 UTC, SparkQA commented
**[Test build #93791 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/93791/testReport)** for PR 21915 at commit [`2ffa2b7`](https://github.com/apache/spark/commit/2ffa2b700eaf9913efd8de77e8194fa093d03581).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-07-30 19:13 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-07-30 19:13 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/93791/
Test PASSed.

2018-07-31 17:33 UTC, mengxr requested changes

2018-07-31 17:33 UTC, mengxr commented on core/src/main/scala/org/apache/spark/scheduler/DAGScheduler.scala
> +      throw new SparkException("Don't support run a barrier stage with dynamic resource " +
* `[SPARK-24942]: Barrier execution mode does not support dynamic resource allocation for now. You can disable dynamic resource allocation by setting Spark conf "spark.dynamicAllocation.enabled" to "false".`
* Make the error message a constant to simplify test.

2018-07-31 17:33 UTC, mengxr commented on core/src/test/scala/org/apache/spark/BarrierStageOnSubmittedSuite.scala
> +      .set("spark.dynamicAllocation.enabled", "true")
Does it work if we use `LocalSparkContext`?

2018-07-31 21:35 UTC, squito commented
thanks @jiangxb1987, lgtm aside from @mengxr 's comments

2018-08-01 11:17 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-08-01 11:17 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/1557/
Test PASSed.

2018-08-01 15:18 UTC, SparkQA commented
**[Test build #93877 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/93877/testReport)** for PR 21915 at commit [`663b900`](https://github.com/apache/spark/commit/663b90004a962768d3fa718c6e3047e38e325519).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-08-01 15:19 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2018-08-01 15:19 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/93877/
Test FAILed.

2018-08-01 17:45 UTC, jiangxb1987 commented
retest this please

2018-08-01 17:47 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-08-01 17:47 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/1569/
Test PASSed.

2018-08-01 17:48 UTC, SparkQA commented
**[Test build #93889 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/93889/testReport)** for PR 21915 at commit [`663b900`](https://github.com/apache/spark/commit/663b90004a962768d3fa718c6e3047e38e325519).

2018-08-01 21:32 UTC, SparkQA commented
**[Test build #93889 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/93889/testReport)** for PR 21915 at commit [`663b900`](https://github.com/apache/spark/commit/663b90004a962768d3fa718c6e3047e38e325519).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-08-01 21:34 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2018-08-01 21:34 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/93889/
Test FAILed.

2018-08-01 22:01 UTC, gatorsmile commented
retest this please

2018-08-01 22:02 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-08-01 22:02 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/1586/
Test PASSed.

2018-08-01 22:03 UTC, SparkQA commented
**[Test build #93910 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/93910/testReport)** for PR 21915 at commit [`663b900`](https://github.com/apache/spark/commit/663b90004a962768d3fa718c6e3047e38e325519).

2018-08-02 02:01 UTC, SparkQA commented
**[Test build #93910 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/93910/testReport)** for PR 21915 at commit [`663b900`](https://github.com/apache/spark/commit/663b90004a962768d3fa718c6e3047e38e325519).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-08-02 02:02 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2018-08-02 02:02 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/93910/
Test FAILed.

2018-08-02 02:54 UTC, jiangxb1987 commented
retest this please

2018-08-02 02:57 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-08-02 02:57 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/1602/
Test PASSed.

2018-08-02 02:58 UTC, SparkQA commented
**[Test build #93931 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/93931/testReport)** for PR 21915 at commit [`663b900`](https://github.com/apache/spark/commit/663b90004a962768d3fa718c6e3047e38e325519).

2018-08-02 06:14 UTC, mengxr approved these changes

2018-08-02 06:15 UTC, mengxr commented
LGTM pending jenkins. Was there a JIRA reported about KafkaContinuousSourceSuite failure? cc: @tedyu ?

https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/93889/testReport/org.apache.spark.sql.kafka010/KafkaMicroBatchV1SourceSuite/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

2018-08-02 07:05 UTC, SparkQA commented
**[Test build #93931 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/93931/testReport)** for PR 21915 at commit [`663b900`](https://github.com/apache/spark/commit/663b90004a962768d3fa718c6e3047e38e325519).
 * This patch **fails due to an unknown error code, -9**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-08-02 07:06 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2018-08-02 07:06 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/93931/
Test FAILed.

2018-08-02 07:10 UTC, jiangxb1987 commented
retest this please

2018-08-02 07:12 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-08-02 07:12 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/1631/
Test PASSed.

2018-08-02 07:13 UTC, SparkQA commented
**[Test build #93971 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/93971/testReport)** for PR 21915 at commit [`663b900`](https://github.com/apache/spark/commit/663b90004a962768d3fa718c6e3047e38e325519).

2018-08-02 11:13 UTC, SparkQA commented
**[Test build #93971 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/93971/testReport)** for PR 21915 at commit [`663b900`](https://github.com/apache/spark/commit/663b90004a962768d3fa718c6e3047e38e325519).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-08-02 11:14 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2018-08-02 11:14 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/93971/
Test FAILed.

2018-08-02 13:18 UTC, jiangxb1987 commented
retest this please

2018-08-03 03:37 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-08-03 03:37 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/1724/
Test PASSed.

2018-08-03 03:38 UTC, SparkQA commented
**[Test build #94089 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/94089/testReport)** for PR 21915 at commit [`f3ea9c6`](https://github.com/apache/spark/commit/f3ea9c6625da255119e360a499e439128f989e1e).

2018-08-03 03:40 UTC, SparkQA commented
**[Test build #94089 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/94089/testReport)** for PR 21915 at commit [`f3ea9c6`](https://github.com/apache/spark/commit/f3ea9c6625da255119e360a499e439128f989e1e).
 * This patch **fails Scala style tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-08-03 03:40 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2018-08-03 03:40 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/94089/
Test FAILed.

2018-08-03 03:42 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-08-03 03:42 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/1725/
Test PASSed.

2018-08-03 03:43 UTC, SparkQA commented
**[Test build #94090 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/94090/testReport)** for PR 21915 at commit [`0796f76`](https://github.com/apache/spark/commit/0796f760c60da9bb8b5cadeee2e751dd898cf8cf).

2018-08-03 07:05 UTC, SparkQA commented
**[Test build #94090 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/94090/testReport)** for PR 21915 at commit [`0796f76`](https://github.com/apache/spark/commit/0796f760c60da9bb8b5cadeee2e751dd898cf8cf).
 * This patch **fails due to an unknown error code, -9**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-08-03 07:06 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2018-08-03 07:06 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/94090/
Test FAILed.

2018-08-03 07:29 UTC, mengxr commented
test this please

2018-08-03 07:33 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-08-03 07:33 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/1742/
Test PASSed.

2018-08-03 07:33 UTC, SparkQA commented
**[Test build #94115 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/94115/testReport)** for PR 21915 at commit [`0796f76`](https://github.com/apache/spark/commit/0796f760c60da9bb8b5cadeee2e751dd898cf8cf).

2018-08-03 11:18 UTC, SparkQA commented
**[Test build #94115 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/94115/testReport)** for PR 21915 at commit [`0796f76`](https://github.com/apache/spark/commit/0796f760c60da9bb8b5cadeee2e751dd898cf8cf).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-08-03 11:19 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2018-08-03 11:19 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/94115/
Test FAILed.

2018-08-03 11:54 UTC, jiangxb1987 commented
retest this please

2018-08-03 11:57 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-08-03 11:57 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/1756/
Test PASSed.

2018-08-03 11:58 UTC, SparkQA commented
**[Test build #94131 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/94131/testReport)** for PR 21915 at commit [`0796f76`](https://github.com/apache/spark/commit/0796f760c60da9bb8b5cadeee2e751dd898cf8cf).

2018-08-03 16:32 UTC, SparkQA commented
**[Test build #94131 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/94131/testReport)** for PR 21915 at commit [`0796f76`](https://github.com/apache/spark/commit/0796f760c60da9bb8b5cadeee2e751dd898cf8cf).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-08-03 16:33 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-08-03 16:33 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/94131/
Test PASSed.

2018-08-03 16:36 UTC, mengxr commented
LGTM. Merged into master. Thanks!

2018-08-03 16:40 UTC, closed without merging