[SPARK-24090][K8S] Update running-on-kubernetes.md
apache/spark pull request #22224
Opened 2018-08-24 18:00 UTC by liyinan926

## What changes were proposed in this pull request?

Updated documentation for Spark on Kubernetes for the upcoming 2.4.0.

Please review http://spark.apache.org/contributing.html before opening a pull request.

@mccheah @erikerlandson

2018-08-24 18:03 UTC, SparkQA commented
**[Test build #95220 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/95220/testReport)** for PR 22224 at commit [`48ecb1e`](https://github.com/apache/spark/commit/48ecb1eac55d625361c0e1f52cde15079055ede5).

2018-08-24 18:12 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/testing-k8s-prb-make-spark-distribution-unified/2536/

2018-08-25 14:21 UTC, srowen requested changes

2018-08-27 05:07 UTC, liyinan926 commented on docs/running-on-kubernetes.md
> +There are several Spark on Kubernetes features that are currently being worked on or planned to be worked on. Those features are expected to eventually make it into future versions of the spark-kuber
You meant removing the entire `Future Work` section?

2018-08-27 05:07 UTC, liyinan926 commented on docs/running-on-kubernetes.md
> +Starting Spark 2.4.0, users can mount the following types of Kubernetes [volumes](https://kubernetes.io/docs/concepts/storage/volumes/) into the driver and executor pods:
Done.

2018-08-27 05:13 UTC, SparkQA commented
**[Test build #95278 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/95278/testReport)** for PR 22224 at commit [`7e8144b`](https://github.com/apache/spark/commit/7e8144ba8111cfeac12051b28c06b7ef87aa4720).

2018-08-27 05:28 UTC, SparkQA commented
**[Test build #95278 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/95278/testReport)** for PR 22224 at commit [`7e8144b`](https://github.com/apache/spark/commit/7e8144ba8111cfeac12051b28c06b7ef87aa4720).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-08-27 05:28 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-08-27 05:28 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/95278/
Test PASSed.

2018-08-27 05:31 UTC, SparkQA commented
Kubernetes integration test status success
URL: https://amplab.cs.berkeley.edu/jenkins/job/testing-k8s-prb-make-spark-distribution-unified/2564/

2018-08-27 05:31 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-08-27 05:31 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/2564/
Test PASSed.

2018-08-27 12:54 UTC, srowen commented on docs/running-on-kubernetes.md
> +There are several Spark on Kubernetes features that are currently being worked on or planned to be worked on. Those features are expected to eventually make it into future versions of the spark-kuber
Just these two sentences, not the whole section. I figured it goes without saying there are features that may be worked on the the future that may go into Spark. But I don't feel strongly about it; this is fine.

2018-08-27 12:54 UTC, srowen approved these changes

2018-08-27 19:43 UTC, liyinan926 commented
Can this be merged?

2018-08-27 20:56 UTC, srowen commented
Yeah, was just seeing if there were more comments. Merged to master

2018-08-27 20:59 UTC, closed without merging