Fix lint failure in 2.2
apache/spark pull request #22596
Opened 2018-09-30 15:44 UTC by samdvr

## What changes were proposed in this pull request?

Line length fixes and 

## How was this patch tested?

Manually verified, but will ensure jenkins lint passes before merging

2018-09-30 15:46 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-09-30 15:46 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-09-30 15:47 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-10-01 01:33 UTC, HyukjinKwon commented
ok to test

2018-10-01 01:37 UTC, HyukjinKwon commented
Can you link the JIRA https://issues.apache.org/jira/browse/SPARK-25576 ? Please see https://spark.apache.org/contributing.html

2018-10-01 01:38 UTC, SparkQA commented
**[Test build #96808 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/96808/testReport)** for PR 22596 at commit [`c4b6920`](https://github.com/apache/spark/commit/c4b6920ed24fd6398da27b978380427e3b0cb62a).

2018-10-01 04:35 UTC, SparkQA commented
**[Test build #96808 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/96808/testReport)** for PR 22596 at commit [`c4b6920`](https://github.com/apache/spark/commit/c4b6920ed24fd6398da27b978380427e3b0cb62a).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-10-01 04:36 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-10-01 04:36 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/96808/
Test PASSed.

2018-10-01 12:20 UTC, samdvr commented
@HyukjinKwon linked the JIRA to this PR and tests have passed.

2018-10-01 17:17 UTC, dongjoon-hyun commented
Thank you for your first contribution, @samdvr . Could you update the title, `[SPARK-25576][BUILD][BRANCH-2.2] Fix lint failure`?

2018-10-01 17:19 UTC, dongjoon-hyun commented on core/src/main/java/org/apache/spark/util/collection/unsafe/sort/UnsafeInMemorySorter.java
> +      // by setting the array to null and its length to 0
`by` -> `By`?

2018-10-01 17:20 UTC, dongjoon-hyun commented on core/src/main/java/org/apache/spark/util/collection/unsafe/sort/UnsafeInMemorySorter.java
> +      // setting the array to null also indicates that it has already been
`setting` -> `Setting`?

2018-10-01 17:27 UTC, samdvr commented
@dongjoon-hyun updated per your comments, thank you.

2018-10-01 17:28 UTC, SparkQA commented
**[Test build #96823 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/96823/testReport)** for PR 22596 at commit [`009d4cf`](https://github.com/apache/spark/commit/009d4cf0529917de32483f9d7686b7dcdbe6e400).

2018-10-01 17:38 UTC, dongjoon-hyun requested changes
Actually, this issue aims to pass `dev/lint-java`. For now, this PR seems to be unable to pass the Jenkins. Could you check it by run `dev/lint-java` in your spark home directory?

```scala
$ dev/lint-java
exec: curl --progress-bar -L https://downloads.typesafe.com/zinc/0.3.11/zinc-0.3.11.tgz
######################################################################## 100.0%
exec: curl --progress-bar -L https://downloads.typesafe.com/scala/2.11.8/scala-2.11.8.tgz
######################################################################## 100.0%
Using `mvn` from path: /usr/local/bin/mvn
Checkstyle checks failed at following occurrences:
[ERROR] src/test/java/org/apache/spark/unsafe/types/UTF8StringSuite.java:[66] (misc) AvoidEscapedUnicodeCharacters: Unicode escape(s) usage should be avoided.
[ERROR] src/main/java/org/apache/spark/util/collection/unsafe/sort/UnsafeInMemorySorter.java:[177] (regexp) RegexpSingleline: No trailing whitespace allowed.
[ERROR] src/main/java/org/apache/spark/util/collection/unsafe/sort/UnsafeInMemorySorter.java:[179] (regexp) RegexpSingleline: No trailing whitespace allowed.
[ERROR] src/main/java/org/apache/spark/util/collection/unsafe/sort/UnsafeInMemorySorter.java:[181] (regexp) RegexpSingleline: No trailing whitespace allowed.
[ERROR] src/test/java/org/apache/spark/util/collection/unsafe/sort/UnsafeExternalSorterSuite.java:[473] (regexp) RegexpSingleline: No trailing whitespace allowed.
[ERROR] src/test/java/org/apache/spark/util/collection/unsafe/sort/UnsafeExternalSorterSuite.java:[478] (regexp) RegexpSingleline: No trailing whitespace allowed.
[ERROR] src/test/java/org/apache/spark/util/collection/unsafe/sort/UnsafeExternalSorterSuite.java:[485] (regexp) RegexpSingleline: No trailing whitespace allowed.
[ERROR] src/test/java/org/apache/spark/util/collection/unsafe/sort/UnsafeExternalSorterSuite.java:[489] (sizes) LineLength: Line is longer than 100 characters (found 120).
[ERROR] src/test/java/org/apache/spark/util/collection/unsafe/sort/UnsafeExternalSorterSuite.java:[491] (sizes) LineLength: Line is longer than 100 characters (found 114).
[ERROR] src/test/java/org/apache/spark/util/collection/unsafe/sort/UnsafeInMemorySorterSuite.java:[186] (sizes) LineLength: Line is longer than 100 characters (found 116).
```

2018-10-01 20:27 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-10-01 20:27 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/96823/
Test PASSed.

2018-10-02 02:08 UTC, SparkQA commented
**[Test build #96835 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/96835/testReport)** for PR 22596 at commit [`2e8836b`](https://github.com/apache/spark/commit/2e8836ba0cab70243a8b5ef8845d045d65856aa1).

2018-10-02 05:02 UTC, SparkQA commented
**[Test build #96835 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/96835/testReport)** for PR 22596 at commit [`2e8836b`](https://github.com/apache/spark/commit/2e8836ba0cab70243a8b5ef8845d045d65856aa1).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-10-02 05:04 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-10-02 05:04 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/96835/
Test PASSed.

2018-10-02 06:21 UTC, dongjoon-hyun requested changes
I made a PR to you, @samdvr . Could you merge that, https://github.com/samdvr/spark/pull/1 ?

2018-10-02 13:09 UTC, samdvr commented
@dongjoon-hyun merged, thank you, did not know how to skip lint rule there.

2018-10-02 13:13 UTC, SparkQA commented
**[Test build #96858 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/96858/testReport)** for PR 22596 at commit [`07156d4`](https://github.com/apache/spark/commit/07156d4d8d3ac40b47a825ecb4fa01bf7eaae1ad).

2018-10-02 16:10 UTC, SparkQA commented
**[Test build #96858 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/96858/testReport)** for PR 22596 at commit [`07156d4`](https://github.com/apache/spark/commit/07156d4d8d3ac40b47a825ecb4fa01bf7eaae1ad).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-10-02 16:11 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-10-02 16:11 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/96858/
Test PASSed.

2018-10-02 17:12 UTC, dongjoon-hyun approved these changes
+1, LGTM. Thank you, @samdvr .
Merged to branch-2.2.

2018-10-02 17:22 UTC, dongjoon-hyun commented
BTW, I chose the most official one, `Sam Davarnia <sdavarnia@apple.com>`. But, it seems that your GitHub is not happy with that. Next time, you had better be consistent in your commit message.
```
Lead-authored-by: Sam Davarnia <sdavarnia@apple.com>
Co-authored-by: Sam Davarnia <>
Co-authored-by: Dongjoon Hyun <dongjoon@apache.org>
Co-authored-by: Sam Davarnia <samdvr@users.noreply.github.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>
```

2018-10-02 17:22 UTC, dongjoon-hyun commented
Since it's merged into `branch-2.2`, could you close this PR? GitHub only closes the PRs against `master` branch. :)

2018-10-02 17:45 UTC, samdvr commented
Thanks will do!

2018-10-02 17:45 UTC, closed without merging