[SPARK-26324][DOCS] Add Spark docs for Running in Mesos with SSL
apache/spark pull request #23342
Opened 2018-12-18 06:34 UTC by jomach

## What changes were proposed in this pull request?
Added docs for running spark jobs with Mesos on SSL

2018-12-18 06:34 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-12-18 06:36 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-12-18 06:39 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-12-18 07:43 UTC, felixcheung commented on docs/running-on-mesos.md
> +If you want to deploy a Spark Application into a Mesos cluster that is running in a secure mode there are some environment's variables that need to be set.
`environment variables`

2018-12-18 07:43 UTC, felixcheung commented on docs/running-on-mesos.md
> +Then submit as usual or as described below
perhaps say `as described in Client mode or Cluster mode below`

2018-12-18 13:12 UTC, srowen requested changes

2018-12-18 13:12 UTC, srowen commented on docs/running-on-mesos.md
> +all options can be found at http://mesos.apache.org/documentation/latest/ssl/
all -> All

2018-12-19 09:18 UTC, jomach commented
@srowen @felixcheung  pr updated

2018-12-19 13:07 UTC, srowen approved these changes

2018-12-20 14:31 UTC, SparkQA commented
**[Test build #4482 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/4482/testReport)** for PR 23342 at commit [`fbc2e70`](https://github.com/apache/spark/commit/fbc2e7029bcffbb0a5f68d2f456a946271c8f930).

2018-12-20 14:32 UTC, closed without merging

2018-12-20 14:45 UTC, jomach commented
@srowen Why did you not merge it ?

2018-12-20 14:55 UTC, srowen commented
It is merged to master. I missed running the tests so those are running now, but it's a doc change and shouldn't be a problem

2018-12-20 14:57 UTC, jomach commented
I saw it. I was just confused about the git symbol. Thx

2018-12-20 19:14 UTC, SparkQA commented
**[Test build #4482 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/4482/testReport)** for PR 23342 at commit [`fbc2e70`](https://github.com/apache/spark/commit/fbc2e7029bcffbb0a5f68d2f456a946271c8f930).
 * This patch **fails PySpark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-12-20 19:32 UTC, srowen commented
That error can be ignored; this didn't cause functional changes in Python