[SPARK-26416] [SQL] Refactor `ColumnPruning` from `Optimizer.scala` to `ColumnPruning.scala`
apache/spark pull request #23359
Opened 2018-12-20 23:44 UTC by dbtsai

## What changes were proposed in this pull request?

As `Optimizer.scala` becomes bigger and bigger, it's hard to add new rules and maintain them. We are refactoring out `ColumnPruning` from `Optimizer.scala` to `ColumnPruning.scala` so it's easier to add new logics in `ColumnPruning`.

## How was this patch tested?

Existing tests.

2018-12-20 23:47 UTC, SparkQA commented
**[Test build #100351 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/100351/testReport)** for PR 23359 at commit [`bf8f1b9`](https://github.com/apache/spark/commit/bf8f1b9a03d48f1feaec1f3ece33b616d29ce074).

2018-12-20 23:48 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-12-20 23:48 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/6315/
Test PASSed.

2018-12-20 23:49 UTC, dbtsai commented
cc @gatorsmile @cloud-fan @dongjoon-hyun

2018-12-21 00:14 UTC, dongjoon-hyun commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/ColumnPruning.scala
> +        if p2.outputSet.subsetOf(child.outputSet) =>
I can see that this is a clean refactoring and this line is the additional style fix.

2018-12-21 00:15 UTC, dongjoon-hyun approved these changes
+1, LGTM (pening Jenkins)

2018-12-21 00:17 UTC, gatorsmile requested changes
I would not suggest to move the code with such a complex change history.

2018-12-21 00:18 UTC, dongjoon-hyun commented
@gatorsmile . Spark 3.0 is a good chance to make this more flexible in the future.

2018-12-21 00:19 UTC, gatorsmile commented
It is hard for us to do the review in the future. Normally, we check the change history when doing the review. The change history is very important for us to do the review.

2018-12-21 02:12 UTC, gatorsmile commented
Discussed it with @dongjoon-hyun offline. There are various bug fixes in the code history. The change history is very valuable for us [especially for new contributors] to understand the code. Previously, we did the split, but it makes us much harder to find out the original PRs who introduced the changes. 

For example, the following screenshot can clearly show all the PRs that changed this column pruning rule. The change history is very useful for reviewers and new learners. 

![screen shot 2018-12-20 at 6 10 41 pm](https://user-images.githubusercontent.com/11567269/50320747-a6127d80-0482-11e9-87b8-eb9e06055b41.png)

2018-12-21 02:15 UTC, gatorsmile commented
Maybe not all of you know this trick. You can get the history by selection in IntelliJ. See the screen shot. 

![screen shot 2018-12-20 at 6 15 09 pm](https://user-images.githubusercontent.com/11567269/50320902-3fda2a80-0483-11e9-9e3d-155ecfb7d7d8.png)

2018-12-21 03:30 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-12-21 03:30 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/100351/
Test PASSed.

2018-12-21 04:47 UTC, dongjoon-hyun commented
Yep. I agree with @gatorsmile now.

2018-12-21 19:00 UTC, dbtsai commented
All the above is great conversation. I'm closing this PR. Thanks.

2018-12-21 19:00 UTC, closed without merging