[SPARK-26470][CORE] Use ConfigEntry for hardcoded configs for eventLog category
apache/spark pull request #23395
Opened 2018-12-28 12:07 UTC by mgaido91

## What changes were proposed in this pull request?

The PR makes hardcoded `spark.eventLog` configs to use `ConfigEntry` and put them in the `config` package.

## How was this patch tested?

existing tests

2018-12-28 12:07 UTC, mgaido91 commented
cc @dongjoon-hyun @HyukjinKwon @srowen @ueshin @vanzin

2018-12-28 12:09 UTC, SparkQA commented
**[Test build #100500 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/100500/testReport)** for PR 23395 at commit [`c21fde0`](https://github.com/apache/spark/commit/c21fde0ea693c18537487716216809634e8f9b33).

2018-12-28 12:10 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-12-28 12:10 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/6446/
Test PASSed.

2018-12-28 12:11 UTC, SparkQA commented
**[Test build #100500 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/100500/testReport)** for PR 23395 at commit [`c21fde0`](https://github.com/apache/spark/commit/c21fde0ea693c18537487716216809634e8f9b33).
 * This patch **fails Scala style tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-12-28 12:11 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2018-12-28 12:11 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/100500/
Test FAILed.

2018-12-28 19:41 UTC, dongjoon-hyun commented
Could you fix the scalastyle?
```
[error] /home/jenkins/workspace/SparkPullRequestBuilder/core/src/test/scala/org/apache/spark/scheduler/EventLoggingListenerSuite.scala:36:0: org.apache.spark.internal.Logging is in wrong order relative to org.apache.spark.internal.config._.
```

2018-12-28 23:51 UTC, mgaido91 commented
sorry, done, thanks @dongjoon-hyun

2018-12-28 23:52 UTC, SparkQA commented
**[Test build #100517 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/100517/testReport)** for PR 23395 at commit [`7b7d5df`](https://github.com/apache/spark/commit/7b7d5dfce4069786ac9a9517829c7a0af6293fa5).

2018-12-28 23:58 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-12-28 23:58 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/6458/
Test PASSed.

2018-12-29 04:18 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-12-29 04:18 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/100517/
Test PASSed.

2018-12-29 09:04 UTC, viirya approved these changes

2018-12-29 10:07 UTC, HyukjinKwon approved these changes
LGTM

2018-12-29 20:32 UTC, mgaido91 commented on core/src/test/scala/org/apache/spark/deploy/history/HistoryServerSuite.scala
> +      .set(EVENT_LOG_PROCESS_TREE_METRICS.key, "true")
we can do that, but I prefer the current way because it is coherent with the other `set` methods here.

2018-12-29 20:34 UTC, dongjoon-hyun commented on core/src/test/scala/org/apache/spark/deploy/history/HistoryServerSuite.scala
> +      .set(EVENT_LOG_PROCESS_TREE_METRICS.key, "true")
It's not. Please see line 85. At least this is not coherent to the surroundings here.

2018-12-29 20:35 UTC, dongjoon-hyun commented on core/src/test/scala/org/apache/spark/deploy/history/HistoryServerSuite.scala
> +      .set(EVENT_LOG_PROCESS_TREE_METRICS.key, "true")
Also, I believe shorter is better for new code.

2018-12-29 20:55 UTC, dongjoon-hyun requested changes
Please address the comment, https://github.com/apache/spark/pull/23395/files#r244507988 .

2018-12-29 21:19 UTC, mgaido91 commented on core/src/test/scala/org/apache/spark/deploy/history/HistoryServerSuite.scala
> +      .set(EVENT_LOG_PROCESS_TREE_METRICS.key, "true")
I see, I updated it, thanks!

2018-12-29 21:20 UTC, SparkQA commented
**[Test build #100542 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/100542/testReport)** for PR 23395 at commit [`a54c241`](https://github.com/apache/spark/commit/a54c2415b877341ee12444abaac894353f5cf8b1).

2018-12-29 23:10 UTC, dongjoon-hyun approved these changes
+1, LGTM (pending Jenkins).
Thank you so much for updating, @mgaido91 !

2018-12-30 01:49 UTC, SparkQA commented
**[Test build #100542 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/100542/testReport)** for PR 23395 at commit [`a54c241`](https://github.com/apache/spark/commit/a54c2415b877341ee12444abaac894353f5cf8b1).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-12-30 01:51 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-12-30 01:51 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/100542/
Test PASSed.

2018-12-30 01:53 UTC, dongjoon-hyun commented
Could you resolve the conflicts?

2018-12-30 11:18 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-12-30 11:18 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/6490/
Test PASSed.

2018-12-30 11:19 UTC, SparkQA commented
**[Test build #100555 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/100555/testReport)** for PR 23395 at commit [`0ebcb67`](https://github.com/apache/spark/commit/0ebcb67e1032dc2590294ec887fc2cdc717c7bec).

2018-12-30 15:42 UTC, SparkQA commented
**[Test build #100555 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/100555/testReport)** for PR 23395 at commit [`0ebcb67`](https://github.com/apache/spark/commit/0ebcb67e1032dc2590294ec887fc2cdc717c7bec).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2018-12-30 15:45 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-12-30 15:45 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/100555/
Test PASSed.

2018-12-31 21:34 UTC, dongjoon-hyun commented
Thank you, @mgaido91 , @viirya , @HyukjinKwon .
Merged to master.

2018-12-31 21:38 UTC, closed without merging