[SPARK-26734] [STREAMING] Fix StackOverflowError with large block queue
apache/spark pull request #23716
Opened 2019-01-31 22:15 UTC by rlodge

## What changes were proposed in this pull request?

SPARK-23991 introduced a bug in `ReceivedBlockTracker#allocateBlocksToBatch`: when a queue with more than a few thousand blocks are in the queue, serializing the queue throws a StackOverflowError.  This change just adds `dequeueAll` to the new `clone` operation on the queue so that the fix in 23991 is preserved but the serialized data comes from an ArrayBuffer which doesn't have the serialization problems that mutable.Queue has.

## How was this patch tested?

A unit test was added.

2019-01-31 22:17 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-01-31 22:17 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-01-31 22:19 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-01-31 23:33 UTC, srowen requested changes

2019-01-31 23:33 UTC, srowen commented on assembly/pom.xml
> +    <version>Using</version>
Oops, need to revert these

2019-01-31 23:47 UTC, rlodge commented on assembly/pom.xml
> +    <version>Using</version>
Ooops, reverted.

2019-02-01 00:36 UTC, rlodge commented on streaming/src/main/scala/org/apache/spark/streaming/scheduler/ReceivedBlockTracker.scala
> +        (streamId, getReceivedBlockQueue(streamId).clone().dequeueAll(x => true))
Sure, I could do:

`mutable.ArrayBuffer.empty[ReceivedBlockInfo] ++= getReceivedBlockQueue(streamId).clone()`

which ensures that we know exactly the sequence type being serialized; would you prefer I did that?

https://issues.apache.org/jira/browse/SPARK-23991 caused it in the sense that it moved from using dequeueAll to just serializing a clone of the queue, and the queue just doesn't serialize correctly after some number of entries (a scala bug, IMO).  You could say it "uncovered" a scala bug that was sitting there, but prior to that checking the code wouldn't error with large numbers of entries because dequeueAll constructs an ArrayBuffer and that's what was being serialized.

2019-02-01 01:11 UTC, srowen commented on streaming/src/main/scala/org/apache/spark/streaming/scheduler/ReceivedBlockTracker.scala
> +        (streamId, getReceivedBlockQueue(streamId).clone().dequeueAll(x => true))
Oh I was looking at the wrong JIRA, number typo. Yeah I see it. @gaborgsomogyi that makes sense?

How about `ArrayBuffer(...:_*)`? might be better as it could exactly allocate the size.

2019-02-01 11:00 UTC, gaborgsomogyi commented on streaming/src/main/scala/org/apache/spark/streaming/scheduler/ReceivedBlockTracker.scala
> +        (streamId, getReceivedBlockQueue(streamId).clone().dequeueAll(x => true))
That's not a scala but java limitation. Serialization is vulnerable to stack overflow for certain kind of structures; for example, a long linked list with no special writeObject() methods will be serialized by recursively writing each link. If you've got a 100k links, you're going to try to use 100k stack frames, and quite likely fail with a StackOverflowError. The main thing here is to use something which is not linked.

2019-02-01 11:34 UTC, gaborgsomogyi requested changes
Thanks for the efforts! I would write down the root cause of this issue in the description as well. It's not obvious why it solves the problem.

2019-02-01 11:34 UTC, gaborgsomogyi commented on streaming/src/main/scala/org/apache/spark/streaming/scheduler/ReceivedBlockTracker.scala
> +        (streamId, getReceivedBlockQueue(streamId).clone().dequeueAll(x => true))
I would also choose a solution which allocates the buffer in one step and we could avoid `amortized O(1)` issue.

Additionally it will be a weird construct which can be tried to simplified by later developers. I would add a comment here which describes the issue not to enforce people to analyze this again.

2019-02-01 11:34 UTC, gaborgsomogyi commented on streaming/src/test/scala/org/apache/spark/streaming/ReceivedBlockTrackerSuite.scala
> +    receivedBlockTracker.allocateBlocksToBatch(1)
I would add assertions here as well. If it's not throwing exception doesn't mean the same blocks deserialized.

2019-02-01 11:34 UTC, gaborgsomogyi commented on streaming/src/test/scala/org/apache/spark/streaming/ReceivedBlockTrackerSuite.scala
> +    val receivedBlockTracker = createTracker(setCheckpointDir = true)
`setCheckpointDir` is already `true`.

2019-02-04 08:57 UTC, gaborgsomogyi commented on streaming/src/main/scala/org/apache/spark/streaming/scheduler/ReceivedBlockTracker.scala
> +        (streamId, getReceivedBlockQueue(streamId).clone().dequeueAll(x => true))
I think `.dequeueAll(x => true)` works but not the right change and I would propose similar things what you've mentioned, for example `ArrayBuffer...`. The main point is to allocate the buffer in one step which is not the case with `dequeueAll`.

2019-02-04 18:03 UTC, rlodge commented on streaming/src/main/scala/org/apache/spark/streaming/scheduler/ReceivedBlockTracker.scala
> +        (streamId, getReceivedBlockQueue(streamId).clone().dequeueAll(x => true))
Sure, I can add a comment.  Is

`ArrayBuffer(queue.clone(): _*)`

sufficient, or do we need

`val clonedQueue = getReceivedBlockQueue(streamId).clone().toList
val bufferToWrite = new mutable.ArrayBuffer[ReceivedBlockInfo](clonedQueue.size)
bufferToWrite ++= clonedQueue
(streamId,
   bufferToWrite)
`

2019-02-04 18:07 UTC, srowen commented on streaming/src/main/scala/org/apache/spark/streaming/scheduler/ReceivedBlockTracker.scala
> +        (streamId, getReceivedBlockQueue(streamId).clone().dequeueAll(x => true))
The first one looks good to me. It definitely makes an ArrayBuffer! and I can only imagine the ordering that is produced is the order of dequeueing the elements. It was so when I tried it locally.

2019-02-04 18:24 UTC, rlodge commented on streaming/src/main/scala/org/apache/spark/streaming/scheduler/ReceivedBlockTracker.scala
> +        (streamId, getReceivedBlockQueue(streamId).clone().dequeueAll(x => true))
Ok, I pushed those changes.

2019-02-05 08:26 UTC, gaborgsomogyi reviewed
Apart from the minor things looks good.

2019-02-05 19:46 UTC, rlodge commented on streaming/src/main/scala/org/apache/spark/streaming/scheduler/ReceivedBlockTracker.scala
> +          mutable.ArrayBuffer(getReceivedBlockQueue(streamId).clone(): _*))
Ok, Sure.

2019-02-06 12:41 UTC, gaborgsomogyi approved these changes
LGTM.

2019-02-06 14:37 UTC, SparkQA commented
**[Test build #4550 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/4550/testReport)** for PR 23716 at commit [`9cd6fb5`](https://github.com/apache/spark/commit/9cd6fb57b631316cd098dcba3337490d9582070c).

2019-02-06 16:00 UTC, SparkQA commented
**[Test build #4550 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/4550/testReport)** for PR 23716 at commit [`9cd6fb5`](https://github.com/apache/spark/commit/9cd6fb57b631316cd098dcba3337490d9582070c).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-02-06 16:47 UTC, closed without merging

2019-02-06 16:48 UTC, srowen commented
Merged to master/2.4/2.3