[WIP][SPARK-27749][SQL] Fix hive-thriftserver module in hadoop-3.2 test issue
apache/spark pull request #24628
Opened 2019-05-16 16:30 UTC by wangyum

## What changes were proposed in this pull request?

This pr fix `hive-thriftserver` module in `hadoop-3.2` test issue.
(Will add more info to description later)

## How was this patch tested?

Exiting test

2019-05-16 16:33 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-05-16 16:33 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/10724/
Test PASSed.

2019-05-16 16:35 UTC, SparkQA commented
**[Test build #105462 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105462/testReport)** for PR 24628 at commit [`89b6e00`](https://github.com/apache/spark/commit/89b6e00e50e9839c42f139cb37cbdf5b0698f66a).

2019-05-16 18:21 UTC, SparkQA commented
**[Test build #105462 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105462/testReport)** for PR 24628 at commit [`89b6e00`](https://github.com/apache/spark/commit/89b6e00e50e9839c42f139cb37cbdf5b0698f66a).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-05-16 18:22 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2019-05-16 18:22 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/105462/
Test FAILed.

2019-05-18 09:12 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-05-18 09:12 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/10769/
Test PASSed.

2019-05-18 09:14 UTC, SparkQA commented
**[Test build #105512 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105512/testReport)** for PR 24628 at commit [`ddb0d69`](https://github.com/apache/spark/commit/ddb0d692516a20c0acd020a99f3d6aaa78b9648b).

2019-05-18 13:04 UTC, SparkQA commented
**[Test build #105512 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105512/testReport)** for PR 24628 at commit [`ddb0d69`](https://github.com/apache/spark/commit/ddb0d692516a20c0acd020a99f3d6aaa78b9648b).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-05-18 13:05 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2019-05-18 13:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/105512/
Test FAILed.

2019-05-18 13:47 UTC, wangyum commented
retest this please

2019-05-18 13:48 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-05-18 13:48 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/10771/
Test PASSed.

2019-05-18 13:50 UTC, SparkQA commented
**[Test build #105514 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105514/testReport)** for PR 24628 at commit [`ddb0d69`](https://github.com/apache/spark/commit/ddb0d692516a20c0acd020a99f3d6aaa78b9648b).

2019-05-18 17:43 UTC, SparkQA commented
**[Test build #105514 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105514/testReport)** for PR 24628 at commit [`ddb0d69`](https://github.com/apache/spark/commit/ddb0d692516a20c0acd020a99f3d6aaa78b9648b).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-05-18 17:44 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2019-05-18 17:44 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/105514/
Test FAILed.

2019-05-19 23:39 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-05-19 23:39 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/10794/
Test PASSed.

2019-05-19 23:41 UTC, SparkQA commented
**[Test build #105538 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105538/testReport)** for PR 24628 at commit [`a7bc4e8`](https://github.com/apache/spark/commit/a7bc4e891ae0862d19403164b223ec3b50a38ff3).

2019-05-20 02:34 UTC, dongjoon-hyun commented
@wangyum . I reopened https://issues.apache.org/jira/browse/SPARK-27402 . Please make an independent follow-up PR using ID `SPARK-27402`. That will give us traceability.

2019-05-20 03:19 UTC, SparkQA commented
**[Test build #105538 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105538/testReport)** for PR 24628 at commit [`a7bc4e8`](https://github.com/apache/spark/commit/a7bc4e891ae0862d19403164b223ec3b50a38ff3).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-05-20 03:20 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2019-05-20 03:20 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/105538/
Test FAILed.

2019-05-22 02:27 UTC, SparkQA commented
**[Test build #105653 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105653/testReport)** for PR 24628 at commit [`c9a003f`](https://github.com/apache/spark/commit/c9a003f711acabd437c22fac9425e6fdfa3bdfe8).

2019-05-22 02:33 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-05-22 02:33 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/10909/
Test PASSed.

2019-05-22 02:37 UTC, SparkQA commented
**[Test build #105653 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105653/testReport)** for PR 24628 at commit [`c9a003f`](https://github.com/apache/spark/commit/c9a003f711acabd437c22fac9425e6fdfa3bdfe8).
 * This patch **fails to build**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-05-22 02:37 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2019-05-22 02:37 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/105653/
Test FAILed.

2019-05-22 02:41 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-05-22 02:41 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/10910/
Test PASSed.

2019-05-22 02:43 UTC, SparkQA commented
**[Test build #105656 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105656/testReport)** for PR 24628 at commit [`38ae34e`](https://github.com/apache/spark/commit/38ae34e1daf8fd543a8bf9eef568ba5d0541a8f4).

2019-05-22 04:33 UTC, dongjoon-hyun commented on sql/hive-thriftserver/src/test/scala/org/apache/spark/sql/hive/thriftserver/CliSuite.scala
> +      "hive-hcatalog-core-2.3.4.jar"
`"hive-hcatalog-core-2.3.5.jar"`?

2019-05-22 04:33 UTC, dongjoon-hyun commented on sql/hive-thriftserver/src/test/scala/org/apache/spark/sql/hive/thriftserver/HiveThriftServer2Suites.scala
> +            "hive-hcatalog-core-2.3.4.jar"
ditto. `"hive-hcatalog-core-2.3.5.jar"`?

2019-05-22 04:34 UTC, dongjoon-hyun commented on sql/hive-thriftserver/src/test/scala/org/apache/spark/sql/hive/thriftserver/HiveThriftServer2Suites.scala
> +        assert(conf.get("spark.sql.hive.version") === Some("2.3.4"))
`Some("2.3.5")`?

2019-05-22 04:34 UTC, dongjoon-hyun commented on sql/hive-thriftserver/src/test/scala/org/apache/spark/sql/hive/thriftserver/HiveThriftServer2Suites.scala
> +        assert(conf.get("spark.sql.hive.version") === Some("2.3.4"))
`Some("2.3.5")`?

2019-05-22 04:36 UTC, dongjoon-hyun commented
So, the files under `v2.3.5` are from Hive `2.3.5`, not Hive `2.3.4`, right?

2019-05-22 04:44 UTC, SparkQA commented
**[Test build #105656 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105656/testReport)** for PR 24628 at commit [`38ae34e`](https://github.com/apache/spark/commit/38ae34e1daf8fd543a8bf9eef568ba5d0541a8f4).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-05-22 04:45 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2019-05-22 04:45 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/105656/
Test FAILed.

2019-05-22 05:00 UTC, dongjoon-hyun commented on sql/hive-thriftserver/src/test/scala/org/apache/spark/sql/hive/thriftserver/HiveThriftServer2Suites.scala
> +        assert(conf.get("spark.sql.hive.version") === Some("2.3.4"))
Yep. `2.3.4` causes UT failure.

2019-05-22 05:01 UTC, dongjoon-hyun requested changes
Please replace `2.3.4` to `2.3.5` to pass the UTs. Thanks.

cc @gatorsmile since this is a massive change.

2019-05-22 06:04 UTC, wangyum commented on sql/hive-thriftserver/src/test/scala/org/apache/spark/sql/hive/thriftserver/CliSuite.scala
> +      "hive-hcatalog-core-2.3.4.jar"
Yes. Thank you @dongjoon-hyun

2019-05-23 00:35 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-05-23 00:35 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/10963/
Test PASSed.

2019-05-23 00:37 UTC, SparkQA commented
**[Test build #105707 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105707/testReport)** for PR 24628 at commit [`a0e52aa`](https://github.com/apache/spark/commit/a0e52aae93fd8c1b3a3b1931b2102943cb0202a4).

2019-05-23 02:43 UTC, SparkQA commented
**[Test build #105707 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105707/testReport)** for PR 24628 at commit [`a0e52aa`](https://github.com/apache/spark/commit/a0e52aae93fd8c1b3a3b1931b2102943cb0202a4).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-05-23 02:45 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-05-23 02:45 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/105707/
Test PASSed.

2019-05-24 02:50 UTC, dongjoon-hyun commented
@wangyum . Just to be clear, did you regenerate Thrift related code always for Spark?
> (Note that we only migrate code without adding features, such as HIVE-4924 and HIVE-15473).

I assumed that this generate code comes from Hive 3.5.3, but the generated code is not the same with Hive 3.5.3.

cc @gatorsmile

2019-05-24 14:32 UTC, wangyum commented
Yes @dongjoon-hyun I did [some changes](https://github.com/wangyum/spark/commit/638c47fabaaa1a07dad9a7a2a376e02cb7551046) to workaround `mvn install` build failure with error: `not found: type AsyncFrameBuffer...`.
Maybe @srowen knows the reason. He also changed these files in #23069.

2019-05-24 17:49 UTC, dongjoon-hyun commented
Thank you for the confirmation and the pointers!

2019-05-25 02:18 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-05-25 02:18 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/11032/
Test PASSed.

2019-05-25 02:20 UTC, SparkQA commented
**[Test build #105777 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105777/testReport)** for PR 24628 at commit [`b38c906`](https://github.com/apache/spark/commit/b38c906b5b0c2ebd8953342b079a7610b0d635ad).

2019-05-25 04:40 UTC, SparkQA commented
**[Test build #105777 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105777/testReport)** for PR 24628 at commit [`b38c906`](https://github.com/apache/spark/commit/b38c906b5b0c2ebd8953342b079a7610b0d635ad).
 * This patch **fails SparkR unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-05-25 04:42 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2019-05-25 04:42 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/105777/
Test FAILed.

2019-05-25 04:55 UTC, wangyum commented
retest this please

2019-05-25 05:00 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-05-25 05:00 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/11033/
Test PASSed.

2019-05-25 05:02 UTC, SparkQA commented
**[Test build #105778 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105778/testReport)** for PR 24628 at commit [`b38c906`](https://github.com/apache/spark/commit/b38c906b5b0c2ebd8953342b079a7610b0d635ad).

2019-05-25 07:04 UTC, SparkQA commented
**[Test build #105778 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105778/testReport)** for PR 24628 at commit [`b38c906`](https://github.com/apache/spark/commit/b38c906b5b0c2ebd8953342b079a7610b0d635ad).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-05-25 07:06 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-05-25 07:06 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/105778/
Test PASSed.

2019-05-28 10:27 UTC, juliuszsompolski commented
For readability, would it make sens to split this PR into 2: one to move change the v2.3.4 code to v2.3.5, and the other to start using it?

2019-05-29 06:12 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-05-29 06:12 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/11149/
Test PASSed.

2019-05-29 06:14 UTC, SparkQA commented
**[Test build #105893 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105893/testReport)** for PR 24628 at commit [`cee5636`](https://github.com/apache/spark/commit/cee56365f1f2a589dde0eb0b602f1db1c912da9f).

2019-05-29 07:05 UTC, SparkQA commented
**[Test build #105893 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105893/testReport)** for PR 24628 at commit [`cee5636`](https://github.com/apache/spark/commit/cee56365f1f2a589dde0eb0b602f1db1c912da9f).
 * This patch **fails due to an unknown error code, -9**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-05-29 07:05 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2019-05-29 07:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/105893/
Test FAILed.

2019-05-29 07:10 UTC, wangyum commented
retest this please

2019-05-29 07:12 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-05-29 07:12 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/11151/
Test PASSed.

2019-05-29 07:14 UTC, SparkQA commented
**[Test build #105895 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105895/testReport)** for PR 24628 at commit [`cee5636`](https://github.com/apache/spark/commit/cee56365f1f2a589dde0eb0b602f1db1c912da9f).

2019-05-29 09:33 UTC, SparkQA commented
**[Test build #105895 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105895/testReport)** for PR 24628 at commit [`cee5636`](https://github.com/apache/spark/commit/cee56365f1f2a589dde0eb0b602f1db1c912da9f).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-05-29 09:35 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-05-29 09:35 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/105895/
Test PASSed.

2019-05-29 11:29 UTC, juliuszsompolski commented
LGTM, though I would do the change of actually upgrading v2.3.4 to v2.3.5 in a separate PR
cc @gatorsmile

2019-06-05 00:36 UTC, gatorsmile commented
retest this please

2019-06-05 00:43 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-06-05 00:43 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/11427/
Test PASSed.

2019-06-05 00:45 UTC, SparkQA commented
**[Test build #106176 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/106176/testReport)** for PR 24628 at commit [`cee5636`](https://github.com/apache/spark/commit/cee56365f1f2a589dde0eb0b602f1db1c912da9f).

2019-06-05 00:46 UTC, gatorsmile commented
@juliuszsompolski Actually, there does not exist code changes in this component from Hive 2.3.4 to 2.3.5. :-) See the change history. https://github.com/apache/hive/commits/branch-2.3

2019-06-05 00:47 UTC, gatorsmile commented
LGTM 

I will merge the code when the tests pass.

2019-06-05 00:48 UTC, gatorsmile commented
After the tests pass, we also need to remove [test-hadoop3.2] tag and then retrigger the test again.

2019-06-05 02:25 UTC, SparkQA commented
**[Test build #106176 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/106176/testReport)** for PR 24628 at commit [`cee5636`](https://github.com/apache/spark/commit/cee56365f1f2a589dde0eb0b602f1db1c912da9f).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-06-05 02:26 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2019-06-05 02:26 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/106176/
Test FAILed.

2019-06-05 02:29 UTC, wangyum commented
retest this please

2019-06-05 02:30 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-06-05 02:30 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/11433/
Test PASSed.

2019-06-05 02:32 UTC, SparkQA commented
**[Test build #106182 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/106182/testReport)** for PR 24628 at commit [`cee5636`](https://github.com/apache/spark/commit/cee56365f1f2a589dde0eb0b602f1db1c912da9f).

2019-06-05 05:01 UTC, SparkQA commented
**[Test build #106182 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/106182/testReport)** for PR 24628 at commit [`cee5636`](https://github.com/apache/spark/commit/cee56365f1f2a589dde0eb0b602f1db1c912da9f).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-06-05 05:03 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-06-05 05:03 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/106182/
Test PASSed.

2019-06-05 05:07 UTC, wangyum commented
retest this please

2019-06-05 05:12 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-06-05 05:12 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/11438/
Test PASSed.

2019-06-05 05:14 UTC, SparkQA commented
**[Test build #106187 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/106187/testReport)** for PR 24628 at commit [`cee5636`](https://github.com/apache/spark/commit/cee56365f1f2a589dde0eb0b602f1db1c912da9f).

2019-06-05 06:48 UTC, SparkQA commented
**[Test build #106187 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/106187/testReport)** for PR 24628 at commit [`cee5636`](https://github.com/apache/spark/commit/cee56365f1f2a589dde0eb0b602f1db1c912da9f).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-06-05 06:49 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2019-06-05 06:49 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/106187/
Test FAILed.

2019-06-05 06:53 UTC, wangyum commented
retest this please

2019-06-05 06:54 UTC, SparkQA commented
**[Test build #106191 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/106191/testReport)** for PR 24628 at commit [`cee5636`](https://github.com/apache/spark/commit/cee56365f1f2a589dde0eb0b602f1db1c912da9f).

2019-06-05 07:00 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-06-05 07:00 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/11442/
Test PASSed.

2019-06-05 07:02 UTC, SparkQA commented
**[Test build #106192 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/106192/testReport)** for PR 24628 at commit [`cee5636`](https://github.com/apache/spark/commit/cee56365f1f2a589dde0eb0b602f1db1c912da9f).

2019-06-05 07:05 UTC, SparkQA commented
**[Test build #106191 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/106191/testReport)** for PR 24628 at commit [`cee5636`](https://github.com/apache/spark/commit/cee56365f1f2a589dde0eb0b602f1db1c912da9f).
 * This patch **fails due to an unknown error code, -9**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-06-05 07:05 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2019-06-05 07:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/106191/
Test FAILed.

2019-06-05 07:16 UTC, wangyum commented
retest this please

2019-06-05 07:17 UTC, SparkQA commented
**[Test build #106193 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/106193/testReport)** for PR 24628 at commit [`cee5636`](https://github.com/apache/spark/commit/cee56365f1f2a589dde0eb0b602f1db1c912da9f).

2019-06-05 07:23 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-06-05 07:23 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/11444/
Test PASSed.

2019-06-05 09:11 UTC, SparkQA commented
**[Test build #106192 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/106192/testReport)** for PR 24628 at commit [`cee5636`](https://github.com/apache/spark/commit/cee56365f1f2a589dde0eb0b602f1db1c912da9f).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-06-05 09:13 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-06-05 09:13 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/106192/
Test PASSed.

2019-06-05 09:21 UTC, SparkQA commented
**[Test build #106193 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/106193/testReport)** for PR 24628 at commit [`cee5636`](https://github.com/apache/spark/commit/cee56365f1f2a589dde0eb0b602f1db1c912da9f).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-06-05 09:23 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-06-05 09:23 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/106193/
Test PASSed.

2019-06-05 09:35 UTC, wangyum commented
All tests passed:
hadoop-3.2: https://github.com/apache/spark/pull/24628#issuecomment-498939301
hadoop-2.7: https://github.com/apache/spark/pull/24628#issuecomment-499007269

2019-06-05 15:39 UTC, gatorsmile commented
Thanks! Merged to master.

2019-06-05 15:44 UTC, closed without merging