[SPARK-28075][SQL][FOLLOW-UP] Support another trim pattern: TRIM(trimStr FROM str)
apache/spark pull request #24924
Opened 2019-06-20 14:25 UTC by wangyum

## What changes were proposed in this pull request?
[PostgreSQL](https://github.com/postgres/postgres/blob/7c850320d8cfa5503ecec61c2559661b924f7595/src/test/regress/sql/strings.sql#L624) support  another trim pattern: `TRIM(trimStr FROM str)`:

Function | Return Type | Description | Example | Result
--- | --- | --- | --- | ---
trim([leading \| trailing \| both] [characters] from string) | text | Remove the longest string containing only characters from characters (a space by default) from the start, end, or both ends (both is the default) of string | trim(both 'xyz' from 'yxTomxx') | Tom

This pr add support this trim pattern. After this pr. We can support all standard syntax except `TRIM(FROM str)` because it conflicts with our Literals:
```sql
Literals of type 'FROM' are currently not supported.(line 1, pos 12)

== SQL ==
SELECT TRIM(FROM ' SPARK SQL ')
```  

PostgreSQL, Vertica and MySQL support this pattern. Teradata, Oracle, DB2, SQL Server, Hive and Presto
**PostgreSQL**:
```
postgres=# SELECT substr(version(), 0, 16), trim('xyz' FROM 'yxTomxx');
     substr      | btrim
-----------------+-------
 PostgreSQL 11.3 | Tom
(1 row)
```
**Vertica**:
```
dbadmin=> SELECT version(), trim('xyz' FROM 'yxTomxx');
              version               | btrim
------------------------------------+-------
 Vertica Analytic Database v9.1.1-0 | Tom
(1 row)
```
**MySQL**:
```
mysql> SELECT version(), trim('xyz' FROM 'yxTomxx');
+-----------+----------------------------+
| version() | trim('xyz' FROM 'yxTomxx') |
+-----------+----------------------------+
| 5.7.26    | yxTomxx                    |
+-----------+----------------------------+
1 row in set (0.00 sec)
```

More details:
https://www.postgresql.org/docs/11/functions-string.html

## How was this patch tested?

unit tests

2019-06-20 14:28 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-06-20 14:28 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/11958/
Test PASSed.

2019-06-20 14:30 UTC, SparkQA commented
**[Test build #106727 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/106727/testReport)** for PR 24924 at commit [`6ec0a4b`](https://github.com/apache/spark/commit/6ec0a4b7c15a8ca91f7c63cc99e6a86352ea126a).

2019-06-20 15:02 UTC, dongjoon-hyun requested changes
Please use a different JIRA id for a new syntax and this is a partial support.
> We can support all standard syntax except TRIM(FROM str) because it conflicts with our Literals

2019-06-20 17:38 UTC, SparkQA commented
**[Test build #106727 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/106727/testReport)** for PR 24924 at commit [`6ec0a4b`](https://github.com/apache/spark/commit/6ec0a4b7c15a8ca91f7c63cc99e6a86352ea126a).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-06-20 17:40 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-06-20 17:40 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/106727/
Test PASSed.

2019-06-23 06:09 UTC, gatorsmile commented
This looks good to me. Beside the one listed in the PR description, the other engines also have the similar syntax.

2019-06-23 06:12 UTC, gatorsmile commented
Thanks! Merged to master.

2019-06-23 06:14 UTC, closed without merging