[SPARK-28435][SQL] Support cast string to interval for SQL interface
apache/spark pull request #25189
Opened 2019-07-18 06:18 UTC by wangyum

## What changes were proposed in this pull request?

https://github.com/apache/spark/pull/7355 add support casting between IntervalType and StringType for scala interface. This pr add this feature for SQL interface.

## How was this patch tested?

unit tests

2019-07-18 06:23 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-07-18 06:23 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/12941/
Test PASSed.

2019-07-18 06:25 UTC, SparkQA commented
**[Test build #107826 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/107826/testReport)** for PR 25189 at commit [`e7e2f5b`](https://github.com/apache/spark/commit/e7e2f5bc2c88958fb672d133b55e8c01b7298f40).

2019-07-18 07:05 UTC, SparkQA commented
**[Test build #107826 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/107826/testReport)** for PR 25189 at commit [`e7e2f5b`](https://github.com/apache/spark/commit/e7e2f5bc2c88958fb672d133b55e8c01b7298f40).
 * This patch **fails due to an unknown error code, -9**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-07-18 07:05 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2019-07-18 07:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/107826/
Test FAILed.

2019-07-18 07:17 UTC, wangyum commented
retest this please

2019-07-18 07:22 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-07-18 07:22 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/12949/
Test PASSed.

2019-07-18 07:24 UTC, SparkQA commented
**[Test build #107835 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/107835/testReport)** for PR 25189 at commit [`e7e2f5b`](https://github.com/apache/spark/commit/e7e2f5bc2c88958fb672d133b55e8c01b7298f40).

2019-07-18 10:37 UTC, SparkQA commented
**[Test build #107835 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/107835/testReport)** for PR 25189 at commit [`e7e2f5b`](https://github.com/apache/spark/commit/e7e2f5bc2c88958fb672d133b55e8c01b7298f40).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-07-18 10:39 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-07-18 10:39 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/107835/
Test PASSed.

2019-07-19 05:37 UTC, maropu commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/parser/DataTypeParserSuite.scala
> +  checkDataType("interval", CalendarIntervalType)
nit: This change accepts an interval keyword in a schema string, so could you add tests in `StructTypeSuite`. too?
```
scala> org.apache.spark.sql.types.StructType.fromDDL("a interval")
res0: org.apache.spark.sql.types.StructType = StructType(StructField(a,CalendarIntervalType,true))
```

2019-07-19 05:38 UTC, maropu commented on sql/core/src/test/resources/sql-tests/inputs/cast.sql
> +
nit: Moves these tests in the end of this file?

2019-07-19 08:27 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-07-19 08:27 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/13006/
Test PASSed.

2019-07-19 08:29 UTC, SparkQA commented
**[Test build #107892 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/107892/testReport)** for PR 25189 at commit [`a2f3676`](https://github.com/apache/spark/commit/a2f3676012cdc47538dc4c7c11c94e5c2b71cd8d).

2019-07-19 08:51 UTC, SparkQA commented
**[Test build #107892 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/107892/testReport)** for PR 25189 at commit [`a2f3676`](https://github.com/apache/spark/commit/a2f3676012cdc47538dc4c7c11c94e5c2b71cd8d).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-07-19 08:51 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2019-07-19 08:51 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/107892/
Test FAILed.

2019-07-19 09:42 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-07-19 09:42 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/13010/
Test PASSed.

2019-07-19 09:45 UTC, SparkQA commented
**[Test build #107896 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/107896/testReport)** for PR 25189 at commit [`4f32916`](https://github.com/apache/spark/commit/4f329162b43115068fe679a25bb1ada4a37023a8).

2019-07-19 13:34 UTC, SparkQA commented
**[Test build #107896 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/107896/testReport)** for PR 25189 at commit [`4f32916`](https://github.com/apache/spark/commit/4f329162b43115068fe679a25bb1ada4a37023a8).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-07-19 13:36 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-07-19 13:36 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/107896/
Test PASSed.

2019-07-21 02:14 UTC, maropu approved these changes
Looks fine to me cc: @dongjoon-hyun @gatorsmile

2019-07-21 20:46 UTC, dongjoon-hyun requested changes
Hi, @wangyum . Your contribution is good, but I'd give -1 for this PR (AS-IS) with the following reasons.

1. This PR silently rename `calendarinterval` to `interval` and that causes most of the changes in this PR (is it inevitable?)
2. However, the PR title and description doesn't mentioned it at all.
3. This situation is repeated several times in your PRs .

The PR should be consist in three parts; title/description/code.

In addition, I'm wondering if this is the only way to support this casting. This is just a design choice. You can double down your direction, but could you please try to find a minimal way before we go down this way?

cc @gatorsmile

2019-07-22 01:50 UTC, wangyum commented
How about split it into 2 PRs:
1. Rename `calendarinterval` to `interval`.
2. Support cast `StringType` to `IntervalType` for SQL interface.

2019-07-22 05:43 UTC, dongjoon-hyun commented
Otherwise, you can update this PR title and description according to your contribution.

If you suggest that, of course, it's possible and those PR look more clear as a single PR. For (1), the PR should describe the context in the PR description instead of pointing this PR.

2019-07-22 06:13 UTC, wangyum commented
Created a new PR(#25225) to make it more clear.

2019-07-23 03:57 UTC, dongjoon-hyun commented
#25225 is merged now. Could you rebase this PR?

2019-07-23 04:48 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-07-23 04:48 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/13141/
Test PASSed.

2019-07-23 04:50 UTC, SparkQA commented
**[Test build #108033 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/108033/testReport)** for PR 25189 at commit [`ca111a4`](https://github.com/apache/spark/commit/ca111a4150155900f70d36381432ca3191bca07f).

2019-07-23 07:05 UTC, SparkQA commented
**[Test build #108033 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/108033/testReport)** for PR 25189 at commit [`ca111a4`](https://github.com/apache/spark/commit/ca111a4150155900f70d36381432ca3191bca07f).
 * This patch **fails due to an unknown error code, -9**.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `class CannotReplaceMissingTableException(`
  * `case class MakeDate(year: Expression, month: Expression, day: Expression)`
  * `case class ReplaceTable(`
  * `case class ReplaceTableAsSelect(`
  * `case class ReplaceTableStatement(`
  * `case class ReplaceTableAsSelectStatement(`
  * `case class ReplaceTableExec(`
  * `case class AtomicReplaceTableExec(`
  * `case class AtomicCreateTableAsSelectExec(`
  * `case class ReplaceTableAsSelectExec(`
  * `case class AtomicReplaceTableAsSelectExec(`

2019-07-23 07:05 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2019-07-23 07:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/108033/
Test FAILed.

2019-07-23 07:09 UTC, wangyum commented
retest this please

2019-07-23 07:10 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-07-23 07:10 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/13148/
Test PASSed.

2019-07-23 07:12 UTC, SparkQA commented
**[Test build #108041 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/108041/testReport)** for PR 25189 at commit [`ca111a4`](https://github.com/apache/spark/commit/ca111a4150155900f70d36381432ca3191bca07f).

2019-07-23 11:19 UTC, SparkQA commented
**[Test build #108041 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/108041/testReport)** for PR 25189 at commit [`ca111a4`](https://github.com/apache/spark/commit/ca111a4150155900f70d36381432ca3191bca07f).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `class CannotReplaceMissingTableException(`
  * `case class MakeDate(year: Expression, month: Expression, day: Expression)`
  * `case class ReplaceTable(`
  * `case class ReplaceTableAsSelect(`
  * `case class ReplaceTableStatement(`
  * `case class ReplaceTableAsSelectStatement(`
  * `case class ReplaceTableExec(`
  * `case class AtomicReplaceTableExec(`
  * `case class AtomicCreateTableAsSelectExec(`
  * `case class ReplaceTableAsSelectExec(`
  * `case class AtomicReplaceTableAsSelectExec(`

2019-07-23 11:21 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-07-23 11:21 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/108041/
Test PASSed.

2019-07-24 01:17 UTC, maropu commented
Weird message log? Is this not related to this pr, right?
```
This patch adds the following public classes (experimental):
class CannotReplaceMissingTableException(
case class MakeDate(year: Expression, month: Expression, day: Expression)
case class ReplaceTable(
case class ReplaceTableAsSelect(
case class ReplaceTableStatement(
case class ReplaceTableAsSelectStatement(
case class ReplaceTableExec(
case class AtomicReplaceTableExec(
case class AtomicCreateTableAsSelectExec(
case class ReplaceTableAsSelectExec(
case class AtomicReplaceTableAsSelectExec(
```
Anyway, could you update the title/description? (It seems the current title doesn't explain about the pr directly?)

2019-07-24 02:31 UTC, wangyum commented
Thank you @maropu  Updated the title and description.

2019-07-24 02:34 UTC, dongjoon-hyun commented on sql/core/src/test/resources/sql-tests/results/cast.sql.out
> +struct<CAST(interval 3 months 1 hours AS STRING):string>
Ur, this is irrelevant to this PR.
Is this column name a bug? `1 hours` instead of `1 hour`?

2019-07-24 02:38 UTC, dongjoon-hyun approved these changes
+1, LGTM. Thank you, @wangyum and @maropu .
Yes. The message is irrelevant to this PR.

Merged to `master`.

2019-07-24 02:45 UTC, closed without merging

2019-08-01 13:39 UTC, cloud-fan commented
I'm a little hesitant to add interval relate features and make interval type more visible to users. AFAIK there are ongoing discussions about if we should revisit the interval type and make it follow SQL standard. cc @MaxGekk @mgaido91 

PRs like this will add more backward compatibility concerns if we change the interval type in the future.

2019-08-01 14:14 UTC, mgaido91 commented
> there are ongoing discussions about if we should revisit the interval type and make it follow SQL standard

@cloud-fan thanks for pinging me. May you please point out which discussion you're referring to? I am probably missing it...

2019-08-01 14:57 UTC, cloud-fan commented
@mgaido91 I really can't recall it, maybe in some PRs or JIRA tickets or dev list emails. I was pinging some people who might be related :P 

Also cc @HyukjinKwon

2019-08-01 16:22 UTC, dongjoon-hyun commented
Hi, @cloud-fan . This is not that-level work because this is only SQL layer.

I guess you mean this.
- [[SPARK-24695][SQL] Move `CalendarInterval` to org.apache.spark.sql.types package](https://github.com/apache/spark/pull/25022)

There was @rxin and @cloud-fan 's positive comment there.
- https://github.com/apache/spark/pull/25022#issuecomment-508815192 (Reynold's)
- https://github.com/apache/spark/pull/25022#issuecomment-509533022 (yours)

Shall we talk on that PR?

2019-08-01 16:57 UTC, MaxGekk commented
> ... if we should revisit the interval type and make it follow SQL standard. cc @MaxGekk @mgaido91

I think we should support 2 separate data types for intervals as it is defined by SQL standard. I opened 2 JIRA tickets for that: [SPARK-27790](https://issues.apache.org/jira/browse/SPARK-27790) ([SPARK-27791](https://issues.apache.org/jira/browse/SPARK-27791) & [SPARK-27793](https://issues.apache.org/jira/browse/SPARK-27793)) but both types must have the same keyword for literals - `interval`. I would keep existing type `CalendarInterval` as is. I don't see any reasons to assign more generic name to it because it is just mix of 2 types with not very well defined semantics.

2019-08-01 17:12 UTC, dongjoon-hyun commented
@MaxGekk . Those are new feature requests. We are open for new features always.

Before those request, we merged #25225 after considering that limitations. Please see the following comments.
- https://github.com/apache/spark/pull/25225#issuecomment-513973108

Please make a PR with a needed change. I'm looking forward to seeing your PRs.

2019-08-02 04:54 UTC, cloud-fan commented
@MaxGekk I think one thing we can do right now is to add a restrict on the interval literal: we can't allow an interval with both year-month fields and day-time fields.

2019-08-02 09:43 UTC, HyukjinKwon commented
Yea, it's really rather about https://github.com/apache/spark/pull/25022. But I have to say there are still multiple tasks to fully support interval. For instance, we should map relevant language-native types into internal in Python and R as well. See [SPARK-28493](https://issues.apache.org/jira/browse/SPARK-28493) and [SPARK-28492](https://issues.apache.org/jira/browse/SPARK-28492). Also, we should consider about mapping R <> Arrow, Pandas <> Arrow too.

I think we should officially those internal related features are experimental and highly unstable to alleviate the concern.

2019-08-03 10:33 UTC, mgaido91 commented
I agree with @MaxGekk when he says:

> I think we should support 2 separate data types for intervals as it is defined by SQL standard.

Hence, I honestly share @cloud-fan 's doubts on making this visible to users. Making visible something which we are going to change (hopefully in the same 3.0 timeframe) seems not a great choice and may introduce more concerns on backward compatibility when we want to get SQL standard compliance and/or we may then break user's applications.

Another thing we may do is to transform the `CalendarInterval` type in order to make it SQL compliant. In this case, I think the only thing to do is changing the type itself in order to add the needed restrictions and the ability to specify its precision. This may cause backward compatibility issues - due to the new restriction introduced - but it may be the cleanest way IMHO.

2019-08-07 13:29 UTC, cloud-fan commented
I'm OK to expose some parts of the interval that are not going to change, e.g. the interval literal syntax is fine to me: `SELECT INTERVAL '3 year 2 month'`.

About this interval cast syntax, does Postgres/Presto/SQL Server/Oracle have it?

2019-08-07 15:53 UTC, dongjoon-hyun commented
Yep. Of course, this is a supported syntax, @cloud-fan .

2019-08-07 15:54 UTC, dongjoon-hyun commented
```
postgres=# SELECT INTERVAL '3 year 2 month';
    interval
----------------
 3 years 2 mons
(1 row)
```

2019-08-07 17:24 UTC, cloud-fan commented
yea I know the interval literal syntax is standard, I was asking about the cast syntax.

2019-08-07 23:28 UTC, dongjoon-hyun commented
Oh, I got it.

2019-08-07 23:31 UTC, maropu commented
Yea, pg can explicitly cast a text to interval;
```
postgres=# \d t
                  Table "public.t"
   Column    | Type | Collation | Nullable | Default 
-------------+------+-----------+----------+---------
 intervalstr | text |           |          | 

postgres=# select * from t;
 intervalstr 
-------------
 1 hour
(1 row)

postgres=# select cast(intervalstr as interval) from t;
 intervalstr 
-------------
 01:00:00
(1 row)

postgres=# create temporary view v as select cast(intervalstr as interval) from t;
postgres=# \d v
                   View "pg_temp_3.v"
   Column    |   Type   | Collation | Nullable | Default 
-------------+----------+-----------+----------+---------
 intervalstr | interval |           |          | 
```

2019-08-07 23:34 UTC, dongjoon-hyun commented
What he meant is `SELECT CAST('interval 3 month 1 hour' AS interval)`, isn't it?
```
postgres=# SELECT CAST('3 month 1 hour' AS interval);
    interval
-----------------
 3 mons 01:00:00
(1 row)

postgres=# SELECT CAST('interval 3 month 1 hour' AS interval);
ERROR:  invalid input syntax for type interval: "interval 3 month 1 hour"
LINE 1: SELECT CAST('interval 3 month 1 hour' AS interval);
```

2019-08-07 23:37 UTC, maropu commented
btw, mysql/presto doesn't have interval as an exposed type for casts.

2019-08-07 23:40 UTC, dongjoon-hyun commented
Yep. It's different and also PostgreSQL has additional variants like https://github.com/apache/spark/pull/25225#issuecomment-513973108 .

2020-01-19 08:04 UTC, yaooqinn commented
Hi, this pr seems to expose interval type to table schema for creating and altering table, e.g. in 2.4 or earlier, `HiveClientImpl.verifyColumnDataType` will fail those commands with intervals. In https://github.com/apache/spark/pull/27277, I'd like to restore this and related unexpected behaviors for keeping interval type internal and keep the expected cast behavior involved here, thanks.