[SPARK-28788][DOC][SQL]Document ANALYZE TABLE statement in SQL Reference
apache/spark pull request #25524
Opened 2019-08-21 05:34 UTC by huaxingao

### What changes were proposed in this pull request?
Document ANALYZE TABLE statement in SQL Reference

### Why are the changes needed?
To complete SQL reference

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
Manually checked newly added doc

2019-08-21 05:40 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-08-21 05:40 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/14524/
Test PASSed.

2019-08-21 05:42 UTC, SparkQA commented
**[Test build #109467 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109467/testReport)** for PR 25524 at commit [`9fd9e2b`](https://github.com/apache/spark/commit/9fd9e2bf186136efe4eb0c3c4ec46e23bb5fd418).

2019-08-21 05:54 UTC, SparkQA commented
**[Test build #109467 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109467/testReport)** for PR 25524 at commit [`9fd9e2b`](https://github.com/apache/spark/commit/9fd9e2bf186136efe4eb0c3c4ec46e23bb5fd418).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-08-21 05:54 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-08-21 05:54 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/109467/
Test PASSed.

2019-08-21 17:50 UTC, dilipbiswal commented
@huaxingao Could you please attach a screenshot of the page ?

2019-08-21 18:20 UTC, srowen requested changes

2019-08-21 18:20 UTC, srowen commented on docs/sql-ref-syntax-aux-analyze-table.md
> +ANALYZE TABLE statement can be used to collect statistics about the table. The information can be used by the query optimizer to find a better plan.
Back-tick the reserved words for clarity.
plan -> query plan? maybe query execution plan?

2019-08-21 19:24 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-08-21 19:24 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/14577/
Test PASSed.

2019-08-21 19:27 UTC, SparkQA commented
**[Test build #109521 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109521/testReport)** for PR 25524 at commit [`1016212`](https://github.com/apache/spark/commit/1016212ccccfff4f8d56f3ecb17eaca83ae71ce6).

2019-08-21 19:37 UTC, huaxingao commented
Here is the screenshot
![image](https://user-images.githubusercontent.com/13592258/63462720-65ec0c00-c410-11e9-9680-6dc93fc3a3fb.png)

2019-08-21 19:40 UTC, srowen commented
Oh, I realize now you are just copying the Databricks documentation? https://docs.databricks.com/spark/latest/spark-sql/language-manual/analyze-table.html I don't think we can do that, or at least, will have to seek permission. @gatorsmile did we discuss this separately with the docs team at Databricks and that's the idea or was the idea to create simple, separate documentation from scratch?

2019-08-21 19:42 UTC, SparkQA commented
**[Test build #109521 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109521/testReport)** for PR 25524 at commit [`1016212`](https://github.com/apache/spark/commit/1016212ccccfff4f8d56f3ecb17eaca83ae71ce6).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-08-21 19:42 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-08-21 19:42 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/109521/
Test PASSed.

2019-08-21 22:52 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-08-21 22:52 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/14586/
Test PASSed.

2019-08-21 22:54 UTC, huaxingao commented
I rewrote some of the sentences to make sure no sentence is the same as in databrick's docs.

2019-08-21 22:54 UTC, SparkQA commented
**[Test build #109530 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109530/testReport)** for PR 25524 at commit [`a5516bb`](https://github.com/apache/spark/commit/a5516bbb37a7b4aa28afc1bf89fcc9fc94c62b29).

2019-08-21 23:06 UTC, SparkQA commented
**[Test build #109530 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109530/testReport)** for PR 25524 at commit [`a5516bb`](https://github.com/apache/spark/commit/a5516bbb37a7b4aa28afc1bf89fcc9fc94c62b29).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-08-21 23:06 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-08-21 23:07 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/109530/
Test PASSed.

2019-08-30 19:25 UTC, SparkQA commented
**[Test build #109959 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109959/testReport)** for PR 25524 at commit [`9cc9be0`](https://github.com/apache/spark/commit/9cc9be0723b58f55e6ed3543ba6b4d9b1c64b9cf).

2019-08-30 19:31 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-08-30 19:31 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/14981/
Test PASSed.

2019-08-30 19:36 UTC, SparkQA commented
**[Test build #109959 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109959/testReport)** for PR 25524 at commit [`9cc9be0`](https://github.com/apache/spark/commit/9cc9be0723b58f55e6ed3543ba6b4d9b1c64b9cf).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-08-30 19:36 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-08-30 19:36 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/109959/
Test PASSed.

2019-08-30 19:39 UTC, huaxingao commented
@dilipbiswal @srowen @gatorsmile 
Could you please review? Thanks!

2019-09-03 15:40 UTC, dilipbiswal commented on docs/sql-ref-syntax-aux-analyze-table.md
> +        <li> NOSCAN
@huaxingao will it read better if we bold this ?

2019-09-03 15:43 UTC, dilipbiswal commented
LGTM

2019-09-03 21:19 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-09-03 21:19 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/15082/
Test PASSed.

2019-09-03 21:25 UTC, SparkQA commented
**[Test build #110064 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/110064/testReport)** for PR 25524 at commit [`5584f48`](https://github.com/apache/spark/commit/5584f48f42db35f07de63f2ab8c1a1802cea38bf).

2019-09-03 21:42 UTC, SparkQA commented
**[Test build #110064 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/110064/testReport)** for PR 25524 at commit [`5584f48`](https://github.com/apache/spark/commit/5584f48f42db35f07de63f2ab8c1a1802cea38bf).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-09-03 21:43 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-09-03 21:43 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/110064/
Test PASSed.

2019-09-03 21:54 UTC, dilipbiswal commented
Looks good to me
cc @gatorsmile

2019-09-03 22:26 UTC, gatorsmile commented
LGTM

Thanks! Merged to master

2019-09-03 22:26 UTC, closed without merging

2019-09-03 22:37 UTC, huaxingao commented
@dilipbiswal @gatorsmile @srowen Thank you all for your help!