[SPARK-28790][DOC][SQL]Document CACHE TABLE statement in SQL Reference
apache/spark pull request #25532
Opened 2019-08-21 07:12 UTC by huaxingao

### What changes were proposed in this pull request?
Document CACHE TABLE statement in SQL Reference

### Why are the changes needed?
To complete SQL Reference

### Does this PR introduce any user-facing change?
No.

### How was this patch tested?
Manually checked the newly added doc.

2019-08-21 07:14 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-08-21 07:14 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/14533/
Test PASSed.

2019-08-21 07:17 UTC, SparkQA commented
**[Test build #109476 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109476/testReport)** for PR 25532 at commit [`6257d53`](https://github.com/apache/spark/commit/6257d533c30922691e3a4f8ef0c731e916a42556).

2019-08-21 07:27 UTC, SparkQA commented
**[Test build #109476 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109476/testReport)** for PR 25532 at commit [`6257d53`](https://github.com/apache/spark/commit/6257d533c30922691e3a4f8ef0c731e916a42556).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-08-21 07:28 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-08-21 07:28 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/109476/
Test PASSed.

2019-08-21 17:50 UTC, dilipbiswal commented
@huaxingao Could you please attach a screenshot of the page ?

2019-08-21 18:19 UTC, srowen requested changes

2019-08-21 18:19 UTC, srowen commented on docs/sql-ref-syntax-aux-cache-cache-table.md
> +Cache the table lazily instead of eagerly scanning the entire table.
Lazy here means "the first time it's used" rather than immediately right? that might be worth clarifying.

2019-08-21 23:45 UTC, huaxingao commented
![image](https://user-images.githubusercontent.com/13592258/63475754-13701700-c433-11e9-863d-3c6a311897ef.png)

2019-08-21 23:47 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-08-21 23:48 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/14592/
Test PASSed.

2019-08-21 23:50 UTC, SparkQA commented
**[Test build #109536 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109536/testReport)** for PR 25532 at commit [`e1f55b3`](https://github.com/apache/spark/commit/e1f55b32c988b84f22b62c9f6d3734e9b4d08f9f).

2019-08-22 00:03 UTC, SparkQA commented
**[Test build #109536 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109536/testReport)** for PR 25532 at commit [`e1f55b3`](https://github.com/apache/spark/commit/e1f55b32c988b84f22b62c9f6d3734e9b4d08f9f).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-08-22 00:03 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-08-22 00:03 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/109536/
Test PASSed.

2019-08-22 01:40 UTC, srowen commented on docs/sql-ref-syntax-aux-cache-cache-table.md
> +`CACHE TABLE` caches the table's contents in the RDD cache within memory. This reduces scanning of the original files in future queries.
memory or disk, right?

2019-08-22 04:59 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-08-22 04:59 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/14608/
Test PASSed.

2019-08-22 05:01 UTC, SparkQA commented
**[Test build #109551 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109551/testReport)** for PR 25532 at commit [`f7ca92a`](https://github.com/apache/spark/commit/f7ca92a6c12705c3132143b375d3d622cb333edf).

2019-08-22 05:11 UTC, SparkQA commented
**[Test build #109551 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109551/testReport)** for PR 25532 at commit [`f7ca92a`](https://github.com/apache/spark/commit/f7ca92a6c12705c3132143b375d3d622cb333edf).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-08-22 05:12 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-08-22 05:12 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/109551/
Test PASSed.

2019-09-01 00:50 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-09-01 00:50 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/15009/
Test PASSed.

2019-09-01 00:52 UTC, SparkQA commented
**[Test build #109990 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109990/testReport)** for PR 25532 at commit [`6912965`](https://github.com/apache/spark/commit/691296562e9b5e22cf54c731d2b2e3c871745c4d).

2019-09-01 01:02 UTC, SparkQA commented
**[Test build #109990 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109990/testReport)** for PR 25532 at commit [`6912965`](https://github.com/apache/spark/commit/691296562e9b5e22cf54c731d2b2e3c871745c4d).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-09-01 01:02 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-09-01 01:03 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/109990/
Test PASSed.

2019-09-01 05:19 UTC, dilipbiswal commented on docs/sql-ref-syntax-aux-cache-cache-table.md
> +  <code>OPTIONS</code> clause with <code>storageLevel</code> key and value pair. If a key other than <code>storageLevel</code> is used, a WARN with message "org.apache.spark.sql.execution.command.Cac
@huaxingao Do we need to detail the exact warning message ? We could say "An warning is issued when .... event occurs" ?

2019-09-01 05:20 UTC, dilipbiswal commented on docs/sql-ref-syntax-aux-cache-cache-table.md
> +  <dd>A query that produces the rows to be inserted. It can be in one of following formats:
@huaxingao you meant "to be cached" ?

2019-09-01 05:25 UTC, dilipbiswal commented on docs/sql-ref-syntax-aux-cache-cache-table.md
> +`CACHE TABLE` statement caches the table's contents with the given storage level. This reduces scanning of the original files in future queries.
@huaxingao caches contents of a given table or output of a query ...

2019-09-01 05:45 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-09-01 05:45 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/15010/
Test PASSed.

2019-09-01 05:47 UTC, SparkQA commented
**[Test build #109991 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109991/testReport)** for PR 25532 at commit [`d0a3dbd`](https://github.com/apache/spark/commit/d0a3dbd718bdc59c8ed6bc3205f7d2d1bf8c6fec).

2019-09-01 05:58 UTC, SparkQA commented
**[Test build #109991 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109991/testReport)** for PR 25532 at commit [`d0a3dbd`](https://github.com/apache/spark/commit/d0a3dbd718bdc59c8ed6bc3205f7d2d1bf8c6fec).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-09-01 05:58 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-09-01 05:58 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/109991/
Test PASSed.

2019-09-01 06:02 UTC, dilipbiswal commented
LGTM

2019-09-02 00:07 UTC, gatorsmile reviewed
LGTM

Thanks! Merged to master

2019-09-02 00:08 UTC, closed without merging

2019-09-02 01:21 UTC, huaxingao commented
Thanks! @gatorsmile @srowen @dilipbiswal