[SPARK-28799][DOC]Documentation for Truncate command
apache/spark pull request #25557
Opened 2019-08-22 13:20 UTC by PavithraRamachandran

### What changes were proposed in this pull request?

Document TRUNCATE  statement in SQL Reference Guide.

### Why are the changes needed?
Adding documentation for SQL reference.

### Does this PR introduce any user-facing change?
yes

Before:
There was no documentation for this.

After.
![image](https://user-images.githubusercontent.com/51401130/63517923-8bab0b00-c50d-11e9-8989-d0ee65597784.png)

### How was this patch tested?

Used jekyll build and serve to verify.

2019-08-22 13:22 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-08-22 13:27 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-08-22 13:28 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-09-12 07:56 UTC, dilipbiswal commented
@PavithraRamachandran  Hello could you please update this by following the convention of existing merged PRS.
https://github.com/apache/spark/pull/25529
https://github.com/apache/spark/pull/25525

2019-09-16 12:15 UTC, PavithraRamachandran commented
@dilipbiswal and @srowen i have reworked on the documentation. Kindly review

2019-09-16 13:46 UTC, srowen commented
Is this copied from Hive or Databricks docs? it looks like some phrases are. I get that there are just not many ways to express the exact same idea, but rewording the prose a little bit would be better.

2019-09-16 18:07 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-09-17 04:17 UTC, PavithraRamachandran commented
@srowen i have reworked. Could you review.

2019-09-17 13:38 UTC, srowen requested changes

2019-09-17 13:38 UTC, srowen commented on docs/sql-ref-syntax-ddl-truncate-table.md
> +or an external/temporary table. Inorder to truncate multiple partitions at once, user can specify the partitions
Inorder -> In order
user -> the user
back-tick partition_spec

2019-09-17 13:38 UTC, srowen commented on docs/sql-ref-syntax-ddl-truncate-table.md
> +--After truncate execution, records belonging to partition age=10 is removed
is -> are

2019-09-17 15:05 UTC, PavithraRamachandran commented
@srowen I have handled the review comments. Could you verify?

2019-09-17 15:20 UTC, srowen approved these changes

2019-09-17 15:21 UTC, SparkQA commented
**[Test build #4875 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/4875/testReport)** for PR 25557 at commit [`39af010`](https://github.com/apache/spark/commit/39af010d3646eac351be730e35202855f762f4e8).

2019-09-17 15:36 UTC, SparkQA commented
**[Test build #4875 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/4875/testReport)** for PR 25557 at commit [`39af010`](https://github.com/apache/spark/commit/39af010d3646eac351be730e35202855f762f4e8).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-09-18 13:44 UTC, srowen commented
Merged to master

2019-09-18 13:44 UTC, closed without merging