[SPARK-28791] [DOC] Documentation for Alter table Command
apache/spark pull request #25590
Opened 2019-08-27 04:37 UTC by PavithraRamachandran

What changes were proposed in this pull request?
Document ALTER TABLE statement in SQL Reference Guide.

Why are the changes needed?
Adding documentation for SQL reference.

Does this PR introduce any user-facing change?
yes

Before:
There was no documentation for this.

After.
![image (1)](https://user-images.githubusercontent.com/51401130/63741344-52c6b980-c8b2-11e9-9b9d-729645056e5d.png)

![image (2)](https://user-images.githubusercontent.com/51401130/63741350-59553100-c8b2-11e9-8403-28701d748d17.png)

![image (3)](https://user-images.githubusercontent.com/51401130/63741351-5e19e500-c8b2-11e9-845c-cd9101a24136.png)

How was this patch tested?
Used jekyll build and serve to verify.

2019-09-15 16:57 UTC, dilipbiswal commented
@PavithraRamachandran Could you please re-check this PR ? It seems to contain un-related changes.

2019-09-16 18:07 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-09-20 20:58 UTC, gatorsmile commented
ok to test

2019-09-20 21:01 UTC, SparkQA commented
**[Test build #111091 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/111091/testReport)** for PR 25590 at commit [`69ac8da`](https://github.com/apache/spark/commit/69ac8dadb45d12e743c7cd768251ff663ea453e3).

2019-09-20 21:02 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-09-20 21:02 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/16175/
Test PASSed.

2019-09-20 21:14 UTC, SparkQA commented
**[Test build #111091 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/111091/testReport)** for PR 25590 at commit [`69ac8da`](https://github.com/apache/spark/commit/69ac8dadb45d12e743c7cd768251ff663ea453e3).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-09-20 21:14 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-09-20 21:14 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/111091/
Test PASSed.

2019-09-26 09:01 UTC, PavithraRamachandran commented
@dilipbiswal could u review the document?

2019-09-26 09:04 UTC, SparkQA commented
**[Test build #111416 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/111416/testReport)** for PR 25590 at commit [`6a74d80`](https://github.com/apache/spark/commit/6a74d80ecb04a1f31df725f98745a7598ed0989f).

2019-09-26 09:05 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-09-26 09:05 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/16455/
Test PASSed.

2019-09-26 09:16 UTC, SparkQA commented
**[Test build #111416 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/111416/testReport)** for PR 25590 at commit [`6a74d80`](https://github.com/apache/spark/commit/6a74d80ecb04a1f31df725f98745a7598ed0989f).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-09-26 09:16 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-09-26 09:16 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/111416/
Test PASSed.

2019-10-21 18:43 UTC, srowen requested changes

2019-10-21 18:43 UTC, srowen commented on docs/sql-ref-syntax-ddl-alter-table.md
> +`ALTER TABLE RENAME` statement changes the table name of an exsisting table in the Database.
Database -> database.
You might need a blank line after this line.

2019-10-21 18:43 UTC, srowen commented on docs/sql-ref-syntax-ddl-alter-table.md
> +`ALTER TABLE SET` command is used for setting the Table properties.If a particular property was already set,
Table -> table
space after period

2019-10-21 18:43 UTC, srowen commented on docs/sql-ref-syntax-ddl-alter-table.md
> +`ALTER TABLE USET` is used to drop the table Property.
`UNSET`
Property -> property

2019-10-21 18:43 UTC, srowen commented on docs/sql-ref-syntax-ddl-alter-table.md
> +`ALTER TABLE SET` command is used for setting the SERDE or SERDE Propeties in Hive tables.If a particular property was already set,
Space after period

2019-10-21 18:43 UTC, srowen commented on docs/sql-ref-syntax-ddl-alter-table.md
> +desc student;
DESC

2019-10-22 16:09 UTC, SparkQA commented
**[Test build #112474 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/112474/testReport)** for PR 25590 at commit [`5a656d3`](https://github.com/apache/spark/commit/5a656d3935c0e171c6d24b0570754f8ecd2ab169).

2019-10-22 16:11 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-10-22 16:11 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/17441/
Test PASSed.

2019-10-22 16:11 UTC, PavithraRamachandran commented
@srowen i have addressed the review comments could you review.

2019-10-22 16:21 UTC, SparkQA commented
**[Test build #112474 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/112474/testReport)** for PR 25590 at commit [`5a656d3`](https://github.com/apache/spark/commit/5a656d3935c0e171c6d24b0570754f8ecd2ab169).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-10-22 16:21 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-10-22 16:21 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/112474/
Test PASSed.

2019-10-23 00:09 UTC, srowen commented on docs/sql-ref-syntax-ddl-alter-table.md
> +show partitions StudentInfo;
Let's consistently UPPER CASE reserved words like `SHOW PARTITIONS`

2019-10-23 00:09 UTC, srowen commented on docs/sql-ref-syntax-ddl-alter-table.md
> +  <dd>Name of the  exsisting database.</dd>
Small nit: extra space here

2019-10-23 10:31 UTC, PavithraRamachandran commented
@srowen reworked on the review comments. Could you review.

2019-10-23 13:25 UTC, srowen commented
@PavithraRamachandran did you push?

2019-10-23 14:22 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-10-23 14:22 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/17510/
Test PASSed.

2019-10-23 14:22 UTC, PavithraRamachandran commented
@srowen i have now..

2019-10-23 14:28 UTC, SparkQA commented
**[Test build #112546 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/112546/testReport)** for PR 25590 at commit [`edfa1ed`](https://github.com/apache/spark/commit/edfa1eded10d1b5d0075d931029826aea5c47f0b).

2019-10-23 14:35 UTC, srowen commented on docs/sql-ref-syntax-ddl-alter-table.md
> +`ALTER TABLE USET` is used to drop the table property.
There are still some issues from the previous review like this one: `UNSET`

2019-10-23 14:38 UTC, SparkQA commented
**[Test build #112546 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/112546/testReport)** for PR 25590 at commit [`edfa1ed`](https://github.com/apache/spark/commit/edfa1eded10d1b5d0075d931029826aea5c47f0b).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-10-23 14:38 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-10-23 14:38 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/112546/
Test PASSed.

2019-10-24 08:18 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-10-24 08:18 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/17562/
Test PASSed.

2019-10-24 08:18 UTC, PavithraRamachandran commented
@srowen sorry..I missed that. I have corrected . Could you review

2019-10-24 08:24 UTC, SparkQA commented
**[Test build #112598 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/112598/testReport)** for PR 25590 at commit [`68e9032`](https://github.com/apache/spark/commit/68e9032443002f59126e276e6cab474ae3209645).

2019-10-24 08:37 UTC, SparkQA commented
**[Test build #112598 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/112598/testReport)** for PR 25590 at commit [`68e9032`](https://github.com/apache/spark/commit/68e9032443002f59126e276e6cab474ae3209645).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-10-24 08:37 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-10-24 08:38 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/112598/
Test PASSed.

2019-10-24 13:18 UTC, srowen approved these changes

2019-10-24 13:19 UTC, srowen commented
Merged to master

2019-10-24 13:19 UTC, closed without merging