[SPARK-29464][PYTHON][ML] PySpark ML should expose Params.clear() to unset a user supplied Param
apache/spark pull request #26130
Opened 2019-10-15 16:36 UTC by huaxingao

### What changes were proposed in this pull request?
change PySpark ml ```Params._clear``` to ```Params.clear```

### Why are the changes needed?
PySpark ML currently has a private _clear() method that will unset a param. This should be made public to match the Scala API and give users a way to unset a user supplied param. 

### Does this PR introduce any user-facing change?
Yes. PySpark ml ```Params._clear``` ---> ```Params.clear```

### How was this patch tested?
Add test.

2019-10-15 16:42 UTC, SparkQA commented
**[Test build #112120 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/112120/testReport)** for PR 26130 at commit [`a555474`](https://github.com/apache/spark/commit/a555474934c531ef6d340b3bddc7e901b1b83cd1).

2019-10-15 16:43 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-10-15 16:43 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/17115/
Test PASSed.

2019-10-15 16:55 UTC, huaxingao commented
@BryanCutler @srowen 
Could you please review? Thanks a lot!

2019-10-15 17:24 UTC, SparkQA commented
**[Test build #112120 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/112120/testReport)** for PR 26130 at commit [`a555474`](https://github.com/apache/spark/commit/a555474934c531ef6d340b3bddc7e901b1b83cd1).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-10-15 17:25 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-10-15 17:25 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/112120/
Test PASSed.

2019-10-15 17:54 UTC, BryanCutler commented
@huaxingao I think there is a problem when the Java object has the param set, then it is cleared in Python but not Java. For example:

```python
In [4]:     >>> from pyspark.ml.linalg import Vectors 
   ...:     >>> df = spark.createDataFrame([(Vectors.dense([1.0]),), (Vectors.dense([2.0]),)], ["a"])
   ...:     >>> maScaler = MaxAbsScaler(inputCol="a", outputCol="scaled") 
   ...:     >>> model = maScaler.fit(df) 
   ...:     >>> model.setOutputCol("scaledOutput")                                                  
Out[4]: MaxAbsScaler_f91118f1dd81                                               

In [7]: model.clear(model.outputCol)                                                               

In [9]: model.getOutputCol()                                                                        
Out[9]: 'MaxAbsScaler_f91118f1dd81__output'

In [11]: model.transform(df).show()                                                                 
+-----+------+
|    a|scaled|
+-----+------+
|[1.0]| [0.5]|
|[2.0]| [1.0]|
+-----+------+
```

2019-10-15 17:54 UTC, BryanCutler requested changes
Need to sync with Java after clear

2019-10-15 22:25 UTC, SparkQA commented
**[Test build #112128 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/112128/testReport)** for PR 26130 at commit [`a21f39c`](https://github.com/apache/spark/commit/a21f39cc48ed41b9254e3b6d9b03d1f101da8862).

2019-10-15 22:26 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-10-15 22:26 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/17123/
Test PASSed.

2019-10-15 22:54 UTC, SparkQA commented
**[Test build #112128 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/112128/testReport)** for PR 26130 at commit [`a21f39c`](https://github.com/apache/spark/commit/a21f39cc48ed41b9254e3b6d9b03d1f101da8862).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-10-15 22:55 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-10-15 22:55 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/112128/
Test PASSed.

2019-10-16 16:59 UTC, srowen approved these changes
Looks OK to me pending tests if it looks good to you both.

2019-10-17 09:40 UTC, zhengruifeng commented
retest this please

2019-10-17 14:41 UTC, SparkQA commented
**[Test build #4900 has started](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/4900/testReport)** for PR 26130 at commit [`a21f39c`](https://github.com/apache/spark/commit/a21f39cc48ed41b9254e3b6d9b03d1f101da8862).

2019-10-17 23:21 UTC, BryanCutler commented on python/pyspark/ml/tests/test_param.py
> +        self.assertEqual(model.getOutputCol()[:12], 'MaxAbsScaler')
Instead, could you check that `outputCol` is equal to the default value?

2019-10-17 23:26 UTC, BryanCutler commented on python/pyspark/ml/tests/test_param.py
> +        self.assertEqual(model.getOutputCol()[:12], 'MaxAbsScaler')
Nvm, I guess there isn't a way to get the default value directly. This is fine then.

2019-10-17 23:32 UTC, BryanCutler approved these changes
LGTM

2019-10-18 00:02 UTC, closed without merging

2019-10-18 00:02 UTC, BryanCutler commented
merged to master, thanks @huaxingao !

2019-10-18 00:41 UTC, huaxingao commented
Thank you all for the help!