[SPARK-29452][WEebUI]Improve tooltip Storage tab
apache/spark pull request #26226
Opened 2019-10-23 12:24 UTC by iRakson

### What changes were proposed in this pull request?
Added Tootips for each column in storage tab of Web UI.

### Why are the changes needed?
Tooltips will help users in understanding columns of storage tabs.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
Manually Tested.

2019-10-23 12:29 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-10-23 12:30 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-10-23 12:43 UTC, wangyum commented
ok to test

2019-10-23 12:45 UTC, SparkQA commented
**[Test build #112544 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/112544/testReport)** for PR 26226 at commit [`6aeff3d`](https://github.com/apache/spark/commit/6aeff3d07e278ef394531e2110264bcbc169238f).

2019-10-23 12:47 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-10-23 12:47 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/17508/
Test PASSed.

2019-10-23 14:32 UTC, SparkQA commented
**[Test build #112544 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/112544/testReport)** for PR 26226 at commit [`6aeff3d`](https://github.com/apache/spark/commit/6aeff3d07e278ef394531e2110264bcbc169238f).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-10-23 14:32 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/112544/
Test FAILed.

2019-10-24 08:20 UTC, uncleGen commented
retest this please.

2019-10-24 17:27 UTC, dongjoon-hyun requested changes
Hi, @iRakson .
Could you fix the UT `StoragePageSuite.rddTable`?
- https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/112544/testReport/org.apache.spark.ui.storage/StoragePageSuite/rddTable/

2019-10-25 05:34 UTC, iRakson commented
@dongjoon-hyun yes working on this issue.

2019-10-25 08:38 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-10-25 08:38 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/17617/
Test PASSed.

2019-10-25 11:07 UTC, SparkQA commented
**[Test build #112659 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/112659/testReport)** for PR 26226 at commit [`8a9fcf6`](https://github.com/apache/spark/commit/8a9fcf644ff04c6783d8eb3985811052048fd8ab).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-10-25 11:09 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-10-25 11:09 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/112659/
Test PASSed.

2019-10-25 13:30 UTC, srowen requested changes

2019-10-25 13:30 UTC, srowen commented on core/src/main/scala/org/apache/spark/ui/storage/ToolTips.scala
> +    "Total size in the memory"
the memory -> memory
Total size of what? (cached partitions)

2019-10-25 13:30 UTC, srowen commented on core/src/main/scala/org/apache/spark/ui/storage/ToolTips.scala
> +    "Fraction of RDD cached"
Interesting, I actually dont' know whether is the fraction of partitions or data cached. That's not quite the same. Would be good to figure it out and clarify here

2019-10-25 13:30 UTC, srowen commented on core/src/main/scala/org/apache/spark/ui/storage/ToolTips.scala
> +    "StorageLevel displays where RDD is stored, " +
Format, Replication, Serialized, De-serialized should not be capitalized
RDD -> the RDD

2019-10-25 13:30 UTC, srowen commented on core/src/main/scala/org/apache/spark/ui/storage/ToolTips.scala
> +    "Name of persisted RDD"
Use 'persisted' or 'cached' consistently

2019-10-25 13:30 UTC, srowen commented on core/src/main/scala/org/apache/spark/ui/storage/ToolTips.scala
> +    "ID of RDD"
This doesn't add anything

2019-10-30 04:37 UTC, SparkQA commented
**[Test build #112883 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/112883/testReport)** for PR 26226 at commit [`f559d6b`](https://github.com/apache/spark/commit/f559d6b1218d5a4a8230a342ac868b97a4e92abd).

2019-10-30 04:40 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-10-30 04:40 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/17807/
Test PASSed.

2019-10-30 07:02 UTC, SparkQA commented
**[Test build #112883 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/112883/testReport)** for PR 26226 at commit [`f559d6b`](https://github.com/apache/spark/commit/f559d6b1218d5a4a8230a342ac868b97a4e92abd).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2019-10-30 07:04 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2019-10-30 07:04 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/112883/
Test PASSed.

2019-10-30 13:25 UTC, srowen approved these changes

2019-10-31 02:55 UTC, iRakson commented
cc @wangyum

2019-11-01 13:27 UTC, closed without merging

2019-11-01 13:27 UTC, srowen commented
Merged to master

2019-11-01 13:28 UTC, srowen commented
Merged to master. @iRakson what's your JIRA ID? I can assign you the issue.

2019-11-01 16:42 UTC, iRakson commented
@srowen Rakesh Raushan