[SPARK-30470][SQL]Uncache cached temp tables on session closed
apache/spark pull request #27149
Opened 2020-01-09 11:21 UTC by liupc

### What changes were proposed in this pull request?

Currently, Spark will not cleanup cached tables in tempViews produced by sql like following
`CACHE TABLE table1 as SELECT ....`
There are risks that the `uncache table` not called due to session closed unexpectedly, or user closed manually. Then these temp views will lost, and we can not visit them in other session, but the cached plan still exists in the `CacheManager`.
Moreover, the leaks may cause the failure of the subsequent query.
```
Caused by: java.io.FileNotFoundException: File does not exist: /user/xxxx/xx/data__db60e76d_91b8_42f3_909d_5c68692ecdd4Caused by: java.io.FileNotFoundException: File does not exist: /user/xxxx/xx/data__db60e76d_91b8_42f3_909d_5c68692ecdd4It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved. at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:131) at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:182) at 
```
This PR will fix it.

### Why are the changes needed?
This PR will fix the above issues by uncache cached temp tables when closing session.

### Does this PR introduce any user-facing change?
Yes

### How was this patch tested?
UT

2020-01-09 11:26 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-01-09 11:27 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-01-10 02:16 UTC, maropu commented
Why did you add a public interface for that? I think this issue should be handled implicitly for users.

2020-01-10 03:05 UTC, liupc commented
Thanks for reply @maropu , Yes, this should be handled implicitly for users, I'll make this interface private.

2020-01-12 03:58 UTC, dongjoon-hyun requested changes
Hi, @liupc . Could you provide a reproducible procedure on master branch? Or at least, Apache Spark 3.0.0-preview2?

Also, cc @LantaoJin because this might be a duplication of #26543 .

2020-01-17 01:07 UTC, dongjoon-hyun commented
Gentle ping, @liupc .

2020-01-20 09:23 UTC, liupc commented
@dongjoon-hyun  Thanks, I think this is a duplication of  of [#26543](https://github.com/apache/spark/pull/26543), I'll close it.

2020-01-20 09:23 UTC, closed without merging

2020-01-20 09:58 UTC, maropu commented
I've closed the corresponding PR, too.

2020-01-21 04:40 UTC, dongjoon-hyun commented
Thank you for confirming and closing PRs, @liupc and @maropu .