[SPARK-30574][DOC] Document GROUP BY Clause of SELECT statement in SQL Reference.
apache/spark pull request #27283
Opened 2020-01-20 01:27 UTC by dilipbiswal

### What changes were proposed in this pull request?
Document GROUP BY clause of SELECT statement in SQL Reference Guide.

### Why are the changes needed?
Currently Spark lacks documentation on the supported SQL constructs causing
confusion among users who sometimes have to look at the code to understand the
usage. This is aimed at addressing this issue.

### Does this PR introduce any user-facing change?
Yes. 

**Before:**
There was no documentation for this.

**After.**
<img width="1093" alt="Screen Shot 2020-01-19 at 5 11 12 PM" src="https://user-images.githubusercontent.com/14225158/72692222-7bf51a00-3adf-11ea-8851-1d313b49020e.png">
<img width="1040" alt="Screen Shot 2020-01-19 at 5 11 32 PM" src="https://user-images.githubusercontent.com/14225158/72692235-90d1ad80-3adf-11ea-947d-df9ab5051069.png">
<img width="1040" alt="Screen Shot 2020-01-19 at 5 11 49 PM" src="https://user-images.githubusercontent.com/14225158/72692257-a8109b00-3adf-11ea-98e8-40742be2ce1a.png">
<img width="1040" alt="Screen Shot 2020-01-19 at 5 12 05 PM" src="https://user-images.githubusercontent.com/14225158/72692372-5d435300-3ae0-11ea-8832-55d9a0426478.png">
<img width="1040" alt="Screen Shot 2020-01-19 at 5 12 31 PM" src="https://user-images.githubusercontent.com/14225158/72692386-69c7ab80-3ae0-11ea-92e4-f1daab6ff897.png">
<img width="960" alt="Screen Shot 2020-01-19 at 5 26 38 PM" src="https://user-images.githubusercontent.com/14225158/72692460-e9ee1100-3ae0-11ea-909e-18e0f90476d9.png">

### How was this patch tested?
Tested using jykyll build --serve

2020-01-20 01:28 UTC, SparkQA commented
**[Test build #117042 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/117042/testReport)** for PR 27283 at commit [`f0f2b18`](https://github.com/apache/spark/commit/f0f2b189d0c572955e7497d22212cddc7e380c53).

2020-01-20 01:29 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-01-20 01:29 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/21807/
Test PASSed.

2020-01-20 01:39 UTC, SparkQA commented
**[Test build #117042 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/117042/testReport)** for PR 27283 at commit [`f0f2b18`](https://github.com/apache/spark/commit/f0f2b189d0c572955e7497d22212cddc7e380c53).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2020-01-20 01:39 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-01-20 01:39 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/117042/
Test PASSed.

2020-01-20 03:47 UTC, huaxingao commented on docs/sql-ref-syntax-qry-select-groupby.md
> +    set is specified by a list of comma separated expressions in parenthses.<br><br>
```parenthses``` typo

2020-01-20 03:47 UTC, huaxingao commented on docs/sql-ref-syntax-qry-select-groupby.md
> +INSERT INTO dealer  VALUES (100, 'Fremont', 'Honda Civic', 10),
There is an extra space between ```dealer``` and   ```VALUES```

2020-01-20 03:51 UTC, huaxingao commented
```displayTitle: GROUPBY Clause``` -> ```displayTitle: GROUP BY Clause```?

2020-01-20 05:41 UTC, huaxingao commented on docs/sql-ref-syntax-qry-select-groupby.md
> +    is a short-hand to using an <code>UNION ALL</code> where each leg of the <code>UNION ALL</code>
```This clause is a short-hand to using an <code>UNION ALL</code>``` 
-> ```This clause is a shorthand for a <code>UNION ALL</code>``` ?

2020-01-20 06:47 UTC, SparkQA commented
**[Test build #117085 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/117085/testReport)** for PR 27283 at commit [`d69ceec`](https://github.com/apache/spark/commit/d69ceecea3e33e3322de4d40d99cf9770ebe5482).

2020-01-20 06:48 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-01-20 06:48 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/21849/
Test PASSed.

2020-01-20 07:01 UTC, SparkQA commented
**[Test build #117085 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/117085/testReport)** for PR 27283 at commit [`d69ceec`](https://github.com/apache/spark/commit/d69ceecea3e33e3322de4d40d99cf9770ebe5482).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2020-01-20 07:02 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-01-20 07:02 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/117085/
Test PASSed.

2020-01-20 15:44 UTC, srowen requested changes

2020-01-20 15:44 UTC, srowen commented on docs/sql-ref-syntax-qry-select-groupby.md
> +    set is specified by a list of comma separated expressions in parenthesis.<br><br>
comma-separated
parentheses

2020-01-20 15:44 UTC, srowen commented on docs/sql-ref-syntax-qry-select-groupby.md
> +    Specifies the crieteria based on which the rows are grouped together. A grouping expression may be a column alias,
critieria
Somewhere above or here do you want to say that the grouping is done on the _values_ that result from the expression? calling them criteria suggests they are logical expressions, perhaps.

2020-01-20 15:44 UTC, srowen commented on docs/sql-ref-syntax-qry-select-groupby.md
> +    is a shorthand for a <code>UNION ALL</code> where each leg of the <code>UNION ALL</code>
I'd say "is shorthand", but either way be consistent as "short-hand" appears below

2020-01-20 15:44 UTC, srowen commented on docs/sql-ref-syntax-qry-select-groupby.md
> +    to GROUP BY warehouse, product GROUPING SETS ((warehouse, product), (warehouse), (product), ()).
Code-font this expression?

2020-01-20 21:57 UTC, SparkQA commented
**[Test build #117134 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/117134/testReport)** for PR 27283 at commit [`9eeca32`](https://github.com/apache/spark/commit/9eeca324b57b9dc4383bb7c81331dfdfc11d7ffd).

2020-01-20 21:59 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-01-20 21:59 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/21898/
Test PASSed.

2020-01-20 22:07 UTC, SparkQA commented
**[Test build #117134 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/117134/testReport)** for PR 27283 at commit [`9eeca32`](https://github.com/apache/spark/commit/9eeca324b57b9dc4383bb7c81331dfdfc11d7ffd).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2020-01-20 22:08 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-01-20 22:08 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/117134/
Test PASSed.

2020-01-22 14:48 UTC, srowen approved these changes

2020-01-23 00:30 UTC, srowen commented
Merged to master

2020-01-23 00:30 UTC, closed without merging