[SPARK-31054][REPL] Turn on deprecation in Scala REPL/SparkShell by default
apache/spark pull request #27813
Opened 2020-03-05 16:22 UTC by Ngone51

### What changes were proposed in this pull request?

In this PR, I propose to turn on `-deprecation` in SparkShell by default.

### Why are the changes needed?

Without `-deprecation`, user can not know details(why we deprecate, any alternatives to use) of the deprecation API and they even don't know the warning is from which deprecated API.

Though, Scala REPL will tell user to use `:setting -deprecation` or `:replay -deprecation` to enable deprecation. But we can not guarantee that user know exactly how to use it and they may even not willing to do it. So, I think show the details of deprecation explicitly by ourself will give user a chance to learn Spark's deprecated API.

Besides, there's always a warning. So, why don't we choose the detail and useful one?

### Does this PR introduce any user-facing change?

Yes. When using a deprecate API,

Before:

```
import org.apache.spark.sql._
scala> Row.merge(Row(1,2,3), Row(4,5,6))
warning: there was one deprecation warning (since 3.0.0); for details, enable `:setting -deprecation' or `:replay -deprecation'
res0: org.apache.spark.sql.Row = [1,2,3,4,5,6]
```

After:

```
import org.apache.spark.sql._
scala> Row.merge(Row(1,2,3), Row(4,5,6))
<console>:28: warning: method merge in object Row is deprecated (since 3.0.0): This method is deprecated and will be removed in future versions.
       Row.merge(Row(1,2,3), Row(4,5,6))
           ^
```

### How was this patch tested?

Tested manually.

2020-03-05 16:22 UTC, Ngone51 commented
ping @cloud-fan @HyukjinKwon What do you think?

2020-03-05 16:27 UTC, SparkQA commented
**[Test build #119405 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/119405/testReport)** for PR 27813 at commit [`3650955`](https://github.com/apache/spark/commit/36509555cb20323d1c5517b07f44f91422267518).

2020-03-05 16:28 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-03-05 16:28 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/24142/
Test PASSed.

2020-03-05 16:38 UTC, srowen commented
Probably OK. I'd only not do it if some common non-deprecated API, when called, triggered some deprecated API and triggered a warning frequently, but I can't think of such a scenario.

2020-03-05 16:49 UTC, SparkQA commented
**[Test build #119405 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/119405/testReport)** for PR 27813 at commit [`3650955`](https://github.com/apache/spark/commit/36509555cb20323d1c5517b07f44f91422267518).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2020-03-05 16:49 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-03-05 16:49 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/119405/
Test PASSed.

2020-03-05 16:55 UTC, cloud-fan commented
Seems like a good idea to me, to warn people about using deprecated APIs.

cc @dongjoon-hyun

2020-03-05 18:29 UTC, dongjoon-hyun commented
Thank you for pinging me, @cloud-fan .

2020-03-05 18:35 UTC, dongjoon-hyun requested changes
@Ngone51 . +1 for the intention, but this has more serious side-effect.

Although this is good for giving the detail warnings for Apache Spark module, this seems to expose non-Apache-Spark deprecation warnings (Java and Scala and 3rd Party library) together like DEBUG message. I'm not sure about that in terms of UX.

**BEFORE**
```scala
scala> new java.rmi.RMISecurityException("a")
warning: there were two deprecation warnings; re-run with -deprecation for details
res0: java.rmi.RMISecurityException = java.rmi.RMISecurityException: a
```

**AFTER**
```scala
scala> new java.rmi.RMISecurityException("a")
<console>:24: warning: constructor RMISecurityException in class RMISecurityException is deprecated: see corresponding Javadoc for more information.
       new java.rmi.RMISecurityException("a")
       ^
<console>:24: warning: class RMISecurityException in package rmi is deprecated: see corresponding Javadoc for more information.
       new java.rmi.RMISecurityException("a")
                    ^
res0: java.rmi.RMISecurityException = java.rmi.RMISecurityException: a
```

In general, I'm -1 because this is too intrusive for non-Apache-Spark deprecations.

Although we are not provide this, user still can add `-deprecation` manually if they want.

2020-03-06 02:53 UTC, HyukjinKwon commented
Yeah, it's Scala shell's option, right? You can already do `./bin/spark-shell -deprecation` too. After this change, there's no way to disable. It seems too invasive in particular when we think about some other notebooks.

I am less strongly against it if we can optionally control it, e.g., a Spark Shell specific option that negates `-deprecation`.

I know we're discussing about deprecation and removal but this seems overkill by forcing to show warnings without a way to disable it back.

2020-03-06 03:27 UTC, gengliangwang commented
Sorry I am -1 too, for end-users' experience.

2020-03-06 03:45 UTC, cloud-fan commented
Is it possible to only show deprecation warnings of Spark?

2020-03-06 07:16 UTC, Ngone51 commented
Thank you guys for all your inputs here. It make sense to me about intrusive warnings from third-party and optionally control.

Since I cannot find better way to improve and address your concern, I'm going to close this.

Thanks, anyway!!

2020-03-06 07:16 UTC, closed without merging