[SPARK-31601][K8S] Fix spark.kubernetes.executor.podNamePrefix to work
apache/spark pull request #28401
Opened 2020-04-29 06:25 UTC by dongjoon-hyun

### What changes were proposed in this pull request?

### Why are the changes needed?

### Does this PR introduce any user-facing change?

### How was this patch tested?

2020-04-29 06:31 UTC, SparkQA commented
**[Test build #122041 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/122041/testReport)** for PR 28401 at commit [`e42d772`](https://github.com/apache/spark/commit/e42d7727a71ba3d6ffa7d3387a79743aba59c734).

2020-04-29 06:31 UTC, dongjoon-hyun commented on resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/features/BasicDriverFeatureStep.scala
> -      KUBERNETES_EXECUTOR_POD_NAME_PREFIX.key -> conf.resourceNamePrefix,
The previous code invoked `KubernetesDriverConf.resourceNamePrefix`. The correct logic for executor is inside `KubernetesExecutorConf.resourceNamePrefix`.

2020-04-29 06:33 UTC, SparkQA commented
**[Test build #122041 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/122041/testReport)** for PR 28401 at commit [`e42d772`](https://github.com/apache/spark/commit/e42d7727a71ba3d6ffa7d3387a79743aba59c734).
 * This patch **fails Scala style tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2020-04-29 06:33 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2020-04-29 06:33 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/122041/
Test FAILed.

2020-04-29 06:39 UTC, SparkQA commented
**[Test build #122043 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/122043/testReport)** for PR 28401 at commit [`fd5378c`](https://github.com/apache/spark/commit/fd5378c6bbda882830e27fa9b6c77fc53170f71a).

2020-04-29 06:54 UTC, SparkQA commented
**[Test build #122043 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/122043/testReport)** for PR 28401 at commit [`fd5378c`](https://github.com/apache/spark/commit/fd5378c6bbda882830e27fa9b6c77fc53170f71a).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2020-04-29 06:55 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-04-29 06:55 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/122043/
Test PASSed.

2020-04-29 07:20 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/26716/

2020-04-29 07:26 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/26714/

2020-04-29 07:37 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/26717/

2020-04-29 07:38 UTC, SparkQA commented
Kubernetes integration test status success
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/26716/

2020-04-29 07:38 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-04-29 07:38 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/26716/
Test PASSed.

2020-04-29 07:48 UTC, SparkQA commented
Kubernetes integration test status failure
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/26714/

2020-04-29 07:48 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2020-04-29 07:48 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/26714/
Test FAILed.

2020-04-29 07:58 UTC, ScrapCodes commented
Hi @dongjoon-hyun , thanks for the fix ! LGTM. 

- Run SparkPi with no resources *** FAILED ***
  The code passed to eventually never returned normally. Attempted 130 times over 2.0021201478333333 minutes. Last failure message: false was not true. (KubernetesSuite.scala:370) 

^^^ Seems to be a flaky test.

2020-04-29 07:58 UTC, ScrapCodes commented
retest

2020-04-29 08:02 UTC, ScrapCodes commented on resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/KubernetesConf.scala
> +  // We need to bypass this conf to KubernetesExecutorConf for further processing
nit. bypass -> pass

2020-04-29 08:05 UTC, SparkQA commented
Kubernetes integration test status success
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/26717/

2020-04-29 08:05 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-04-29 08:05 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/26717/
Test PASSed.

2020-04-29 09:02 UTC, ScrapCodes requested changes

2020-04-29 09:26 UTC, ScrapCodes commented on resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/features/BasicDriverFeatureStep.scala
> +      additionalProps.put(KUBERNETES_EXECUTOR_POD_NAME_PREFIX.key, _))
Feel free to correct me, I could be missing something.

2020-04-29 15:55 UTC, dongjoon-hyun commented on resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/features/BasicDriverFeatureStep.scala
> +      additionalProps.put(KUBERNETES_EXECUTOR_POD_NAME_PREFIX.key, _))
Thanks! I'll update like that.

2020-04-29 16:00 UTC, dongjoon-hyun commented
Thank you so much for review, @ScrapCodes .

2020-04-29 16:00 UTC, SparkQA commented
**[Test build #122073 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/122073/testReport)** for PR 28401 at commit [`c1e181d`](https://github.com/apache/spark/commit/c1e181d77692db8622e95b219d3c31cdb51991f0).

2020-04-29 16:14 UTC, SparkQA commented
**[Test build #122073 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/122073/testReport)** for PR 28401 at commit [`c1e181d`](https://github.com/apache/spark/commit/c1e181d77692db8622e95b219d3c31cdb51991f0).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2020-04-29 16:14 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-04-29 16:14 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/122073/
Test PASSed.

2020-04-29 16:48 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/26748/

2020-04-29 17:14 UTC, SparkQA commented
Kubernetes integration test status failure
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/26748/

2020-04-29 17:14 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2020-04-29 17:14 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/26748/
Test FAILed.

2020-04-29 18:02 UTC, dongjoon-hyun commented
Retest this please.

2020-04-29 18:07 UTC, SparkQA commented
**[Test build #122083 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/122083/testReport)** for PR 28401 at commit [`c1e181d`](https://github.com/apache/spark/commit/c1e181d77692db8622e95b219d3c31cdb51991f0).

2020-04-29 18:23 UTC, SparkQA commented
**[Test build #122083 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/122083/testReport)** for PR 28401 at commit [`c1e181d`](https://github.com/apache/spark/commit/c1e181d77692db8622e95b219d3c31cdb51991f0).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2020-04-29 18:23 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-04-29 18:23 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/122083/
Test PASSed.

2020-04-29 18:56 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/26758/

2020-04-29 19:01 UTC, dongjoon-hyun commented
cc @holdenk

2020-04-29 19:14 UTC, SparkQA commented
Kubernetes integration test status success
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/26758/

2020-04-29 19:14 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-04-29 19:14 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/26758/
Test PASSed.

2020-04-30 03:00 UTC, dongjoon-hyun commented
Could you review this once more, @ScrapCodes ?

2020-04-30 03:27 UTC, ScrapCodes commented
Thanks ! @dongjoon-hyun , LGTM :)

2020-04-30 03:28 UTC, ScrapCodes approved these changes

2020-04-30 03:29 UTC, ScrapCodes commented
I wish we had a merge bot, which could detect a LGTM from a committer and do the need full.

2020-04-30 03:42 UTC, ScrapCodes commented
I am going to merge this into Master and branch-3.0.

2020-04-30 03:46 UTC, closed without merging

2020-04-30 04:50 UTC, dongjoon-hyun commented
Thank you for review and merging, @ScrapCodes .
Ya. Bot is popular in these days. :)

2020-04-30 05:09 UTC, dongjoon-hyun commented
Since the bug exists in `branch-2.4`, I cherry-pick this to branch-2.4, too.

cc @holdenk

2020-04-30 05:11 UTC, ScrapCodes commented
@dongjoon-hyun honestly, I was about to say that, thanks for doing it. :)

2020-04-30 05:12 UTC, dongjoon-hyun commented
:)