[SPARK-31959][SQL][3.0] Fix Gregorian-Julian micros rebasing while switching standard time zone offset
apache/spark pull request #28809
Opened 2020-06-12 07:55 UTC by MaxGekk

### What changes were proposed in this pull request?
Fix the bug in microseconds rebasing during transitions from one standard time zone offset to another one. In the PR, I propose to change the implementation of `rebaseGregorianToJulianMicros` which performs rebasing via local timestamps. In the case of overlapping:
1. Check that the original instant belongs to earlier or later instant of overlapped local timestamp.
2. If it is an earlier instant, take zone and DST offsets from the previous day otherwise
3. Set time zone offsets to Julian timestamp from the next day.

Note: The fix assumes that transitions cannot happen more often than once per 2 days.

### Why are the changes needed?
Current implementation handles timestamps overlapping only during daylight saving time but overlapping can happen also during transition from one standard time zone to another one. For example in the case of `Asia/Hong_Kong`, the time zone switched from `Japan Standard Time` (UTC+9) to `Hong Kong Time` (UTC+8) on _Sunday, 18 November, 1945 01:59:59 AM_. The changes allow to handle the special case as well.

### Does this PR introduce _any_ user-facing change?
It might affect micros rebasing in before common era when not-optimised version of `rebaseGregorianToJulianMicros()` is used directly.

### How was this patch tested?
1. By existing tests in `DateTimeUtilsSuite`, `RebaseDateTimeSuite`, `DateFunctionsSuite`, `DateExpressionsSuite` and `TimestampFormatterSuite`.
2. Added new test to `RebaseDateTimeSuite`
3. Regenerated `gregorian-julian-rebase-micros.json` with the step of 30 minutes, and got the same JSON file. The JSON file isn't affected because previously it was generated with the step of 1 week. And the spike in diffs/switch points during 1 hour of timestamp overlapping wasn't detected.

Authored-by: Max Gekk <max.gekk@gmail.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>
(cherry picked from commit c259844df8b6690b752a1c67b241de2981cdb5fe)
Signed-off-by: Max Gekk <max.gekk@gmail.com>

2020-06-12 07:55 UTC, MaxGekk commented
@cloud-fan Please, take a look at the backport of https://github.com/apache/spark/pull/28787 to branch-3.0

2020-06-12 08:01 UTC, SparkQA commented
**[Test build #123906 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/123906/testReport)** for PR 28809 at commit [`35245c0`](https://github.com/apache/spark/commit/35245c0fb5e018ca6c1d4b1b9a7dda36ae5cdc4b).

2020-06-12 08:02 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-06-12 08:02 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/28530/
Test PASSed.

2020-06-12 09:28 UTC, cloud-fan commented
do you know what caused the conflicts?

2020-06-12 09:34 UTC, MaxGekk commented
> do you know what caused the conflicts?

As usual - `fromMillis()`

2020-06-12 09:45 UTC, cloud-fan approved these changes

2020-06-12 11:51 UTC, SparkQA commented
**[Test build #123906 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/123906/testReport)** for PR 28809 at commit [`35245c0`](https://github.com/apache/spark/commit/35245c0fb5e018ca6c1d4b1b9a7dda36ae5cdc4b).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2020-06-12 11:52 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2020-06-12 11:52 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/123906/
Test FAILed.

2020-06-12 12:49 UTC, MaxGekk commented
Jenkins, retest this, please

2020-06-12 12:51 UTC, SparkQA commented
**[Test build #123925 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/123925/testReport)** for PR 28809 at commit [`35245c0`](https://github.com/apache/spark/commit/35245c0fb5e018ca6c1d4b1b9a7dda36ae5cdc4b).

2020-06-12 12:52 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-06-12 12:52 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/28547/
Test PASSed.

2020-06-12 18:30 UTC, gatorsmile commented
We need to split such a long Jenkin job to multiple shorter Jenkins Jobs

2020-06-12 18:41 UTC, SparkQA commented
**[Test build #123925 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/123925/testReport)** for PR 28809 at commit [`35245c0`](https://github.com/apache/spark/commit/35245c0fb5e018ca6c1d4b1b9a7dda36ae5cdc4b).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2020-06-12 18:44 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-06-12 18:44 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/123925/
Test PASSed.

2020-06-14 21:30 UTC, dongjoon-hyun commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/util/RebaseDateTimeSuite.scala
> +  test("SPARK-31959: JST -> HKT at Asia/Hong_Kong in 1945") {
Please hold on this. This test case is flaky in `master` branch already.
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-master-test-maven-hadoop-3.2-hive-2.3/lastCompletedBuild/testReport/org.apache.spark.sql.catalyst.util/RebaseDateTimeSuite/SPARK_31959__JST____HKT_at_Asia_Hong_Kong_in_1945/
```
- SPARK-31959: JST -> HKT at Asia/Hong_Kong in 1945 *** FAILED ***
  -766744200000000 did not equal -766747800000000 (RebaseDateTimeSuite.scala:432)
```

2020-06-14 21:43 UTC, dongjoon-hyun requested changes
After some investigations, I found that the failures seem to reported consistently on `research-jenkins-worker-09`. It might be Amplap Jenkins host issue (Java version or environment). We had better fix the host or make this PR more robust on those problems before merging this PR to `branch-3.0`.

2020-06-15 05:59 UTC, MaxGekk commented
> It might be Amplap Jenkins host issue (Java version or environment).

It uses JDK w/ outdated time zone database (not clear from log which version):
```
JAVA_HOME=/usr/lib/jvm/java-8-oracle
```
other jenkins machines have:
```
JAVA_HOME=/usr/java/jdk1.8.0_191
```
If we are not able to upgrade JDK 1.8 to the recent version, can we have at least the same JDK on all jenkins machines?

2020-06-15 06:06 UTC, MaxGekk commented
I am going to skip the test checks if JDK tzdb is outdated and Asia/Hong_Kong doesn't have timestamps overlapping in 1945 at all.

2020-06-15 08:48 UTC, MaxGekk commented
I will cherry-pick https://github.com/apache/spark/pull/28832 here when it will be merged to master.

2020-06-15 15:10 UTC, dongjoon-hyun commented
It's merged now. Thanks!

2020-06-15 15:23 UTC, SparkQA commented
**[Test build #124060 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/124060/testReport)** for PR 28809 at commit [`63898cf`](https://github.com/apache/spark/commit/63898cf439762d198a022e0fe7e4c4a4bb196350).

2020-06-15 15:24 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-06-15 15:24 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/28679/
Test PASSed.

2020-06-15 15:55 UTC, cloud-fan approved these changes

2020-06-15 20:33 UTC, SparkQA commented
**[Test build #124060 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/124060/testReport)** for PR 28809 at commit [`63898cf`](https://github.com/apache/spark/commit/63898cf439762d198a022e0fe7e4c4a4bb196350).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2020-06-15 20:36 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-06-15 20:36 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/124060/
Test PASSed.

2020-06-16 04:56 UTC, cloud-fan commented
thanks, merging to 3.0!

2020-06-16 05:00 UTC, closed without merging