[SPARK-32393][SQL] Fix postgres bpchar array support
apache/spark pull request #29192
Opened 2020-07-22 16:29 UTC by kujon

### What changes were proposed in this pull request?
This PR fixes the support for char(n)[], character(n)[] data types. Prior to this change, a user would get `Unsupported type ARRAY` exception when attempting to interact with the table with such types.

The description is a bit more detailed in the JIRA itself, but the crux of the issue is that postgres driver names char and character types as `bpchar`. The relevant driver code can be found [here](https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java#L85-L87). `char` is very likely to be still needed, as it seems that pg makes a distinction between `char(1)` and `char(n > 1)` as per [this code](https://github.com/pgjdbc/pgjdbc/blob/b7fd9f3cef734b4c219e2f6bc6c19acf68b2990b/pgjdbc/src/main/java/org/postgresql/core/Oid.java#L64).

### Why are the changes needed?
For completeness of the pg dialect support.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Unit tests

2020-07-22 16:33 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-07-22 16:34 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-07-23 01:32 UTC, maropu commented
Could you add tests in `PostgresIntegrationSuite` then check if the test can pass on your local env? (Note: our testing framework, Jenkins, does not run it).

2020-07-23 01:35 UTC, maropu commented
`bpchar` is internally used in postgresql (https://www.postgresql.org/docs/current/typeconv-query.html), but users can use it in DDL;
```
postgres=# create table t (v bpchar);
CREATE TABLE
```
So, I think its okay to add it for better interoperability.

2020-07-23 02:00 UTC, maropu commented
btw, thanks for your contribution, @kujon !

2020-07-23 02:31 UTC, maropu commented
ok to test

2020-07-23 02:36 UTC, SparkQA commented
**[Test build #126374 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/126374/testReport)** for PR 29192 at commit [`1000377`](https://github.com/apache/spark/commit/1000377777d580766ec2db4ffc230dae045838e0).

2020-07-23 02:38 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-07-23 02:38 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/30990/
Test PASSed.

2020-07-23 05:03 UTC, kujon commented
> Could you add tests in PostgresIntegrationSuite then check if the test can pass on your local env? (Note: our testing framework, Jenkins, does not run it).

will do!

2020-07-23 07:05 UTC, SparkQA commented
**[Test build #126374 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/126374/testReport)** for PR 29192 at commit [`1000377`](https://github.com/apache/spark/commit/1000377777d580766ec2db4ffc230dae045838e0).
 * This patch **fails due to an unknown error code, -9**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2020-07-23 07:06 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2020-07-23 07:06 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/126374/
Test FAILed.

2020-07-24 18:20 UTC, dongjoon-hyun requested changes
Thank you for your first contribution, @kujon . Also, thank you for trying to add a test into `PostgresIntegrationSuite`.
Could you revise the PR description to be complete without referencing JIRA? The PR description will become a permanent commit log and will be read much more times.

2020-07-28 00:02 UTC, maropu commented
@kujon Any update? If you get stuck, please let me know.

2020-07-28 08:23 UTC, kujon commented
Hi @maropu, I just need a few more days. I'm the meantime, I struggled finding said file, do you want me to add a fresh integration test?

2020-07-28 08:36 UTC, maropu commented
This one: https://github.com/apache/spark/blob/master/external/docker-integration-tests/src/test/scala/org/apache/spark/sql/jdbc/PostgresIntegrationSuite.scala
You can add test cases there, then run the tests via `./build/mvn -Pdocker-integration-tests -Dtest=none -DwildcardSuites=org.apache.spark.sql.jdbc.PostgresIntegrationSuite
`

2020-08-03 02:37 UTC, maropu commented
kindly ping.

2020-08-09 19:46 UTC, dongjoon-hyun commented
It seems that it's too hard requirement for a new contributor. How do you want to proceed this, @maropu ?

2020-08-10 01:47 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-08-10 01:47 UTC, dongjoon-hyun commented
I reopened this again, @kujon .

Hi, @maropu . It seems that this PR aims to support `CREATE TABLE t (a char(64)[]);` instead `CREATE TABLE t (a bpchar)`.

2020-08-10 01:48 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-08-10 01:52 UTC, dongjoon-hyun commented
ok to test

2020-08-10 01:55 UTC, SparkQA commented
**[Test build #127252 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/127252/testReport)** for PR 29192 at commit [`1000377`](https://github.com/apache/spark/commit/1000377777d580766ec2db4ffc230dae045838e0).

2020-08-10 01:56 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-08-10 01:56 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/31872/
Test PASSed.

2020-08-10 02:02 UTC, dongjoon-hyun reviewed
I manually verified that this achieved the goal. We will add a test coverage later as a follow-up.
```
postgres=# \d t
                     Table "public.t"
 Column |      Type       | Collation | Nullable | Default
--------+-----------------+-----------+----------+---------
 a      | character(64)[] |           |          |

scala> spark.read.jdbc("jdbc:postgresql://127.0.0.1:5432/?user=postgres&password=rootpass", "t", new java.util.Properties).show
+--------------------+
|                   a|
+--------------------+
|[str1            ...|
+--------------------+


scala> spark.read.jdbc("jdbc:postgresql://127.0.0.1:5432/?user=postgres&password=rootpass", "t", new java.util.Properties).printSchema
root
 |-- a: array (nullable = true)
 |    |-- element: string (containsNull = true)
```

2020-08-10 02:03 UTC, closed without merging

2020-08-10 02:06 UTC, dongjoon-hyun commented
Thank you for your first contribution, @kujon .
We added you to the Apache Spark contributor group and assign SPARK-32576 to you.
Welcome!

2020-08-10 07:05 UTC, SparkQA commented
**[Test build #127252 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/127252/testReport)** for PR 29192 at commit [`1000377`](https://github.com/apache/spark/commit/1000377777d580766ec2db4ffc230dae045838e0).
 * This patch **fails due to an unknown error code, -9**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2020-08-10 07:07 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2020-08-10 07:07 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/127252/
Test FAILed.

2020-08-10 09:15 UTC, kujon commented
@dongjoon-hyun apologies, I am quite short on time recently. Thanks for accepting the PR. I'll add the tests when I find some spare time.

2020-08-10 09:53 UTC, kujon commented
Ahh, I see it's being tackled in https://github.com/apache/spark/pull/29397 already. Thank you for that!

2020-08-10 10:04 UTC, maropu commented
Never mind, @kujon! Thanks for your contribution!

2020-08-10 13:32 UTC, dongjoon-hyun commented
Yep. Thank you, @kujon and @maropu . We are collaborating! :)