SPARK-32691 Bump commons-crypto to v1.1.0
apache/spark pull request #30275
Opened 2020-11-06 07:00 UTC by huangtianhua

The package commons-crypto-1.0.0 doesn't support aarch64 platform, it lead
the tests of replication failed due to crypto timeout, bump up to v1.1.0 which 
support aarch64.

See: 
https://issues.apache.org/jira/browse/CRYPTO-139
http://commons.apache.org/proper/commons-crypto/changes-report.html

2020-11-06 07:03 UTC, dongjoon-hyun commented
Thank you for your contribution, @huangtianhua . Could you recover the original PR description style please?

2020-11-06 07:06 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-11-06 07:07 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-11-06 18:07 UTC, dongjoon-hyun requested changes
Please run the following to update the dependency manifest and commit the change together. It will make GitHub Action pass.
```
dev/test-dependencies.sh --replace-manifest
```

2020-11-08 07:53 UTC, viirya commented
Why change the PR description style from
```
### Why are the changes needed?
```

to

```
**What changes were proposed in this pull request?**
```
?

Please just copy the original PR description template and fill the sections.

2020-11-09 02:34 UTC, dongjoon-hyun commented
ok to test

2020-11-09 02:40 UTC, SparkQA commented
**[Test build #130761 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/130761/testReport)** for PR 30275 at commit [`f85835b`](https://github.com/apache/spark/commit/f85835bee05c301ddf336dced2eeadf1fa236c20).

2020-11-09 02:48 UTC, dongjoon-hyun requested changes
BTW, could you elaborate more about the logic more technically?
> The package commons-crypto-1.0.0 doesn't support aarch64 platform, it lead the tests related with replication failure.

Also, if the root cause of failure is library `v1.0.0`, we need to backport this to `branch-3.0` at least with a new dedicate test suite because Apache Spark 3.0/2.4 also have `v1.0.0`. Please add a new and independent test case which is applicable for `master` and `branch-3.0` for SPARK-32691.

2020-11-09 03:24 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/35370/

2020-11-09 03:52 UTC, SparkQA commented
Kubernetes integration test status failure
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/35370/

2020-11-09 03:52 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2020-11-09 03:52 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/35370/
Test FAILed.

2020-11-09 05:11 UTC, SparkQA commented
**[Test build #130761 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/130761/testReport)** for PR 30275 at commit [`f85835b`](https://github.com/apache/spark/commit/f85835bee05c301ddf336dced2eeadf1fa236c20).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2020-11-09 05:13 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-11-09 05:13 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/130761/
Test PASSed.

2020-11-09 07:28 UTC, huangtianhua commented
@dongjoon-hyun,  thanks and I will add more logic details in the PR description.
Please add a new and independent test case which is applicable for master and branch-3.0 for SPARK-32691. --- I think the caching tests in DistributedSuite.scala is enough.

2020-11-09 16:48 UTC, dongjoon-hyun commented
Thank you for updating the PR description, @huangtianhua .

For the following, do you mean `the caching tests` fail in `branch-3.0` currently? For the unit test, we need a unit test which fails without this patch.
>  I think the caching tests in DistributedSuite.scala is enough.

2020-11-09 22:30 UTC, dongjoon-hyun commented
@huangtianhua . I'll merge this to `master` branch for Apache Spark 3.1.0.
If you need a backport to `branch-3.0` for Apache Spark 3.0.x, please make a backporting PR with the test case.

2020-11-09 22:33 UTC, closed without merging