[BugFix]fix the bug in issue SPARK-34760.
apache/spark pull request #31851
Opened 2021-03-16 13:01 UTC by zengruios

### What changes were proposed in this pull request?
In JavaSparkSQLExample when excecute 'peopleDF.write().partitionBy("favorite_color").bucketBy(42,"name").saveAsTable("people_partitioned_bucketed");'
throws Exception: 'Exception in thread "main" org.apache.spark.sql.AnalysisException: partition column favorite_color is not defined in table people_partitioned_bucketed, defined table columns are: age, name;'
Change the column favorite_color to age.

### Why are the changes needed?
Run JavaSparkSQLExample successfully.

### Does this PR introduce _any_ user-facing change?
NO

### How was this patch tested?
test in JavaSparkSQLExample .

2021-03-16 13:02 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2021-03-16 14:47 UTC, maropu commented
ok to test

2021-03-16 14:47 UTC, maropu commented
Looks fine.

2021-03-16 14:48 UTC, maropu approved these changes

2021-03-16 15:02 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/40702/

2021-03-16 15:43 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/136120/

2021-03-16 16:43 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2021-03-16 18:14 UTC, dongjoon-hyun requested changes
Thank you for the fix, @zengruios .

However, this PR introduces inconsistency from Scala/Python examples.

Please see Scala/Python example.
```scala
    # $example on:write_partition_and_bucket$
    df = spark.read.parquet("examples/src/main/resources/users.parquet")
    (df
        .write
        .partitionBy("favorite_color")
        .bucketBy(42, "name")
        .saveAsTable("people_partitioned_bucketed"))
    # $example off:write_partition_and_bucket$
```
```python
    # $example on:write_partition_and_bucket$
    df = spark.read.parquet("examples/src/main/resources/users.parquet")
    (df
        .write
        .partitionBy("favorite_color")
        .bucketBy(42, "name")
        .saveAsTable("people_partitioned_bucketed"))
    # $example off:write_partition_and_bucket$
```

I guess we need to replace `peopleDF` with `usersDF` instead at line 207.

2021-03-16 23:00 UTC, zengruios commented
@dongjoon-hyun, thanks for you suggestion, maybe the table's name should be changed to user_partitioned_bucketed, I will try to fix it like this.

2021-03-16 23:07 UTC, maropu commented
Could you merge the https://github.com/apache/spark/pull/31852 fix into this PR? These issues are similar and minor, so merging them looks okay.

2021-03-16 23:14 UTC, zengruios commented
@maropu, OK，I will merge them.

2021-03-16 23:16 UTC, maropu commented
Thank you, @zengruios

2021-03-17 00:27 UTC, zengruios commented
@maropu, @dongjoon-hyun, I have update it, can you review it again, thanks!

2021-03-17 01:01 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/136130/

2021-03-17 01:44 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/40712/

2021-03-18 04:49 UTC, HyukjinKwon approved these changes

2021-03-18 14:06 UTC, yaooqinn approved these changes

2021-03-18 14:08 UTC, HyukjinKwon commented
@yaooqinn maybe can you try merging this as a brand new committer :-)?

2021-03-18 14:12 UTC, yaooqinn commented
thanks, @HyukjinKwon. I will merge this to master only, is it Okay?

2021-03-18 14:15 UTC, HyukjinKwon commented
Improvements are not backported in general but looks like this is a bug fix in the example (reading from JIRA) which is usually backported. The JIRA states the affected versions are 3.0.1 and 3.1.1 so I would merge this to branch-3.1 and branch-3.0.

2021-03-18 14:17 UTC, yaooqinn commented
Yea, LGTM~

2021-03-18 14:54 UTC, closed without merging

2021-03-18 14:56 UTC, yaooqinn commented
My network is not in good condition at the moment.  It took years to fetch and push this PR to master :(.. Now, it's fighting for branch-3.1

2021-03-18 15:17 UTC, yaooqinn commented
@zengruios Thanks for your first contribution to Apache Spark.

I have added you as a contributor at the JIRA side, and SPARK-34760 has been assigned to you.

Thanks for the review, @dongjoon-hyun @maropu @HyukjinKwon

Merged to master/3.1/3.0.

2021-03-18 15:44 UTC, HyukjinKwon commented
👏

2021-03-18 16:14 UTC, dongjoon-hyun commented
Congratulation, @zengruios and @yaooqinn .

2021-03-18 23:41 UTC, maropu commented
late lgtm 👏