[WIP] add column names to column number mismatch runtimeerror
apache/spark pull request #31999
Opened 2021-03-29 21:58 UTC by jlherzberg

### What changes were proposed in this pull request?
Adds names of columns returned by function to error message. 
Change suggested here http://apache-spark-user-list.1001560.n3.nabble.com/Error-Message-Suggestion-td39884.html

### Why are the changes needed?
In the error message, the number of returned columns and number of expected columns are returned, but with the names of the actual columns returned, the error would be much more helpful and easier to debug.

### Does this PR introduce _any_ user-facing change?
Users would see the changed error when developing. 

### How was this patch tested?
No new tests. Passes related tests on my machine.

2021-03-29 22:00 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2021-03-31 03:35 UTC, HyukjinKwon reviewed
Can you file a JIRA, fix the PR title, etc. according to http://spark.apache.org/contributing.html? Also it would be great if we have a test to verify it with showing before/after error messages in the PR description.

2021-04-06 14:36 UTC, Yikun requested changes
A tiny format problem need to fix.

2021-04-06 14:36 UTC, Yikun commented on python/pyspark/worker.py
> +                "Expected: {} Actual: {}"
```suggestion
                "Expected: {} Actual: {} "
```

2021-07-17 00:07 UTC, closed without merging