[SPARK-35116] The generated data fits the precision of DayTimeIntervalType in spark
apache/spark pull request #32212
Opened 2021-04-17 14:18 UTC by beliefer

### What changes were proposed in this pull request?
The precision of `java.time.Duration` is nanosecond, but when it is used as `DayTimeIntervalType` in Spark, it is microsecond.
At present, the `DayTimeIntervalType` data generated in the implementation of `RandomDataGenerator` is accurate to nanosecond, which will cause the `DayTimeIntervalType` to be converted to long, and then back to `DayTimeIntervalType` to lose the accuracy, which will cause the test to fail. For example: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/137390/testReport/org.apache.spark.sql.hive.execution/HashAggregationQueryWithControlledFallbackSuite/udaf_with_all_data_types/

### Why are the changes needed?
Improve `RandomDataGenerator` so that the generated data fits the precision of DayTimeIntervalType in spark.

### Does this PR introduce _any_ user-facing change?
'No'. Just change the test class.

### How was this patch tested?
Jenkins test.

2021-04-17 14:51 UTC, SparkQA commented
**[Test build #137506 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/137506/testReport)** for PR 32212 at commit [`0b7de13`](https://github.com/apache/spark/commit/0b7de13d2b6477df8682189fb66dc8f1fa3955be).

2021-04-17 15:39 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/42080/

2021-04-17 15:44 UTC, SparkQA commented
Kubernetes integration test status failure
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/42080/

2021-04-17 15:49 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/42080/

2021-04-17 16:07 UTC, MaxGekk commented on sql/catalyst/src/test/scala/org/apache/spark/sql/RandomDataGenerator.scala
>        })
I think we can simplify the code:
```scala
      case DayTimeIntervalType => Some(() => Duration.of(rand.nextLong(), ChronoUnit.MICROS))
```

2021-04-17 16:15 UTC, MaxGekk commented on sql/catalyst/src/test/scala/org/apache/spark/sql/RandomDataGenerator.scala
>        case YearMonthIntervalType => Some(() => {
The same here:
```scala
      case YearMonthIntervalType => Some(() => Period.ofMonths(rand.nextInt()))
```

2021-04-17 16:17 UTC, MaxGekk requested changes
The changes look good but I would simplify the code.

2021-04-17 19:23 UTC, SparkQA commented
**[Test build #137506 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/137506/testReport)** for PR 32212 at commit [`0b7de13`](https://github.com/apache/spark/commit/0b7de13d2b6477df8682189fb66dc8f1fa3955be).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2021-04-17 19:49 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/137506/

2021-04-18 01:29 UTC, beliefer commented on sql/catalyst/src/test/scala/org/apache/spark/sql/RandomDataGenerator.scala
>        })
OK

2021-04-18 01:52 UTC, SparkQA commented
**[Test build #137516 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/137516/testReport)** for PR 32212 at commit [`e28601f`](https://github.com/apache/spark/commit/e28601f4ac03af101619f471026f16d25eace4da).

2021-04-18 02:35 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/42090/

2021-04-18 02:39 UTC, SparkQA commented
Kubernetes integration test status failure
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/42090/

2021-04-18 02:51 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/42090/

2021-04-18 05:54 UTC, MaxGekk approved these changes

2021-04-18 06:03 UTC, MaxGekk commented
+1, LGTM. GA passed. Merging to master.
Thank you, @beliefer .

2021-04-18 06:04 UTC, closed without merging

2021-04-18 06:17 UTC, SparkQA commented
**[Test build #137516 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/137516/testReport)** for PR 32212 at commit [`e28601f`](https://github.com/apache/spark/commit/e28601f4ac03af101619f471026f16d25eace4da).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2021-04-18 06:41 UTC, beliefer commented
@MaxGekk Thanks for your review.

2021-04-18 06:51 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/137516/