[WIP][GRAPHX] Allow to turn off the normalization applied in the end of static PageRank utilities
apache/spark pull request #32485
Opened 2021-05-09 14:12 UTC by bonnal-enzo

### What changes were proposed in this pull request?

Overload methods `PageRank.runWithOptions` and  `PageRank.runWithOptionsWithPreviousPageRank` (not to break any user-facing signature) with a `normalized` parameter that describes "whether or not to normalize the rank sum".

### Why are the changes needed?

https://issues.apache.org/jira/browse/SPARK-

When dealing with a non negligible proportion of sinks in a graph, algorithm based on incremental update of ranks can get a **precision gain for free** if they are allowed to manipulate non normalized ranks.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

By adding a unit test that verifies that (even when dealing with a graph containing a sink) we end up with the same result for both these scenarios:
a)
  - Run **6 iterations** of pagerank in a row using `PageRank.runWithOptions` with **normalization enabled**

b)
  - Run **2 iterations** using `PageRank.runWithOptions` with **normalization disabled**
  - Resume from the `preRankGraph1` and run **2 more iterations** using `PageRank.runWithOptionsWithPreviousPageRank` with **normalization disabled**
  - Finally resume from the `preRankGraph2` and run **2 more iterations** using `PageRank.runWithOptionsWithPreviousPageRank` with **normalization enabled**

2021-05-09 14:12 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2021-05-10 04:04 UTC, Ayushsunny approved these changes

2021-05-10 12:31 UTC, HyukjinKwon commented
ok to test

2021-05-10 13:15 UTC, SparkQA commented
**[Test build #138334 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/138334/testReport)** for PR 32485 at commit [`60482b3`](https://github.com/apache/spark/commit/60482b37c33a812a7e2d22db61819a63c055298b).

2021-05-10 13:16 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/42856/

2021-05-10 13:20 UTC, SparkQA commented
Kubernetes integration test status failure
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/42856/

2021-05-10 13:20 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/42856/

2021-05-10 13:33 UTC, SparkQA commented
**[Test build #138334 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/138334/testReport)** for PR 32485 at commit [`60482b3`](https://github.com/apache/spark/commit/60482b37c33a812a7e2d22db61819a63c055298b).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2021-05-11 01:40 UTC, srowen requested changes
Looks OK, only one tiny comment about 'since'

2021-05-11 01:40 UTC, srowen commented on graphx/src/test/scala/org/apache/spark/graphx/lib/PageRankSuite.scala
> +      assert(ranksA.zip(ranksB).forall{ case(rankA, rankB) => rankA == rankB })
I thought our style-checks might want `.forall { case (..., ...) ...` but looks like it passed so maybe not. Not worth changing... looks OK to me.

2021-05-11 01:40 UTC, srowen commented on graphx/src/main/scala/org/apache/spark/graphx/lib/PageRank.scala
> +   *
We might add `@since 3.2.0` on the new methods

2021-05-11 11:16 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/42898/

2021-05-11 11:17 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/42898/

2021-05-11 11:17 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/138375/

2021-05-11 14:29 UTC, srowen approved these changes

2021-05-12 13:56 UTC, closed without merging

2021-05-12 13:57 UTC, srowen commented
Merged to master