[Spark-35494] Timestamp cast performance issue
apache/spark pull request #32640
Opened 2021-05-23 15:47 UTC by rluta

### What changes were proposed in this pull request?

This patch fixes the performance issue when casting datetime with timezone strings to timestamp in Spark SQL
by replacing the StringOps.format operation in the DateTimeUtils.stringToTimestamp by a simple StringBuilder

### Why are the changes needed?

This patch improves some of our data processing jobs run time by nearly 30%, especially when source data is exported from an Oracle DBMS.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

A TmestampConversionBenchmark has been introduced to validate that all source timestamp formats have similar performance profiles.
We are also currently running this patch in production.

2021-05-23 16:19 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2021-05-24 00:17 UTC, HyukjinKwon commented
@rluta, Spark 2.4 is EOL. Can you see if the issue persists in higher Spark versions, and submit the PR to the correct branches?

2021-05-24 10:17 UTC, rluta commented
I'm aware 2.4 is EOL but since 2.4.8 has just been released, I figured this patch may be included in a possible 2.4.9 since it had a pretty dramatic effect on some of our Oracle workloads.

3.x branches have a completely different (and better) implementation with only 1 usual path with lower performance:

```
OpenJDK 64-Bit Server VM 1.8.0_292-b10 on Mac OS X 10.16
Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz

Timestamp Conversion:                     Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
no tz                                               917            940          20          4,6         218,6       1,0X
with UTC tz                                        2172           2232          84          1,9         517,8       0,4X
with hours tz                                       937            946           9          4,5         223,5       1,0X
```

I can also provide a different patch on master to fix the UTC performance and provide the benchmark class if you're interested but maybe it should be attached to another issue in Jira.

2021-05-25 13:37 UTC, srowen commented
We could merge it, just may not get released

2021-05-25 13:37 UTC, srowen commented
Jenkins test this please

2021-05-25 13:38 UTC, SparkQA commented
**[Test build #138929 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/138929/testReport)** for PR 32640 at commit [`5deff2b`](https://github.com/apache/spark/commit/5deff2b0920b40ce8b90bc6b4056470db0a0c491).

2021-05-25 14:03 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/43450/

2021-05-25 14:18 UTC, SparkQA commented
Kubernetes integration test status success
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/43450/

2021-05-25 14:25 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/43450/

2021-05-25 15:21 UTC, srowen commented
Jenkins retest this please

2021-05-25 15:26 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/138929/

2021-05-25 15:28 UTC, SparkQA commented
**[Test build #138932 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/138932/testReport)** for PR 32640 at commit [`5deff2b`](https://github.com/apache/spark/commit/5deff2b0920b40ce8b90bc6b4056470db0a0c491).

2021-05-25 15:54 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/43453/

2021-05-25 16:11 UTC, SparkQA commented
Kubernetes integration test status success
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/43453/

2021-05-25 16:26 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/43453/

2021-05-25 16:57 UTC, SparkQA commented
**[Test build #138932 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/138932/testReport)** for PR 32640 at commit [`5deff2b`](https://github.com/apache/spark/commit/5deff2b0920b40ce8b90bc6b4056470db0a0c491).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2021-05-25 17:26 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/138932/

2021-05-25 18:37 UTC, dongjoon-hyun requested changes
Hi, @rluta .

Sorry, but I'm -1 for this PR because this is an improvement on the behavior of Apache Spark 2.2.0+. In general, Apache Spark community don't backport an improvement or a new feature. In addition, Apache Spark 2.4 is already EOL as mentioned in the above.

If you don't mind, let's not touch `branch-2.4` to avoid any further confusions in the community.

2021-05-25 19:37 UTC, srowen commented
It's not really a backport, but is indeed not strictly a fix in a maintenance branch. Probably a moot point either way

2021-05-26 07:34 UTC, rluta commented
I'm fine either way. I created this issue/PR mainly so that other current users and fork maintainers of the 2.4 branch are aware of the performance issue.

I will create another ticket to fix the milder performance issue in the master branch and contribute the benchmark class.

2021-05-27 02:52 UTC, dongjoon-hyun commented
> I'm fine either way. I created this issue/PR mainly so that other current users and fork maintainers of the 2.4 branch are aware of the performance issue.
> 
> I will create another ticket to fix the milder performance issue in the master branch and contribute the benchmark class.

+1 for that. Thank you, @rluta !

2021-05-27 02:53 UTC, dongjoon-hyun commented
Let me close this for now.

2021-05-27 02:53 UTC, closed without merging