[SPARK-35056][SQL] Group exception messages in execution/streaming
apache/spark pull request #32880
Opened 2021-06-11 07:29 UTC by beliefer

### What changes were proposed in this pull request?
This PR group exception messages in `sql/core/src/main/scala/org/apache/spark/sql/execution/streaming`.

### Why are the changes needed?
It will largely help with standardization of error messages and its maintenance.

### Does this PR introduce _any_ user-facing change?
No. Error messages remain unchanged.

### How was this patch tested?
No new tests - pass all original tests to make sure it doesn't break any existing behavior.

2021-06-11 08:24 UTC, SparkQA commented
**[Test build #139694 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/139694/testReport)** for PR 32880 at commit [`b15ef1b`](https://github.com/apache/spark/commit/b15ef1b159968c210b6dc4331c3744dcea26227c).

2021-06-11 16:45 UTC, SparkQA commented
**[Test build #139694 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/139694/testReport)** for PR 32880 at commit [`b15ef1b`](https://github.com/apache/spark/commit/b15ef1b159968c210b6dc4331c3744dcea26227c).
 * This patch **fails from timeout after a configured wait of `500m`**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2021-06-11 22:36 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/44228/

2021-06-11 23:15 UTC, SparkQA commented
Kubernetes integration test status success
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/44228/

2021-06-11 23:45 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/44228/

2021-06-12 03:08 UTC, beliefer commented
retest this please

2021-06-12 03:46 UTC, SparkQA commented
**[Test build #139727 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/139727/testReport)** for PR 32880 at commit [`b15ef1b`](https://github.com/apache/spark/commit/b15ef1b159968c210b6dc4331c3744dcea26227c).

2021-06-12 04:46 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/44252/

2021-06-12 05:18 UTC, SparkQA commented
Kubernetes integration test status success
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/44252/

2021-06-12 05:46 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/44252/

2021-06-12 08:04 UTC, SparkQA commented
**[Test build #139727 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/139727/testReport)** for PR 32880 at commit [`b15ef1b`](https://github.com/apache/spark/commit/b15ef1b159968c210b6dc4331c3744dcea26227c).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2021-06-12 08:46 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/139727/

2021-06-14 18:29 UTC, MaxGekk requested changes

2021-06-14 18:29 UTC, MaxGekk commented on sql/catalyst/src/main/scala/org/apache/spark/sql/errors/QueryExecutionErrors.scala
> +             |Earlier version of Spark incorrectly escaped paths when writing out the
Please, fix indentation here and below.

2021-06-15 02:20 UTC, beliefer commented on sql/catalyst/src/main/scala/org/apache/spark/sql/errors/QueryExecutionErrors.scala
> +             |Earlier version of Spark incorrectly escaped paths when writing out the
Thanks you for reminder.

2021-06-15 02:21 UTC, beliefer commented
ping @allisonwang-db

2021-06-15 02:59 UTC, SparkQA commented
**[Test build #139790 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/139790/testReport)** for PR 32880 at commit [`7c8d275`](https://github.com/apache/spark/commit/7c8d275364b1ccf83492e55f0a63f357ec7fb8ad).

2021-06-15 03:44 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/44316/

2021-06-15 04:19 UTC, SparkQA commented
Kubernetes integration test status success
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/44316/

2021-06-15 04:58 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/44316/

2021-06-15 07:30 UTC, SparkQA commented
**[Test build #139790 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/139790/testReport)** for PR 32880 at commit [`7c8d275`](https://github.com/apache/spark/commit/7c8d275364b1ccf83492e55f0a63f357ec7fb8ad).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds no public classes.

2021-06-15 07:58 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/139790/

2021-06-15 09:17 UTC, MaxGekk approved these changes

2021-06-15 09:19 UTC, MaxGekk commented
+1, LGTM. Merging to master.
Thank you, @beliefer .

2021-06-15 09:20 UTC, closed without merging

2021-06-15 09:22 UTC, beliefer commented
@MaxGekk Thank you!