[SHUFFLE] [WIP] Prototype: store shuffle file on external storage like S3
apache/spark pull request #34864
Opened 2021-12-10 21:52 UTC by hiboyang

### What changes were proposed in this pull request?
This PR provides support to store shuffle files on external shuffle storage like S3. It helps Dynamic
Allocation on Kubernetes. Spark driver could release idle executors without worrying about losing
shuffle data because the shuffle data is store on external shuffle storage which are different
from executors.

This could be viewed as a followup work for https://issues.apache.org/jira/browse/SPARK-25299.

### Why are the changes needed?

To better support Dynamic Allocation on Kubernetes, we need to decouple shuffle data from Spark
executor. This PR implements another Shuffle Manager and support writing shuffle data on S3.

### Does this PR introduce _any_ user-facing change?

Yes, this PR adds two Spark config like following to plug in another StarShuffleManager and store
shuffle data on provided S3 location.
```
spark.shuffle.manager=org.apache.spark.shuffle.StarShuffleManager
spark.shuffle.star.rootDir=s3://my_bucket_name/my_shuffle_folder
```

### How was this patch tested?

Added a unit test for StartShuffleManager. A lot of classes are copied from Spark, thus not add tests
for those classes. We will work with the community to get feedback first, then work on removing code
copy/duplication.

2021-12-10 22:06 UTC, SparkQA commented
**[Test build #146081 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/146081/testReport)** for PR 34864 at commit [`4b67c8a`](https://github.com/apache/spark/commit/4b67c8a193b3389ca400e276f0dcea2ba4749d26).

2021-12-10 22:45 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/50556/

2021-12-10 23:28 UTC, SparkQA commented
Kubernetes integration test status failure
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/50556/

2021-12-11 00:02 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/50556/

2021-12-11 00:28 UTC, c21 commented
@hiboyang, thanks for the work here! Could you create a design doc for this? That might help get more people attention and easier for them to understand.

2021-12-11 00:31 UTC, hiboyang commented
> @hiboyang, thanks for the work here! Could you create a design doc for this? That might help get more people attention and easier for them to understand.

Yes, good suggestion. Will create some design doc.

2021-12-11 00:43 UTC, SparkQA commented
**[Test build #146081 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/146081/testReport)** for PR 34864 at commit [`4b67c8a`](https://github.com/apache/spark/commit/4b67c8a193b3389ca400e276f0dcea2ba4749d26).
 * This patch passes all tests.
 * This patch merges cleanly.
 * This patch adds the following public classes _(experimental)_:
  * `public class ByteBufUtils `
  * `public class StarBlockStoreClient extends BlockStoreClient `
  * `public class StarBypassMergeSortShuffleWriter<K, V> extends ShuffleWriter<K, V> `
  * `public class StarLocalFileShuffleFileManager implements StarShuffleFileManager `
  * `public class StarMapResultFileInfo `
  * `public class StarS3ShuffleFileManager implements StarShuffleFileManager `
  * `    public static class S3BucketAndKey `
  * `public class StarUtils `
  * `public class StartFileSegmentWriter `
  * `class StarShuffleManager(conf: SparkConf) extends ShuffleManager with Logging `
  * `final class StarShuffleBlockFetcherIterator(`
  * `  case class FetchRequest(`
  * `  case class DeferFetchRequestResult(fetchRequest: FetchRequest) extends FetchResult`

2021-12-11 00:57 UTC, linzebing commented
Quickly glanced through the code, seems for writing shuffle data we are writing locally first and then upload to S3, similarly for reading shuffle data we are downloading data to a local temp file first and then read.

We should be able to write/read direct to/from S3, right?

2021-12-11 01:02 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/146081/

2021-12-12 03:48 UTC, dongjoon-hyun requested changes
Hi, All. Thank you!

BTW, for the record, Apache Spark 3.1+ already stores its shuffle files into the external storage like S3 and reads back from it.
  - [SPARK-33545][CORE] Support Fallback Storage during Worker decommission
  - [SPARK-34142][CORE] Support Fallback Storage Cleanup during stopping SparkContext
  - [SPARK-37509][CORE] Improve Fallback Storage upload speed by avoiding S3 rate limiter

It would be great not to ignore the existing Spark feature and avoid over-claiming.

Dynamic allocation is the same. Apache Spark has been supporting Dynamic Allocation in K8s too.

2021-12-13 17:51 UTC, hiboyang commented
> Quickly glanced through the code, seems for writing shuffle data we are writing locally first and then upload to S3, similarly for reading shuffle data we are downloading data to a local temp file first and then read.
> 
> We should be able to write/read direct to/from S3, right?

Thanks for looking! Yes, we should be able to write/read direct on S3. This PR is a prototype. Still need to improve the code and performance of writing/reading shuffle data on S3.

2021-12-13 17:57 UTC, hiboyang commented
> Hi, All. Thank you!
> 
> BTW, for the record, Apache Spark 3.1+ already stores its shuffle files into the external storage like S3 and reads back from it.
> 
> * [[SPARK-33545](https://issues.apache.org/jira/browse/SPARK-33545)][CORE] Support Fallback Storage during Worker decommission (Apache Spark 3.1.0)
> * [[SPARK-34142](https://issues.apache.org/jira/browse/SPARK-34142)][CORE] Support Fallback Storage Cleanup during stopping SparkContext (Apache Spark 3.2.0)
> * [[SPARK-37509](https://issues.apache.org/jira/browse/SPARK-37509)][CORE] Improve Fallback Storage upload speed by avoiding S3 rate limiter (Apache Spark 3.3.0)
> 
> It would be great not to ignore the existing Spark feature and avoid over-claiming.
> 
> Dynamic allocation is the same. Apache Spark has been supporting Dynamic Allocation in K8s too.

Right, Spark has shuffle tracking to support Dynamic Allocation on Kubernetes, but it will not work well when there is shuffle data distributed on many executors (those executors cannot be released).

The work here (storing shuffle data on S3) does not conflict with worker decommission feature. The eventual goal is to store shuffle data on S3 or other external storage directly. Before getting there, people could still use the worker decommission feature.

2021-12-13 18:13 UTC, dongjoon-hyun commented
You are completely wrong because you already know the worker decommission feature.
>  but it will not work well when there is shuffle data distributed on many executors (those executors cannot be released).

You should mention this in the PR description explicitly instead of misleading the users.
> The work here (storing shuffle data on S3) does not conflict with worker decommission feature. The eventual goal is to store shuffle data on S3 or other external storage directly.

2021-12-13 22:17 UTC, SparkQA commented
**[Test build #146147 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/146147/testReport)** for PR 34864 at commit [`8222f38`](https://github.com/apache/spark/commit/8222f383e25af2c66a14c96cb3f8153d6828cbad).

2021-12-13 22:58 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/50620/

2021-12-13 23:43 UTC, SparkQA commented
Kubernetes integration test status failure
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/50620/

2021-12-14 00:14 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/50620/

2021-12-14 00:20 UTC, SparkQA commented
**[Test build #146147 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/146147/testReport)** for PR 34864 at commit [`8222f38`](https://github.com/apache/spark/commit/8222f383e25af2c66a14c96cb3f8153d6828cbad).
 * This patch **fails Spark unit tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2021-12-14 00:21 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/146147/

2021-12-17 00:28 UTC, SparkQA commented
**[Test build #146303 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/146303/testReport)** for PR 34864 at commit [`761fe2a`](https://github.com/apache/spark/commit/761fe2a850a4e3ee73caf4cf37378914c1acc8b8).

2021-12-17 01:25 UTC, SparkQA commented
Kubernetes integration test starting
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/50775/

2021-12-17 02:22 UTC, SparkQA commented
Kubernetes integration test status failure
URL: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/50775/

2021-12-17 02:26 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder-K8s/50775/

2021-12-17 08:48 UTC, SparkQA commented
**[Test build #146303 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/146303/testReport)** for PR 34864 at commit [`761fe2a`](https://github.com/apache/spark/commit/761fe2a850a4e3ee73caf4cf37378914c1acc8b8).
 * This patch **fails from timeout after a configured wait of `500m`**.
 * This patch merges cleanly.
 * This patch adds no public classes.

2021-12-17 09:27 UTC, AmplabJenkins commented
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/146303/

2021-12-20 19:39 UTC, hiboyang commented
Add a [design doc](https://docs.google.com/document/d/10rhvjXUlbQfWg-zh02_aqRqDT_ZnwYmICPAR--aRv64) for this prototype.

2022-01-05 11:53 UTC, steveloughran reviewed
some quick comments on the pr

2022-01-05 15:11 UTC, steveloughran commented
Obviously I am biased, but I believe that rather than trying to use the AWS APIs yourself, you should just use the hadoop file system APIs and interact with S3 through the s3a connector.

For a high-performance upload of a local file, use `FileSystem.copyFromLocalFile` in s3a on hadoop 3.3.2 this uses the same transfer manager class as this PR does but adds: exception handling/mapping, encryption settings, auditing. And the s3a integration tests verify all this works... By the time you get to use it here you can assume the S3 upload works, and it becomes a matter of linking it up to spark.


As `copyFromLocalFile` is implemented for all filesystems, it means the component will also work with other stores including google cloud and azure abfs, even if they do not override the base method for a high-performance implementation -yet.

This also means that you could write tests for the feature using file:// as the destination store and include these in the spark module; if you design such tests to be overrideable to work with other file systems, they could be picked up and reused as the actual integration test suites in an external module.

And, because someone else owns the problem of the s3 connector binding, you get to avoid fielding support calls related to configuring of AWS endpoint, region, support for third-party s3 stores, qualifying AWS SDK updates, etc.

Accordingly, I would propose 

* ripping out `StarS3ShuffleFileManager` and using FileSystem APIs
* write tests which can be pointed at the local FS, but then targeted at real object stores in a downstream test module, as https://github.com/hortonworks-spark/cloud-integration does for committer testing.

Getting integration tests set up is inevitably going to be somewhat complicated. I can provide a bit of consultation there.

2022-01-05 23:48 UTC, hiboyang commented on external-shuffle-storage/pom.xml
> +            <groupId>com.amazonaws</groupId>
Thanks for the suggestion! Yes, I was thinking to use that hadoop library as well, then did not do it due to wanting to start small with this prototype. It sounds a good idea to switch to hadoop library.

2022-01-05 23:51 UTC, hiboyang commented on external-shuffle-storage/src/main/java/org/apache/spark/starshuffle/StarBlockStoreClient.java
> +                    throw new RuntimeException(String.format(
Yes, good catch! Will add inner excepion!

2022-01-05 23:53 UTC, hiboyang commented on external-shuffle-storage/src/main/java/org/apache/spark/starshuffle/StarBypassMergeSortShuffleWriter.java
> +import java.io.*;
Good point, let me remove .* here.

2022-01-05 23:54 UTC, hiboyang commented on external-shuffle-storage/src/main/java/org/apache/spark/starshuffle/StarS3ShuffleFileManager.java
> +    private static Object transferManagerLock = new Object();
yes!

2022-01-05 23:55 UTC, hiboyang commented on external-shuffle-storage/src/main/java/org/apache/spark/starshuffle/StarS3ShuffleFileManager.java
> +            transferManager.shutdownNow();
This was a code mistake. I should not shutdown shuffle manager here. Will remove this.

2022-01-05 23:57 UTC, hiboyang commented
> Obviously I am biased, but I believe that rather than trying to use the AWS APIs yourself, you should just use the hadoop file system APIs and interact with S3 through the s3a connector.
> 
> For a high-performance upload of a local file, use `FileSystem.copyFromLocalFile` in s3a on hadoop 3.3.2 this uses the same transfer manager class as this PR does but adds: exception handling/mapping, encryption settings, auditing. And the s3a integration tests verify all this works... By the time you get to use it here you can assume the S3 upload works, and it becomes a matter of linking it up to spark.
> 
> As `copyFromLocalFile` is implemented for all filesystems, it means the component will also work with other stores including google cloud and azure abfs, even if they do not override the base method for a high-performance implementation -yet.
> 
> This also means that you could write tests for the feature using file:// as the destination store and include these in the spark module; if you design such tests to be overrideable to work with other file systems, they could be picked up and reused as the actual integration test suites in an external module.
> 
> And, because someone else owns the problem of the s3 connector binding, you get to avoid fielding support calls related to configuring of AWS endpoint, region, support for third-party s3 stores, qualifying AWS SDK updates, etc.
> 
> Accordingly, I would propose
> 
> * ripping out `StarS3ShuffleFileManager` and using FileSystem APIs
> * write tests which can be pointed at the local FS, but then targeted at real object stores in a downstream test module, as https://github.com/hortonworks-spark/cloud-integration does for committer testing.
> 
> Getting integration tests set up is inevitably going to be somewhat complicated. I can provide a bit of consultation there.

Yes, these are great suggestions! Thanks again! I will find time to make change for this, and may also reach out to your for consultation when adding integration test :)

2022-04-17 00:19 UTC, closed without merging

2022-05-05 14:02 UTC, pspoerri commented
@hiboyang I looked at your work earlier this year and I wanted to let you know that I used it as a basis for a shuffle plugin. Ultimately I decided to rewrite the plugin from scratch (except the tests) and orient myself on the design of the Spark shuffle manager.

The code is available here: https://github.com/ibm/spark-s3-shuffle/ . It acts as an external Spark plugin and allows to be loaded into Spark binary releases as a plugin.

I'm open to contributing this work back to Apache Spark if there is any interest.

2022-05-05 21:48 UTC, dongjoon-hyun commented
Apache Spark community is open for any contribution, @pspoerri . You can make your own PR.
BTW, do you have any sharable result in terms of the stability and performance, @pspoerri ?

2022-05-06 04:59 UTC, hiboyang commented
Hi @pspoerri great you are working on this and thanks for letting us know! I stopped working on my previous PR due to changing of work priority, but still would like to see people continue working in this area.

There is big value if storing Spark shuffle data on S3. It will save cost and also make Spark more resilient to disk error.

During my previous experiment, shuffle data on S3 will have very worse performance. There are a lot of optimization needed, e.g. S3 key prefix randomization to avoid S3 throttling and async S3 write. Will be happy to hear your thoughts on this as well.

2024-04-16 20:54 UTC, steveloughran commented
@michaelbilow hadoop s3a is on v2 sdk; the com.amazonaws classes are not on the CP and amazon are slowly stopping support. you cannot for example use the lower latency S3 express stores with it.

Like I say: I think you would be better off using the Hue file system APIs to talk to s3. If there are aspects of s3 storage which aren't available through the API -or just very inefficiently due to the effort to preserve the Posix metaphor, then lets fix the API so that other stores can offer the same features, and other apps can pick up.

For example, here's our ongoing delete API for iceberg and other manifest-based tables
https://github.com/apache/hadoop/pull/6726
It maps to s3 bulk delete calls, but there's scope to add to other stores (we now actually want to add it as a page-size == 1 option for all filesystems as it simplifies iceberg integration).

2024-04-17 07:05 UTC, pspoerri commented
@steveloughran How do I call the Hue APIs from Spark? Can you point me to a package?
I agree with you that using the Hadoop APIs are not ideal performance wise, but they are great from a usability and portability perspective.

Another issue is that Hadoop wants to know the size of every file it wants to read. While this makes sense for formats like parquet where the header is located at the last few bytes of the file. It does not make sense for shuffle where you know the exact block/file you want to read.

2024-09-07 10:43 UTC, xleoken commented
+1, would be great to get this working and part of the Spark ecosystem.