[SPARK-38213][CORE] Adding KafkaSink Metrics feature
apache/spark pull request #35697
Opened 2022-03-01 10:43 UTC by senthh

### What changes were proposed in this pull request?

KafkaSink Metrics feature is added
### Why are the changes needed?

KafkaSink Metrics feature will be useful to collect and store the Spark application's metrics into Kafka topic.
### Does this PR introduce _any_ user-facing change?

Yes
### How was this patch tested?

1. Created  test case
2. also tested manually in local cluster too

2022-03-02 04:13 UTC, senthh commented
@dongjoon-hyun @HyukjinKwon @cloud-fan Could you pls review this MR?

2022-03-02 04:22 UTC, dongjoon-hyun requested changes

2022-03-02 04:22 UTC, dongjoon-hyun commented on dev/deps/spark-deps-hadoop-2-hive-2.3
> +kafka-clients/3.1.0//kafka-clients-3.1.0.jar
This is the evidence of the breaking dependency change.

2022-03-02 04:34 UTC, senthh commented on core/pom.xml
> +    </dependency>
@dongjoon-hyun Thanks for pointing this.  Moving this KafkaSink metrics features into external module will be correct?

2022-03-02 17:29 UTC, closed without merging

2022-03-09 11:50 UTC, senthh commented
Creating new PR so I m closing this PR