[SPARK-38561][K8S][DOCS][FOLLOWUP] Add note for specific scheduler configuration and fix typos
apache/spark pull request #36001
Opened 2022-03-29 09:37 UTC by Yikun

### What changes were proposed in this pull request?
Add note for specific scheduler configuration and fix typos

### Why are the changes needed?
We address some comments on https://github.com/apache/spark/pull/35955

### Does this PR introduce _any_ user-facing change?
No, doc only

### How was this patch tested?
CI passed

2022-03-29 11:38 UTC, martin-g approved these changes

2022-03-30 03:47 UTC, weixiuli approved these changes

2022-04-01 13:51 UTC, srowen requested changes

2022-04-01 13:51 UTC, srowen commented on docs/running-on-kubernetes.md
> +   Users can specify custom scheduler using <code>spark.kubernetes.scheduler.name</code> or
"a" was correct here

2022-04-02 02:07 UTC, Yikun commented
@srowen Thanks for review,  I'm not a native speaker, lack the mastery of words. I'm so sorry about back and forth due to tiny typo.

2022-04-02 02:13 UTC, srowen approved these changes

2022-04-02 16:39 UTC, closed without merging

2022-04-02 16:39 UTC, srowen commented
Merged to master (conflicted with 3.3)