[SPARK-38722][SQL][TESTS] Test the error class: CAST_CAUSES_OVERFLOW
apache/spark pull request #36199
Opened 2022-04-14 12:09 UTC by panbingkun

### What changes were proposed in this pull request?
This pr aims to Add one test for the error class CAST_CAUSES_OVERFLOW to QueryExecutionErrorsSuite, it's a followup of SPARK-37935.

### Why are the changes needed?
Add one test for the error class CAST_CAUSES_OVERFLOW to QueryExecutionErrorsSuite

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

- Manual test：

```
./build/sbt "sql/testOnly *QueryExecutionErrorsSuite*"
```

All tests passed.

2022-04-14 15:04 UTC, MaxGekk requested changes

2022-04-14 15:04 UTC, MaxGekk commented on sql/core/src/test/scala/org/apache/spark/sql/errors/QueryExecutionErrorsSuite.scala
> +      sql("select CAST(CAST('9999-12-31T12:13:14.56789Z' AS TIMESTAMP) AS INT)").collect()
Can you use the timestamp literal instead of cast: `timestamp'9999-12-31T12:13:14.56789Z'`?

2022-04-14 15:04 UTC, MaxGekk commented on sql/core/src/test/scala/org/apache/spark/sql/errors/QueryExecutionErrorsSuite.scala
> +  test("CAST_CAUSES_OVERFLOW") {
add the specific title like:
```suggestion
  test("CAST_CAUSES_OVERFLOW: from timestamp to int") {
```

2022-04-15 01:41 UTC, panbingkun commented on sql/core/src/test/scala/org/apache/spark/sql/errors/QueryExecutionErrorsSuite.scala
> +      sql("set spark.sql.ansi.enabled=true")
ok

2022-04-15 04:24 UTC, panbingkun commented on sql/core/src/test/scala/org/apache/spark/sql/errors/QueryExecutionErrorsSuite.scala
> +  test("CAST_CAUSES_OVERFLOW") {
Done，@MaxGekk！Thanks

2022-04-15 06:29 UTC, MaxGekk approved these changes

2022-04-15 06:30 UTC, MaxGekk commented
+1, LGTM. Checked new test locally. Merging to master.
Thank you, @panbingkun.

2022-04-15 06:31 UTC, closed without merging