[SPARK-38746][SQL][TESTS] Move the tests for `PARSE_EMPTY_STATEMENT` to QueryParsingErrorsSuite
apache/spark pull request #36221
Opened 2022-04-16 12:41 UTC by panbingkun

### What changes were proposed in this pull request?
This pr aims to Move tests for the error class PARSE_EMPTY_STATEMENT from ErrorParserSuite to QueryParsingErrorsSuite., it's a followup of [SPARK-37935](https://issues.apache.org/jira/browse/SPARK-37935).

### Why are the changes needed?
Move tests for the error class PARSE_EMPTY_STATEMENT from ErrorParserSuite to QueryParsingErrorsSuite

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
- Manual test：

```
./build/sbt "sql/testOnly *QueryParsingErrorsSuite*"
```

All tests passed.

2022-04-17 08:31 UTC, MaxGekk requested changes

2022-04-17 08:31 UTC, MaxGekk commented on sql/core/src/test/scala/org/apache/spark/sql/errors/QueryParsingErrorsSuite.scala
> +  test("PARSE_EMPTY_STATEMENT: ") {
nit:
```suggestion
  test("PARSE_EMPTY_STATEMENT: empty input") {
```

2022-04-17 08:31 UTC, MaxGekk commented on sql/core/src/test/scala/org/apache/spark/sql/errors/QueryParsingErrorsSuite.scala
> +          """
Can't you from a single string?

2022-04-17 08:31 UTC, MaxGekk commented on sql/core/src/test/scala/org/apache/spark/sql/errors/QueryParsingErrorsSuite.scala
> +          """
The same as above - form one string, please.

2022-04-17 08:53 UTC, panbingkun commented on sql/core/src/test/scala/org/apache/spark/sql/errors/QueryParsingErrorsSuite.scala
> +  test("PARSE_EMPTY_STATEMENT: ") {
ok

2022-04-17 09:04 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2022-04-17 09:10 UTC, panbingkun commented on sql/core/src/test/scala/org/apache/spark/sql/errors/QueryParsingErrorsSuite.scala
> +          """
ok

2022-04-18 07:43 UTC, MaxGekk approved these changes

2022-04-18 07:47 UTC, MaxGekk commented
Waiting for https://github.com/panbingkun/spark/actions/runs/2182508354

2022-04-18 08:05 UTC, MaxGekk commented
+1, LGTM. Merging to master.
Thank you, @panbingkun.

2022-04-18 08:05 UTC, closed without merging