[SPARK-38740][SQL][TESTS] Test the error class: INVALID_JSON_SCHEMA_MAPTYPE
apache/spark pull request #36298
Opened 2022-04-21 08:19 UTC by panbingkun

## What changes were proposed in this pull request?
This PR aims to add a test for the error class INVALID_JSON_SCHEMA_MAPTYPE to `QueryCompilationErrorsSuite`.

### Why are the changes needed?
The changes improve test coverage, and document expected error messages in tests.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
By running new test:
```
$ build/sbt "sql/testOnly *QueryCompilationErrorsSuite*"
```

2022-04-22 06:00 UTC, MaxGekk requested changes

2022-04-22 06:00 UTC, MaxGekk commented on sql/core/src/test/scala/org/apache/spark/sql/errors/QueryCompilationErrorsSuite.scala
> +          "can only contain StringType as a key type for a MapType.")
Could you use the `checkErrorClass` method added by https://github.com/apache/spark/pull/36287.

2022-04-22 10:49 UTC, MaxGekk commented on sql/core/src/test/scala/org/apache/spark/sql/errors/QueryCompilationErrorsSuite.scala
> +          spark.read.schema(schema).json(path.getCanonicalPath)
I think no need to create a temporary dir. AFAK, `json()` accepts a `Dataset`. Could you pass an empty dataset to `json()`, please.

2022-04-23 06:14 UTC, MaxGekk commented
@panbingkun Could you resolve conflicts, please.

2022-04-23 07:39 UTC, panbingkun commented
> @panbingkun Could you resolve conflicts, please.

Done

2022-04-24 07:33 UTC, MaxGekk approved these changes

2022-04-24 07:34 UTC, MaxGekk commented
+1, LGTM. Merging to master.
Thank you, @panbingkun.

2022-04-24 07:34 UTC, closed without merging