[SPARK-39167][SQL] Throw an exception w/ an error class for multiple rows from a subquery used as an expression
apache/spark pull request #36580
Opened 2022-05-17 13:27 UTC by panbingkun

### What changes were proposed in this pull request?
In the PR, I propose to use the MULTI_VALUE_SUBQUERY_ERROR error classes for multiple rows from a subquery used as an expression.

### Why are the changes needed?
Porting the executing errors for multiple rows from a subquery used as an expression to the new error framework should improve user experience with Spark SQL.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Added new test suite

2022-05-18 08:39 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2022-05-19 16:20 UTC, MaxGekk requested changes

2022-05-19 16:20 UTC, MaxGekk commented on sql/catalyst/src/main/scala/org/apache/spark/sql/errors/QueryExecutionErrors.scala
> +    new SparkIllegalStateException(
Please, use SparkException or SparkRuntimeException. I removed the the exception by https://github.com/apache/spark/pull/36550.

BTW, we shouldn't throw `IllegalStateException` if the exception can be trigger by user code in regular cases.

2022-05-20 06:56 UTC, MaxGekk approved these changes
LGTM, @panbingkun could you re-trigger GAs via an empty commit:
```
$ git commit --allow-empty -m "Trigger build"
```

2022-05-20 09:35 UTC, panbingkun commented
> git commit --allow-empty -m "Trigger build"

Done

2022-05-21 04:50 UTC, MaxGekk approved these changes
+1, LGTM. Merging to master.
Thank you, @panbingkun.

2022-05-21 04:51 UTC, closed without merging