[SPARK-40280][SQL] Add support for parquet push down for annotated int and long
apache/spark pull request #37747
Opened 2022-08-31 19:12 UTC by revans2

### What changes were proposed in this pull request?
This fixes SPARK-40280 by normalizing a parquet int/long that has optional metadata with it to look like the expected version that does not have the extra metadata.

## Why are the changes needed?
This allows predicate push down in parquet to work when reading files that are complaint with the parquet specification, but different from what Spark writes.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
I added unit tests that cover this use case. I also did some manual testing on some queries to verify that less data is actually read after this change.

2022-09-01 14:18 UTC, tgravescs approved these changes
lgtm. This make sense to me based on the wording in the spec.

2022-09-02 22:06 UTC, huaxingao commented on sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFilterSuite.scala
> -
nit: unnecessary change?

2022-09-02 22:06 UTC, huaxingao commented on sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFilterSuite.scala
> +  test("filter pushdown - int SPARK-40280") {
nit: maybe `test("SPARK-40280: filter pushdown - int with annotation")`?

2022-09-02 22:06 UTC, huaxingao commented on sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFilterSuite.scala
> +      Seq(Row(1), Row(4)))
nit: shall we also test `In` ?

2022-09-02 22:12 UTC, huaxingao commented
The changes look good to me.

2022-09-05 04:26 UTC, HyukjinKwon commented
cc @wangyum FYI

2022-09-05 04:32 UTC, HyukjinKwon commented
looks making sense to me too

2022-09-05 04:47 UTC, sadikovi requested changes
Looks good. I left a few comments, would appreciate it if you could address them.

2022-09-05 04:47 UTC, sadikovi commented on sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFilters.scala
> +        case la : IntLogicalTypeAnnotation if la.isSigned &&
nit: `case la: IntLogicalTypeAnnotation`

2022-09-05 04:47 UTC, sadikovi commented on sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFilters.scala
> +        case la : IntLogicalTypeAnnotation if la.isSigned &&
nit: `case la: IntLogicalTypeAnnotation`

2022-09-05 04:47 UTC, sadikovi commented on sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFilters.scala
> +        case la : IntLogicalTypeAnnotation if la.isSigned &&
Also, what does "la" stand for?

2022-09-05 04:47 UTC, sadikovi commented on sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFilters.scala
> +      // signed 64 bits on an INT64 and signed 32 bits on an INT32 are optional, but the rest of
nit: `SPARK-40280: Signed 64 ...`.

2022-09-05 04:47 UTC, sadikovi commented on sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFilters.scala
> +      // the code here assumes they are not set, so normalize them to not being set. SPARK-40280
nit: Remove `SPARK-40280` at the end.

2022-09-05 04:47 UTC, sadikovi commented on sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFilters.scala
> +            la.getBitWidth == 64 && p.getPrimitiveTypeName == PrimitiveTypeName.INT64 =>
I would suggest rewriting it match statement like this, IMHO cleaner: 
```scala
(p.getPrimitiveTypeName, p.getLogicalTypeAnnotation) match {
  case (INT32, intType: IntLogicalTypeAnnotation)
    if intType.getBitWidth() == 32 && intType.isSigned() => null
  case (INT64, intType: IntLogicalTypeAnnotation)
    if intType.getBitWidth() == 64 && intType.isSigned() => null
  case (_, otherType) => otherType
}
```

2022-09-05 04:47 UTC, sadikovi commented on sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFilterSuite.scala
> +  test("filter pushdown - int SPARK-40280") {
+1

2022-09-06 17:43 UTC, revans2 commented
@huaxingao and @sadikovi I think I have addressed all of your review comments. Please take another look.

2022-09-06 19:49 UTC, huaxingao approved these changes

2022-09-06 19:50 UTC, huaxingao commented
LGTM. Thanks a lot for working on this! @revans2

2022-09-07 00:21 UTC, sadikovi approved these changes
Thanks for making the changes!

2022-09-07 00:53 UTC, wangyum approved these changes

2022-09-08 13:54 UTC, closed without merging

2022-09-08 14:00 UTC, tgravescs commented
merged to master, branch-3.3 and branch-3.2.  Thanks @revans2