[SPARK-40291][SQL] Improve the message for column not in group by clause error
apache/spark pull request #37742
Opened 2022-08-31 17:16 UTC by linhongliu-db

### What changes were proposed in this pull request?
Improve the message for columns not in group by clause error

### Why are the changes needed?
Use the new error class framework for columns not in group by clause error

### Does this PR introduce _any_ user-facing change?
Yes, adding error class

### How was this patch tested?
UT

2022-09-01 05:47 UTC, linhongliu-db commented
cc @cloud-fan

2022-09-01 05:47 UTC, linhongliu-db commented
cc @cloud-fan

2022-09-01 10:08 UTC, MaxGekk requested changes

2022-09-01 21:21 UTC, linhongliu-db commented
@MaxGekk Thanks for reviewing! I updated the PR

2022-09-02 18:03 UTC, MaxGekk commented on sql/core/src/test/scala/org/apache/spark/sql/execution/SQLViewSuite.scala
> +                e.contains("\"c1\""))
Could you use `checkError()`, please. See the check above.

2022-09-02 18:03 UTC, MaxGekk commented on core/src/main/resources/error/error-classes.json
> +      "expression <expression> is neither present in the group by, nor is it an aggregate function. Add to group by or wrap in `first()` (or `first_value()`) if you don't care which value you get."
Usually, the error messages starts from an upper case char (see messages around):
```suggestion
      "The expression <expression> is neither present in the group by, nor is it an aggregate function. Add to group by or wrap in `first()` (or `first_value()`) if you don't care which value you get."
```

2022-09-07 05:25 UTC, MaxGekk approved these changes

2022-09-07 19:31 UTC, MaxGekk commented
+1, LGTM. Merging to master.
Thank you, @linhongliu-db.

2022-09-07 19:32 UTC, closed without merging