[SPARK-39546][Kubernetes] Executor pod template should support port definitions
apache/spark pull request #37803
Opened 2022-09-05 10:59 UTC by fanyilun

### What changes were proposed in this pull request?
This pr changes the fabric8 k8s method used in BasicExecutorFeatureStep about setting blockmanager ports. Because It will override port definitions in executor pod template file.

### Why are the changes needed?
We use spark.kubernetes.executor.podTemplateFile to specify executor pod definition. However, we cannot set port definition to pod. For example, this is my executorPodTemplate.yaml 
`
apiversion: v1
kind: Pod
spec:
  containers:
    - name: spark-kubernetes-executor
      ports:
        - containerPort: 8090
          name: jmx-exporter
          protocol: TCP
`
When executors start, the pod definitions only show default blockmanager port.
`
      ports:
        - containerPort: 7079
          name: blockmanager
          protocol: TCP
`
It looks like a bug, because the BasicExecutorFeatureStep uses withPorts to override all port definitions.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Add unit test

2022-09-05 23:16 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2022-09-06 08:21 UTC, fanyilun commented
cc @dongjoon-hyun could u take a look? thanks

2022-09-08 07:37 UTC, dongjoon-hyun commented on resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/k8s/features/BasicExecutorFeatureStepSuite.scala
> +
Shalll we remove this redundant empty line?

2022-09-08 08:05 UTC, dongjoon-hyun commented on resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/k8s/features/BasicExecutorFeatureStepSuite.scala
> +    baseDriverPod.container.setPorts(JavaConverters.seqAsJavaListConverter(Seq(ports)).asJava)
```scala
-    baseDriverPod.container.setPorts(JavaConverters.seqAsJavaListConverter(Seq(ports)).asJava)
+    baseDriverPod.container.setPorts(Seq(ports).asJava)
```

2022-09-08 08:05 UTC, dongjoon-hyun commented on resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/k8s/features/BasicExecutorFeatureStepSuite.scala
> +import scala.collection.JavaConverters
Let's remove this after applying https://github.com/apache/spark/pull/37803/files#r965636530.

2022-09-08 08:12 UTC, dongjoon-hyun requested changes
I finished the first round review, @fanyilun .
- I added a few comments about test code.
- Since Apache Spark 2.4.0, SPARK-22839 added this behavior. I revised the PR title because this PR is categorized as a new improvement on executor pod template feature instead of bugs.

The main code itself looks reasonable to me.

2022-09-08 11:08 UTC, fanyilun commented
Hi @dongjoon-hyun , please take another look

2022-09-08 17:53 UTC, dongjoon-hyun approved these changes
+1, LGTM. Thank you, @fanyilun .
Merged to master for Apache Spark 3.4.0.

2022-09-08 17:54 UTC, closed without merging

2022-09-08 17:56 UTC, dongjoon-hyun commented
Welcome to the Apache Spark community, @fanyilun . I added you to the Apache Spark contributor group and assigned SPARK-39546 to you. Do we need this patch for driver pod template? If then, please feel free to make another JIRA and continue.

2022-09-10 03:09 UTC, fanyilun commented
Thanks, driver pod template already supports ports definition. It works for me.