[SPARK-40642][DOC] doc for String memory size since java>=9
apache/spark pull request #38085
Opened 2022-10-03 20:42 UTC by Arnaud-Nauwynck

The doc is wrong for java >= 9 as described here https://openjdk.org/jeps/254
( in detailed here https://issues.apache.org/jira/browse/SPARK-40642 )

2022-10-03 21:25 UTC, dongjoon-hyun commented
Thank you for making a PR, @Arnaud-Nauwynck .

2022-10-03 21:44 UTC, amaliujia commented
@Arnaud-Nauwynck I am thinking you gonna need to enable GITHUB actions on your side to trigger the tests: https://github.com/apache/spark/pull/38085/checks?check_run_id=8686380379

2022-10-04 13:19 UTC, srowen requested changes
There's no need to get into much detail here. Just say "40-44" bytes, etc. The point is clear either way

2022-10-04 20:43 UTC, dongjoon-hyun commented
+1 for Sean's comment.

2022-10-05 20:31 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2022-12-05 14:51 UTC, closed without merging