[SPARK-41742][SPARK-41745][CONNECT] Cleanup previously failing doctest cases.
apache/spark pull request #39330
Opened 2022-12-31 16:27 UTC by grundprinzip

### What changes were proposed in this pull request?
Cleanup previously disabled test cases.

### Why are the changes needed?
Compatibility

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Reenabling doc tests.

2022-12-31 20:13 UTC, dongjoon-hyun requested changes
Thank you, @grundprinzip . Your main contribution is adding `alias` to `def count` in `group.py`. Could you revise the PR title?

2022-12-31 20:39 UTC, grundprinzip commented
Sure, I'll revise. Though I'd say that the "contribution" is rather checking that the previously disabled tests actually pass.

2022-12-31 23:36 UTC, HyukjinKwon approved these changes

2023-01-01 09:09 UTC, HyukjinKwon commented
Merged to master.

2023-01-01 09:10 UTC, closed without merging