[SPARK-42603][SQL] Set spark.sql.legacy.createHiveTableByDefault  to false.
apache/spark pull request #40196
Opened 2023-02-27 13:00 UTC by huangxiaopingRD

### What changes were proposed in this pull request?
Set `spark.sql.legacy.createHiveTableByDefault ` to false.

### Why are the changes needed?
In the spark [documentation](https://github.com/apache/spark/blob/master/docs/sql-ref-syntax-ddl-create-table-datasource.md?plain=1#L121), it is stated that the default creation table is parquet, but you need to set "spark.sql.legacy.createHiveTableByDefault" to false, otherwise the default is textfile.
### Does this PR introduce _any_ user-facing change?
Yes

### How was this patch tested?
tests were added

2023-02-27 22:52 UTC, dongjoon-hyun requested changes
You are suggesting a breaking change here. The existing behavior is correct and consistent with old Spark versions. I guess we need to revise the test comment instead, @huangxiaopingRD .

2023-02-28 02:24 UTC, huangxiaopingRD commented
> 
Sorry, I don't understand what you say we should do next. I want to make this change just because I think the default format of Spark's data source is parquet, and I think the default fileformat of "`create table`" should be consistent with the default value (parquet) of "spark.sql.sources.default".

2023-02-28 02:25 UTC, huangxiaopingRD commented
> > 
> 
> 




> You are suggesting a breaking change here. The existing behavior is correct and consistent with old Spark versions. I guess we need to revise the test comment instead, @huangxiaopingRD .

Sorry, I don't understand what you say we should do next. I want to make this change just because I think the default format of Spark's data source is parquet, and I think the default fileformat of "`create table`" should be consistent with the default value (parquet) of "spark.sql.sources.default".

2023-03-01 12:24 UTC, huangxiaopingRD commented
> In my test, the hive table format depends on the conf `hive.default.fileformat` when set `spark.sql.legacy.createHiveTableByDefault` is true . And if `spark.sql.legacy.createHiveTableByDefault` is false, it hive table format depends on the conf `spark.sql.sources.default` .
> 
> I think it's reasonable .
> 
> So maybe we should only fix the describtion of the https://github.com/apache/spark/blob/master/docs/sql-ref-syntax-ddl-create-table-datasource.md?plain=1#L121 ?

I agree with you. I will launch another PR to modify the description of the document. Thanks @zzzzming95 

what do you think about this? @dongjoon-hyun

2023-03-06 03:34 UTC, closed without merging