[SPARK_42742]access apiserver by pod env
apache/spark pull request #40361
Opened 2023-03-10 06:56 UTC by thousandhu

### What changes were proposed in this pull request?
When start spark on k8s，driver pod  use spark.kubernetes.driver.master to get apiserver address. This config  us  https://kubernetes.default.svc/ as default and do not care about the apiserver port.

In our case, apiserver port is not 443 will driver will throw connectException. As k8s doc mentioned （https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/#directly-accessing-the-rest-api）, we can get master url by getting KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT_HTTPS environment variables from pod. So we add a new conf spark.kubernetes.driver.master.from.pod.env to allow driver get master url from env in cluster mode on k8s

### Why are the changes needed?
Add a new conf spark.kubernetes.driver.master.from.pod.env  to let the driver pod get apiserver automatically from pod env instead of by  spark.kubernetes.driver.master.

### Does this PR introduce _any_ user-facing change?
Yes. When user set new conf spark.kubernetes.driver.master.from.pod.env as true, the logic of driver get apiserver url will changed. In some case it will help user to get right apiserver url.
By default, the conf spark.kubernetes.driver.master.from.pod.env  is false, and the driver logic changes nothing.

### How was this patch tested?
No. the apiserver is mocked in unit test. we tested this feature in our k8s cluster

2023-03-10 07:21 UTC, thousandhu commented
I've enabled GitHub Actions in your forked repository. How to rerun the build check failed above?

2023-03-11 03:41 UTC, dongjoon-hyun requested changes
Could you add a test case to validate your code? Especially, the test case should show that `spark.kubernetes.driver.master` is not enough.

2023-03-14 06:12 UTC, thousandhu commented
In our product environment, the k8s cluster is managed by other system and the port of apiserver is different between clusters. In this case, the spark.kubernetes.driver.master  on spark client side can't set a port for all clusters.

2023-03-17 03:42 UTC, dongjoon-hyun commented on resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/Config.scala
> +      .version("3.1.2")
This is wrong.

2023-03-17 03:45 UTC, dongjoon-hyun requested changes
There are mutliple issues which I commented already (test case, version, config namespaces). In addition, this is unsafe completely in the production environment. So, I'm -1 for this direction.

2023-03-17 03:45 UTC, dongjoon-hyun commented on resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/Config.scala
> +    ConfigBuilder("spark.kubernetes.driver.master.from.pod.env")
This introduces redundant namespace unintentionally to Apache Spark configs.
```
- spark.kubernetes.driver.master.from.
- spark.kubernetes.driver.master.from.pod.
```

2023-06-27 00:22 UTC, closed without merging