[SPARK-43294][BUILD] Upgrade zstd-jni to 1.5.5-2
apache/spark pull request #40962
Opened 2023-04-26 15:00 UTC by LuciferYang

### What changes were proposed in this pull request?

### Why are the changes needed?

### Does this PR introduce _any_ user-facing change?

### How was this patch tested?

2023-05-04 14:57 UTC, srowen approved these changes
Looks OK, just add context about what the update does

2023-05-04 19:09 UTC, LuciferYang commented
Thanks for your review @srowen. I am on vacation and will continue to complete these tasks after May 8th.

________________________________
发件人: Sean Owen ***@***.***>
发送时间: 2023年5月4日 22:57:27
收件人: apache/spark
抄送: yangjie01; Author
主题: Re: [apache/spark] [SPARK-43294][BUILD] Upgrade zstd-jni to 1.5.5-2 (PR #40962)


@srowen approved this pull request.

Looks OK, just add context about what the update does

―
Reply to this email directly, view it on GitHub<https://mailshield.baidu.com/check?q=4%2fgpZ9TUEilYD9%2fXl%2f%2fdZ08xybHnY39K5GNnRidojzsXOcQrY4G74%2ftGPWda%2f0bG4rBPHY0ERfSeAWNQe0IWpFuPmjDRr01b0B39Jw%3d%3d>, or unsubscribe<https://mailshield.baidu.com/check?q=TboBl7gBc9ssIw%2fYtfvVtyVmwybmo1xowOHIEtt99hxrTkRQwwlxhTAqm6PKe8JFikz38E%2brBzEwW4wnNg2bfgrGkPmhNQuOrjnb8SXet2ZBamJzhIHTAlf6q8NZ5jsCpAi%2f6Nn5zu0%3d>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-05-05 15:36 UTC, srowen commented
The changes are minor:
https://github.com/luben/zstd-jni/compare/v1.5.5-1...v1.5.5-2
I think it's fine.

2023-05-05 23:13 UTC, dongjoon-hyun approved these changes
+1.

Have a nice vacation, @LuciferYang . :)

2023-05-08 02:50 UTC, LuciferYang commented
Thanks @dongjoon-hyun @srowen , I am checking the microbenchmark results and updating this pr later

2023-05-10 13:04 UTC, LuciferYang commented on core/benchmarks/ZStandardBenchmark-results.txt
> +Compression 10000 times at level 1 with buffer pool               257            259           1          0.0       25702.7       1.4X
https://github.com/apache/spark/pull/40721#discussion_r1161989573

It seems that this problem has occurred again. I ran `ZStandardBenchmark` on GA 13 times and did not get the same results as before ... @dongjoon-hyun

2023-05-10 13:10 UTC, LuciferYang commented on core/benchmarks/ZStandardBenchmark-results.txt
> +Compression 10000 times at level 1 with buffer pool               257            259           1          0.0       25702.7       1.4X
also cc @pan3793

2023-05-10 16:50 UTC, dongjoon-hyun commented
Since the one failure seems to be flaky one, we can ignore it.
```
[info] *** 1 TEST FAILED ***
[error] Failed: Total 3638, Failed 1, Errors 0, Passed 3637, Ignored 10, Canceled 2
[error] Failed tests:
[error] 	org.apache.spark.scheduler.HealthTrackerIntegrationSuite
```

2023-05-11 04:42 UTC, dongjoon-hyun requested changes
Ur, @LuciferYang . I tried to merge but this PR seems to have corrupted commits
![Screenshot 2023-05-10 at 9 41 35 PM](https://github.com/apache/spark/assets/9700541/683003ec-1c51-4b90-8283-4a1858615742)

2023-05-11 04:42 UTC, dongjoon-hyun commented
Please make a clean PR.

2023-05-11 08:08 UTC, LuciferYang commented
> Please make a clean PR.

OK, Let me make a new one.

2023-05-11 08:15 UTC, LuciferYang commented
@dongjoon-hyun I open a new one : https://github.com/apache/spark/pull/41135

2023-05-11 08:15 UTC, closed without merging