[WIP] Similarity search fix
apache/spark pull request #41038
Opened 2023-05-03 22:53 UTC by vitaliili-db

### What changes were proposed in this pull request?

### Why are the changes needed?

### Does this PR introduce _any_ user-facing change?

### How was this patch tested?

2023-05-05 15:37 UTC, srowen commented
What is this?

2023-05-05 17:25 UTC, vitaliili-db commented
@srowen fixed description, didn't expect you to be so quick

2023-05-10 09:24 UTC, MaxGekk requested changes

2023-05-10 09:24 UTC, MaxGekk commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/StringUtils.scala
> +    // will also reconstruct multi-part identifier for the cases of nested columnns. E.g. for a
```suggestion
    // will also reconstruct multi-part identifier for the cases of nested columns. E.g. for a
```

2023-05-10 09:24 UTC, MaxGekk commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/StringUtils.scala
> +    // will also reconstruct multi-part identifier for the cases of nested columnns. E.g. for a
```suggestion
    // will also reconstruct multi-part identifier for the cases of nested columns. E.g. for a
```

2023-05-10 09:24 UTC, MaxGekk commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/StringUtils.scala
> +        (parts.take(parts.size - 1).map(quoteIfNeeded).mkString("."), quoteIfNeeded(parts.last))
```suggestion
        val parts = UnresolvedAttribute.parseAttributeName(ident).map(quoteIfNeeded)
        (parts.init.mkString("."), parts.last)
```

2023-05-11 07:38 UTC, MaxGekk approved these changes
Waiting for CI.

2023-05-12 05:38 UTC, MaxGekk commented
+1, LGTM. Merging to master.
Thank you, @vitaliili-db.

2023-05-12 05:38 UTC, closed without merging