[SPARK-39281][SQL] Speed up Timestamp type inference with legacy format  in JSON/CSV data source
apache/spark pull request #41091
Opened 2023-05-08 12:45 UTC by Hisoka-X

### What changes were proposed in this pull request?
Follow up https://github.com/apache/spark/pull/36562 , performance improvement when Timestamp type inference with legacy format.

In the current implementation of CSV/JSON data source, the schema inference with legacy format relies on methods that will throw exceptions if the fields can't convert as some data types .

Throwing and catching exceptions can be slow. We can improve it by creating methods that return optional results instead.

The optimization of DefaultTimestampFormatter has been implemented in https://github.com/apache/spark/pull/36562 , this PR adds the optimization of legacy format. The basic logic is to prevent the formatter from throwing exceptions, and then use catch to determine whether the parsing is successful.

### Why are the changes needed?

Performance improvement when Timestamp type inference with legacy format.

When use JSON datasource, the speed up `67%`. CSV datasource speed also up, but not obvious.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Add new test

2023-05-10 11:15 UTC, MaxGekk requested changes
Do the benchmarks `CSVBenchmark` and `JsonBenchmark` show any improvements? Could you regenerate the results `JsonBenchmark.*.txt` and `CSVBenchmark.*.txt`, please.

2023-05-10 14:48 UTC, Hisoka-X commented
> Do the benchmarks `CSVBenchmark` and `JsonBenchmark` show any improvements? Could you regenerate the results `JsonBenchmark.*.txt` and `CSVBenchmark.*.txt`, please.

I'm doing benchmarks, but I found a problem, like @gengliangwang said in https://github.com/apache/spark/pull/36562#issuecomment-1127600354 .The benchmarks no case for `the string inputs are not valid timestamps`. The speed up only work when `string input are not valid timestamps`. I'm worry about the benchmarks can't prove anything. Can I create a PR for add benchmarks for `type inference when string input are not valid timestamps`

2023-05-14 07:25 UTC, MaxGekk commented
@Hisoka-X Please, resolve the conflicts and rebase on the recent master.

2023-05-14 07:30 UTC, Hisoka-X commented
> @Hisoka-X Please, resolve the conflicts and rebase on the recent master.

Ok, I will add benchmarks for this too. Please wait. Thanks!

2023-05-14 12:35 UTC, Hisoka-X commented on sql/core/benchmarks/JsonBenchmark-results.txt
> -infer error timestamps from Dataset[String] with legacy format                  6836           6876          63          0.1        6836.1       0.0X
@MaxGekk Hi, I updated the benchmark, the speed already up.

2023-05-16 12:57 UTC, MaxGekk approved these changes

2023-05-16 12:58 UTC, MaxGekk commented
+1, LGTM. Merging to master.
Thank you, @Hisoka-X.

2023-05-16 12:59 UTC, closed without merging