[SPARK-43649][SPARK-43650][SPARK-43651][SQL] Assign a name to the error class _LEGACY_ERROR_TEMP_240[1-3]
apache/spark pull request #41252
Opened 2023-05-22 08:08 UTC by beliefer

### What changes were proposed in this pull request?
The pr aims to assign a name to the error class _LEGACY_ERROR_TEMP_240[1-3].

### Why are the changes needed?
Improve the error framework.

### Does this PR introduce _any_ user-facing change?
'No'.

### How was this patch tested?
Exists test cases.

2023-05-22 09:21 UTC, MaxGekk requested changes
Could you add the error class `INVALID_LIMIT_LIKE` with error format like `The limit like clause <expr> is invalid.`, and add sub-classes:
- `DATA_TYPE`: `Expects ..., but got ... `
- `IS_NEGATIVE`
- `IS_NULL`

2023-05-22 10:08 UTC, beliefer commented
> 

Got it.

2023-05-22 13:50 UTC, MaxGekk requested changes

2023-05-22 13:50 UTC, MaxGekk commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/CheckAnalysis.scala
>            "dataType" -> e.dataType.catalogString))
Please, wrap it by `toSQLType()`

2023-05-22 13:50 UTC, MaxGekk commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/CheckAnalysis.scala
>                "v" -> v.toString))
Wrap it by `toSQLValue(v, IntegerType)`

2023-05-22 13:50 UTC, MaxGekk commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/analysis/AnalysisErrorSuite.scala
>    errorTest(
The same, please, use `errorClassTest`.

2023-05-23 03:14 UTC, beliefer commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/CheckAnalysis.scala
>            "dataType" -> e.dataType.catalogString))
Got it.

2023-05-23 03:14 UTC, beliefer commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/CheckAnalysis.scala
>                "v" -> v.toString))
Got it.

2023-05-23 03:14 UTC, beliefer commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/analysis/AnalysisErrorSuite.scala
>    errorTest(
I see.

2023-05-23 09:39 UTC, MaxGekk approved these changes

2023-05-23 09:40 UTC, MaxGekk commented
+1, LGTM. Merging to master.
Thank you, @beliefer.

2023-05-23 09:41 UTC, closed without merging

2023-05-23 10:08 UTC, beliefer commented
@MaxGekk Thank you!