[SPARK-43948][SQL] Assign names to the error class _LEGACY_ERROR_TEMP_[0050|0057|0058|0059]
apache/spark pull request #41451
Opened 2023-06-04 12:18 UTC by panbingkun

### What changes were proposed in this pull request?
The pr aims to assign names to the error class `_LEGACY_ERROR_TEMP_[0050|0057|0058|0059]`, details as follows:
- _LEGACY_ERROR_TEMP_0050 => LOCAL_MUST_WITH_SCHEMA_FILE
- _LEGACY_ERROR_TEMP_0057 => UNSUPPORTED_DEFAULT_VALUE.WITHOUT_SUGGESTION
- _LEGACY_ERROR_TEMP_0058 => UNSUPPORTED_DEFAULT_VALUE.WITH_SUGGESTION
- _LEGACY_ERROR_TEMP_0059 => REF_DEFAULT_VALUE_IS_NOT_ALLOWED_IN_PARTITION

### Why are the changes needed?
The changes improve the error framework.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
- Manually test.
- Pass GA.

2023-06-04 14:05 UTC, panbingkun commented
cc @MaxGekk

2023-06-05 10:04 UTC, MaxGekk requested changes

2023-06-05 14:57 UTC, panbingkun commented on core/src/main/resources/error/error-classes.json
> +          "Enable it by setting `spark.sql.defaultColumn.enabled` to `true`."
This is done.

2023-06-06 07:13 UTC, MaxGekk approved these changes

2023-06-06 07:15 UTC, closed without merging