[SPARK-43915][SQL] Assign names to the error class _LEGACY_ERROR_TEMP_[2438-2445]
apache/spark pull request #41553
Opened 2023-06-12 13:12 UTC by beliefer

### What changes were proposed in this pull request?
The pr aims to assign names to the error class _LEGACY_ERROR_TEMP_[2438-2445].

### Why are the changes needed?
Improve the error framework.

### Does this PR introduce _any_ user-facing change?
'No'.

### How was this patch tested?
Exists test cases updated.

2023-06-12 13:15 UTC, beliefer commented on sql/core/src/test/scala/org/apache/spark/sql/connector/DeltaBasedDeleteFromTableSuite.scala
> +            |WriteDelta RelationV2[pk#2810, id#2811, dep#2812] cat.ns1.test_table cat.ns1.test_table
@MaxGekk The `exprId` for expression is not stable. Do you have any suggestions?

2023-06-15 18:23 UTC, MaxGekk requested changes

2023-06-15 18:23 UTC, MaxGekk commented on core/src/main/resources/error/error-classes.json
> +      "Function '<funcName>' does not implement ScalarFunction or AggregateFunction."
As I can see you quote `funcName` by `toSQLId`, please, remove ''

2023-06-18 05:49 UTC, beliefer commented
ping @MaxGekk The GA failure is unrelated to this PR.

2023-06-18 11:02 UTC, MaxGekk requested changes

2023-06-18 11:02 UTC, MaxGekk commented on core/src/main/resources/error/error-classes.json
> +  "SET_OPERATION_ON_MAP_TYPE_UNSUPPORTED" : {
Technically, it can be supported, right? Could you add a sub-class to `UNSUPPORTED_FEATURE`.

2023-06-20 09:19 UTC, MaxGekk requested changes

2023-06-20 09:19 UTC, MaxGekk commented on core/src/main/resources/error/error-classes.json
> +      "SET_OPERATION_ON_MAP_TYPE_UNSUPPORTED" : {
You can omit `_UNSUPPORTED` in the sub-class of `UNSUPPORTED_FEATURE`.

2023-06-20 09:19 UTC, MaxGekk commented on sql/core/src/test/scala/org/apache/spark/sql/DataFrameSetOperationsSuite.scala
> +        "colName" -> "\"m\"",
Shouldn't `m` be considered as an id and quoted by backticks instead of ""?

2023-06-20 09:19 UTC, MaxGekk commented on sql/core/src/test/scala/org/apache/spark/sql/connector/UpdateTableSuiteBase.scala
> +    assert(e.message.contains("The operator expects a deterministic expression"))
Could you use `checkError`

2023-06-21 18:18 UTC, MaxGekk approved these changes

2023-06-21 18:19 UTC, MaxGekk commented
+1, LGTM. Merging to master.
Thank you, @beliefer.

2023-06-21 18:20 UTC, closed without merging

2023-06-23 03:56 UTC, beliefer commented
@MaxGekk Thank you a lot!