[SPARK-44328][SQL] Assign names to the error class _LEGACY_ERROR_TEMP_[2325-2328]
apache/spark pull request #41889
Opened 2023-07-07 04:38 UTC by beliefer

### What changes were proposed in this pull request?
The pr aims to assign names to the error class _LEGACY_ERROR_TEMP_[2325-2328].

### Why are the changes needed?
Improve the error framework.

### Does this PR introduce _any_ user-facing change?
'No'.

### How was this patch tested?
Exists test cases updated and added new test cases.

2023-07-07 10:39 UTC, beliefer commented
ping @MaxGekk The failure GA is unrelated to this PR.

2023-07-07 12:28 UTC, oss-maker approved these changes
Looks good overall. +1 for adding a nice test!

2023-07-07 14:26 UTC, MaxGekk requested changes

2023-07-07 14:26 UTC, MaxGekk commented on common/utils/src/main/resources/error/error-classes.json
> +  "INVALID_UPDATE_FIELD" : {
Sorry, invalid FIELD or UPDATE? How about `CANNOT_UPDATE_FIELD`?

2023-07-07 14:26 UTC, MaxGekk commented on common/utils/src/main/resources/error/error-classes.json
> +      "ARRAY_TYPE_UNSUPPORTED" : {
Let's make sub-class names shorter like `ARRAY_TYPE`. In any case, users will observe `CANNOT_UPDATE_FIELD .ARRAY_TYPE`

2023-07-08 08:29 UTC, MaxGekk approved these changes
Waiting for CI.

2023-07-10 04:07 UTC, beliefer commented
@MaxGekk The GA failure is unrelated to this PR.

2023-07-10 06:18 UTC, MaxGekk commented
+1, LGTM. Merging to master.
Thank you, @beliefer and @oss-maker for review.

2023-07-10 06:19 UTC, closed without merging

2023-07-10 06:50 UTC, beliefer commented
@MaxGekk Thank you.