[SPARK-44782][INFRA] Adjust PR template to Generative Tooling Guidance recommendations
apache/spark pull request #42469
Opened 2023-08-12 10:25 UTC by zero323

### What changes were proposed in this pull request?

This PR adds _Was this patch authored or co-authored using generative AI tooling?_ section to the PR template.

### Why are the changes needed?

To reflect recommendations of the [ASF Generative Tooling Guidance](https://www.apache.org/legal/generative-tooling.html).

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual inspection.

2023-08-14 00:49 UTC, zhengruifeng commented
I guess this should be documented in https://spark.apache.org/developer-tools.html instead of PR template?

cc @HyukjinKwon @gatorsmile @srowen

2023-08-14 02:08 UTC, srowen commented
It should be in both places.

It's interesting. The typical CONTRIBUTING.md text that we have says, "When you contribute code, you affirm that the contribution is your original work", which seems at odds with the ASF guidance. I assume we are counting AI-assisted code as original work.

2023-08-15 09:19 UTC, yaooqinn commented on .github/PULL_REQUEST_TEMPLATE
> +frase 'Generated-by: ' followed by the name of the tool and its version.
```suggestion
phrase 'Generated-by: ' followed by the name of the tool and its version.
```

2023-08-16 13:52 UTC, srowen requested changes

2023-08-16 13:52 UTC, srowen commented on .github/PULL_REQUEST_TEMPLATE
> +If a generative AI tooling has been used in the process of authoring this patch, please include
Change to "If generative AI ..."
Change to "please include the"

2023-08-19 02:13 UTC, closed without merging

2023-08-19 02:13 UTC, srowen commented
Merged to master (the failure can't be related)