[SPARK-44435][SPARK-44484][3.5][SS][CONNECT] Tests for foreachBatch and Listener
apache/spark pull request #42664
Opened 2023-08-24 20:44 UTC by WweiL

### What changes were proposed in this pull request?

Add several new test cases for streaming foreachBatch and streaming query listener events to test various scenarios.
Also merge this PR to 3.5 to fix the test error: https://github.com/apache/spark/pull/42077

### Why are the changes needed?

More tests is better

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Test only change

2023-08-24 22:27 UTC, dongjoon-hyun commented on connector/connect/client/jvm/src/main/scala/org/apache/spark/sql/streaming/progress.scala
> +      ("batchDuration" -> JInt(batchDuration)) ~
Thank you for making a new PR.

However, given the previous discussion on SPARK-44484. We cannot backport a new feature like this under a different `Tests for foreachBatch and Listener` title.

- https://github.com/apache/spark/pull/42077

2023-08-24 22:28 UTC, dongjoon-hyun requested changes
If SPARK-44484 is inevitable for SPARK-44435, I'd prefer to stop backporting, @WweiL .

2023-08-24 23:13 UTC, WweiL commented
@dongjoon-hyun I see. I'll close this. Thanks for the context.

2023-08-25 02:26 UTC, dongjoon-hyun commented
Thank you for closing this, @WweiL .

2023-08-25 17:18 UTC, WweiL commented on python/pyspark/sql/streaming/listener.py
> +            batchDuration=j["batchDuration"] if "batchDuration" in j else None,
@dongjoon-hyun Hi Dongjoon, sorry for the back and forth. On second thought I actually find out that the newly added tests and the test failure in https://github.com/apache/spark/pull/42521#issuecomment-1691547730 actually finds out a bug. Here before I assume `batchDuration` is always in the passed in json, but before 4.0 it is not there.

Given that we don't add the change in https://github.com/apache/spark/pull/42077, this check is needed. I reverted that commit, and add this check.

2023-08-25 18:30 UTC, dongjoon-hyun requested changes
It's totally fine. :)

If this is a bug fix, please make a new JIRA to proceed it instead of SPARK-44435 or SPARK-44484. The JIRA title should be clear that is a bug fix. We can merge that first.

2023-09-05 19:13 UTC, WweiL commented
fixed in https://github.com/apache/spark/commit/7be69bf7da036282c2c7c0b62c32e7666fa1b579

2023-09-05 19:13 UTC, closed without merging