[SPARK-46208][PS][DOCS] Use specific Pandas version for API specifications.
apache/spark pull request #44115
Opened 2023-12-02 02:28 UTC by itholic

### What changes were proposed in this pull request?

This PR proposes to use specific Pandas version for API specifications.

### Why are the changes needed?

We can not always support the "latest version" of Pandas, specifically when newer Pandas introduces breaking change. Therefore, we would better to indicate the exact Pandas version currently supported to avoid confusion.

### Does this PR introduce _any_ user-facing change?

No, but it update the user-facing documentation as below:

**Before**
<img width="778" alt="Screenshot 2023-12-02 at 11 12 49 AM" src="https://github.com/apache/spark/assets/44108233/e3f7e5e1-a295-453b-b256-598894626a7a">

**After**
<img width="780" alt="Screenshot 2023-12-02 at 11 20 33 AM" src="https://github.com/apache/spark/assets/44108233/38f19d42-3772-4294-a006-6e965d9affb1">

### How was this patch tested?

The existing CI should pass

### Was this patch authored or co-authored using generative AI tooling?

No.

2023-12-02 09:19 UTC, itholic commented on python/docs/source/reference/pyspark.pandas/index.rst
> -   pandas API on Spark follows the API specifications of latest pandas release.
I believe we cannot always support the latest pandas version in some cases, especially when they introduce the breaking changes.

2023-12-02 21:18 UTC, dongjoon-hyun requested changes
Given that the monthly Pandas release cycle, it's also impossible to update this documentation at every month.

<img width="161" alt="Screenshot 2023-12-02 at 1 17 43 PM" src="https://github.com/apache/spark/assets/9700541/c58c8863-4b55-4b41-860c-9e1c5bd5f21b">

2023-12-03 02:13 UTC, dongjoon-hyun commented on python/docs/source/reference/pyspark.pandas/index.rst
> +   pandas API on Spark follows the API specifications of `Pandas 2.1.3 <https://pandas.pydata.org/pandas-docs/version/2.1.3/index.html>`_.
+1, this one looks reasonable.

2023-12-03 02:14 UTC, dongjoon-hyun approved these changes

2023-12-03 05:41 UTC, dongjoon-hyun approved these changes

2023-12-03 06:47 UTC, HyukjinKwon approved these changes

2023-12-03 06:47 UTC, HyukjinKwon commented
Merged to master.

2023-12-03 06:48 UTC, closed without merging