SPARK-47043 add `jackson-core` and `jackson-annotations` dependencies to module `spark-common-utils`
apache/spark pull request #45103
Opened 2024-02-14 15:28 UTC by William1104

### What changes were proposed in this pull request?
This PR aims to fix `spark-common-utils` module by adding explicit `jackson-core` and `jackson-annotations` dependencies. 

### Why are the changes needed?
`spark-common-utils` uses `jackson-core` and `jackson-annotations` like the following, but we didn't declare it explicitly. 

https://github.com/apache/spark/blob/a6bed5e9bcc54dac51421263d5ef73c0b6e0b12c/common/utils/src/main/scala/org/apache/spark/ErrorClassesJSONReader.scala#L26
https://github.com/apache/spark/blob/a6bed5e9bcc54dac51421263d5ef73c0b6e0b12c/common/utils/src/main/scala/org/apache/spark/ErrorClassesJSONReader.scala#L25
https://github.com/apache/spark/blob/a6bed5e9bcc54dac51421263d5ef73c0b6e0b12c/common/utils/src/main/scala/org/apache/spark/util/JsonUtils.scala#L23

### How was this patch tested?
Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?
No.

2024-02-14 16:30 UTC, dongjoon-hyun requested changes
May I ask why do we need this? Did you hit any issue? For me, this looks like correctly linked transitive dependencies by `Jackson-databind` like the following.

```
[INFO] --- dependency:3.6.0:tree (default-cli) @ spark-common-utils_2.13 ---
[INFO] org.apache.spark:spark-common-utils_2.13:jar:4.0.0-SNAPSHOT
[INFO] +- org.apache.spark:spark-tags_2.13:jar:4.0.0-SNAPSHOT:compile
[INFO] |  \- org.scala-lang:scala-library:jar:2.13.12:compile
[INFO] +- org.apache.xbean:xbean-asm9-shaded:jar:4.24:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.16.1:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.16.1:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.16.1:compile
```

2024-02-14 16:36 UTC, dongjoon-hyun commented
Please note that we usually fix the wrong dependency like the following situation in order to unblock other PRs. If you have a similar issue, please describe in the PR description, @William1104 .
> Previously, it was provided by some unused `htmlunit-driver`'s transitive dependency accidentally. This causes a weird situation which `kvstore` module starts to fail to compile when we upgrade `htmlunit-driver`. We need to fix this first.

2024-02-14 18:20 UTC, William1104 commented
Hi @dongjoon-hyun 

I am sorry about that. I created the JIRA via cloning. I don't know how to update the assignee back to myself. Would you mind to change it back to me, or let me know how I can update the assignee. 

Best regards,
William

2024-02-14 18:26 UTC, dongjoon-hyun commented
No problem. I just wanted to inform you. I fixed the field by removing my name. :)

2024-02-16 17:14 UTC, dongjoon-hyun commented
Unlike other communities like Apache ORC, Apache Spark community doesn't  take advantage of `maven-dependency-plugin` to enforce those `Used undeclared` and `Unused declared` and `Non-test scoped test only dependencies`. The main reason is because it would be quite inconvenient in a large and dynamic community like Apache Spark community.

Apache ORC Example:
https://github.com/apache/orc/blob/0a02e4cde165b81fb93fc99456a130da4625ef30/java/core/pom.xml#L160-L172

In addition, if you want to propose it, it should be applied systematically like Apache ORC community for all modules, not like many small PRs like this PR and #45101 .

However, if you have a concern about this area and want to contribute that area, I'd like to recommend you to send an email to dev@spark.apache.org . We can discuss more and build a consensus on the necessity of your proposal, @William1104 . You can use your PRs' links in your email.

2024-02-16 18:25 UTC, William1104 commented
Hi @dongjoon-hyun , 

Thanks for your explanation. Yes, the spark is a large and very dynamic community. It could be challenging to enforce this, especially since some modules already have more than required dependencies. I would propose fixing dependencies issue module by module, and then enforcing it in a systematic way (via maven dependency plugin). 

Let me send an email to dev@spark.apache.org on this topic. Thanks a lot. 

Best regards, 
William

2024-02-22 18:17 UTC, srowen commented
I think this change itself is fine, and indeed technically correct. Not sure if we want to make lots of changes like this, but the occasional targeted one seems OK.

2024-02-22 18:55 UTC, dongjoon-hyun commented
Did you send an email to dev, @William1104 ? It seems that I missed it.
> Let me send an email to [dev@spark.apache.org](mailto:dev@spark.apache.org) on this topic. Thanks a lot.

Ya, I totally agree with you and want to get some further consensus in dev mailing list because @William1104 seems to be interested in this area. (Already 2 opened and I guess more to come).

> Not sure if we want to make lots of changes like this, but the occasional targeted one seems OK.

2024-06-03 00:20 UTC, closed without merging