[SPARK-47085][SQL] reduce the complexity of toTRowSet from n^2 to n
apache/spark pull request #45164
Opened 2024-02-19 08:00 UTC by igreenfield

### What changes were proposed in this pull request?
reduce the complexity of RowSetUtils.toTRowSet from n^2 to n

### Why are the changes needed?
This causes performance issues.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Tests + test manually on AWS EMR

### Was this patch authored or co-authored using generative AI tooling?
No

2024-02-19 08:58 UTC, yaooqinn approved these changes

2024-02-19 09:10 UTC, yaooqinn commented
can you retrigger the CI？

2024-02-19 19:02 UTC, dongjoon-hyun requested changes
Hi, @igreenfield and @yaooqinn .

This could be a good improvement. However, Apache Spark community has a backporting policy which allows a bug-fix only.

![Screenshot 2024-02-19 at 10 59 16](https://github.com/apache/spark/assets/9700541/42e58306-eaa7-464d-a806-a2def39f1f50)

If you really want to backport this, please change the issue type to `BUG` and provide some background why this is a regression at Apache Spark 3.4.0.

2024-02-20 20:41 UTC, dongjoon-hyun approved these changes
+1, LGTM (Pending CIs).

Could you re-trigger the CI once more, @igreenfield ?

2024-02-20 20:42 UTC, dongjoon-hyun commented
For the record, the JIRA was updated correctly like the following.

![Screenshot 2024-02-20 at 12 42 08](https://github.com/apache/spark/assets/9700541/62393779-aae1-4fbd-912f-72daffa377ae)

2024-02-21 16:13 UTC, dongjoon-hyun commented
Merged to branch-3.4.

2024-02-21 16:13 UTC, closed without merging