[FOLLOWUP][SPARK-47152][SQL][BUILD] Provide `CodeHaus Jackson` dependencies via a new optional directory
apache/spark pull request #45241
Opened 2024-02-25 19:04 UTC by bjornjorgensen

### What changes were proposed in this pull request?
change `mv $f "$DISTDIR"/hive-jackson/` to `mv "$f" "$DISTDIR"/hive-jackson/`

### Why are the changes needed?

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA

### Was this patch authored or co-authored using generative AI tooling?
No.

2024-02-25 19:13 UTC, bjornjorgensen commented
@dongjoon-hyun


This Dockerfile worked as everyday at 0800 UTC+1
 
```
FROM debian:testing AS dep-builder

ARG openjdk_version="21"

USER root

RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
    "openjdk-${openjdk_version}-jdk" \
    "openjdk-${openjdk_version}-jre-headless" \
    ca-certificates-java \
    git wget python3.12 python3-venv && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    python3 -m venv /opt/venv

# Activate virtual environment
ENV PATH="/opt/venv/bin:$PATH"

# Now use pip to install packages
RUN pip install --upgrade pip setuptools



WORKDIR /tmp/

RUN git clone https://github.com/apache/spark.git

WORKDIR /tmp/spark 

RUN ./dev/make-distribution.sh --name custom-spark --pip -Pkubernetes

RUN rm -rf /tmp/spark
```

but today I get this error 
```
(...)
Downloaded from gcs-maven-central-mirror: https://maven-central.storage-download.googleapis.com/maven2/org/jline/jline-terminal-jna/3.14.1/jline-terminal-jna-3.14.1.jar (63 kB at 18 kB/s)
885.1 Downloading from gcs-maven-central-mirror: https://maven-central.storage-download.googleapis.com/maven2/com/lihaoyi/scalaparse_2.13/2.3.0/scalaparse_2.13-2.3.0.jar
Downloaded from gcs-maven-central-mirror: https://maven-central.storage-download.googleapis.com/maven2/com/thesamet/scalapb/scalapb-runtime_2.13/0.11.13/scalapb-runtime_2.13-0.11.13.jar (2.4 MB at 690 kB/s)
885.1 Downloading from gcs-maven-central-mirror: https://maven-central.storage-download.googleapis.com/maven2/org/javassist/javassist/3.21.0-GA/javassist-3.21.0-GA.jar
Downloaded from gcs-maven-central-mirror: https://maven-central.storage-download.googleapis.com/maven2/org/jline/jline-reader/3.14.1/jline-reader-3.14.1.jar (161 kB at 46 kB/s)
885.1 Downloading from gcs-maven-central-mirror: https://maven-central.storage-download.googleapis.com/maven2/com/github/javaparser/javaparser-core/3.2.5/javaparser-core-3.2.5.jar
Downloaded from gcs-maven-central-mirror: https://maven-central.storage-download.googleapis.com/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar (1.5 MB at 371 kB/s)
885.1 Downloading from gcs-maven-central-mirror: https://maven-central.storage-download.googleapis.com/maven2/com/typesafe/mima-core_2.13/1.1.3/mima-core_2.13-1.1.3.jar
Downloaded from gcs-maven-central-mirror: https://maven-central.storage-download.googleapis.com/maven2/com/github/javaparser/javaparser-core/3.2.5/javaparser-core-3.2.5.jar (862 kB at 210 kB/s)
Downloaded from gcs-maven-central-mirror: https://maven-central.storage-download.googleapis.com/maven2/com/lihaoyi/ammonite-compiler_2.13.12/2.5.11/ammonite-compiler_2.13.12-2.5.11.jar (394 kB at 96 kB/s)
Downloaded from gcs-maven-central-mirror: https://maven-central.storage-download.googleapis.com/maven2/com/lihaoyi/scalaparse_2.13/2.3.0/scalaparse_2.13-2.3.0.jar (412 kB at 100 kB/s)
Downloaded from gcs-maven-central-mirror: https://maven-central.storage-download.googleapis.com/maven2/org/javassist/javassist/3.21.0-GA/javassist-3.21.0-GA.jar (735 kB at 166 kB/s)
Downloaded from gcs-maven-central-mirror: https://maven-central.storage-download.googleapis.com/maven2/com/typesafe/mima-core_2.13/1.1.3/mima-core_2.13-1.1.3.jar (568 kB at 119 kB/s)
885.1 [INFO] 
885.1 [INFO] --- clean:3.3.2:clean (default-clean) @ spark-connect-client-jvm_2.13 ---
885.1 [INFO] 
885.1 [INFO] --- enforcer:3.4.1:enforce (enforce-versions) @ spark-connect-client-jvm_2.13 ---
885.1 [INFO] Rule 2: org.apache.maven.enforcer.rules.dependency.BannedDependencies passed
885.1 [INFO] Rule 3: org.codehaus.mojo.extraenforcer.dependencies.EnforceBytecodeVersion passed
885.1 [INFO] 
885.1 [INFO] --- enforcer:3.4.1:enforce (enforce-no-duplicate-dependencies) @ spark-connect-client-jvm_2.13 ---
885.1 [INFO] Rule 0: org.apache.maven.enforcer.rules.BanDuplicatePomDependencyVersions passed
885.1 [INFO] 
885.1 [INFO] --- scalafmt:1.1.1640084764.9f463a9:format (default) @ spark-connect-client-jvm_2.13 ---
885.1 [WARNING] format.skipSources set, ignoring main directories
885.1 [WARNING] format.skipTestSources set, ignoring validateOnly directories
885.1 [WARNING] No sources specified, skipping formatting
885.1 [INFO] 
885.1 [INFO] --- build-helper:3.4.0:timestamp-property (module-timestamp-property) @ spark-connect-client-jvm_2.13 ---
885.1 [WARNING] Using platform locale (en_US actually) to format date/time, i.e. build is platform dependent!
885.1 [INFO] 
885.1 [INFO] --- build-helper:3.4.0:timestamp-property (local-timestamp-property) @ spark-connect-client-jvm_2.13 ---
885.1 [WARNING] Using platform locale (en_US actually) to format date/time, i.e. build is platform dependent!
885.1 [INFO] 
885.1 [INFO] --- scala:4.7.1:add-source (eclipse-add-source) @ spark-connect-client-jvm_2.13 ---
885.1 [INFO] Add Source directory: /tmp/spark/connector/connect/client/jvm/src/main/scala
885.1 [INFO] Add Test Source directory: /tmp/spark/connector/connect/client/jvm/src/test/scala
885.1 [INFO] 
885.1 [INFO] --- dependency:3.6.1:build-classpath (default-cli) @ spark-connect-client-jvm_2.13 ---
885.1 [INFO] Dependencies classpath:
885.1 /tmp/spark/connector/connect/common/target/spark-connect-common_2.13-4.0.0-SNAPSHOT.jar:/root/.m2/repository/org/scala-lang/scala-library/2.13.12/scala-library-2.13.12.jar:/root/.m2/repository/io/grpc/grpc-netty/1.59.0/grpc-netty-1.59.0.jar:/root/.m2/repository/io/grpc/grpc-core/1.59.0/grpc-core-1.59.0.jar:/root/.m2/repository/com/google/android/annotations/4.1.1.4/annotations-4.1.1.4.jar:/root/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.23/animal-sniffer-annotations-1.23.jar:/root/.m2/repository/io/grpc/grpc-context/1.59.0/grpc-context-1.59.0.jar:/root/.m2/repository/io/perfmark/perfmark-api/0.26.0/perfmark-api-0.26.0.jar:/root/.m2/repository/io/grpc/grpc-protobuf/1.59.0/grpc-protobuf-1.59.0.jar:/root/.m2/repository/io/grpc/grpc-api/1.59.0/grpc-api-1.59.0.jar:/root/.m2/repository/com/google/api/grpc/proto-google-common-protos/2.22.0/proto-google-common-protos-2.22.0.jar:/root/.m2/repository/io/grpc/grpc-protobuf-lite/1.59.0/grpc-protobuf-lite-1.59.0.jar:/root/.m2/repository/io/grpc/grpc-services/1.59.0/grpc-services-1.59.0.jar:/root/.m2/repository/io/grpc/grpc-util/1.59.0/grpc-util-1.59.0.jar:/root/.m2/repository/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar:/root/.m2/repository/io/grpc/grpc-stub/1.59.0/grpc-stub-1.59.0.jar:/root/.m2/repository/io/grpc/grpc-inprocess/1.59.0/grpc-inprocess-1.59.0.jar:/root/.m2/repository/io/netty/netty-codec-http2/4.1.107.Final/netty-codec-http2-4.1.107.Final.jar:/root/.m2/repository/io/netty/netty-common/4.1.107.Final/netty-common-4.1.107.Final.jar:/root/.m2/repository/io/netty/netty-buffer/4.1.107.Final/netty-buffer-4.1.107.Final.jar:/root/.m2/repository/io/netty/netty-transport/4.1.107.Final/netty-transport-4.1.107.Final.jar:/root/.m2/repository/io/netty/netty-resolver/4.1.107.Final/netty-resolver-4.1.107.Final.jar:/root/.m2/repository/io/netty/netty-codec/4.1.107.Final/netty-codec-4.1.107.Final.jar:/root/.m2/repository/io/netty/netty-handler/4.1.107.Final/netty-handler-4.1.107.Final.jar:/root/.m2/repository/io/netty/netty-codec-http/4.1.107.Final/netty-codec-http-4.1.107.Final.jar:/root/.m2/repository/io/netty/netty-handler-proxy/4.1.107.Final/netty-handler-proxy-4.1.107.Final.jar:/root/.m2/repository/io/netty/netty-codec-socks/4.1.107.Final/netty-codec-socks-4.1.107.Final.jar:/root/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.107.Final/netty-transport-native-unix-common-4.1.107.Final.jar:/root/.m2/repository/org/apache/tomcat/annotations-api/6.0.53/annotations-api-6.0.53.jar:/tmp/spark/sql/api/target/spark-sql-api_2.13-4.0.0-SNAPSHOT.jar:/root/.m2/repository/org/scala-lang/scala-reflect/2.13.12/scala-reflect-2.13.12.jar:/root/.m2/repository/org/scala-lang/modules/scala-parser-combinators_2.13/2.3.0/scala-parser-combinators_2.13-2.3.0.jar:/tmp/spark/common/utils/target/spark-common-utils_2.13-4.0.0-SNAPSHOT.jar:/tmp/spark/common/unsafe/target/spark-unsafe_2.13-4.0.0-SNAPSHOT.jar:/root/.m2/reposit [...]

2024-02-25 20:05 UTC, dongjoon-hyun commented
Thanks. Did you verify that this PR recover it, @bjornjorgensen ?

2024-02-25 20:10 UTC, bjornjorgensen commented
> Thanks. Did you verify that this PR recover it, @bjornjorgensen ?

No, I haven't done that.

2024-02-25 20:21 UTC, dongjoon-hyun requested changes
Well, could you try to verify it? I don't find any special chararter in the Dockerfile, @bjornjorgensen .

2024-02-26 04:01 UTC, dongjoon-hyun commented
Did you get a chance to find the root cause of why your system hits the issue, @bjornjorgensen ?

2024-02-26 05:05 UTC, dongjoon-hyun commented
Could you revise the PR title properly, @bjornjorgensen ?

2024-02-26 06:00 UTC, dongjoon-hyun requested changes
This PR could be useful for the other case. However, this PR is irrelevant what you reported. Let me make a new PR to help your environment, @bjornjorgensen .
> RUN ./dev/make-distribution.sh --name custom-spark --pip -Pkubernetes

2024-02-26 06:15 UTC, dongjoon-hyun commented
Here is a correct PR for your system. I didn't include your contribution of this PR to isolate issues. You can proceed this contribution independently.
- #45253

2024-02-26 08:28 UTC, bjornjorgensen commented
yes, yours fix in https://github.com/apache/spark/pull/45253 
works :) 

![image](https://github.com/apache/spark/assets/47577197/cf6d7c3b-3212-4fd4-8167-c6bffc1cbac8)

I will close this PR for now. 
ones again thank you @dongjoon-hyun

2024-02-26 08:28 UTC, closed without merging

2024-02-26 17:25 UTC, dongjoon-hyun commented
Thank you, @bjornjorgensen .