[SPARK-47330][SQL] XML: Added XmlExpressionsSuite
apache/spark pull request #45445
Opened 2024-03-08 19:02 UTC by yhosny

### What changes were proposed in this pull request?

Replicated JsonExpressionsSuite to XmlExpressionsSuite for additional XML unit test coverage .

### Why are the changes needed?

Improve XML Expressions unit testing coverage.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Uni tests.

### Was this patch authored or co-authored using generative AI tooling?

No.

2024-03-17 10:26 UTC, MaxGekk requested changes
@yhosny Could you fix coding style, please:
```
[error] /home/runner/work/spark/spark/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/XmlExpressionsSuite.scala:22:0: There should at least one a single empty line separating groups java and 3rdParty.
[error] /home/runner/work/spark/spark/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/XmlExpressionsSuite.scala:23:0: There should at least one a single empty line separating groups 3rdParty and spark.
```

2024-03-18 20:56 UTC, shujingyang-db requested changes
blocking this OSS PR...Will discuss the test cases offline.

2024-03-18 23:42 UTC, HyukjinKwon commented
@sandip-db does it LG to you?

2024-03-19 00:09 UTC, sandip-db requested changes

2024-03-19 00:09 UTC, sandip-db commented on sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/XmlExpressionsSuite.scala
> +  test("from/to xml - interval support") {
remove this test as CalendarIntervalType is not supported yet.

2024-03-19 17:54 UTC, shujingyang-db approved these changes

2024-03-19 17:57 UTC, sandip-db approved these changes

2024-03-20 02:16 UTC, HyukjinKwon approved these changes

2024-03-20 02:17 UTC, HyukjinKwon commented
Merged to master.

2024-03-20 02:17 UTC, closed without merging