[SPARK-47488][core][k8s] Driver stuck when thread pool is not shut down
apache/spark pull request #45613
Opened 2024-03-20 12:46 UTC by littlelittlewhite09

### What changes were proposed in this pull request?
The issue is open on JIRA. Link:[SPARK-47488](https://issues.apache.org/jira/browse/SPARK-47488)

### Why are the changes needed?
On k8s-client mode, if encounters exception and thread pool is not closed, driver pod may stuck. This pr is used to fix this issue.

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
UT

### Was this patch authored or co-authored using generative AI tooling?
no

2024-03-20 14:27 UTC, dongjoon-hyun requested changes
Thank you for making a PR, @littlelittlewhite09 .

Could you add a test case to Kubernetes Integration tests?

https://github.com/apache/spark/tree/master/resource-managers/kubernetes/integration-tests

2024-03-20 14:30 UTC, dongjoon-hyun commented on core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala
> +              System.exit(1)
Please use the official `SparkExitCode`.

https://github.com/apache/spark/blob/a3c04ec1145662e4227d57cd953bffce96b8aad7/core/src/main/scala/org/apache/spark/util/SparkExitCode.scala#L23

2024-03-20 14:32 UTC, dongjoon-hyun commented on core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala
> +          logWarning("Begin to close SparkContext inside driver pod......")
This extra warning message is a regression in a healthy Spark K8s jobs.

2024-03-20 14:32 UTC, dongjoon-hyun commented on core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala
> +    //    this variable is used to judge whether driver pod is normal if spark is on k8s
Extra spaces, `//      this`?

2024-03-20 14:33 UTC, dongjoon-hyun commented on core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala
> +            logWarning("Finished to close SparkContext inside driver pod successfully.")
This extra warning message is a regression in a healthy Spark K8s jobs.

2024-03-20 14:35 UTC, dongjoon-hyun commented on core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala
> +          }
Indentation is correct? Line 1019 and 1020 seems to have some gap.

2024-03-20 14:36 UTC, dongjoon-hyun commented on core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala
> +            logWarning("Failed to close SparkContext.")
May I ask when does this happen actually? And, what was the previous behavior?

2024-03-21 02:23 UTC, yaooqinn commented
I checked your example code in the JIRA and it looks weird. Ideally, you should stop the non-daemon threads for a JVM to exit， and stop SparkContext to terminate the app

2024-03-21 15:27 UTC, littlelittlewhite09 commented
> I checked your example code in the JIRA and it looks weird. Ideally, you should stop the non-daemon threads for a JVM to exit， and stop SparkContext to terminate the app
If non-daemon threads is not stopped on yarn-cluster, driver can stop. But it does not work on k8s.

2024-03-21 15:30 UTC, littlelittlewhite09 commented
> I checked your example code in the JIRA and it looks weird. Ideally, you should stop the non-daemon threads for a JVM to exit， and stop SparkContext to terminate the app

When thread pool is not closed, driver can stop if app is on yarn-cluser. But it does not on k8s. I'm not sure if this situation is reasonable.

2024-03-22 11:16 UTC, closed without merging