[SPARK-47730][K8S] Support APP_ID and EXECUTOR_ID placeholders in labels
apache/spark pull request #46149
Opened 2024-04-21 12:50 UTC by jshmchenxi

Currently, only the pod annotations supports `APP_ID` and `EXECUTOR_ID` placeholders. This commit aims to add the same function to pod labels.

The use case is to support using customized labels for availability zone based topology pod affinity. We want to use the Spark application ID as the customized label value, to allow Spark executor pods to run in the same availability zone as Spark driver pod.

Although we can use the Spark internal label `spark-app-selector` directly, this is not a good practice when using it along with YuniKorn Gang Scheduling. When Gang Scheduling is enabled, the YuniKorn placeholder pods should use the same affinity as real Spark pods. In this way, we have to add the internal `spark-app-selector` label to the placeholder pods. This is not good because the placeholder pods could be recognized as Spark pods in the monitoring system.

Thus we propose supporting the `APP_ID` and `EXECUTOR_ID` placeholders in Spark pod labels as well for flexibility.

### What changes were proposed in this pull request?

### Why are the changes needed?

### Does this PR introduce _any_ user-facing change?

### How was this patch tested?

### Was this patch authored or co-authored using generative AI tooling?

2024-04-21 13:20 UTC, jshmchenxi commented
cc @dongjoon-hyun
This is a similar feature as #35704 and #42600. Please take a look, thanks!

2024-04-22 02:40 UTC, dongjoon-hyun commented on resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/k8s/features/BasicDriverFeatureStepSuite.scala
> +    "yunikorn.apache.org/app-id" -> "{{APPID}}")
Although I understand the intention, let's isolate `yunikorn` related feature inside `YuniKornSuite.scala`.

2024-04-22 02:41 UTC, dongjoon-hyun commented on resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/k8s/features/BasicDriverFeatureStepSuite.scala
> +    "yunikorn.apache.org/app-id" -> "{{APPID}}")
Previously, we mixed that and it turns that it was not good in a long term perspective.

2024-04-22 02:42 UTC, dongjoon-hyun commented on resource-managers/kubernetes/integration-tests/src/test/scala/org/apache/spark/deploy/k8s/integrationtest/BasicTestsSuite.scala
> +      .set("spark.kubernetes.driver.label.yunikorn.apache.org/app-id", "{{APP_ID}}")
Could you try to add this test coverage in `YuniKornSuite.scala`?

2024-04-22 02:43 UTC, dongjoon-hyun commented on resource-managers/kubernetes/integration-tests/src/test/scala/org/apache/spark/deploy/k8s/integrationtest/KubernetesSuite.scala
> +    val appIdAnnotation = pod.getMetadata.getAnnotations.get("yunikorn.apache.org/app-id")
It would be better if we can move all yunikorn stuff into `YuniKornSuite` .

2024-04-22 02:44 UTC, dongjoon-hyun requested changes
Thank you for making a PR, @jshmchenxi .

I'm interested in your proposal and use case. Could you address my review comments?

2024-04-23 05:36 UTC, dongjoon-hyun commented
Gentle ping, @jshmchenxi .

2024-04-27 08:16 UTC, jshmchenxi commented
It's been a busy week, sorry for the delay. I'll address your comments today, thanks! @dongjoon-hyun

2024-04-27 09:10 UTC, jshmchenxi reviewed
@dongjoon-hyun Thanks for the suggestions! I've updated the label key in the unit test to use a general one instead of the app id key of YuniKorn.

And our use case, we could use any custom label key for the app id. We are reusing `yunikorn.apache.org/app-id` for simplicity and it is in the new standards YuniKorn labels - [YUNIKORN-1351](https://issues.apache.org/jira/browse/YUNIKORN-1351). So there is no need to put the labels in the `YuniKornSuite` yet.

2024-04-29 01:29 UTC, dongjoon-hyun approved these changes
+1, LGTM. Thank you for updating, @jshmchenxi .
Merged to master for Apache Spark 4.0.0.

2024-04-29 01:30 UTC, closed without merging

2024-04-29 01:31 UTC, dongjoon-hyun commented
I added you (Xi Chen) to Apache Spark contributor group and assigned SPARK-47730 to you.
Welcome to the Apache Spark community, @jshmchenxi !

2024-08-31 12:51 UTC, jshmchenxi commented
Glad to join the community. Thank you! @dongjoon-hyun