[SPARK-49199][BUILD] `build/mvn` should check project local install Maven ahead
apache/spark pull request #47706
Opened 2024-08-12 02:44 UTC by pan3793

### What changes were proposed in this pull request?

This PR modifies the `mvn` command detection logic in `build/mvn`, to check project local installed `build/apache-maven-${MVN_VERSION}/bin/mvn` ahead to avoid unnecessary network accessing.

### Why are the changes needed?

To speed up `build/mvn` bootstrap time.

I found sometimes `build/mvn -version` is pretty slow even `build/apache-maven-${MVN_VERSION}` is already cached, and I found it may stuck at the following call when network quality is not good.

https://github.com/apache/spark/blob/879924491944be5d022df895b947bcee25837cc0/build/mvn#L129

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Tested `build/mvn -version` in the following cases:
1. when `build/apache-maven-${MVN_VERSION}/bin/mvn` is available, the command always finishes quickly.
2. when `build/apache-maven-${MVN_VERSION}/bin/mvn` is unavailable but global installed `mvn` version matched `maven.version` defined in root `pom.xml`, the command always finishes quickly too.
3. otherwise, it automatically downloads the maven binary tarball from network.

### Was this patch authored or co-authored using generative AI tooling?

No.

2024-08-12 02:46 UTC, pan3793 commented
To reviewers, it's recommended to hide whitespace on viewing the diff of this patch
<img width="728" alt="image" src="https://github.com/user-attachments/assets/440e232f-6364-4f5d-b859-e58dec064d77">

2024-08-12 05:51 UTC, pan3793 commented on build/mvn
> +  MVN_BIN="${_DIR}/apache-maven-${MVN_VERSION}/bin/mvn"
this also works, changed as suggested

2024-08-12 05:59 UTC, LuciferYang approved these changes

2024-08-12 17:48 UTC, dongjoon-hyun requested changes
Please recover `install_app` because we still need to verify the checkable binary after untarring the downloaded tarball, @pan3793 .

2024-08-13 02:19 UTC, pan3793 commented
@dongjoon-hyun okay, restored.

2024-08-13 05:30 UTC, dongjoon-hyun approved these changes
+1, LGTM. Thank you, @pan3793 and @LuciferYang .
Merged to master.

2024-08-13 05:30 UTC, closed without merging