[SPARK-49342][SQL] Make TO_AVRO SQL function 'jsonFormatSchema' argument optional
apache/spark pull request #47834
Opened 2024-08-21 22:00 UTC by dtenedor

### What changes were proposed in this pull request?

This PR make the `TO_AVRO` SQL function `jsonFormatSchema` argument optional.

For example, now it is possible to just call it with a single input argument:

```
create table t as
  select named_struct('u', named_struct('member0', member0, 'member1', member1)) as s
  from values (1, null), (null,  'a') tab(member0, member1);

select length(to_avro(s)) > 0 from t;

> true
  true
```

### Why are the changes needed?

This makes the `TO_AVRO` SQL function easier to use.

### Does this PR introduce _any_ user-facing change?

Yes, see above.

### How was this patch tested?

This PR adds unit test coverge.

### Was this patch authored or co-authored using generative AI tooling?

No.

2024-08-21 22:00 UTC, dtenedor commented
cc @gengliangwang

2024-08-22 00:17 UTC, HyukjinKwon approved these changes

2024-08-22 05:26 UTC, MaxGekk requested changes
@dtenedor Could you update the expression description and show optionality of `jsonFormatSchema`: 
```
_FUNC_(child[, jsonFormatSchema]) - Converts a Catalyst binary input value into its corresponding
```

2024-08-22 23:44 UTC, dtenedor commented
Sure, good catch @MaxGekk, this is done.

2024-08-23 05:10 UTC, MaxGekk approved these changes

2024-08-23 05:11 UTC, MaxGekk commented
+1, LGTM. Merging to master.
Thank you, @dtenedor and @HyukjinKwon for review.

2024-08-23 05:11 UTC, closed without merging