Avoid sorting in validateAndMaybeEvolveStateSchema
apache/spark pull request #48116
Opened 2024-09-16 00:13 UTC by tedyu

### What changes were proposed in this pull request?
In `validateAndMaybeEvolveStateSchema`, existing schema and new schema are sorted by column family name.
The sorting can be skipped.
When computing `colFamiliesAddedOrRemoved`, we can use `toSet` to compare column families.

### Why are the changes needed?
This would make `validateAndMaybeEvolveStateSchema` faster.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?

Existing tests.

### Was this patch authored or co-authored using generative AI tooling?
No.

2024-09-16 03:29 UTC, tedyu commented
@eric-maynard @HeartSaVioR 
Can you review ?

2024-09-16 16:59 UTC, ericm-db approved these changes
LGTM, pending CI

2024-09-16 17:02 UTC, tedyu commented
@ericm-db 
Accoding to https://github.com/tedyu/spark/runs/30175945976, tests passed.

2024-09-16 18:21 UTC, tedyu commented
@ericm-db 
Are you waiting for a committer to review this ?

2024-09-16 18:24 UTC, tedyu commented
@MaxGekk 
Can you take a look ?
Thanks

2024-09-16 20:00 UTC, tedyu commented
@dongjoon-hyun 
Can you take a look ?

Thanks

2024-09-17 06:56 UTC, MaxGekk reviewed
> This would make validateAndMaybeEvolveStateSchema faster.

Can you proof this, any microbenchmarks? BTW, building a `Set` is not for free.

And the code before and after is not logically the same. The `Set` removes duplicates naturally.  @HeartSaVioR Pleae, have a look at the changes.

2024-09-17 12:08 UTC, tedyu commented
bq. building a Set is not for free.

Sorting is an O(N log N) operation while building Set is linear in complexity.

bq. The Set removes duplicates 

In this code, there is no duplicate in the schema.

2024-09-17 12:21 UTC, MaxGekk approved these changes

2024-09-17 14:36 UTC, dongjoon-hyun reviewed
To @tedyu , could you file a JIRA issue, @tedyu ?

2024-09-17 14:50 UTC, tedyu commented
@dongjoon-hyun 
I have filed https://issues.apache.org/jira/browse/SPARK-49687

Thanks

2024-09-17 14:53 UTC, tedyu commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/StateSchemaCompatibilityChecker.scala
> -    val newStateSchemaList = newStateSchema.sortBy(_.colFamilyName)
Agreed.
The sorting is done when needed.

2024-09-17 15:08 UTC, dongjoon-hyun requested changes
> Agreed. The sorting is done when needed.

No, it's not addressed properly, @tedyu . 

There are multiple places of `createSchemaFile(newStateSchemaList, stateSchemaVersion)` at line 176 and 193.

2024-09-17 15:10 UTC, tedyu commented
I have covered the other `createSchemaFile` call.
Please take a look.

2024-09-17 15:21 UTC, dongjoon-hyun requested changes
No, please sort once.

2024-09-17 15:22 UTC, dongjoon-hyun commented
I explicitly suggest to keep it, @tedyu . :) 
> https://github.com/apache/spark/pull/48116#discussion_r1763393870

2024-09-17 15:27 UTC, tedyu commented
Here is why I moved the `sort` call:
```
      if (stateSchemaVersion == SCHEMA_FORMAT_V3 && colFamiliesAddedOrRemoved) {
```
when `colFamiliesAddedOrRemoved` is false, the call to `createSchemaFile` would be skipped and there is no need to sort.

Effectively the sorting is done lazily.
What do you think, @dongjoon-hyun ?

2024-09-17 15:43 UTC, dongjoon-hyun commented
Got it. it's slightly different from what the PR title and description claims because we still have `sort`.

Could you revise the PR title and description first about when we skip sorting and when we do the sort? Then, I believe I can agree with the proposal.

2024-09-17 15:46 UTC, tedyu commented
The PR and JIRA's titles and descriptions have been updated.

Thanks for your patience.

2024-09-17 16:36 UTC, dongjoon-hyun approved these changes
+1, LGTM.

2024-09-17 17:47 UTC, tedyu commented
@dongjoon-hyun 
Test suite passed. FYI

2024-09-17 17:58 UTC, closed without merging

2024-09-17 17:58 UTC, dongjoon-hyun commented
Merged to master. Thank you, @tedyu .

BTW, did you change your ID? I added you to the Apache Spark contributor group in order to assigne SPARK-49687 to you.

2024-09-17 18:02 UTC, tedyu commented
Thanks @dongjoon-hyun 
Zhihong is my Chinese name.