[SPARK-49971][SQL] Assign proper error condition for _LEGACY_ERROR_TEMP_1097
apache/spark pull request #48471
Opened 2024-10-15 06:53 UTC by itholic

### What changes were proposed in this pull request?

This PR proposes to assign proper error condition & sqlstate for` _LEGACY_ERROR_TEMP_1097`

### Why are the changes needed?

To improve the error message by assigning proper error condition and SQLSTATE

### Does this PR introduce _any_ user-facing change?

No, only user-facing error message improved

### How was this patch tested?

Updated the existing tests

### Was this patch authored or co-authored using generative AI tooling?

No

2024-10-15 12:21 UTC, MaxGekk requested changes

2024-10-15 12:21 UTC, MaxGekk commented on common/utils/src/main/resources/error/error-conditions.json
> +      "The field <columnName> for corrupt records must be string type and nullable."
```suggestion
      "The column <columnName> for corrupt records must have the nullable STRING type, but got <actualType>"
```

2024-10-15 12:21 UTC, MaxGekk commented on common/utils/src/main/resources/error/error-conditions.json
> +  "UNSUPPORTED_DATA_TYPE_FOR_CORRUPTED_RECORD" : {
```suggestion
  "INVALID_CORRUPT_RECORD_TYPE" : {
```

2024-10-15 12:21 UTC, MaxGekk commented on common/utils/src/main/resources/error/error-conditions.json
> +    ]
please, set `sqlState`

2024-10-16 00:26 UTC, itholic commented
Thanks @MaxGekk for the review! Applied the comments

2024-10-16 07:02 UTC, MaxGekk approved these changes

2024-10-16 07:03 UTC, MaxGekk commented
@itholic Could you fix the failed tests:
```
[info] - verify corrupt column *** FAILED *** (3 milliseconds)
[info]   (non-codegen mode) Expected error message is `The field for corrupt records must be string type and nullable`, but `[INVALID_CORRUPT_RECORD_TYPE] The column `_unparsed` for corrupt records must have the nullable STRING type, but got "BOOLEAN". SQLSTATE: 42804` found (ExpressionEvalHelper.scala:226)
```

2024-10-17 09:02 UTC, MaxGekk commented
+1, LGTM. Merging to master.
Thank you, @itholic.

2024-10-17 09:03 UTC, closed without merging