[SPARK-49663][SQL] Enable RTRIM suggestions in collation expressions
apache/spark pull request #48545
Opened 2024-10-18 13:24 UTC by jovanpavl-db

### What changes were proposed in this pull request?
Add RTRIM collation suggestion for collation expressions in case of the wrong name.

### Why are the changes needed?
Better customer experience. 

### Does this PR introduce _any_ user-facing change?
Yes.

### How was this patch tested?
Added tests in CollationFactorySuite.

### Was this patch authored or co-authored using generative AI tooling?
No.

2024-10-23 09:35 UTC, MaxGekk requested changes
@jovanpavl-db Please, fix the coding style issue:
```
[error] /__w/spark/spark/common/unsafe/src/test/scala/org/apache/spark/unsafe/types/CollationFactorySuite.scala: illegal start of simple expression: Token(RPAREN,),4621,))
```

2024-10-27 09:40 UTC, MaxGekk reviewed
@stefankandic @uros-db @stevomitric Could you review this PR, please.

2024-10-28 07:58 UTC, uros-db approved these changes
this is fine, although just a note: we may need to re-visit this again in the future in order to improve the overall suggestions algorithm

for example, `SR_CI_RTRIM_AI` is a valid collation, while `SR_CI_TRIM_AI` is not - although I doubt that the suggestions will be very accurate in this case (and many others)

2024-10-28 08:25 UTC, MaxGekk reviewed
Does it make sense to use the levenshtein distance for suggestions like we do in `UNRESOLVED_FIELD.WITH_SUGGESTION`, see
https://github.com/apache/spark/blob/bb15eb7b91ab775bdb84b6b17353a706794b122d/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/StringUtils.scala#L75-L97

2024-10-29 09:31 UTC, jovanpavl-db commented
> Does it make sense to use the Levenshtein distance for suggestions like we do in `UNRESOLVED_FIELD.WITH_SUGGESTION`, see
> 
> https://github.com/apache/spark/blob/bb15eb7b91ab775bdb84b6b17353a706794b122d/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/StringUtils.scala#L75-L97

I went through this implementation and it seems useful, however it can be quite problematic in our case to do suggestion on specifiers (we currently want 100% match on them because they are usually 2 chars long), for example if someone puts _C you can suggest _CI, _CS and even some UNICODE collations like ci. For every wrong specifier we can have multiple suggestions so it can really explode. That's why I think we (currently) stayed out of business of doing suggestions on specifiers but rather whole collation. We can definitely rethink this approach in the future at least for the some of specifiers like trim.

2024-10-29 13:48 UTC, MaxGekk reviewed
lgtm except of a couple comments.

2024-10-29 13:48 UTC, MaxGekk commented on common/unsafe/src/test/scala/org/apache/spark/unsafe/types/CollationFactorySuite.scala
> +      ("UTF8_BINARY_AI_CI_RTRIM","UTF8_BINARY_RTRIM"),
let's be consistent and use spaces:
```suggestion
      ("UTF8_BINARY_CI_RTRIM", "UTF8_BINARY_RTRIM"),
      ("UTF8_BINARY_AI_CI_RTRIM", "UTF8_BINARY_RTRIM"),
```

2024-10-29 13:48 UTC, MaxGekk commented on common/unsafe/src/test/scala/org/apache/spark/unsafe/types/CollationFactorySuite.scala
> +      ("UNICODE_RTRIM_LCASE_X","UNICODE"),
```suggestion
      ("UNICODE_RTRIM_LCASE_X", "UNICODE"),
```

2024-10-29 14:07 UTC, MaxGekk approved these changes
Waiting for CI.

2024-10-30 10:51 UTC, MaxGekk commented
+1, LGTM. Merging to master.
Thank you, @jovanpavl-db and @uros-db for your review.

2024-10-30 10:52 UTC, closed without merging