[SPARK-50234][PYTHON][SQL] Improve error message and test for transpose DataFrame API
apache/spark pull request #48766
Opened 2024-11-05 20:04 UTC by itholic

### What changes were proposed in this pull request?

This PR proposes to improve error message and test for transpose DataFrame API

### Why are the changes needed?

To improve error message and negative testing

### Does this PR introduce _any_ user-facing change?

No API changes, but user-facing error message is improved

### How was this patch tested?

Updated the existing UTs

### Was this patch authored or co-authored using generative AI tooling?

No

2024-11-05 20:04 UTC, itholic commented
cc @xinrong-meng

2024-11-05 21:04 UTC, HyukjinKwon approved these changes

2024-11-07 08:52 UTC, MaxGekk requested changes

2024-11-07 08:52 UTC, MaxGekk commented on sql/core/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveTranspose.scala
> +              "dt2" -> toSQLType(dt2.sql))
`toSQLType` over strings is some kind of workaround. In general case, let's leave convertions to strings intirely to `toSQLType`:
```suggestion
              "dt1" -> toSQLType(dt1),
              "dt2" -> toSQLType(dt2))
```

2024-11-11 02:17 UTC, xinrong-meng approved these changes

2024-11-11 02:17 UTC, xinrong-meng commented
LGTM, thank you!

2024-11-13 00:37 UTC, closed without merging

2024-11-13 00:38 UTC, itholic commented
Merged to master.
Thanks @HyukjinKwon @MaxGekk @xinrong-meng for the review!