[MINOR][PYTHON][TESTS] Group pandas function related tests
apache/spark pull request #49074
Opened 2024-12-05 12:30 UTC by zhengruifeng

### What changes were proposed in this pull request?
Group pandas function related tests

### Why are the changes needed?
these tests were grouped in classic side, also group the parity tests for consistency

### Does this PR introduce _any_ user-facing change?
no, test-only

### How was this patch tested?
updated ci

### Was this patch authored or co-authored using generative AI tooling?
no

2024-12-05 15:49 UTC, dongjoon-hyun requested changes
We need a JIRA issue for this, @zhengruifeng . :)

+1 for the code.

2024-12-06 00:47 UTC, HyukjinKwon approved these changes

2024-12-06 01:33 UTC, zhengruifeng commented
@dongjoon-hyun thanks, add the JIRA number

2024-12-06 01:49 UTC, dongjoon-hyun approved these changes
+1, LGTM. Thank you, @zhengruifeng and @HyukjinKwon .
Merged to master for Apache Spark 4.0.0 on February 2025.

2024-12-06 01:50 UTC, closed without merging