[SPARK-49461][SS][FOLLOWUP]
apache/spark pull request #49278
Opened 2024-12-24 01:09 UTC by WweiL

### What changes were proposed in this pull request?

Per request from this comment, https://github.com/apache/spark/pull/48355/files#r1866546734, we will put `None` in the `stateUniqueIds` of `CommitMetadata` when in V1. So now the logic is as follows:

1. In V1, `CommitMetadata.stateUniqueIds = None` for all stateful and stateless queries
2. In V2, `CommitMetadata.stateUniqueIds = Some(Map.empty)` for stateless queries
3. In V2, `CommitMetadata.stateUniqueIds = Some(<non-empty-map>)` for stateful queries

Also removed the legacy test as a side effect

### Why are the changes needed?

Follow up

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unit tests

### Was this patch authored or co-authored using generative AI tooling?

No

2025-01-06 23:23 UTC, siying commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/CommitLog.scala
> +  private val VERSION = SQLConf.get.stateStoreCheckpointFormatVersion
Why is it moved here?

2025-01-06 23:23 UTC, siying commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/IncrementalExecution.scala
> +    Option(MutableMap[Long, Array[Array[String]]]()))
Is this variable never None? There is no point to make Option in that case. If we make it Option, perhaps we should do the same as `MicroBatchExecution.currentStateStoreCkptId`

2025-01-08 06:30 UTC, brkyvz commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/IncrementalExecution.scala
> +    Option(MutableMap[Long, Array[Array[String]]]()))
+1

2025-01-08 06:30 UTC, brkyvz commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/IncrementalExecution.scala
> +    Option(MutableMap[Long, Array[Array[String]]]()))
I don't think these need to be changed

2025-01-08 06:33 UTC, brkyvz requested changes
I think all you need to change is the `CommitMetadata` class, and the usage of it - the rest of the code can remain the same

2025-01-08 06:33 UTC, brkyvz commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/MicroBatchExecution.scala
> +  private var currentStateStoreCkptId: Option[MutableMap[Long, Array[Array[String]]]] = None
I don't think the option changes here are necessary - it's only important for the serialization case class, not the rest imho. @siying please let me know if you disagree

2025-01-10 00:06 UTC, WweiL commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/CommitLog.scala
> +  private val VERSION = SQLConf.get.stateStoreCheckpointFormatVersion
As Burak said here, https://github.com/apache/spark/pull/49275#discussion_r1906535722

the conf can be changed per session, and in the test we need to change the conf during test.

2025-01-14 17:52 UTC, brkyvz approved these changes
LGTM! Thanks for the changes

2025-01-14 18:51 UTC, siying approved these changes

2025-01-14 21:16 UTC, siying commented on sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/MicroBatchExecution.scala
> +  private var currentStateStoreCkptId: Option[MutableMap[Long, Array[Array[String]]]] = None
@brkyvz I agree. Only the one in commit log is the one I am worried about.

2025-01-15 22:29 UTC, brkyvz commented
@HeartSaVioR I'm still having trouble pushing to apache. Can I ask for your help in merging this to master and 4.0?

2025-01-16 02:53 UTC, HeartSaVioR commented
Will do! I'm merging on behalf of @brkyvz . Thanks! Merging to master/4.0.

2025-01-16 02:54 UTC, closed without merging